Repository open-condo-software/condo, pull requests merged in 2021-12, with the labels that each got.

#897 DOMA-1709 Expanded fix-ticket after support details
  bin/fix-tickets-contacts.js
Labels: small, ✋🙂 Review please

#896 DOMA-376 Removed error throwing on cookie resetting
  packages/@core.next/organization.jsx
Labels: small, ✋🙂 Review please

#899 DOMA-1661 Restore Service Consumer logic
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
Labels: small, HOTFIX, ✋🙂 Review please

#895 DOMA-1661 Fix EPS logs add pages
  apps/condo/domains/acquiring/schema/MultiPayment.js
Labels: small, ✋🙂 Review please

#906 DOMA-1735 fix head meta tag warning
  apps/condo/pages/_app.tsx
  apps/condo/pages/_document.tsx
Labels: small, ✋🙂 Review please

#920 HOTFIX check ref on empty property map
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: HOTFIX

#923 DOMA-1664 remove fire update unit names on remove preview unit
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: small, ✋🙂 Review please

#924 DOMA-1757 add req.id middleware
  apps/condo/index.js
Labels: small, ✋🙂 Review please

#935 DOMA-1767 increased z-index of fullscreen header component
  apps/condo/domains/property/components/panels/Builder/Fullscreen.tsx
Labels: small, ✋🙂 Review please

#937 DOMA-1665 remove unit directly if it has custom label
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: small, ✋🙂 Review please

#934 DOMA-1678 set null property on clear property select
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Labels: small, ✋🙂 Review please

#941 DOMA-1777 add hidden map input property to BasePropertyForm
  apps/condo/domains/property/components/BasePropertyForm/index.tsx
Labels: small, ✋🙂 Review please

#832 DOMA-1356 mobile menu redesign
  apps/condo/domains/user/components/UserMenu/MobileUserMenu.tsx
  apps/condo/domains/user/components/UserMenu/styles.ts
Labels: small, ✋🙂 Review please

#939 DOMA-1781 fix organization select null option
  apps/condo/domains/organization/components/OrganizationSelect.tsx
Labels: small, ✋🙂 Review please

#948 DOMA-1787 add classifier placeholder
  apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
Labels: small, ✋🙂 Review please

#960 HOTFIX update README.md
  README.md
  docs/contributing.md
  docs/getting-started.md
  docs/images/screen1.png
Labels: small, HOTFIX, ✋🙂 Review please

#964 DOMA-1810 change CreatePropertyForm redirect path to created object view
  apps/condo/domains/property/components/PropertyForm/CreatePropertyForm.tsx
Labels: small, ✋🙂 Review please

#963 DOMA-1788 scroll to last unit when it should be added to last section
  apps/condo/domains/property/components/panels/Builder/BuildingPanelCommon.tsx
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/domains/property/components/panels/Builder/UnitButton.tsx
Labels: small, ✋🙂 Review please

#972 DOMA-1814 update section & unit number when section has been removed
  apps/condo/domains/property/components/panels/Builder/MapConstructor.spec.ts
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: small, ✋🙂 Review please

#974 DOMA-1822 move section name generation to separate method
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: small, HOTFIX, ✋🙂 Review please

#986 HOTFIX add FILE_FIELD_ADAPTER to read me
  apps/condo/docs/development.md
Labels: small, HOTFIX, ✋🙂 Review please

#990 Feature/condo/doma 1872/clean comments and remove multitariff values from non electricity meters in meter import example excel file
  apps/condo/public/meter-import-example.xlsx
Labels: small

#997 DOMA-1876 Fix payment categories
  apps/condo/domains/resident/constants.js
Labels: small

#1009 DOMA-1868 ticket type options layout was fixed (emergency/paid)
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Labels: small, ✋🙂 Review please

#1016 DOMA-1885 fix property data search when objects count more than 100 units
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Labels: small, HOTFIX, ✋🙂 Review please

#1018 DOMA-1886 case insensitive address comparsion in `Resident.property.validateInput`
  apps/condo/domains/resident/schema/Resident.js
  apps/condo/domains/resident/schema/Resident.test.js
Labels: 🔥 HOTFIX

#1027 DOMA-1870 reset time at date filter
  apps/condo/domains/ticket/schema/TicketReportService.js
Labels: small, 🔥 HOTFIX, ✋🙂 Review please
