Repository open-condo-software/condo, pull requests merged in 2021-07, with the labels that each got.

#289 SBERDOMA-478 fix max sender length for mobile
  apps/condo/domains/common/schema/fields.js
Labels: small

#296 SBERDOMA-698 fix long name overflowing
  apps/condo/pages/ticket/[id]/index.tsx
Labels: small

#295 SBERDOMA-699 Comments input are now limited by size and by maximum length
  apps/condo/domains/common/components/Comments/CommentForm.tsx
  apps/condo/lang/en.json
  apps/condo/lang/ru.json
Labels: small

#299 SBERDOMA-702 add demo deploy concurrency
  .github/workflows/nodejs.condo.deploy.yml
Labels: small

#303 SBERDOMA-709 add not implemented tooltip on details button
  apps/condo/domains/common/components/StatsCard.tsx
Labels: small

#297 SBERDOMA-314 fix select to auto open if organization link is lost
  apps/condo/domains/organization/components/OrganizationSelect.tsx
Labels: small

#301 SBERDOMA-692 catch sms error
  apps/condo/pages/auth/register.tsx
Labels: small

#310 SBERDOMA-734 fix isRejected employee request
  apps/condo/pages/employee/[id]/index.tsx
Labels: small

#321 SBERDOMA-767 fix kmigrator path
  bin/kmigrator.py
Labels: small

#320 SBERDOMA-766 fixed contact is not created in ticket create page
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: HOTFIX

#304 SBERDOMA-715 add transparent background to header
  apps/condo/domains/user/components/containers/AuthLayout.tsx
Labels: small

#331 SBERDOMA-754 allow only сyrillic and latin letters and spaces for name field in register page
  apps/condo/lang/en.json
  apps/condo/lang/ru.json
  apps/condo/pages/auth/register.tsx
Labels: small

#334 SBERDOMA-753 replace smscode input with maskedInput
  apps/condo/pages/auth/register.tsx
Labels: small

#339 SBERDOMA-649 Fix access for SigninResident and rename gql mutation
  apps/condo/domains/user/access/SigninResidentUserService.js
  apps/condo/domains/user/gql.js
  apps/condo/domains/user/schema/SigninResidentUserService.test.js
Labels: HOTFIX, small

#341 SBERDOMA-627 unbind search input value
  apps/condo/domains/common/components/BaseSearchInput/index.tsx
Labels: small

#346 SBERDOMA-636 fixed missing placeholder for "name" field in Ticket form
  apps/condo/domains/contact/components/ContactsEditor/ContactSyncedAutocompleteFields.tsx
  apps/condo/lang/en.json
  apps/condo/lang/ru.json
Labels: small

#351 SBERDOMA-711 fixed missing whitespace of close button on select input
  apps/condo/domains/common/components/containers/GlobalStyle.tsx
Labels: small

#349 SBERDOMA-710 shorten `name` field label in ticket page
  apps/condo/pages/ticket/[id]/index.tsx
Labels: small

#345 SBERDOMA-831 handle redis connection error
  apps/condo/domains/user/utils/serverSchema/guards.js
  packages/@core.keystone/setup.utils.js
Labels: small

#348 SBERDOMA-577 fixed focus on wrong field in ticket form
  apps/condo/domains/common/components/BaseSearchInput/index.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Labels: small

#350 SBERDOMA-711 removed orphaned 'email' field in ticket page
  apps/condo/pages/ticket/[id]/index.tsx
Labels: small

#352 SBERDOMA-833 unauth users doesn't redirect on index when click on logo
  apps/condo/domains/user/components/containers/AuthLayout.tsx
Labels: small

#355 SBERDOMA-716 added client phone input validations on register screen
  apps/condo/pages/auth/register.tsx
Labels: small

#353 SBERDOMA-714 Translation fix
  apps/condo/lang/ru.json
Labels: small

#359 SBERDOMA-841 Added width style to ticket container
  apps/condo/domains/common/components/TicketCard/TicketOverview.tsx
Labels: small

#361 SBERDOMA-821 Add generic not found message
  apps/condo/domains/common/components/BaseSearchInput/index.tsx
  apps/condo/lang/en.json
  apps/condo/lang/ru.json
Labels: small

#357 SBERDOMA-839 Fixed error with undefined `COOKIE_SECRET` in Docker `worker` service
  docker-compose.yml
Labels: small

#368 SBERDOMA-666 Create custom middleware for large JSON bodysizes
  apps/condo/index.js
Labels: HOTFIX, small, ✋🙂 Review please

#370 SBERDOMA-874 add .vscode to .gitignore
  .gitignore
Labels: small

#372 SBERDOMA-860 table filter
  apps/condo/domains/common/components/containers/GlobalStyle.tsx
Labels: small, ✋🙂 Review please

#366 Update support mail and phone number
  apps/condo/domains/common/constants/requisites.js
Labels: small

#374 SBERDOMA-891 fix organization filtering, first load issue
  apps/condo/domains/common/components/StatsCard.tsx
  apps/condo/domains/ticket/components/TicketsWidget.tsx
  apps/condo/domains/ticket/schema/TicketAnalyticsReportService.js
  apps/condo/pages/analytics/index.tsx
Labels: HOTFIX, ✋🙂 Review please

#379 SBERDOMA-898 fixed duplication of ticket changes block in ticket page
  apps/condo/pages/ticket/[id]/index.tsx
Labels: small

#380 SBERDOMA-899 add tooltip instead to email in share ticket
  apps/condo/domains/ticket/components/ShareTicketModal.tsx
Labels: small
