Repository open-condo-software/condo, pull requests merged in 2021-11, with the labels that each got.

#719 DOMA-1435 add prisma adapter support for fields
  packages/@core.keystone/fields/AutoIncrementInteger/Implementation.js
  packages/@core.keystone/fields/AutoIncrementInteger/index.js
  packages/@core.keystone/fields/Json/Implementation.js
  packages/@core.keystone/fields/Json/index.js
  packages/@core.keystone/fields/LocalizedText/index.js
  packages/@core.keystone/fields/Options/Implementation.js
  packages/@core.keystone/fields/Options/index.js
  packages/@core.keystone/fields/Stars/Implementation.js
  packages/@core.keystone/fields/Stars/index.js
Labels: small, ✋🙂 Review please

#735 Role access with deletedAt check
  apps/condo/domains/organization/utils/accessSchema.js
Labels: small, ✋🙂 Review please

#775 HOTFIX update dd-trace lib to the latest version
  apps/condo/package.json
Labels: small, ✋🙂 Review please

#776 HOTFIX add robots.txt
  apps/condo/public/robots.txt
Labels: small, ✋🙂 Review please

#787 DOMA-1424 Tickets export
  apps/condo/domains/ticket/templates/TicketsExportTemplate.xlsx
Labels: small, HOTFIX, ✋🙂 Review please

#630 DOMA-1293 added build step to checklists/pull-request
  apps/condo/docs/checklists/pull-request.md
Labels: small

#793 DOMA-1363 Change Ticket status transitions
  apps/condo/domains/ticket/constants/statusTransitions.js
Labels: small, HOTFIX, ✋🙂 Review please

#799 DOMA-1603 update ticket table columns width
  apps/condo/domains/ticket/hooks/useTableColumns.tsx
Labels: small, ✋🙂 Review please

#803 DOMA-1609 fix sort and pagination on employee and contact pages
  apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
  apps/condo/domains/common/hooks/useSearch.ts
  apps/condo/domains/common/utils/filters.utils.ts
  apps/condo/domains/ticket/hooks/useEmergencySearch.ts
  apps/condo/domains/ticket/hooks/usePaidSearch.ts
  apps/condo/pages/contact/index.tsx
  apps/condo/pages/employee/index.tsx
  apps/condo/pages/ticket/index.tsx
Labels: small, ✋🙂 Review please

#829 DOMA-1443 Add isHidden flag to billing integration
  apps/condo/domains/billing/components/Settings/BillingChooser.tsx
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/BillingIntegration.js
  apps/condo/domains/billing/utils/clientSchema/BillingIntegration.ts
  apps/condo/domains/billing/utils/testSchema/index.js
  apps/condo/migrations/20211118115512-0081_auto_20211118_1155.js
  apps/condo/pages/settings/integration/[id]/index.tsx
  apps/condo/schema.ts
Labels: small, ✋🙂 Review please, Migrations

#830 DOMA-1259 HOTFIX process deleted addresses at contact detail page
  apps/condo/domains/common/components/TicketCard/TicketCardList.tsx
Labels: small, HOTFIX, ✋🙂 Review please

#836 HOTFIX fix test: check message, path and name
  apps/condo/domains/user/schema/ChangePhoneNumberResidentUserService.test.js
Labels: small, ✋🙂 Review please

#839 HOTFIX test util import
  apps/condo/domains/user/schema/User.test.js
Labels: merged 🐛, HOTFIX

#833 DOMA-1589 fix typo zavyaki
  apps/condo/domains/notification/templates.js
Labels: small

#867 DOMA-1653 Added ability for acquiring integration to create context for existing organizations
  apps/condo/domains/acquiring/constants/errors.js
  apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.js
  apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.test.js
  apps/condo/domains/organization/access/Organization.js
Labels: small, ✋🙂 Review please

#877 DOMA-1708 add missed fields to render address
  apps/condo/domains/common/components/Table/Renders.tsx
  apps/condo/domains/common/utils/helpers.ts
  apps/condo/domains/division/utils/clientSchema/Renders.tsx
Labels: small, ✋🙂 Review please

#882 DOMA-1498 Added invites to mobile version
  apps/condo/domains/common/components/TopNotifications.tsx
  apps/condo/domains/common/components/containers/BaseLayout/Header.tsx
  apps/condo/domains/common/components/containers/BaseLayout/components/TopMenuItems.tsx
Labels: small, ✋🙂 Review please

#889 HOTFIX update ServiceConsumer.organization doc
  apps/condo/domains/resident/schema/ServiceConsumer.js
Labels: small, ✋🙂 Review please

#892 DOMA-1724 Property areas with comma
  apps/condo/domains/common/hooks/useValidations.ts
  apps/condo/domains/property/components/BasePropertyForm/index.tsx
Labels: small, ✋🙂 Review please

#893 DOMA-1727 Fix null integration option
  apps/condo/domains/billing/constants/errors.js
  apps/condo/domains/billing/schema/BillingIntegrationOrganizationContext.js
  apps/condo/domains/billing/schema/BillingIntegrationOrganizationContext.test.js
Labels: small, ✋🙂 Review please
