Repository open-condo-software/condo, pull requests merged in 2021-08, with the labels that each got.

#399 SBERDOMA-794 add access to share ticket
  apps/condo/domains/ticket/access/ShareTicketService.js
Labels: small

#407 SBERDOMA-752 Fix token init on register page and change validation to…
  apps/condo/pages/auth/register.tsx
Labels: small, ✋🙂 Review please

#378 SBERDOMA-895 fixed wrapping of datetime in ticket changes
  apps/condo/domains/ticket/components/TicketChanges/TicketChange.tsx
Labels: small

#417 SBERDOMA-900 debug real client mode
  packages/@core.keystone/test.utils.js
Labels: small

#420 SBERDOMA-955 remove optional chainig
  apps/condo/domains/ticket/schema/CreateResidentTicketService.js
  apps/condo/domains/ticket/schema/UpdateResidentTicketService.js
  apps/condo/domains/ticket/utils/testSchema/index.js
Labels: small

#424 SBERDOMA-759 Added custom width to partly success modal window
  apps/condo/domains/common/components/Import/ModalConfigs.tsx
Labels: small, ✋🙂 Review please

#425 HOTFIX SBERDOMA-476 Localization: rebase migrations
  apps/condo/migrations/20210805182022-0035_auto_20210805_1820.js
  apps/condo/migrations/20210806130833-0036_auto_20210806_0808.js
  apps/condo/migrations/20210806130940-0037_manual_localize_static_roles_and_statuses.js
Labels: HOTFIX

#432 HOTFIX SBERDOMA-476 fix AdminUI for new field type
  packages/@core.keystone/fields/LocalizedText/index.js
Labels: HOTFIX

#426 SBERDOMA-818 Ticket generator
  bin/generate-tickets.js
Labels: small, ✋🙂 Review please

#437 SBERDOMA-980 Three level classifier fixes
  apps/condo/domains/ticket/components/TicketClassifierSelect.tsx
  apps/condo/domains/ticket/schema/TicketClassifierRule.js
  apps/condo/schema.d.ts
Labels: small, HOTFIX, ✋🙂 Review please

#436 SBERDOMA-653 Check access to bucket on file upload
  apps/condo/domains/common/utils/sberCloudFileAdapter.js
Labels: small, HOTFIX, ✋🙂 Review please

#441 SBERDOMA-982 Removed case-sensitivity from property search
  apps/condo/domains/property/schema/CheckPropertyWithAddressExistService.js
Labels: small, ✋🙂 Review please

#444 SBERDOMA-818 Fix Resend message test
  apps/condo/domains/notification/schema/SendMessageService.test.js
Labels: small, HOTFIX, ✋🙂 Review please

#448 SBERDOMA-975 add unitName in ResidentTicketWhereInput
  apps/condo/domains/ticket/schema/GetAllResidentTicketsService.js
  apps/condo/schema.d.ts
Labels: small, ✋🙂 Review please

#449 SBERDOMA-137 added new ability `canManageDivisions` to OrganizationEmployeeRole
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.test.js
  apps/condo/migrations/20210811124116-0040_auto_20210811_1241.js
Labels: small, ✋🙂 Review please, Migrations

#452 SBERDOMA-999 - fix analytics page tabs default margin
  apps/condo/pages/analytics/detail/report_by_tickets/index.tsx
Labels: small, ✋🙂 Review please

#455 SBERDOMA-1003 Include req in gql context
  apps/condo/domains/common/utils/codegeneration/generate.server.utils.js
  apps/condo/domains/ticket/schema/TicketStatus.test.js
Labels: small, ✋🙂 Review please

#466 SBERDOMA-996 mobile api fix
  apps/condo/domains/organization/access/Organization.js
  apps/condo/domains/property/access/Property.js
Labels: small, HOTFIX, ✋🙂 Review please

#470 SBERDOMA-1025 Fix AddressMeta Json-validator schema for checkPropertyWithAddressExist
  apps/condo/domains/common/utils/addressApi/AddressMetaSchema.js
Labels: small, ✋🙂 Review please

#446 SBERDOMA-963 Migrate OrganizationEmployee PK to UUID.
  apps/condo/migrations/20210813135914-0042_auto_20210813_1359.js
  apps/condo/migrations/20210817111732-0043_auto_20210817_1117.js
Labels: ✋🙂 Review please, Migrations

#473 SBERDOMA-1038 Fix access to files for resident users
  apps/condo/domains/common/utils/sberCloudFileAdapter.js
Labels: small, HOTFIX, ✋🙂 Review please

#474 SBERDOMA-1041 - fix menu path in analytics
  apps/condo/pages/_app.tsx
Labels: small, ✋🙂 Review please

#476 SBERDOMA-1040 - replace local components loaders with antd skeleton
  apps/condo/domains/ticket/components/analytics/TicketChartView.tsx
  apps/condo/domains/ticket/components/analytics/TicketListView.tsx
Labels: small, ✋🙂 Review please

#483 SBERDOMA-910 add autoSize to details TextArea
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Labels: small

#490 SBERDOMA-1061 Make BillingIntegrationAccessRight PK to be UUID
  apps/condo/domains/billing/schema/BillingIntegrationAccessRight.js
  apps/condo/migrations/20210820182823-0046_auto_20210820_1328.js
Labels: small, ✋🙂 Review please, Migrations

#480 Fix/condo/sberdoma 1032&sberdoma 1033/validate settlement and house types
  apps/condo/domains/property/components/BasePropertyForm/index.tsx
  apps/condo/domains/property/constants/property.ts
  apps/condo/lang/en.json
  apps/condo/lang/ru.json
Labels: small, ✋🙂 Review please

#494 SBERDOMA-1039 Fix migrations script (delpoy demo fail)
  apps/condo/migrations/20210823172647-0047_auto_20210823_1226.js
Labels: small, HOTFIX, ✋🙂 Review please

#496 SBERDOMA-902 fix scroll in property map
  apps/condo/domains/property/components/BasePropertyForm/index.tsx
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: small, ✋🙂 Review please

#478 Fix/condo/sberdoma 1046/wrong data merging in use create client util
  apps/condo/domains/common/utils/codegeneration/generate.hooks.ts
Labels: small

#504 SBERDOMA-1084 Remove using of email from auth by phone
  apps/condo/domains/user/constants/common.js
  apps/condo/domains/user/schema/AuthenticateUserWithPhoneAndPasswordService.js
Labels: small, HOTFIX, ✋🙂 Review please

#512 SBERDOMA-1113 Add volume to validators
  apps/condo/domains/billing/utils/validation.utils.js
Labels: small, HOTFIX
