Repository open-condo-software/condo, pull requests merged in 2021-09, with the labels that each got.

#521 SBERDOMA-1116 migration to set `canManageDivisions` to administrator roles
  apps/condo/migrations/20210831103000-0050_manual_set_can_manage_divisions_to_administrator_organization_employee_roles.js
Labels: small, Migrations

#525 SBERDOMA-1135 fix ticket export add oldClassifier fill createdBy
  apps/condo/domains/ticket/schema/ExportTicketsService.js
  apps/condo/domains/ticket/templates/TicketsExportTemplate.xlsx
  apps/condo/domains/ticket/utils/serverSchema/index.js
Labels: small, HOTFIX, ✋🙂 Review please

#520 SBERDOMA-1128 property range limit
  apps/condo/domains/ticket/schema/TicketAnalyticsReportService.js
  apps/condo/schema.d.ts
Labels: small, HOTFIX

#529 SBERDOMA-1128 - analytics xlsx generation fix
  apps/condo/domains/ticket/schema/TicketAnalyticsReportService.js
  apps/condo/domains/ticket/utils/serverSchema/dayGroupDataMapper.js
  apps/condo/domains/ticket/utils/serverSchema/propertySummaryDataMapper.js
Labels: small, HOTFIX, ✋🙂 Review please

#535 SBERDOMA-1152 remove required fields from addressMeta
  apps/condo/domains/property/schema/fields/AddressMetaField.js
  apps/condo/schema.ts
Labels: small, HOTFIX

#537 SBERDOMA-1122 added type `AddressMetaDataMetroField` to `addressMeta.data.metro` field
  apps/condo/domains/property/schema/fields/AddressMetaField.js
Labels: small

#539 SBERDOMA-1122 changed `addressMeta.data.metro` from typed object to array of typed objects
  apps/condo/domains/property/schema/fields/AddressMetaField.js
Labels: small, 🦑 API CHANGES

#541 SBERDOMA-1157 Added colors for antd typography.text + alert
  apps/condo/domains/common/components/containers/GlobalStyle.tsx
  apps/condo/domains/common/constants/style.js
Labels: small, ✋🙂 Review please

#543 HOTFIX onboarding race condition
  apps/condo/domains/organization/components/OrganizationRequired.tsx
Labels: small, HOTFIX

#546 Fix/condo/sberdoma 1159/case insensitive check of address in register resident
  apps/condo/domains/resident/schema/Resident.js
  apps/condo/domains/resident/schema/Resident.test.js
Labels: HOTFIX

#549 DOMA-1167 Fixed russian plurals translation
  apps/condo/lang/ru.json
Labels: small, ✋🙂 Review please

#555 HOTFIX revered `shadow` constant suddenly replaced during rebase
  apps/condo/domains/common/constants/style.js
Labels: small, HOTFIX

#565 DOMA-1206 Fix "/property" layout
  apps/condo/domains/property/components/BuildingsTable.tsx
  apps/condo/domains/property/hooks/useTableColumns.tsx
Labels: small, ✋🙂 Review please

#575 DOMA-1192 fix property coords
  apps/condo/domains/common/components/PropertiesMap.tsx
Labels: small, ✋🙂 Review please

#581 DOMA-1229 Fix profile form reset password link
  apps/condo/domains/user/components/UserPasswordResetButton.tsx
Labels: small, HOTFIX, ✋🙂 Review please

#583 DOMA-1230 Changed phone generation for our tests
  apps/condo/domains/user/utils/testSchema/index.js
Labels: small, ✋🙂 Review please

#585 DOMA-1231 wrap analytics property page with feature flag
  apps/condo/pages/reports/detail/report-by-tickets/index.tsx
  apps/condo/pages/reports/detail/report-by-tickets/pdf.tsx
Labels: small, HOTFIX, ✋🙂 Review please

#587 DOMA-1237 Moved menuitem icons render from SSR to CSR
  apps/condo/domains/common/components/MenuItem.tsx
  apps/condo/domains/common/components/icons/ClientRenderedIcon.tsx
Labels: small, ✋🙂 Review please

#588 DOMA-1204 changed icon and title of division onboarding step
  apps/condo/domains/common/components/icons/DivisionIcon.tsx
  apps/condo/domains/onboarding/components/OnBoardingContext.tsx
  apps/condo/lang/ru.json
Labels: small

#589 DOMA-1183 renamed labels for groups "Technicians on division" to "Exe…
  apps/condo/lang/en.json
  apps/condo/lang/ru.json
Labels: small

#584 DOMA-1189 remove deleted properties from export
  apps/condo/domains/property/components/BuildingsTable.tsx
  apps/condo/domains/property/schema/ExportPropertiesToExcelService.js
Labels: small, HOTFIX, ✋🙂 Review please

#599 DOMA-1252 in test file from `createschema` changed relative import to absolute
  packages/@core.codegen/templates/schema00/domains/{{domain}}/schema/{{name}}.test.js
Labels: small

#597 DOMA-1246 Changing BillingReceipt services caching behaviour
  apps/condo/pages/_app.tsx
Labels: small, ✋🙂 Review please

#605 DOMA-1261 fix pie chart responsive style
  apps/condo/domains/ticket/components/analytics/TicketChartView.tsx
  apps/condo/domains/ticket/utils/helpers.ts
  apps/condo/pages/reports/detail/report-by-tickets/index.tsx
Labels: small, ✋🙂 Review please

#611 DOMA-1265 fix ticket warning modal translations
  apps/condo/lang/en.json
  apps/condo/lang/ru.json
Labels: small, HOTFIX, ✋🙂 Review please

#613 DOMA-1280 Fix settings feature-flags
  apps/condo/pages/_app.tsx
  apps/condo/pages/settings/index.tsx
Labels: small, ✋🙂 Review please

#612 DOMA-1278 add canManageAccess to default roles
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/schema/RegisterNewOrganizationService.test.js
  apps/condo/migrations/20210923141750-0060_manual_set_can_manage_meters_roles.js
  apps/condo/schema.ts
Labels: small, ✋🙂 Review please, Migrations

#616 DOMA-1267 use useSearch hook for reset offset in search input
  apps/condo/domains/division/components/DivisionsTable.tsx
  apps/condo/domains/property/components/BuildingsTable.tsx
Labels: small, ✋🙂 Review please

#626 HOTFIX add property address unique constraint
  apps/condo/domains/property/schema/Property.js
  apps/condo/migrations/20210927012007-0061_property_property_unique_organization_and_address.js
Labels: small, HOTFIX, Migrations

#628 HOTFIX fix problem with restore deleted resident
  apps/condo/domains/resident/schema/RegisterResidentService.test.js
  apps/condo/domains/resident/schema/Resident.js
Labels: small, HOTFIX

#627 DOMA-1282 add specification input state based on selected date range
  apps/condo/pages/reports/detail/report-by-tickets/index.tsx
Labels: small, ✋🙂 Review please

#621 DOMA-1262 add maxTagTextLength restriction for property search control
  apps/condo/domains/ticket/constants/restrictions.ts
  apps/condo/pages/reports/detail/report-by-tickets/index.tsx
Labels: small, ✋🙂 Review please

#633 DOMA-1294 decrease ticket details field min length from 20 to 6
  apps/condo/domains/ticket/components/BaseTicketForm/useTicketValidations.tsx
Labels: small, HOTFIX, ✋🙂 Review please

#635 DOMA-1305 add source field to xlsx ticket export
  apps/condo/domains/ticket/schema/ExportTicketsService.js
  apps/condo/domains/ticket/templates/TicketsExportTemplate.xlsx
  apps/condo/domains/ticket/utils/serverSchema/index.js
Labels: small, ✋🙂 Review please

#618 DOMA-1285 reset offset in filters modal
  apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
Labels: small, ✋🙂 Review please

#638 DOMA-1320 add support user access to read most of our entities
  apps/condo/domains/division/access/Division.js
  apps/condo/domains/meter/access/Meter.js
  apps/condo/domains/meter/access/MeterReading.js
  apps/condo/domains/organization/access/OrganizationEmployee.js
  apps/condo/domains/organization/access/OrganizationEmployeeRole.js
  apps/condo/domains/property/access/Property.js
  apps/condo/domains/ticket/access/Ticket.js
  apps/condo/domains/ticket/access/TicketCategoryClassifier.js
  apps/condo/domains/ticket/access/TicketChange.js
  apps/condo/domains/ticket/access/TicketClassifier.js
  apps/condo/domains/ticket/access/TicketClassifierRule.js
  apps/condo/domains/ticket/access/TicketComment.js
  apps/condo/domains/ticket/access/TicketFile.js
  apps/condo/domains/ticket/access/TicketPlaceClassifier.js
  apps/condo/domains/ticket/access/TicketProblemClassifier.js
  apps/condo/domains/ticket/access/TicketStatus.js
Labels: small, ✋🙂 Review please

#636 DOMA-1316 add eps submodule
  .gitmodules
Labels: small, ✋🙂 Review please

#642 Doma-1316 Eps submodule fix
  .gitmodules
Labels: small, ✋🙂 Review please, Collective work 🐜🐜🐜

#629 DOMA-1291 add createCronTask and removeCronTask
  packages/@core.keystone/tasks.js
Labels: small, ✋🙂 Review please
