Repository open-condo-software/condo, pull requests merged in 2022-08, with the labels that each got.

#2013 DOMA-3739 fix last column in table in create meter page
  apps/condo/domains/common/components/Table/Index.tsx
  apps/condo/domains/meter/components/CreateMeterReadingsForm.tsx
  apps/condo/domains/meter/hooks/useMeterTableColumns.tsx
Labels: 👶 small, ✋🙂 Review please

#2022 DOMA-3735 Fixed meter resident access
  apps/condo/domains/meter/access/Meter.js
  apps/condo/domains/meter/access/MeterReading.js
  apps/condo/domains/meter/schema/Meter.test.js
  apps/condo/domains/meter/schema/MeterReading.test.js
  apps/condo/domains/meter/utils/serverSchema/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1971 DOMA-3548 remove unnecessary useOrganizations
  apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx
Labels: 👶 small, ✋🙂 Review please

#2041 DOMA-3793 connected contact before connect resident client
  apps/condo/domains/ticket/schema/Ticket.js
  apps/condo/domains/ticket/schema/Ticket.test.js
Labels: 👶 small, ✋🙂 Review please

#2044 HOTFIX fix registration
  apps/condo/domains/user/components/auth/ValidatePhoneForm.tsx
Labels: 👶 small, ✋🙂 Review please

#2039 HOTFIX change task holder position
  apps/condo/domains/common/components/tasks/TaskProgress.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2050 DOMA-3810 add error state for `<TaskProgress />`
  apps/condo/domains/common/components/icons/CloseCircleIcon.tsx
  apps/condo/domains/common/components/tasks/TaskProgress.tsx
Labels: 👶 small, ✋🙂 Review please

#2033 DOMA-3722 added task, script, message data
  apps/condo/bin/notification/send-billing-receipt-push-notifications.js
  apps/condo/bin/notification/send-billing-receipt-push-residents.js
  apps/condo/bin/notification/send-remote-clients-upgrade-app-notifications.js
  apps/condo/domains/common/utils/date.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/gql.js
  apps/condo/domains/notification/schema/RemoteClient.js
  apps/condo/domains/notification/schema/RemoteClient.test.js
  apps/condo/domains/notification/tasks/index.js
  apps/condo/domains/notification/tasks/sendRemoteClientsUpgradeAppNotifications.js
  apps/condo/domains/notification/tasks/sendRemoteClientsUpgradeAppNotifications.spec.js
  apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.spec.js
  apps/condo/domains/resident/tasks/sendResidentsNoAccountNotifications.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/RESIDENT_UPGRADE_APP/default.njk
  apps/condo/lang/en/messages/RESIDENT_UPGRADE_APP/push.njk
  apps/condo/lang/en/messages/RESIDENT_UPGRADE_APP/sms.njk
  apps/condo/lang/en/messages/STAFF_UPGRADE_APP/default.njk
  apps/condo/lang/en/messages/STAFF_UPGRADE_APP/push.njk
  apps/condo/lang/en/messages/STAFF_UPGRADE_APP/sms.njk
  apps/condo/lang/ru/messages/RESIDENT_UPGRADE_APP/default.njk
  apps/condo/lang/ru/messages/RESIDENT_UPGRADE_APP/push.njk
  apps/condo/lang/ru/messages/RESIDENT_UPGRADE_APP/sms.njk
  apps/condo/lang/ru/messages/STAFF_UPGRADE_APP/default.njk
  apps/condo/lang/ru/messages/STAFF_UPGRADE_APP/push.njk
  apps/condo/lang/ru/messages/STAFF_UPGRADE_APP/sms.njk
  apps/condo/lang/ru/ru.json
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#2056 DOMA-3372 Placeholder for role name field
  apps/condo/domains/contact/components/contactRoles/BaseContactRoleForm.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2023 DOMA-3751 added lastCommentAt and completedAt to omit ticket change trackable fields
  apps/condo/domains/ticket/constants.js
  apps/condo/migrations/20220808113050-0163_remove_ticketchange_completedatfrom_and_more.js
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#2062 DOMA-3402 fixed filter labels text
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2071 HOTFIX added deletedAt filter in getByCondition in canManageUserTicketCommentReadTimes
  apps/condo/domains/ticket/access/UserTicketCommentReadTime.js
  apps/condo/domains/ticket/schema/UserTicketCommentReadTime.test.js
Labels: 👶 small, ✋🙂 Review please

#2072 DOMA-3879 added deletedAt checks on Resident in billing receipt push notification scripts
  apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.js
  apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.spec.js
  apps/condo/domains/resident/tasks/sendResidentsNoAccountNotifications.js
  apps/condo/domains/resident/tasks/sendResidentsNoAccountNotifications.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2084 DOMA-3887 add missed tooltip
  apps/condo/domains/common/components/icons/MobileIcon.tsx
  apps/condo/domains/ticket/components/TicketId/TicketResidentFeatures.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2038 HOTFIX enable cypress test run on each opened pr
  .github/workflows/nodejs.condo.cypress.yml
Labels: 👶 small, ✋🙂 Review please

#2100 DOMA-3921 fix isToday plugin import for dayjs at TasksLocalStorage
  apps/condo/domains/common/components/tasks/storage/TasksLocalStorage.tsx
  apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
Labels: 👶 small, ✋🙂 Review please

#2111 DOMA-3939 added pushToken logging
  apps/condo/domains/notification/adapters/firebaseAdapter.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2115 DOMA-3945 changed uniqKey from deviceId+date to userId+date
  apps/condo/domains/notification/tasks/sendRemoteClientsUpgradeAppNotifications.js
  apps/condo/domains/notification/tasks/sendRemoteClientsUpgradeAppNotifications.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2101 Adding meter readings without contacts
  apps/condo/domains/meter/components/CreateMeterReadingsActionBar.tsx
  apps/condo/domains/meter/components/CreateMeterReadingsForm.tsx
  apps/condo/domains/meter/components/ErrorsContainer.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2121 HOTFIX fixed ticketComment connect to ticketCommentFile
  apps/condo/domains/ticket/access/TicketCommentFile.js
  apps/condo/domains/ticket/access/TicketFile.js
  apps/condo/domains/ticket/schema/TicketCommentFile.test.js
  apps/condo/domains/ticket/schema/TicketFile.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2123 HOTFIX fixed ticket comment file null organization
  apps/condo/domains/organization/schema/plugins/addOrganizationFieldPlugin.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2112 DOMA-3924 add user filter to global miniapp tasks
  apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
Labels: 👶 small, ✋🙂 Review please

#2134 DOMA-3965 fixed billing-receipt-added script logic and tests
  apps/condo/domains/billing/gql.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.js
  apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2114 DOMA-3889 changed ticket hint styles
  apps/condo/domains/common/constants/style.js
  apps/condo/domains/ticket/components/TicketPropertyHint/TicketPropertyHintCard.tsx
Labels: 👶 small, ✋🙂 Review please

#2149 DOMA-3947 fix when settings page reload changes tab
  apps/condo/domains/common/constants/settingsTabs.js
  apps/condo/pages/settings/index.tsx
Labels: 👶 small

#2150 DOMA-3770 added redirect to ticket/{id} from ticket create page.
  apps/condo/domains/ticket/components/TicketForm/UpdateTicketForm.tsx
Labels: 👶 small, ✋🙂 Review please

#2156 HOTFIX: Support organization with >100 properties
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
Labels: 👶 small, 🔥 HOTFIX

#2159 DOMA-3439 fix Properties Export Template
  apps/condo/domains/property/templates/PropertiesExportTemplate.xlsx
Labels: 👶 small, ✋🙂 Review please

#2166 HOTFIX Fixed exporter job for new yarn
  .github/workflows/gitexporter.sh
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2157 DOMA-3983 clear search sting after select any option
  apps/condo/domains/common/components/GraphQlSearchInput.tsx
Labels: 👶 small, ✋🙂 Review please

#2170 DOMA-4020 fixed ios push sound issue
  apps/condo/domains/notification/adapters/firebaseAdapter.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😎 Cool

#2173 HOTFIX added style to select and input components
  apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
  apps/condo/domains/ticket/hooks/useModalFilterClassifiers.tsx
Labels: 🔥 HOTFIX

#2186 DOMA-3924 watch for user authenticated state
  apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
Labels: 👶 small, ✋🙂 Review please

#2184 DOMA-4062 fixed format date in deferred date picker
  apps/condo/domains/ticket/hooks/useTicketDeferModal.tsx
Labels: 👶 small, ✋🙂 Review please

#2193 build: added figma-tokens parse pipeline
  package.json
  packages/ui/.gitignore
  packages/ui/README.md
  packages/ui/bin/build-vars.js
  packages/ui/bin/prepare-tokens.js
  packages/ui/package.json
  packages/ui/sd.config.js
  yarn.lock
Labels: ✋🙂 Review please, 😎 Cool

#2182 DOMA-4061 fixed manual changing datepicker
  apps/condo/domains/ticket/components/BaseTicketForm/TicketDeadlineField.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/TicketDeferredDateField.tsx
Labels: 👶 small, ✋🙂 Review please

#2198 💄💄REFACTOR remove unnecessary TODO at ExternalReport schema💄💄
  apps/condo/domains/analytics/utils/clientSchema/ExternalReport.ts
  apps/condo/domains/analytics/utils/testSchema/index.js
Labels: 👶 small, ✋🙂 Review please

#2208 HOTFIX refetch global miniapps one time
  apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please
