Repository open-condo-software/condo, pull requests merged in 2022-09, with the labels that each got.

#2204 ci(DOMA-3814): added figma-tokens CI
  .github/workflows/packages.ui.lint.tokens.yml
  .github/workflows/packages.ui.merge.tokens.yml
  .github/workflows/packages.ui.rebase.tokens.yaml
  .stylelintrc.json
  package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 🎨 UI-kit

#2218 DOMA-4080 added cleaning duplicated organization ids in access checks…
  apps/condo/domains/ticket/access/TicketExportTask.js
  apps/condo/domains/ticket/schema/TicketExportTask.test.js
Labels: 👶 small

#2183 DOMA-3163 fix downloading files in ticket view (step 1)
  apps/condo/domains/common/utils/sberCloudFileAdapter.js
  apps/condo/domains/ticket/components/TicketId/TicketFileList.tsx
Labels: 👶 small, ✋🙂 Review please

#2230 DOMA-3291 added "returned" in ticket pdf printout
  apps/condo/pages/ticket/[id]/pdf.tsx
Labels: 👶 small, ✋🙂 Review please

#2231 DOMA-3874 added CUSTOM_CONTEXT_MESSAGE with templates, added script
  apps/condo/bin/lib/prompt.js
  apps/condo/bin/notification/send-custom-message-batch.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/gql.js
  apps/condo/domains/notification/schema/SendMessageService.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/CUSTOM_CONTENT_MESSAGE/default.njk
  apps/condo/lang/en/messages/CUSTOM_CONTENT_MESSAGE/push.njk
  apps/condo/lang/en/messages/CUSTOM_CONTENT_MESSAGE/sms.njk
  apps/condo/lang/ru/messages/CUSTOM_CONTENT_MESSAGE/default.njk
  apps/condo/lang/ru/messages/CUSTOM_CONTENT_MESSAGE/push.njk
  apps/condo/lang/ru/messages/CUSTOM_CONTENT_MESSAGE/sms.njk
  apps/condo/lang/ru/ru.json
  apps/condo/schema.ts
Labels: 🔥 HOTFIX, ✋🙂 Review please

#2233 DOMA-3874 fixed email sending issues
  apps/condo/bin/notification/send-custom-message-batch.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😎 Cool

#2232 build: DOMA-3815 added color-generator script
  .github/workflows/packages.ui.lint.tokens.yml
  packages/ui/.gitignore
  packages/ui/bin/generate-colors.js
  packages/ui/package.json
  packages/ui/src/colors/index.ts
  packages/ui/tsconfig.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 🎨 UI-kit

#2239 build: added basic webpack config for ts files
  packages/ui/.babelrc
  packages/ui/package.json
  packages/ui/src/colors/index.ts
  packages/ui/webpack.config.js
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😵‍💫 dependencies, 🎨 UI-kit

#2241 DOMA-4133 Added clear filter function for tooltip filters and fix it …
  apps/condo/domains/common/components/Table/Filters.tsx
Labels: 👶 small, ✋🙂 Review please

#2238 DOMA-4026 fix flattened import buttons on contact and meter page
  apps/condo/pages/contact/index.tsx
  apps/condo/pages/meter/index.tsx
Labels: 👶 small

#2234 DOMA-3964 fix parking label for resident ticket
  apps/condo/domains/ticket/utils/unit.js
Labels: 👶 small, ✋🙂 Review please

#2200 DOMA-4067 added delete contact duplicates script
  apps/condo/bin/contact/deleteContactDuplicates.js
  apps/condo/bin/contact/deleteContactDuplicates.spec.js
  apps/condo/bin/delete-contact-duplicates.js
Labels: ✋🙂 Review please

#2235 DOMA-3291 added reopen counter
  apps/condo/pages/ticket/[id]/pdf.tsx
Labels: 👶 small, ✋🙂 Review please

#2243 Add todo notes
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
Labels: 👶 small, ✋🙂 Review please

#2247 DOMA-4025 remove translation to lower case
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
Labels: 👶 small, ✋🙂 Review please

#2248 DOMA-4156 added try catch to reopen deffered tickets
  apps/condo/domains/ticket/tasks/reopenDeferredTickets.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2249 DOMA-4085 Pass role id instead of erroneous role name
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
Labels: 👶 small, ✋🙂 Review please

#2251 DOMA-4067 fixed deleteContactDuplicates tests
  apps/condo/bin/contact/deleteContactDuplicates.spec.js
Labels: 🔬 WIP

#2244 feat(condo): DOMA-3819 added customized storybook
  packages/ui/.gitignore
  packages/ui/.storybook/main.js
  packages/ui/.storybook/manager-head.html
  packages/ui/.storybook/manager.js
  packages/ui/.storybook/preview.js
  packages/ui/.storybook/theme.js
  packages/ui/package.json
  packages/ui/postcss.config.js
  packages/ui/public/favicon.ico
  packages/ui/public/logo.svg
  packages/ui/tsconfig.json
  packages/ui/webpack.config.js
  yarn.lock
Labels: ✋🙂 Review please, 😎 Cool, 🎨 UI-kit

#2253 feat(condo): DOMA-4151 switch to less tokens
  .github/workflows/packages.ui.build.yml
  .github/workflows/packages.ui.lint.tokens.yml
  .stylelintrc.json
  package.json
  packages/ui/bin/buildStyleVars/runner.js
  packages/ui/bin/buildStyleVars/transformers.js
  packages/ui/package.json
  packages/ui/sd.config.js
  yarn.lock
Labels: ✋🙂 Review please, 😵‍💫 dependencies, 🎨 UI-kit

#2257 DOMA-3964 fix unitType&sectionType in resident ticket
  apps/condo/domains/ticket/utils/unit.js
Labels: 👶 small, ✋🙂 Review please

#2258 DOMA-4109 fixed re fetch interval
  apps/condo/pages/ticket/index.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2259 chore(condo): DOMA-4133 close dropdown after clear filter
  apps/condo/domains/common/components/Table/Filters.tsx
Labels: 👶 small

#2262 fix(condo): DOMA-4091 correct display external report card on small screens
  apps/condo/pages/reports/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2264 ci(property-importer): DOMA-4160 change workspace name
  werf.yaml
Labels: 👶 small, ✋🙂 Review please

#2265 fix(condo): DOMA-1601 remove space from negative floor
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#2267 fix(condo): DOMA-3809 fix ticketCommentFileCount in exportTickets
  apps/condo/domains/ticket/tasks/exportTickets.js
Labels: 👶 small, ✋🙂 Review please

#2270 fix(condo): DOMA-4179 fixed BillingProperty display in admin-ui
  apps/condo/domains/billing/schema/BillingProperty.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2279 fix(condo): DOMA-4183 wrap words at PageHeader component
  apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
Labels: 👶 small, ✋🙂 Review please

#2274 fix(condo): DOMA-4122 fixed payments available indicator in ticket id page
  apps/condo/domains/ticket/components/TicketId/TicketResidentFeatures.tsx
Labels: 👶 small, ✋🙂 Review please

#2281 hotfix: resolute npm package
  package.json
  release.config.js
  yarn.lock
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😵‍💫 dependencies

#2280 feat(condo): DOMA-4121 added MessageBatch schema & migration and other
  apps/condo/bin/notification/send-custom-message-batch.js
  apps/condo/bin/notification/send-remote-clients-upgrade-app-notifications.js
  apps/condo/domains/common/constants/errors.js
  apps/condo/domains/common/utils/sleep.js
  apps/condo/domains/notification/access/MessageBatch.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/gql.js
  apps/condo/domains/notification/helpers/index.js
  apps/condo/domains/notification/helpers/sendRemoteClientsUpgradeAppNotifications.js
  apps/condo/domains/notification/helpers/sendRemoteClientsUpgradeAppNotifications.spec.js
  apps/condo/domains/notification/schema/MessageBatch.js
  apps/condo/domains/notification/schema/MessageBatch.test.js
  apps/condo/domains/notification/schema/SendMessageService.js
  apps/condo/domains/notification/schema/index.js
  apps/condo/domains/notification/tasks/deliverMessage.js
  apps/condo/domains/notification/tasks/index.js
  apps/condo/domains/notification/tasks/sendMessageBatch.helpers.js
  apps/condo/domains/notification/tasks/sendMessageBatch.helpers.test.js
  apps/condo/domains/notification/tasks/sendMessageBatch.js
  apps/condo/domains/notification/utils/clientSchema/MessageBatch.ts
  apps/condo/domains/notification/utils/clientSchema/index.ts
  apps/condo/domains/notification/utils/serverSchema/index.js
  apps/condo/domains/notification/utils/testSchema/index.js
  apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.js
  apps/condo/domains/resident/tasks/sendResidentsNoAccountNotifications.js
  apps/condo/migrations/20220914134959-0171_messagebatch_messagebatchhistoryrecord.js
  apps/condo/schema.ts
  packages/keystone/tasks.js
  packages/keystone/test.utils.js
Labels: ✋🙂 Review please, 🚨 Migrations, 😎 Cool

#2286 fix(condo): DOMA-4215 check country at existingItem
  apps/condo/domains/organization/schema/Organization.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2287 fix(condo): DOMA-4217 add react import on page load
  apps/condo/admin-ui/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2294 fix(condo): DOMA-3886 fix unitType display
  apps/condo/domains/billing/components/ServicesModal.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2295 ci(ui): DOMA-4211 UI-kit review job
  .github/workflows/packages.ui.review.yml
  packages/ui/package.json
  packages/ui/src/stories/colors.stories.tsx
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😵‍💫 dependencies, 😎 Cool, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit

#2283 DOMA-4103 change filter type
  apps/condo/domains/contact/hooks/useTableFilters.tsx
Labels: 👶 small, ✋🙂 Review please

#2305 fix(condo): DOMA-3992 fixed mobile icon markup
  apps/condo/domains/common/components/icons/MobileIcon.tsx
Labels: 👶 small, ✋🙂 Review please

#2308 DOMA-3200 unit name validation at property map form
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: 👶 small, ✋🙂 Review please

#2309 DOMA-3883 rename parking unit label
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2307 DOMA-3162 change map edit page title
  apps/condo/pages/property/[id]/map/update.tsx
Labels: 👶 small, ✋🙂 Review please

#2288 feat(condo): DOMA-4182 added validation for creating a duplicate cont…
  apps/condo/domains/common/components/containers/FormList.tsx
  apps/condo/domains/contact/components/CreateContactForm.tsx
  apps/condo/domains/contact/gql.js
  apps/condo/domains/contact/schema/Contact.js
  apps/condo/domains/contact/schema/Contact.test.js
  apps/condo/domains/user/constants/errors.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#2316 fix(condo): DOMA-4270 Localhost auth was fixed
  packages/keystone/setup.utils.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2311 fix(condo): DOMA-2866 correct a typo in error message
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2318 fix(condo): DOMA-2866 change error message
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2320 fix(condo): DOMA-4278 Fixed global apps endless re-rendering
  apps/condo/domains/common/hooks/useDeepCompareEffect.ts
  apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
  apps/condo/domains/miniapp/schema/B2BApp.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2319 fix(condo): DOMA-4262 fix validation in full name field
  apps/condo/domains/organization/components/EmployeeForm/CreateEmployeeForm.tsx
Labels: 👶 small

#2321 chore(condo): DOMA-3883 change unit ru translation at rename description
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2322 fix(condo): DOMA-4230 fix validation in email field
  apps/condo/domains/organization/components/EmployeeForm/CreateEmployeeForm.tsx
Labels: 👶 small, ✋🙂 Review please

#2326 DOMA-2628 added check suggested property with entered address
  apps/condo/domains/property/hooks/useImporterFunctions.tsx
Labels: 👶 small, ✋🙂 Review please

#2331 DOMA-3579 fix displaying create employee btn. Wrong access use
  apps/condo/pages/employee/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2324 DOMA-3529 fix import after changing organization
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/domains/meter/hooks/useImporterFunction.ts
  apps/condo/domains/property/hooks/useImporterFunctions.tsx
Labels: 👶 small, ✋🙂 Review please

#2327 fix(condo): DOMA-4014 trim role names before save
  apps/condo/domains/contact/components/contactRoles/BaseContactRoleForm.tsx
  apps/condo/domains/contact/components/contactRoles/useExistingContactRoles.tsx
  apps/condo/domains/contact/hooks/useContactRoleValidationRules.tsx
Labels: 👶 small, ✋🙂 Review please

#2334 fix(condo): DOMA-4306 refactor tests, fix random failing tests issue on MessageBatch
  apps/condo/domains/notification/access/MessageBatch.js
  apps/condo/domains/notification/schema/MessageBatch.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😎 Cool

#2338 fix(condo): DOMA-4307 fix get organization id
  apps/condo/pages/employee/index.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2345 chore(condo): DOMA-4316 increased max properties in the division
  apps/condo/domains/division/constants.js
  apps/condo/domains/division/schema/Division.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please
