Repository open-condo-software/condo, pull requests merged in 2022-04, with the labels that each got.

#1321 DOMA-2616 Extended filters popup
  apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
Labels: small, ✋🙂 Review please

#1334 DOMA-2439 add missed range picker callback
  apps/condo/pages/reports/detail/report-by-tickets/index.tsx
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1301 HOTFIX remove redundant file (apps/condo/domains/yarn.lock)
  apps/condo/domains/yarn.lock
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1345 DOMA-2342 More complex punctuation regex
  apps/condo/domains/common/utils/text.js
  apps/condo/domains/common/utils/text.spec.js
Labels: small, ✋🙂 Review please

#1351 DOMA-2647 Hide rubbish payments
  apps/condo/domains/acquiring/access/Payment.js
Labels: small, ✋🙂 Review please

#1362 DOMA-2629 fix auto classifier after QA tests
  apps/condo/domains/ticket/components/TicketClassifierSelect.tsx
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1382 DOMA-2710 disabled escaping for text emails
  apps/condo/lang/en/messages/MESSAGE_FORWARDED_TO_SUPPORT/email.njk
  apps/condo/lang/ru/messages/MESSAGE_FORWARDED_TO_SUPPORT/email.njk
Labels: small, ✋🙂 Review please

#1385 DOMA-2717 footer spacing between company contacts
  apps/condo/domains/user/components/containers/PosterLayout.tsx
Labels: small

#1388 DOMA-2532 remove unnecessary save button at edit parking form
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: small, ✋🙂 Review please

#1387 DOMA-2115 add responsive styles to unitType select control
  apps/condo/domains/property/components/panels/Builder/BuildingPanelCommon.tsx
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: small, ✋🙂 Review please

#1400 DOMA-2745 The ability for miniapp to use cross-site cookies
  apps/miniapp/index.js
Labels: small, ✋🙂 Review please

#1403 HOTFIX Added support access for creating billing / acquiring context
  apps/condo/domains/acquiring/access/AcquiringIntegrationContext.js
  apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.js
  apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.test.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
  apps/condo/domains/billing/access/BillingIntegrationOrganizationContext.js
  apps/condo/domains/billing/schema/BillingIntegrationOrganizationContext.js
  apps/condo/domains/billing/schema/BillingIntegrationOrganizationContext.test.js
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1413 DOMA-2742 fix bottom and color for footer + fix safari phone label align
  apps/condo/domains/user/components/auth/InputPhoneForm.tsx
  apps/condo/domains/user/components/auth/SignInForm.tsx
  apps/condo/domains/user/components/containers/PosterLayout.tsx
  apps/condo/domains/user/components/containers/styles.tsx
Labels: small, ✋🙂 Review please

#1402 DOMA-2072 fix modal buttons disabled styles
  apps/condo/domains/common/components/Button.tsx
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: small, ✋🙂 Review please

#1417 DOMA-2704 Add refetching query on finish
  apps/condo/domains/common/components/Import/Index.tsx
Labels: small, ✋🙂 Review please

#1419 DOMA-2768 fixed push notification titles for ticket assignee/executor connections
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/TICKET_ASSIGNEE_CONNECTED/push.njk
  apps/condo/lang/en/messages/TICKET_EXECUTOR_CONNECTED/push.njk
  apps/condo/lang/ru/messages/TICKET_ASSIGNEE_CONNECTED/push.njk
  apps/condo/lang/ru/messages/TICKET_EXECUTOR_CONNECTED/push.njk
  apps/condo/lang/ru/ru.json
Labels: small, 🔥 HOTFIX

#1394 HOTFIX run tests in single worker mode
  .github/workflows/nodejs.condo.test.yml
Labels: 🔥 HOTFIX

#1356 HOTFIX revert commented expect block at test utils
  apps/condo/domains/user/utils/testSchema/index.js
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1422 HOTFIX Update getting canManageProperties access
  apps/condo/domains/property/components/BuildingsTable.tsx
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1424 DOMA-2453 remove required email from sbbol user
  apps/condo/domains/organization/integrations/sbbol/common.js
  apps/condo/domains/organization/integrations/sbbol/sync/index.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1428 DOMA-1900 request configuration fixed
  apps/condo/domains/notification/schema/SetMessageStatusService.js
  apps/condo/domains/notification/utils/serverSchema/index.js
Labels: small, 🔥 HOTFIX

#1429 DOMA-1688 allow landline phones at contact create & update form
  apps/condo/domains/contact/components/CreateContactForm.tsx
  apps/condo/domains/contact/components/EditContactForm.tsx
Labels: small, ✋🙂 Review please

#1431 HOTFIX rollback jest run flags
  .github/workflows/nodejs.condo.test.yml
Labels: 🔥 HOTFIX

#1432 DOMA-2802 allow register new resident with unitType diff only
  apps/condo/domains/resident/schema/RegisterResidentService.js
  apps/condo/domains/resident/schema/RegisterResidentService.test.js
  apps/condo/domains/resident/schema/Resident.js
Labels: small, ✋🙂 Review please

#1434 DOMA-1688 allow landline phones via xlsx import
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
Labels: small, ✋🙂 Review please

#1436 DOMA-1523 fix floor saving to db
  apps/condo/domains/property/components/panels/Builder/BuildingEditTopMenu.tsx
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: small, ✋🙂 Review please

#1437 HOTFIX fix user.type === SERVICE logic
  apps/condo/domains/ticket/schema/TicketComment.js
Labels: 🔥 HOTFIX

#1438 DOMA-2772 fix import wrapper visibility
  apps/condo/domains/property/components/BuildingsTable.tsx
  apps/condo/pages/contact/index.tsx
  apps/condo/pages/meter/index.tsx
Labels: 👶 small, ✋🙂 Review please

#1458 DOMA-2811 fix undefined query at searchAddress callback
  apps/condo/domains/property/components/PropertyAddressSearchInput.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1454 DOMA-2772 toggle visibility of `<EmptyListView/>` when using with `<ImportWrapper />`
  apps/condo/domains/common/components/EmptyListView.tsx
  apps/condo/domains/property/components/BuildingsTable.tsx
  apps/condo/pages/contact/index.tsx
  apps/condo/pages/meter/index.tsx
Labels: 👶 small, ✋🙂 Review please

#1462 DOMA-2813 fix getClientSecret
  apps/condo/domains/organization/integrations/sbbol/utils/getOrganizationAccessToken.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1464 DOMA-2808 fix preview section floor index typo
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#1469 HOTFIX enable cypress tests on each push to master
  .github/workflows/nodejs.condo.cypress.yml
  apps/condo/cypress/integration/pages/auth.js
  apps/condo/cypress/integration/pages/ticket.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1473 HOTFIX remove console log
  apps/condo/domains/ticket/schema/Ticket.js
Labels: 👶 small, ✋🙂 Review please

#1472 HOTFIX adjust cypress config params
  apps/condo/cypress/cypress.json
  apps/condo/cypress/integration/pages/ticket.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1474 DOMA-1523 wrap add section floor with feature flag
  apps/condo/domains/property/components/panels/Builder/BuildingEditTopMenu.tsx
Labels: 👶 small, ✋🙂 Review please

#1480 DOMA-2832 extend address suggestion valid types array
  apps/condo/domains/property/constants/property.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1481 DOMA-2831 russian spelling fix
  apps/condo/lang/ru/ru.json
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1489 💄💄[DOMA-2850] 💄💄 Refactored text alignment in miniapps section
  apps/condo/domains/miniapp/components/AppDescription/AboutCard.tsx
Labels: 👶 small, ✋🙂 Review please

#1494 DOMA-2858 fixed isEmpty call
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1493 DOMA-2630 added dublicate contact validation error in contacts import
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#1495 DOMA-2860 increased allowed sender.fingerprint max length up to 256 symbols
  apps/condo/domains/common/schema/fields.js
  apps/condo/domains/notification/utils/testSchema/index.js
Labels: 👶 small

#1496 DOMA-2854 hide overdue message in completed, closed or canceled tickets
  apps/condo/pages/ticket/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#1503 DOMA-2885 calculate scrollTopMax if no scrollTopMax property in target
  apps/condo/domains/common/utils/select.utils.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1506 DOMA-2887 fixed infinity scroll in gql search
  apps/condo/domains/common/components/GraphQlSearchInput.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please
