Repository open-condo-software/condo, pull requests merged in 2022-01, with the labels that each got.

#1024 DOMA-1891: werf.yaml: add base image and optimise yarn install
  werf.yaml
Labels: small, ✋🙂 Review please

#1038 DOMA-1930 fix random test in OrganizationLink domain
  apps/condo/domains/organization/schema/OrganizationLink.test.js
Labels: small, ✋🙂 Review please

#1042 DOMA-1720 fixed text color on disabled ticket status select
  apps/condo/domains/ticket/components/TicketStatusSelect.tsx
Labels: small, ✋🙂 Review please

#1041 DOMA-1875 disabled ability to edit closed ticket
  apps/condo/pages/ticket/[id]/index.tsx
Labels: small, ✋🙂 Review please

#1044 Add access to support users to change/softDelete organisation employees
  apps/condo/domains/organization/access/OrganizationEmployee.js
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1047 DOMA-1770 added spase after import button on contact and property pages
  apps/condo/domains/property/components/BuildingsTable.tsx
  apps/condo/pages/contact/index.tsx
Labels: ✋🙂 Review please

#1022 HOTFIX clean up index.js style
  apps/condo/index.js
Labels: small, ✋🙂 Review please

#1033 Fix/condo/doma 1907/missing classifier in print version of ticket page
  apps/condo/pages/ticket/[id]/index.tsx
  apps/condo/pages/ticket/[id]/pdf.tsx
Labels: 🔥 HOTFIX

#1057 DOMA-2001 fix section button overflow
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: small, ✋🙂 Review please

#1059 DOMA-1748 send sms after sbbol auth
  apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js
Labels: small, ✋🙂 Review please

#1068 DOMA-2013 adjust ticket table column size for small screens
  apps/condo/domains/ticket/hooks/useTableColumns.tsx
Labels: small, ✋🙂 Review please

#1070 DOMA-2017 new template for tickets export
  apps/condo/domains/ticket/templates/TicketsExportTemplate.xlsx
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1075 DOMA-2023 fix noninteractive style for unit button
  apps/condo/domains/property/components/panels/Builder/UnitButton.tsx
Labels: small, ✋🙂 Review please

#984 DOMA-625 Remove dots from username
  apps/condo/domains/user/components/UserMenu/DesktopUserMenu.tsx
Labels: small

#1074 DOMA-2024 fixed unit filter on meter page
  apps/condo/domains/meter/hooks/useFilters.tsx
Labels: small, ✋🙂 Review please

#1093 DOMA-2108 used null instead undefined in unitName search
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: small, ✋🙂 Review please
