Repository open-condo-software/condo, pull requests merged in 2022-02, with the labels that each got.

#1108 DOMA-2147 remove number symbol from section name at property import
  apps/condo/domains/property/hooks/useImporterFunctions.tsx
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1112 DOMA-2163 fix negative floor creation
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: small, ✋🙂 Review please

#1116 [BUG 🐞] DOMA-1667 Pagination on division page was fixed
  apps/condo/domains/common/components/Table/Index.tsx
  apps/condo/pages/division/[id]/index.tsx
Labels: small, ✋🙂 Review please

#1117 DOMA-1410 [BUG 🐞] SMS code input is now clearing any non-digit characters
  apps/condo/domains/user/components/auth/ValidatePhoneForm.tsx
Labels: small, ✋🙂 Review please

#1126 DOMA-2197 add apple-app-site-association
  apps/condo/public/apple-app-site-association
Labels: small, ✋🙂 Review please

#1137 HOTFIX add unitType constants to property
  apps/condo/domains/property/constants/common.js
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1141 DOMA-2231 fixed auto detecded message on update form of old tickets
  apps/condo/domains/ticket/components/BaseTicketForm/TicketDeadlineField.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
  apps/condo/domains/user/components/UnitNameInput.tsx
Labels: small, ✋🙂 Review please

#1144 [INFRA 🌎] DOMA-2233 Expand session-cookie lifetime
  packages/@core.keystone/setup.utils.js
Labels: small, ✋🙂 Review please

#1148 DOMA-2236 fixed crash of Keystone while `changeTrackable` module processed fields of type `Select`
  apps/condo/domains/common/utils/serverSchema/changeTrackable.js
Labels: 🔥 HOTFIX

#1161 DOMA-1956 Fixed typo in the onboarding header
  apps/condo/lang/en.json
  apps/condo/lang/ru.json
Labels: small, ✋🙂 Review please

#1162 DOMA-1961 Fixed typo in the creation/edit organization popup
  apps/condo/lang/en.json
  apps/condo/lang/ru.json
Labels: small, ✋🙂 Review please

#1147 DOMA-2235 added meter account number client validation
  apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalAccountNumberField.tsx
  apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx
  apps/condo/domains/meter/components/CreateMeterReadingsForm.tsx
  apps/condo/domains/meter/hooks/useCreateMeterModal.tsx
  apps/condo/domains/meter/hooks/useMeterValidations.ts
  apps/condo/domains/meter/hooks/useUpdateMeterModal.tsx
  apps/condo/lang/en.json
  apps/condo/lang/ru.json
Labels: ✋🙂 Review please

#1169 DOMA-2302 fixed FIELDS const in clientSchema
  apps/condo/domains/meter/utils/clientSchema/MeterReadingFilterTemplate.ts
Labels: small, ✋🙂 Review please

#1178 DOMA-2309 swapped primary and secondary colors
  apps/condo/domains/ticket/components/TicketStatusSelect.tsx
  apps/condo/domains/ticket/constants/style.js
  apps/condo/domains/ticket/hooks/useTableColumns.tsx
  apps/condo/domains/ticket/schema/TicketAnalyticsReportService.js
Labels: 🔥 HOTFIX, ✋🙂 Review please

#1179 fix/condo/DOMA-2310/use full url for localhost
  apps/condo/domains/common/utils/fileAdapter.js
  apps/condo/domains/notification/transports/email.js
  apps/condo/domains/user/schema/SendMessageToSupportService.js
Labels: small, ✋🙂 Review please

#1184 DOMA-2315 fix sender type for sendMessageToSupport
  apps/condo/domains/user/schema/SendMessageToSupportService.js
  apps/condo/schema.ts
Labels: small, ✋🙂 Review please

#1189 DOMA-2346 fix multiPayment amount calculation
  apps/condo/domains/acquiring/schema/MultiPayment.js
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1187 DOMA-1600 ignore browser history when resolve ticket update action
  apps/condo/domains/ticket/components/TicketForm/UpdateTicketForm.tsx
Labels: small, ✋🙂 Review please

#1191 HOTFIX fix en translations for modal unit types after rebase
  apps/condo/lang/en.json
Labels: small, merged 🐛, 🔥 HOTFIX, ✋🙂 Review please
