Repository open-condo-software/condo, pull requests merged in 2022-07, with the labels that each got.

#1827 HOTFIX generate.test.utils.js: remove useless legacy
  apps/condo/domains/common/utils/codegeneration/generate.test.utils.js
Labels: 👶 small, ✋🙂 Review please

#1860 DOMA-3282 add description for payment order
  apps/condo/domains/acquiring/schema/Payment.js
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#1862 HOTFIX improve local test debugging
  apps/condo/docs/development/local-setup.md
  packages/@core.keystone/test.utils.js
Labels: 👶 small, ✋🙂 Review please

#1878 DOMA-3163 fixed opening files in ticket view
  apps/condo/pages/ticket/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#1883 DOMA-3260 rolled back wydr params
  apps/condo/domains/common/components/wdyr.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1866 HOTFIX use dvAndSender() plugin for AcquiringIntegration.js
  apps/condo/domains/acquiring/schema/AcquiringIntegration.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1887 [DOMA-3470] add ability to set `Ticket.unitType` to null
  apps/condo/domains/ticket/schema/Ticket.js
  apps/condo/domains/ticket/schema/Ticket.test.js
  apps/condo/migrations/20220706181040-0143_alter_ticket_unittype.js
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#1896 [DOMA-3477] add ability to set `Contact.unitType` to null
  apps/condo/domains/contact/schema/Contact.js
  apps/condo/domains/contact/schema/Contact.test.js
  apps/condo/migrations/20220707181939-0145_alter_contact_unittype.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#1892 DOMA-3204 fixed test out of memory issue
  .github/workflows/nodejs.condo.test.yml
Labels: 👶 small, ✋🙂 Review please

#1916 DOMA-3141 fixed where condition in useOrganizationInvites hook
  apps/condo/domains/organization/hooks/useOrganizationInvites.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1852 DOMA-3375 fixed `reduceNonEmpty` function
  apps/condo/pages/ticket/index.tsx
Labels: 👶 small, ✋🙂 Review please

#1929 HOTFIX Add dv and sender
  apps/condo/domains/meter/schema/Meter.js
Labels: 👶 small, 🔥 HOTFIX

#1928 DOMA-3556 updated message type detection logic, added tests
  apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.js
  apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.spec.js
Labels: 👶 small, ✋🙂 Review please

#1936 DOMA-3199 fixed closedAt value in export tickets
  apps/condo/domains/ticket/utils/serverSchema/index.js
Labels: 👶 small, ✋🙂 Review please

#1954 DOMA-3622 fixed connect ticketPropertyHint statement
  apps/condo/domains/ticket/components/TicketPropertyHint/BaseTicketPropertyHintForm.tsx
  apps/condo/domains/ticket/components/TicketPropertyHint/SettingsContent.tsx
Labels: 👶 small, ✋🙂 Review please

#1953 DOMA-2570 some fixes made to billing receipt notification scripts
  apps/condo/bin/notification/send-billing-receipt-push-notifications.js
  apps/condo/bin/notification/send-residents-no-account-notifications.js
  apps/condo/bin/notification/send-residents-receipt-added-notifications.js
  apps/condo/domains/notification/adapters/firebaseAdapter.js
  apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.js
  apps/condo/domains/resident/tasks/sendResidentsNoAccountNotifications.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1940 Fix/condo/doma 3536/deleting meter readings by property id script
  apps/condo/bin/README.md
  apps/condo/bin/delete-meters-by-property-ids.js
Labels: 👶 small, ✋🙂 Review please

#1956 DOMA-3635 resetUser will remove all OrganizationEmployee
  apps/condo/domains/user/schema/ResetUserService.js
  apps/condo/domains/user/schema/ResetUserService.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1957 HOTFIX remove deprecated ticket fields from cypress ticket plugin
  apps/condo/cypress/plugins/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1958 HOTFIX add side effects dependencies to all visit actions at ticket tests
  apps/condo/cypress/objects/Ticket.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1972 DOMA-2934 fixed layout in create ticket view
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Labels: 👶 small

#1973 DOMA-2933 fixed grid for block with residents contacts in create tick…
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small

#1976 DOMA-2924 fixed align items in divisions table in properties view
  apps/condo/domains/division/components/DivisionsTable.tsx
Labels: 👶 small, ✋🙂 Review please

#1990 fix/condo/doma-3697/roles-sorting
  apps/condo/domains/contact/components/contactRoles/ContactRolesSettingsContent.tsx
Labels: 👶 small, ✋🙂 Review please

#1989 fix/condo/doma-3696/deleted-roles-in-export
  apps/condo/domains/contact/schema/ExportContactsService.js
Labels: 👶 small, ✋🙂 Review please

#1992 fix/condo/doma-3699/settings-page-layout
  apps/condo/domains/common/components/settings/SettingsPageContent.tsx
  apps/condo/domains/common/components/settings/Tabs.tsx
Labels: 👶 small, ✋🙂 Review please

#1970 Contact fields validation added on meter create page
  apps/condo/domains/meter/components/CreateMeterReadingsActionBar.tsx
  apps/condo/domains/meter/components/ErrorsContainer.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#1991 fix/condo/doma-3698/wrong-roles-sorting
  apps/condo/domains/contact/components/contactRoles/ContactRolesSettingsContent.tsx
Labels: 👶 small, ✋🙂 Review please

#1998 fix/condo/doma-3727/fix-submodule-url
  .gitmodules
Labels: 👶 small, ✋🙂 Review please

#1995 fix/condo/doma-3726/rename-role
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#1984 DOMA-3404 fixed deliting file from comment
  apps/condo/domains/common/components/MultipleFileUpload.tsx
Labels: 👶 small, ✋🙂 Review please

#2000 DOMA-3692 fixed section and floor render in ticket table
  apps/condo/domains/ticket/components/TicketId/TicketPropertyField.tsx
  apps/condo/domains/ticket/hooks/useTableColumns.tsx
  apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
Labels: 👶 small, ✋🙂 Review please

#2001 fix/cindo/doma-3730/filter-roles-for-support
  apps/condo/domains/contact/components/contactRoles/ContactRolesSettingsContent.tsx
Labels: 👶 small, ✋🙂 Review please

#2006 fix/condo/doma-3636/detect-active-menu-item
  apps/condo/domains/common/components/MenuItem.tsx
Labels: 👶 small, ✋🙂 Review please
