Repository open-condo-software/condo, pull requests merged in 2022-05, with the labels that each got.

#1522 DOMA-2909 Expanded meter domain
  apps/condo/domains/meter/access/MeterReadingSource.js
  apps/condo/domains/meter/constants/constants.js
  apps/condo/domains/meter/schema/Meter.js
  apps/condo/domains/meter/schema/Meter.test.js
  apps/condo/domains/meter/schema/MeterReading.test.js
  apps/condo/domains/meter/schema/MeterReadingSource.js
  apps/condo/domains/meter/schema/MeterReadingSource.test.js
  apps/condo/domains/meter/utils/serverSchema/index.js
  apps/condo/migrations/20220504150845-0126_meter_isautomatic_meterhistoryrecord_isautomatic_and_more.js
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#1542 DOMA-2917 script fixed after testing
  apps/condo/bin/send-billing-receipt-push-notifications.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1547 HOTFIX revert property map constant require path
  apps/condo/domains/property/utils/testSchema/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1572 DOMA-2695 fix assignee link
  apps/condo/pages/ticket/[id]/index.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1571 Doma-2864 print phones on ticket pdf
  apps/condo/pages/ticket/[id]/pdf.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1584 DOMA-2976 fix build
  apps/condo/domains/common/utils/fileAdapter.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1568 DOMA-2852 Add trim to string filters
  apps/condo/domains/common/utils/tables.utils.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1581 DOMA-2867 fix empty list view shown on loading stage
  apps/condo/domains/property/components/BuildingsTable.tsx
  apps/condo/pages/contact/index.tsx
  apps/condo/pages/meter/index.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1549 HOTFIX explicit value for checking resident access rights
  apps/condo/domains/ticket/access/TicketComment.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1582 DOMA-2971 added script sending notifications to all residents on properties with billing receipts for period and context
  apps/condo/bin/send-billing-receipt-push-notifications.js
  apps/condo/bin/send-billing-receipt-push-residents.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/BILLING_RECEIPT_AVAILABLE_NO_ACCOUNT_MANUAL/default.njk
  apps/condo/lang/en/messages/BILLING_RECEIPT_AVAILABLE_NO_ACCOUNT_MANUAL/push.njk
  apps/condo/lang/en/messages/BILLING_RECEIPT_AVAILABLE_NO_ACCOUNT_MANUAL/sms.njk
  apps/condo/lang/ru/messages/BILLING_RECEIPT_AVAILABLE_NO_ACCOUNT_MANUAL/default.njk
  apps/condo/lang/ru/messages/BILLING_RECEIPT_AVAILABLE_NO_ACCOUNT_MANUAL/push.njk
  apps/condo/lang/ru/messages/BILLING_RECEIPT_AVAILABLE_NO_ACCOUNT_MANUAL/sms.njk
  apps/condo/lang/ru/ru.json
Labels: 🔥 HOTFIX, ✋🙂 Review please

#1587 DOMA-2968 fix division page display on master delete
  apps/condo/pages/division/[id]/index.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1597 HOTFIX add Url field support to createschema util
  packages/@core.codegen/index.js
  packages/@core.codegen/templates/schema00/domains/{{domain}}/schema/{{name}}.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1599 INFRA add miniapp folder to gitexporter
  .github/workflows/gitexporter.sh
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1600 DOMA-2989 remove deleted objects from exports with GqlWithKnexLoadList
  apps/condo/domains/common/utils/serverSchema/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1601 DOMA-2864 Add assignee and executor phone to pdf file
  apps/condo/pages/ticket/[id]/pdf.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1598 HOTFIX use dvAndSender() plugin inside templates
  packages/@core.codegen/templates/schema00/domains/{{domain}}/schema/{{name}}.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1607 INFRA Specified adapter for front build test
  .github/workflows/nodejs.condo.test.yml
Labels: 👶 small, ✋🙂 Review please

#1613 INFRA Fix FILE_FIELD_ADAPTER during the build
  apps/condo/index.js
Labels: 👶 small, ✋🙂 Review please

#1614 DOMA-3029 add unitType to ContactEditor search expression
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Labels: 👶 small, ✋🙂 Review please

#1617 DOMA-3040 display unitType prefix at contact table cell
  apps/condo/domains/contact/hooks/useTableColumns.tsx
Labels: 👶 small, ✋🙂 Review please

#1596 HOTFIX change default template access to FALSE to avoid developer errors
  packages/@core.codegen/templates/schema00/domains/{{domain}}/access/{{name}}.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1624 HOTFIX Make auth viable throw API
  apps/condo/domains/user/schema/AuthenticateUserWithPhoneAndPasswordService.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1620 DOMA-2447 fix date selection for `TicketAnaliticsReportService`
  apps/condo/domains/ticket/utils/serverSchema/analytics.helper.js
Labels: 👶 small, ✋🙂 Review please

#1627 DOMA-2443 Remove a group of radio buttons for selecting a period
  apps/condo/pages/reports/detail/report-by-tickets/index.tsx
Labels: 👶 small

#1628 DOMA-3074 reenabled push notifications on ticket comments for resident
  apps/condo/domains/ticket/schema/TicketComment.js
  apps/condo/domains/ticket/schema/TicketComment.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1632 DOMA-2442 fix filter selection `groupTicketsBy` in table on report-b…
  apps/condo/pages/reports/detail/report-by-tickets/index.tsx
Labels: 👶 small

#1630 DOMA-3086 Center alignment of numbers on ticket page
  apps/condo/domains/ticket/hooks/useTableColumns.tsx
Labels: 👶 small

#1636 DOMA-3092 contact import include unit type
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/domains/ticket/utils/clientSchema/search.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/public/contact-import-example.xlsx
Labels: 👶 small, ✋🙂 Review please

#1640 DOMA-3097 add unitType field to contact exporting fields
  apps/condo/domains/common/utils/exportToExcel.js
  apps/condo/domains/contact/schema/ExportContactsService.js
  apps/condo/domains/contact/templates/ContactsExportTemplate.xlsx
  apps/condo/domains/contact/utils/serverSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#1648 DOMA-2988 add unitName column to `ReceiptsTable`
  apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
  apps/condo/domains/billing/hooks/useReceiptTableColumns.ts
Labels: 👶 small, ✋🙂 Review please

#1645 DOMA-3088 Ability to send commands to IFrame and send answer back
  apps/condo/domains/common/components/IFrame/IFrame.tsx
  apps/condo/domains/common/utils/iframe.utils.ts
Labels: ✋🙂 Review please

#1662 DOMA-3138 fixed ticket number overlapping by indicator on small screens
  apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
Labels: 👶 small, ✋🙂 Review please
