Repository open-condo-software/condo, pull requests merged in 2022-12, with the labels that each got.

#2643 fix(address-service): DOMA-4797 Some address parts types were added t…
  apps/address-service/domains/address/schema/AddressInjection.js
  packages/keystone/fields/AddressPartWithType/views/Field.js
Labels: 👶 small, ✋🙂 Review please

#2646 DOMA-4814 make property map submit button primary
  apps/condo/domains/property/components/panels/Builder/forms/FloorForm.tsx
  apps/condo/domains/property/components/panels/Builder/forms/ParkingForm.tsx
  apps/condo/domains/property/components/panels/Builder/forms/ParkingUnitForm.tsx
  apps/condo/domains/property/components/panels/Builder/forms/SectionForm.tsx
  apps/condo/domains/property/components/panels/Builder/forms/UnitForm.tsx
Labels: 👶 small, ✋🙂 Review please

#2652 fix(condo): DOMA-4793 don't show receipt modal if no services
  apps/condo/domains/billing/components/ServicesModal.tsx
Labels: 👶 small

#2633 fix(condo): DOMA-3203 fixed default filters on second click to /payme…
  apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx
Labels: 👶 small, ✋🙂 Review please

#2657 hotfix(condo): HOTFIX fix employees search
  apps/condo/domains/organization/hooks/useTableFilters.tsx
Labels: 🔥 HOTFIX

#2660 fix(condo): DOMA-4835 fix AutoAssigner
  apps/condo/domains/organization/utils/clientSchema/OrganizationEmployee.ts
  apps/condo/domains/ticket/components/BaseTicketForm/AutoAssigner.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/TicketAssignments.tsx
  packages/codegen/generate.hooks.ts
Labels: ✋🙂 Review please

#2663 hotfix(condo): HOTFIX used get in getEmployeesSortedByTicketVisibilityType
  apps/condo/domains/scope/utils/clientSchema/utils.tsx
Labels: 🔥 HOTFIX

#2664 refactor(condo): DOMA-4604 Moved block tabs out of settings
  apps/condo/domains/common/components/Tabs.tsx
  apps/condo/domains/common/components/settings/SettingsPageContent.tsx
  apps/condo/domains/common/components/settings/Tabs.tsx
  apps/condo/domains/common/constants/style.js
Labels: 👶 small, ✋🙂 Review please

#2675 feat(condo): DOMA-4877 added type to push data payload
  apps/condo/domains/notification/adapters/firebaseAdapter.js
  apps/condo/domains/notification/adapters/firebaseAdapter.spec.js
  apps/condo/domains/notification/schema/MessageBatch.test.js
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#2679 fix(condo): DOMA-2566 fixed notification type in message payload issue
  apps/condo/domains/notification/adapters/firebaseAdapter.js
  apps/condo/domains/notification/adapters/firebaseAdapter.spec.js
  apps/condo/domains/notification/templates.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😎 Cool

#2677 fix(address-service): DOMA-4883 restrict some resident's fields to be…
  apps/condo/domains/property/schema/Property.js
  apps/condo/domains/resident/schema/Resident.js
  packages/keystone/plugins/addressService.js
Labels: 👶 small, ✋🙂 Review please

#2681 fix(address-service): DOMA-4880 Address service client + POST = ❤️
  packages/keystone/plugins/addressService.js
  packages/keystone/plugins/utils/address-service-client/AddressServiceClient.js
  packages/keystone/plugins/utils/address-service-client/index.js
Labels: 👶 small, ✋🙂 Review please

#2682 fix(condo): DOMA-4898 fix contact phone validation
  apps/condo/domains/contact/components/ContactsEditor/NewContactFields.tsx
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2684 fix(condo): DOMA-4901 fix AssigneeScope creation error
  apps/condo/domains/scope/schema/AssigneeScope.test.js
  apps/condo/domains/scope/utils/serverSchema/index.js
Labels: 👶 small, ✋🙂 Review please

#2685 feat(global): add empty option to kmigrator
  bin/kmigrator.py
Labels: 👶 small, ✋🙂 Review please

#2690 fix(condo): DOMA-4908 fix name input enable when no contacts on unit
  apps/condo/domains/contact/components/ContactsEditor/NewContactFields.tsx
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2693 feat(condo): DOMA-4917 add analytics for ticket blank export
  apps/condo/domains/ticket/hooks/useTicketExportToPdfTask.tsx
  apps/condo/pages/ticket/[id]/index.tsx
  apps/condo/pages/ticket/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2696 fix(condo): DOMA-4939 fix filter employee by role
  apps/condo/domains/organization/hooks/useTableFilters.tsx
Labels: 👶 small, ✋🙂 Review please

#2697 fix(condo): DOMA-4940 fix order calculation
  apps/condo/domains/ticket/schema/Ticket.js
Labels: 👶 small, ✋🙂 Review please

#2695 chore(condo): DOMA-4913 update text in notification after ticket creation
  apps/condo/domains/common/constants/regexps.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/ticket/utils/handlers.js
  apps/condo/lang/ru/messages/TRACK_TICKET_IN_DOMA_APP/default.njk
  apps/condo/lang/ru/messages/TRACK_TICKET_IN_DOMA_APP/sms.njk
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#2698 DOMA-4899 add meter number validation to update modal
  apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx
  apps/condo/domains/meter/hooks/useMeterValidations.ts
Labels: 👶 small, ✋🙂 Review please

#2700 DOMA-4857 existing property validation
  apps/condo/domains/property/components/BasePropertyForm/index.tsx
  apps/condo/domains/property/hooks/usePropertyValidations.ts
Labels: 👶 small, ✋🙂 Review please

#2708 fix(condo): DOMA-4405 fix print ticket blank
  apps/condo/pages/ticket/index.tsx
Labels: ✋🙂 Review please

#2711 fix(condo): DOMA-4643 Fixed icon behaviour in tabs
  apps/condo/domains/common/components/Tabs.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2699 feat(condo) DOMA-2566 HUAWEI transport draft implementation done
  .env.example
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/notification/adapters/firebaseAdapter.js
  apps/condo/domains/notification/adapters/firebaseAdapter.spec.js
  apps/condo/domains/notification/adapters/hcm/auth.js
  apps/condo/domains/notification/adapters/hcm/constants.js
  apps/condo/domains/notification/adapters/hcm/messaging.js
  apps/condo/domains/notification/adapters/hcm/messaging.spec.js
  apps/condo/domains/notification/adapters/hcm/validators.js
  apps/condo/domains/notification/adapters/hcmAdapter.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/constants/errors.js
  apps/condo/domains/notification/tasks/deliverMessage.js
  apps/condo/domains/notification/tasks/sendMessageBatch.helpers.js
  apps/condo/domains/notification/tasks/sendMessageBatch.helpers.test.js
  apps/condo/domains/notification/transports/push.js
  apps/condo/domains/notification/transports/push.spec.js
  apps/condo/domains/notification/utils/testSchema/helpers.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.js
  apps/condo/domains/ticket/schema/Ticket.test.js
  apps/condo/domains/ticket/schema/TicketComment.test.js
  apps/condo/domains/user/utils/googleRecaptcha3.js
  apps/condo/package.json
  yarn.lock
Labels: ✋🙂 Review please, 😎 Cool, 🐘 BIG

#2719 hotfix(condo): Returned support rights to visit billing miniapps temporally
  apps/condo/domains/miniapp/components/AppIndex/BillingAppPage.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2720 DOMA-4857 check for initial address at property update form
  apps/condo/domains/property/components/BasePropertyForm/index.tsx
  apps/condo/domains/property/hooks/usePropertyValidations.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2723 hotfix(condo): Extend miniapps gql to include external
  apps/condo/domains/miniapp/gql.js
  apps/condo/domains/miniapp/schema/B2BAppPromoBlock.test.js
Labels: 👶 small, 🔥 HOTFIX

#2706 feat(condo): DOMA-4395 added new relationship `property` to BankAccount
  apps/condo/domains/banking/schema/BankAccount.js
  apps/condo/domains/banking/schema/BankAccount.test.js
  apps/condo/domains/banking/utils/testSchema/index.js
  apps/condo/migrations/20221221153346-0203_auto_20221221_1234.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🔬 WIP

#2683 fix(ui): DOMA-4653 fix borders style of markdown table
  packages/ui/src/components/style/mixins/table.less
Labels: 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#2715 fix(condo): DOMA-4998 fix files download without redirect url
  apps/condo/domains/common/hooks/useDownloadFileFromServer.ts
Labels: 👶 small, ✋🙂 Review please

#2737 fix(ui): DOMA-5035 added bottom margin to first header in markdown
  packages/ui/src/components/Markdown/style.less
Labels: 👶 small, 🎨 UI-kit, 📦 Packages

#2730 fix(ui): DOMA-5029 fix modal animation
  packages/ui/src/components/Modal/modal.tsx
  packages/ui/src/components/Modal/style.less
  packages/ui/src/stories/Modal.stories.tsx
Labels: ✋🙂 Review please, 🎨 UI-kit, 📦 Packages

#2742 feat(tsconfig): DOMA-5048 Introduced tsconfig package
  bin/publish-packages.js
  packages/codegen/templates/app00/tsconfig.json
  packages/tsconfig/README.md
  packages/tsconfig/base.json
  packages/tsconfig/next-app.json
  packages/tsconfig/package.json
  packages/tsconfig/react-lib.json
  packages/ui/package.json
  packages/ui/tsconfig.json
  packages/ui/tsconfig.prod.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😵‍💫 dependencies, 📦 Packages

#2748 fix(icons): DOMA-5017 Expanded docs and trigger publishing job
  packages/icons/README.md
Labels: 👶 small, 🔥 HOTFIX, 📦 Packages

#2745 DOMA-3960 fix layout task progress bar
  apps/condo/domains/common/components/tasks/TaskProgress.tsx
Labels: 👶 small, ✋🙂 Review please
