Repository open-condo-software/condo, pull requests merged in 2022-11, with the labels that each got.

#2511 DOMA-4406 manual migration canReadBillingReceipts = true to Manager role
  apps/condo/domains/organization/constants/common.js
  apps/condo/migrations/20221101131455-0182_manual_organizationemployeerole_canreadbillingreceipts_change_to_manager.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#2518 DOMA-4557 fix cyclic function call
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#2515 chore(condo): DOMA-4552 added script for broken tickets statusUpdatedAt
  apps/condo/bin/fix-tickets-status-updated-at.js
Labels: ✋🙂 Review please

#2521 DOMA-4543 billing and acquiring to onBoarding steps
  apps/condo/domains/onboarding/components/OnBoardingContext.tsx
  apps/condo/domains/onboarding/constants.js
Labels: 👶 small, ✋🙂 Review please

#2522 HOTFIX added number of migration into start manual migration file
  apps/condo/migrations/20221101131455-0182_manual_organizationemployeerole_canreadbillingreceipts_change_to_manager.js
  apps/condo/migrations/20221102124530-0183_manual_organizationemployeerole_canreadpayments_change_to_manager.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#2526 DOMA-4566 fix remove section
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#2527 DOMA-4573 fixed search input rerender on tickets table page
  apps/condo/domains/common/hooks/useSearch.ts
  apps/condo/pages/ticket/index.tsx
Labels: ✋🙂 Review please

#2528 DOMA-4578 fixed editMode change
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#2525 fix(condo): DOMA-4568 fixed search in GraphQlSearchInput if prop "sea…
  apps/condo/domains/common/components/GraphQlSearchInput/GraphQlSearchInput.tsx
Labels: 👶 small, ✋🙂 Review please

#2533 hotfix(condo): HOTFIX added await to return value in getClientSecret
  apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.js
  apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.spec.js
  apps/condo/domains/organization/tasks/refreshSbbolClientSecret.js
Labels: 👶 small, ✋🙂 Review please

#2540 fix(condo): DOMA-4579 fixed ticket comments width
  apps/condo/domains/common/components/Comments/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2554 feat(condo): DOMA-4585 added analytics to MultipleFiltersModal
  apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
  apps/condo/pages/ticket/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2566 refactor(global): DOMA-3817 removed old webpack config
  packages/ui/webpack.config.js
Labels: 👶 small, 🎨 UI-kit, 📦 Packages

#2564 DOMA-4630 reset property map viewMode on section remove
  apps/condo/cypress/objects/Property.ts
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#2569 feat(ui): DOMA-4634 Added carousel component
  packages/ui/src/components/Carousel/arrow.tsx
  packages/ui/src/components/Carousel/carousel.tsx
  packages/ui/src/components/Carousel/index.ts
  packages/ui/src/components/Carousel/style.less
  packages/ui/src/index.ts
  packages/ui/src/stories/Carousel.stories.tsx
Labels: ✋🙂 Review please, 😎 Cool, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#2560 feat(condo): DOMA-4600 added silent-data-push ability
  apps/condo/domains/notification/adapters/firebaseAdapter.js
  apps/condo/domains/notification/adapters/firebaseAdapter.spec.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/gql.js
  apps/condo/domains/notification/schema/RemoteClient.js
  apps/condo/domains/notification/schema/SyncRemoteClientService.js
  apps/condo/domains/notification/schema/SyncRemoteClientService.test.js
  apps/condo/domains/notification/tasks/deliverMessage.js
  apps/condo/domains/notification/tasks/sendMessageBatch.helpers.js
  apps/condo/domains/notification/transports/push.js
  apps/condo/domains/notification/utils/testSchema/index.js
  apps/condo/migrations/20221115202053-0186_auto_20221115_1520.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/codegen/generate.server.utils.js
Labels: 🚨 Migrations, 🦑 API CHANGES, 😎 Cool

#2574 fix(condo): DOMA-4517 Fix display payments indicator logic
  apps/condo/domains/ticket/components/TicketId/TicketResidentFeatures.tsx
Labels: 👶 small, ✋🙂 Review please

#2582 fix(condo): DOMA-4517 fixed isPaymentsAvailable condition
  apps/condo/domains/ticket/components/TicketId/TicketResidentFeatures.tsx
Labels: 👶 small, ✋🙂 Review please

#2576 DOMA-4665 feat custom redirect after SBBOL authComplete
  apps/condo/domains/organization/integrations/sbbol/routes.js
Labels: 👶 small, ✋🙂 Review please

#2575 chore(condo): exclude cypress chai types from tsconfig
  apps/condo/cypress/tsconfig.json
  apps/condo/tsconfig.json
Labels: 👶 small, ✋🙂 Review please

#2593 fix(condo): DOMA-4684 fixed table columns width
  apps/condo/domains/billing/hooks/useReceiptTableColumns.ts
Labels: 👶 small

#2592 DOMA-4632 check preview prop at property-map form validation
  apps/condo/domains/property/components/BasePropertyMapForm/index.tsx
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2587 fix(condo): DOMA-4631 add cross to clear search field
  apps/condo/domains/division/components/DivisionsTable.tsx
Labels: 👶 small

#2586 fix(condo): DOMA-4633 make recaptcha doesn't block sbbol button
  apps/condo/domains/user/components/containers/PosterLayout.tsx
Labels: 👶 small

#2597 fix(condo): DOMA-4698 fixed meter readings displayed for deleted meters
  apps/condo/pages/meter/index.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2577 fix(condo): DOMA-4679 fixed ticket deadline autoset. Removed unused code
  apps/condo/domains/ticket/components/BaseTicketForm/TicketDeadlineField.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2588 fix(condo): DOMA-4492 add number of applied filters and reset button
  apps/condo/pages/meter/index.tsx
Labels: 👶 small

#2604 fix(condo): DOMA-4517 update payment indicator display logic
  apps/condo/domains/ticket/components/TicketId/TicketResidentFeatures.tsx
Labels: 👶 small, ✋🙂 Review please

#2608 DOMA-4657 add messageForUser to user TOO_MANY_REQUESTS error
  apps/condo/domains/user/constants/errors.js
  apps/condo/domains/user/schema/ConfirmPhoneActionService.js
  apps/condo/domains/user/utils/serverSchema/guards.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#2599 feat(ui): DOMA-4692 Added Modal
  packages/ui/src/components/Modal/cross.tsx
  packages/ui/src/components/Modal/index.ts
  packages/ui/src/components/Modal/modal.tsx
  packages/ui/src/components/Modal/style.less
  packages/ui/src/index.ts
  packages/ui/src/stories/Modal.stories.tsx
Labels: ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit

#2620 feat(address-service): DOMA-3580 Allow support users login to admin i…
  apps/address-service/index.js
Labels: 👶 small, ✋🙂 Review please

#2621 feat(address-service): DOMA-3580 Allow support users login to admin i…
  apps/address-service/domains/common/oidc.js
  apps/address-service/index.js
Labels: 👶 small, ✋🙂 Review please

#2622 feat(address-service): DOMA-3580 Address key generator improved
  apps/address-service/domains/common/utils/addressKeyUtils.js
  apps/address-service/domains/common/utils/addressKeyUtils.spec.js
Labels: 👶 small, ✋🙂 Review please

#2616 fix(condo): DOMA-4667 remove unused code
  apps/condo/domains/ticket/hooks/useStatusTransitions.ts
Labels: 👶 small, ✋🙂 Review please

#2623 feat(address-service): DOMA-3580 Restore deleted models on demand
  apps/address-service/domains/common/utils/services/search/plugins/SearchByAddressKey.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchByInjectionId.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchBySource.js
  apps/address-service/domains/common/utils/services/search/searchServiceUtils.js
Labels: 👶 small, ✋🙂 Review please

#2624 feat(address-service): DOMA-3580 Return address.id instead of address…
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
Labels: 👶 small, ✋🙂 Review please

#2626 fix(condo): DOMA-4798 error in changeClientSecret invoked from `refreshSbbolClientSecret`
  apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js
Labels: 🔥 HOTFIX

#2629 feat(address-service): DOMA-4795 Prevent call to address service in c…
  packages/keystone/plugins/addressService.js
Labels: 👶 small, ✋🙂 Review please

#2630 DOMA-4776 ignore calnceled tickets at property inwork count
  apps/condo/domains/property/gql.js
Labels: 👶 small, ✋🙂 Review please

#2634 fix(address-service): DOMA-4797 Import improvements
  apps/address-service/domains/address/schema/AddressInjection.js
  apps/address-service/domains/common/constants/contexts.js
  apps/address-service/domains/common/utils/services/InjectionsSeeker.js
Labels: 👶 small, ✋🙂 Review please

#2632 refactor(condo): DOMA-4804 remove unused services
  apps/condo/domains/ticket/access/CreateResidentTicketService.js
  apps/condo/domains/ticket/access/GetAllResidentTicketsService.js
  apps/condo/domains/ticket/access/UpdateResidentTicketService.js
  apps/condo/domains/ticket/schema/CreateResidentTicketService.js
  apps/condo/domains/ticket/schema/CreateResidentTicketService.test.js
  apps/condo/domains/ticket/schema/GetAllResidentTicketsService.js
  apps/condo/domains/ticket/schema/GetAllResidentTicketsService.test.js
  apps/condo/domains/ticket/schema/UpdateResidentTicketService.js
  apps/condo/domains/ticket/schema/UpdateResidentTicketService.test.js
  apps/condo/domains/ticket/schema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🦑 API CHANGES

#2639 fix(address-service): DOMA-4815 No error, but warning
  apps/address-service/index.js
Labels: 👶 small

#2638 fix(condo): Use account number instead of account id
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
Labels: 👶 small
