Repository open-condo-software/condo, pull requests merged in 2022-03, with the labels that each got.

#1199 DOMA-2354 Remove default selection on first element if no contact
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: small, 🔥 HOTFIX

#1214 HOTFIX Switched to random distribution
  apps/condo/domains/acquiring/schema/MultiPayment.test.js
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1217 DOMA-2390 fixed incorrect display onboarding modal in safari
  apps/condo/domains/onboarding/components/WelcomePopup.tsx
Labels: small, ✋🙂 Review please

#1225 HOTFIX skip deleted billing receipts in fix-billing-receipts.js
  apps/condo/bin/fix-billing-receipts.js
Labels: small

#1241 DOMA-2433 Fix receiver find on receipt create
  apps/condo/domains/billing/schema/BillingReceipt.js
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1234 DOMA-2200 Export to excel button disappears fixed
  apps/condo/domains/common/components/ExportToExcelActionBar.tsx
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1245 DOMA-2441 Remove global filtering from amount column
  apps/condo/domains/billing/hooks/useReceiptTableColumns.ts
Labels: small, ✋🙂 Review please

#1251 DOMA-2458 fix buttons position on registration screen
  apps/condo/domains/user/components/auth/InputPhoneForm.tsx
Labels: 🔥 HOTFIX, ✋🙂 Review please

#1256 HOTFIX make dependencies immutable with lockfile
  Dockerfile
  werf.yaml
Labels: 🔥 HOTFIX

#1258 DOMA-1706. Excess symbols ")}" in mail of despetcherskaya
  apps/condo/domains/notification/templates.js
Labels: small, 🔥 HOTFIX

#1270 HOTFIX Upgrade BillingRecipient model
  apps/condo/domains/billing/schema/BillingRecipient.js
  apps/condo/domains/billing/schema/BillingRecipient.test.js
  apps/condo/migrations/20220324102016-0114_auto_20220324_0720.js
Labels: small, ✋🙂 Review please

#1276 HOTFIX fix text align for footer
  apps/condo/domains/user/components/containers/PosterLayout.tsx
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1285 DOMA-2439 `ticketType` cache issue
  apps/condo/pages/reports/detail/report-by-tickets/index.tsx
Labels: small, ✋🙂 Review please

#1297 fix/condo/doma-2487/payments registry default filter
  apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx
Labels: small, ✋🙂 Review please

#1298 fix/condo/doma-2511/payments search by date and sum
  apps/condo/domains/acquiring/hooks/usePaymentsTableFilters.ts
Labels: small, ✋🙂 Review please

#1303 DOMA-2487 restore the default filter after the page leaves
  apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx
Labels: small, ✋🙂 Review please

#1305 DOMA-2599 remove beautiful colors from logger
  apps/condo/domains/common/utils/logger.js
Labels: small, 🔥 HOTFIX, ✋🙂 Review please

#1308 DOMA-2597 The `amount` column was added to excel template for payment…
  apps/condo/domains/acquiring/schema/ExportPaymentsService.js
  apps/condo/domains/acquiring/templates/PaymentsExportTemplate.xlsx
Labels: small, ✋🙂 Review please

#1309 DOMA-2438 The order of displaying of stubs was changed.
  apps/condo/domains/acquiring/components/payments/PaymentsPageContent.tsx
Labels: small, ✋🙂 Review please

#1311 DOMA-2549 The calculation of the number of filters applied was fixed.
  apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx
Labels: small, ✋🙂 Review please

#1312 DOMA-2488 Localized labels were added to datepicker
  apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx
Labels: small, ✋🙂 Review please

#1313 DOMA-2493 Display filter names at filters templates tabs.
  apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
Labels: small, ✋🙂 Review please

#1314 DOMA-2597 Formatting of the amount field within Excel export.
  apps/condo/domains/acquiring/schema/ExportPaymentsService.js
Labels: small, ✋🙂 Review please

#1317 DOMA-2603 Date picker at reports page
  apps/condo/pages/reports/detail/report-by-tickets/index.tsx
Labels: small, ✋🙂 Review please
