Repository open-condo-software/condo, pull requests merged in 2022-06, with the labels that each got.

#1670 DOMA-3134 add check for uniqueness for parking unit labels
  apps/condo/domains/property/components/panels/Builder/MapConstructor.spec.ts
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#1669 DOMA-2902 Override the `loadExistingGrant` function to detect if cond…
  apps/condo/domains/user/oidc/configuration.js
Labels: 👶 small, ✋🙂 Review please

#1660 DOMA-3136 Remove all traces of isActive field
  apps/condo/domains/user/schema/User.js
  apps/condo/migrations/20220530121004-0132_remove_user_isactive_and_more.js
  apps/condo/schema.ts
  packages/@core.codegen/templates/app00/initialData.js
  packages/@core.keystone/access.js
  packages/@core.keystone/schemas/User.js
  packages/@core.next/README.md
Labels: ✋🙂 Review please, 🚨 Migrations

#1679 DOMA-3134 add notification error on form submit
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: 👶 small, ✋🙂 Review please

#1682 DOMA-3175 Message.uniqKey field with constraints for deduplication of notifications
  apps/condo/domains/common/constants/errors.js
  apps/condo/domains/notification/adapters/firebaseAdapter.js
  apps/condo/domains/notification/gql.js
  apps/condo/domains/notification/schema/Device.test.js
  apps/condo/domains/notification/schema/Message.js
  apps/condo/domains/notification/schema/Message.test.js
  apps/condo/domains/notification/schema/SendMessageService.js
  apps/condo/domains/notification/schema/SendMessageService.test.js
  apps/condo/migrations/20220602135536-0134_auto_20220602_0855.js
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#1685 DOMA-1896 update logo and ticket creation menu icon
  apps/condo/domains/common/components/Logo.tsx
  apps/condo/domains/common/components/icons/AppealIcon.tsx
  apps/condo/domains/common/components/icons/MeterIcon.tsx
  apps/condo/public/logoDoma.svg
  apps/condo/public/logoHouse.svg
  apps/condo/public/logoSun.svg
Labels: 👶 small, ✋🙂 Review please

#1695 HOTFIX remove slashes from tracker domain name
  apps/condo/domains/common/components/trackers/TrackerInstance.spec.ts
Labels: 🔥 HOTFIX

#1676 Parallel test execution
  apps/condo/package.json
  packages/@core.keystone/fields/AutoIncrementInteger/Implementation.js
  packages/@core.keystone/schema.js
  packages/@core.keystone/tasks.js
Labels: 👶 small, ✋🙂 Review please

#1703 HOTFIX update common <domain>/<Model>.test.js template
  packages/@core.codegen/templates/schema00/domains/{{domain}}/schema/{{name}}.test.js
Labels: 🔥 HOTFIX, ✋🙂 Review please

#1701 HOTFIX remove test logic duplication
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.test.js
Labels: 👶 small, ✋🙂 Review please

#1714 Fix normalisation and expiresAt check!
  apps/condo/domains/user/schema/RegisterNewUserService.js
  apps/condo/domains/user/schema/SigninResidentUserService.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1715 HOTFIX use dvAndSender() plugin for OrganizationEmployee
  apps/condo/domains/organization/schema/OrganizationEmployee.js
Labels: 🔥 HOTFIX, ✋🙂 Review please

#1704 DOMA-2113 fix element layout
  apps/condo/domains/ticket/components/TicketForm/CreateTicketForm.tsx
Labels: 👶 small

#1727 DOMA-3213 fix validation placeClassifier&categoryClassifier on ticket…
  apps/condo/domains/ticket/components/TicketClassifierSelect.tsx
Labels: 👶 small

#1739 HOTFIX changePasswordWithToken: add dv, sender; Save sender fields
  apps/condo/domains/user/schema/ForgotPasswordService.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1757 DOMA-3259 use `emailFrom` field as value for `Reply-To` header
  apps/condo/domains/common/constants/requisites.js
  apps/condo/domains/notification/schema/SendMessageService.js
  apps/condo/domains/notification/transports/email.js
  apps/condo/domains/user/schema/SendMessageToSupportService.js
  apps/condo/schema.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1758 DOMA-1651 fix empty list view
  apps/condo/domains/common/components/EmptyListView.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1736 HOTFIX resetUser should pass dv and save sender request info
  apps/condo/domains/user/schema/ResetUserService.js
Labels: 👶 small, ✋🙂 Review please

#1735 HOTFIX sendMessageToSupport: add guard to easy developer debugging
  apps/condo/domains/user/schema/SendMessageToSupportService.js
Labels: 👶 small, ✋🙂 Review please

#1775 DOMA-3265 MIGRATION! add new ticket source type - mobile staff
  apps/condo/domains/common/utils/serverSchema/changeTrackable.js
  apps/condo/domains/ticket/constants/common.js
  apps/condo/domains/ticket/schema/TicketChange.test.js
  apps/condo/domains/ticket/schema/TicketSource.js
  apps/condo/domains/ticket/schema/TicketSource.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20220616205429-0137_alter_ticketsource_type.js
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#1807 DOMA-2676 fix xlsx ticket export template
  apps/condo/domains/ticket/templates/TicketsExportTemplate.xlsx
Labels: 👶 small, ✋🙂 Review please

#1812 DOMA-3163 fix opening file in new window in ticket view
  apps/condo/pages/ticket/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#1824 DOMA-3365 remove GraphQLLoggerApp and init GraphQLLoggerPlugin
  apps/condo/domains/common/utils/GraphQLLoggerApp.js
  apps/condo/domains/common/utils/apolloErrorFormatter.js
  apps/condo/domains/common/utils/apolloErrorFormatter.spec.js
  apps/condo/index.js
Labels: 🔥 HOTFIX, ✋🙂 Review please

#1817 DOMA-3163 fix downloading files in ticket view
  apps/condo/pages/ticket/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#1831 DOMA-3349 Added shallow redirect support to IFrame
  apps/condo/domains/common/components/IFrame/IFrame.tsx
  apps/condo/domains/common/utils/iframe.utils.spec.ts
  apps/condo/domains/common/utils/iframe.utils.ts
Labels: 👶 small, ✋🙂 Review please

#1834 DOMA-3382 add payment status to excel export
  apps/condo/domains/acquiring/schema/ExportPaymentsService.js
  apps/condo/domains/acquiring/templates/PaymentsExportTemplate.xlsx
  apps/condo/domains/common/utils/exportToExcel.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small

#1840 DOMA-3386 fixed url in new comment push notification
  apps/condo/domains/ticket/utils/handlers.js
Labels: 👶 small, ✋🙂 Review please

#1838 DOMA-3375 fix missing filterUnit
  apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
Labels: 👶 small, ✋🙂 Review please

#1851 HOTFIX propertly check for pending requests at cypress ticket test
  apps/condo/cypress/objects/Ticket.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#1848 DOMA-3100 add formatter convert to number for some colomns
  apps/condo/domains/ticket/templates/TicketAnalyticsExportTemplate[property_status].xlsx
  apps/condo/domains/ticket/templates/TicketAnalyticsExportTemplate[status_assignee].xlsx
  apps/condo/domains/ticket/templates/TicketAnalyticsExportTemplate[status_categoryClassifier].xlsx
  apps/condo/domains/ticket/templates/TicketAnalyticsExportTemplate[status_dayGroup].xlsx
  apps/condo/domains/ticket/templates/TicketAnalyticsExportTemplate[status_executor].xlsx
  apps/condo/domains/ticket/templates/TicketAnalyticsExportTemplate[status_property].xlsx
  apps/condo/domains/ticket/templates/TicketsExportTemplate.xlsx
Labels: 👶 small, ✋🙂 Review please
