Repository open-condo-software/condo, pull requests merged in 2022-10, with the labels that each got.

#2347 DOMA-3170 check unit label uniqueness before add
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#2348 DOMA-2810 restrict adding existing floor to the section
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#2349 DOMA-4317 added display mode to intl description of BuildingEmptyBlock
  apps/condo/domains/property/components/panels/Builder/BuildingPanelCommon.tsx
Labels: 👶 small, ✋🙂 Review please

#2350 fix(condo): DOMA-2809 delete a section when it is empty
  apps/condo/domains/property/components/panels/Builder/MapConstructor.spec.ts
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#2352 DOMA-4330 consider unit placement changes at validation
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Labels: 👶 small, ✋🙂 Review please

#2358 DOMA-4330 extend unit form validation to consider with unitType changes
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Labels: 👶 small, ✋🙂 Review please

#2366 fix(condo): DOMA-4336 use expressErrorHandler to catch unhandled errors
  apps/condo/index.js
Labels: 👶 small, ✋🙂 Review please

#2310 refactor(condo): fix race-condition
  packages/keystone/cache.js
Labels: 🔬 WIP

#2372 feat(condo): DOMA-4243 remove check by unitName in registerMultiPaymentService
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
Labels: 👶 small, ✋🙂 Review please

#2371 feat(condo): DOMA-4258 cron task added, feature flag enabled, scripts fixed, code refactored
  apps/condo/bin/lib/keystone.helpers.js
  apps/condo/bin/notification/send-custom-message-batch.js
  apps/condo/bin/notification/send-remote-clients-upgrade-app-notifications.js
  apps/condo/bin/notification/send-residents-billing-receipt-notifications.js
  apps/condo/bin/notification/send-residents-no-account-notifications.js
  apps/condo/bin/notification/send-residents-receipt-added-notifications.js
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/common/utils/date.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/tasks/helpers/index.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptNotifications.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.spec.js
  apps/condo/domains/resident/tasks/helpers/sendResidentsNoAccountNotifications.js
  apps/condo/domains/resident/tasks/helpers/sendResidentsNoAccountNotifications.spec.js
  apps/condo/domains/resident/tasks/helpers/spec.helpers.js
  apps/condo/domains/resident/tasks/index.js
  apps/condo/domains/resident/tasks/residentTicket.task.js
  apps/condo/domains/resident/tasks/sendBillingReceiptNotifications.task.js
  packages/featureflags/featureToggleManager.js
Labels: ✋🙂 Review please, 😎 Cool

#2384 DOMA-4288 added organization and role name to user info for UseDeskWidget
  apps/condo/domains/common/components/UseDeskWidget.tsx
Labels: 👶 small, ✋🙂 Review please

#2375 fix(condo): DOMA-2995 fixed loading for FilterModalBaseClassifierSelect
  apps/condo/domains/ticket/hooks/useModalFilterClassifiers.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2388 fix(condo): DOMA-4258 fixed errors
  apps/condo/domains/resident/tasks/helpers/sendResidentsNoAccountNotifications.js
  packages/keystone/redis.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2391 fix(condo): DOMA-4380 Added phone normalization when ticket import
  apps/condo/domains/ticket/hooks/useImporterFunctions.ts
Labels: 👶 small, ✋🙂 Review please

#2394 fix(condo): DOMA-4279 fix filters on the payment page
  apps/condo/domains/acquiring/schema/fields/PaymentsFilter.js
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#2393 fix(condo): DOMA-4258 fixed cron according to UTC
  apps/condo/domains/resident/tasks/sendBillingReceiptNotifications.task.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😎 Cool

#2398 fix(condo): DOMA-4388 fixed parse empty response with feature flags
  packages/featureflags/featureToggleManager.js
Labels: 👶 small, ✋🙂 Review please

#2400 fix(condo): DOMA-4389 removed ticket import from callcenter
  apps/condo/pages/ticket/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2386 fix(condo): DOMA-4222 fixed selected filter template after saving
  apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
Labels: 👶 small, ✋🙂 Review please

#2404 fix(condo): DOMA-2678 blocked employees are hidden from select
  apps/condo/domains/common/components/GraphQlSearchInput/GraphQlSearchInput.tsx
  apps/condo/domains/common/components/GraphQlSearchInput/Renders.tsx
  apps/condo/domains/common/components/GraphQlSearchInput/index.ts
  apps/condo/domains/division/components/BaseDivisionForm/index.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/TicketAssignments.tsx
  apps/condo/domains/ticket/utils/clientSchema/search.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2403 fix(condo): DOMA-4258 fixed crontab issues
  apps/condo/domains/resident/tasks/index.js
  apps/condo/domains/resident/tasks/sendBillingReceiptNotifications.task.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😎 Cool

#2407 DOMA-4236 change gql of BuildingsTable to smaller amount of subfields
  apps/condo/domains/property/components/BuildingsTable.tsx
  apps/condo/domains/property/gql.js
  apps/condo/domains/property/schema/fields/AddressMetaField.js
  apps/condo/domains/property/utils/clientSchema/PropertyTable.ts
  apps/condo/domains/property/utils/clientSchema/index.ts
Labels: 👶 small, ✋🙂 Review please

#2410 hotfix(codegen): DOMA-4394 Add back prefix support
  packages/codegen/generate.gql.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2374 feat(condo): DOMA-4351 added billing receipt notification deduplication logic
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.spec.js
  apps/condo/domains/resident/tasks/helpers/spec.helpers.js
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#2408 fix(condo): DOMA-4258 removed arguments on wrapper for cron task
  apps/condo/domains/resident/tasks/sendBillingReceiptNotifications.task.js
Labels: 👶 small

#2415 fix(condo): DOMA-4418 fixed display of the number of days since the last status change
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/ticket/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2414 fix(condo): DOMA-4159 fixed ticket template for pdf export
  apps/condo/pages/ticket/[id]/pdf.tsx
Labels: 👶 small, ✋🙂 Review please

#2266 DOMA-3363 fix getIntegerPartOfReading fn
  apps/condo/domains/common/components/Table/Renders.tsx
Labels: 👶 small, ✋🙂 Review please

#2426 fix(condo): DOMA-4161 fixed display of ticket changes
  apps/condo/domains/common/components/PhoneLink.tsx
  apps/condo/domains/ticket/components/TicketChanges/TicketChange.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#2425 DOMA-4437 Aded script for deleting all contacts from organization
  apps/condo/bin/delete-contacts-by-organization-id.js
Labels: 👶 small, ✋🙂 Review please

#2429 DOMA-4386 add canManageProperties access check at all related forms
  apps/condo/domains/property/components/BasePropertyMapForm/index.tsx
  apps/condo/domains/property/components/PropertyForm/CreatePropertyForm.tsx
  apps/condo/domains/property/components/PropertyMapForm/CreatePropertyMapForm.tsx
  apps/condo/domains/property/components/panels/Builder/BuildingPanelCommon.tsx
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/domains/property/components/panels/Builder/BuildingPanelView.tsx
  apps/condo/domains/property/components/panels/index.tsx
  apps/condo/pages/property/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2423 DOMA-2656 Use spec char validator for employee name
  apps/condo/domains/organization/components/EmployeeForm/CreateEmployeeForm.tsx
  apps/condo/pages/employee/index.tsx
  apps/condo/pages/meter/create.tsx
  apps/condo/pages/property/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2436 DOMA-3541 ignore emails and links at normalizeText util
  apps/condo/domains/common/utils/text.js
  apps/condo/domains/common/utils/text.spec.js
Labels: 👶 small, ✋🙂 Review please

#2434 DOMA-4406 access check for side menu links
  apps/condo/pages/_app.tsx
Labels: 👶 small, ✋🙂 Review please

#2441 feat(global): DOMA-4408 added webhooks utils
  .github/workflows/packages.ui.merge.tokens.yml
  .github/workflows/packages.webhooks.test.yaml
  packages/webhooks/README.md
  packages/webhooks/jest.config.js
  packages/webhooks/jest.setupSpec.js
  packages/webhooks/model-validator/test.schema.json
  packages/webhooks/model-validator/test.schema.ts
  packages/webhooks/model-validator/validator.js
  packages/webhooks/model-validator/validator.spec.js
  packages/webhooks/package.json
  yarn.lock
Labels: ✋🙂 Review please, 😵‍💫 dependencies, 🐘 BIG, 📦 Packages

#2451 hotfix(condo): HOTFIX reverted logic when all organizations added in black list
  apps/condo/domains/notification/schema/MessageOrganizationBlackList.test.js
  apps/condo/domains/notification/utils/serverSchema/index.js
Labels: 🔥 HOTFIX, ✋🙂 Review please

#2450 fix(condo): DOMA-4479 added feature flags for disabling meter notifications cron task
  apps/condo/bin/send-verification-date-reminder.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.spec.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotificationsTask.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotificationsTask.spec.js
  apps/condo/domains/meter/tasks/sendVerificationDateReminder.js
  apps/condo/domains/meter/tasks/sendVerificationDateReminder.spec.js
  apps/condo/domains/meter/tasks/sendVerificationDateReminderTask.js
  apps/condo/domains/meter/tasks/sendVerificationDateReminderTask.spec.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptNotifications.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptNotifications.spec.js
  apps/condo/domains/resident/tasks/sendBillingReceiptNotifications.task.js
  apps/condo/domains/ticket/utils/handlers.js
  packages/featureflags/featureToggleManager.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😎 Cool

#2447 fix(condo): DOMA-4161 fixed date format for ticket change
  apps/condo/domains/ticket/components/TicketChanges/TicketChange.tsx
Labels: 👶 small, ✋🙂 Review please

#2464 test(condo): DOMA-4467 added auto-generation test "statusUpdatedAt"
  apps/condo/domains/ticket/schema/Ticket.test.js
Labels: 👶 small, ✋🙂 Review please

#2465 refactor(condo): DOMA-4489 refactoring after review
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotificationsTask.spec.js
  apps/condo/domains/meter/tasks/sendVerificationDateReminderTask.spec.js
  apps/condo/domains/notification/helpers/sendRemoteClientsUpgradeAppNotifications.spec.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptNotifications.spec.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.spec.js
  apps/condo/domains/resident/tasks/helpers/sendResidentsNoAccountNotifications.spec.js
  apps/condo/domains/ticket/components/TicketOrganizationDeadline/TicketDeadlinePreview.tsx
  apps/condo/domains/ticket/tasks/reopenDeferredTickets.spec.js
  apps/condo/domains/user/gql.js
  apps/condo/jest.setupSpec.js
  apps/condo/public/ticketDeadlinePreview_ru.png
Labels: 👶 small, ✋🙂 Review please

#2468 fix(condo): DOMA-4504 fixed ticket history message for reopened deferred ticket
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2364 DOMA-4185 Added new InviteNewOrganizationEmployees access
  apps/condo/domains/organization/access/InviteNewOrganizationEmployeeService.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.test.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/migrations/20221024142150-0180_organizationemployeerole_caninviteneworganizationemployees_and_more.js
  apps/condo/pages/employee/[id]/index.tsx
  apps/condo/pages/employee/index.tsx
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#2471 fix(condo): DOMA-4154 added script for fix tickets
  apps/condo/bin/fix-tickets-client-name-client-phone.js
Labels: 👶 small, ✋🙂 Review please

#2430 fix(condo): DOMA-4059 fixed GraphQlSearchInput
  apps/condo/cypress/objects/Ticket.js
  apps/condo/domains/common/components/GraphQlSearchInput/GraphQlSearchInput.tsx
Labels: ✋🙂 Review please

#2435 fix(condo): DOMA-4333 fixed updating values in getGQLSelectFilterDropdown
  apps/condo/domains/common/components/Table/Filters.tsx
Labels: 👶 small, ✋🙂 Review please

#2482 hotfix(condo): DOMA-4392 fix deploy to development
  .github/workflows/nodejs.apps.build.yml
  .github/workflows/nodejs.condo.cypress.yml
  apps/condo/domains/user/schema/SendMessageToSupportService.js
  werf.yaml
Labels: 🔥 HOTFIX

#2474 DOMA-4339 dont update units/parking number when delete sections/parking
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
  apps/condo/lang/en/en.json
Labels: 👶 small, ✋🙂 Review please

#2483 DOMA-4392 fix deploy to dev
  apps/condo/domains/user/schema/SendMessageToSupportService.js
Labels: 🔥 HOTFIX

#2487 perf(webhooks): DOMA-4514 Webhooks validator speed up
  packages/webhooks/model-validator/test.schema.graphql
  packages/webhooks/model-validator/test.schema.json
  packages/webhooks/model-validator/test.schema.ts
  packages/webhooks/model-validator/validator.js
  packages/webhooks/model-validator/validator.spec.js
  packages/webhooks/package.json
  yarn.lock
Labels: ✋🙂 Review please, 😵‍💫 dependencies, 😎 Cool, 📦 Packages

#2489 chore(condo): HOTFIX move FeaturesMiddleware to package
  apps/condo/index.js
  packages/featureflags/FeaturesMiddleware.js
  packages/featureflags/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please

#2488 chore(condo): DOMA-4514 Make schema available at build / run time
  .gitignore
  apps/condo/schema.graphql
Labels: 🐘 BIG

#2496 DOMA-4364 Remove volume, units and tariff from receipts modal
  apps/condo/domains/billing/hooks/useServicesTableColumns.tsx
Labels: 👶 small

#2490 DOMA-4507 fix map constructor
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
  apps/condo/domains/property/components/panels/Builder/forms/ParkingUnitForm.tsx
  apps/condo/domains/property/components/panels/Builder/forms/UnitForm.tsx
Labels: 👶 small, ✋🙂 Review please

#2509 DOMA-4392 change help req style on auth page
  apps/condo/domains/user/components/containers/PosterLayout.tsx
Labels: 👶 small, ✋🙂 Review please

#2498 fix(condo): DOMA-4237 fixed classifier display
  apps/condo/domains/ticket/components/TicketId/TicketClassifierField.tsx
Labels: 👶 small, ✋🙂 Review please
