Repository open-condo-software/condo, pull requests merged in 2023-08, with the labels that each got.

#3634 feat(ui): DOMA-6670 added Button with dropdown items
  packages/ui/src/components/Button/button.tsx
  packages/ui/src/components/Button/index.ts
  packages/ui/src/components/Dropdown/button/extendedButton.tsx
  packages/ui/src/components/Dropdown/button/index.tsx
  packages/ui/src/components/Dropdown/button/style.less
  packages/ui/src/components/Dropdown/dropdown.tsx
  packages/ui/src/components/Dropdown/hooks/useItems.tsx
  packages/ui/src/components/Dropdown/index.ts
  packages/ui/src/components/Dropdown/style.less
  packages/ui/src/components/_utils/analytics.ts
  packages/ui/src/components/style/core/global.less
  packages/ui/src/components/style/core/motion/index.less
  packages/ui/src/components/style/core/motion/slide.less
  packages/ui/src/components/style/mixins/motion.less
  packages/ui/src/index.ts
  packages/ui/src/stories/ActionBar.stories.tsx
  packages/ui/src/stories/Dropdown.stories.tsx
Labels: ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#3674 fix(condo): DOMA-6788 added year in ticket creation date
  apps/condo/domains/ticket/utils/helpers.ts
Labels: 👶 small, ✋🙂 Review please

#3673 fix(condo): DOMA-6716 filter deleted users in query for ticket assigments
  apps/condo/domains/ticket/components/BaseTicketForm/AutoAssigner.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/TicketAssignments.tsx
Labels: 👶 small, ✋🙂 Review please

#3679 refactor(condo): DOMA-6795 removed migration script
  apps/condo/bin/fix-app-roles.js
Labels: 👶 small, ✋🙂 Review please

#3678 feat(condo): DOMA-6695 added bank account info to payment details
  apps/condo/domains/banking/components/BankAccountInfo.tsx
  apps/condo/domains/organization/components/Recipient/SettingsContent.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#3681 fix(condo): DOMA-6735 change location of organization name message in phone page
  apps/condo/pages/phone/[number]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3687 DOMA-6808 rid of private repo import
  apps/condo/domains/ticket/hooks/useCallRecordTableColumns.tsx
Labels: 👶 small, ✋🙂 Review please

#3685 DOMA-6805 allow user to filter almost all of the dashboard entities by date
  apps/condo/domains/analytics/components/Dashboard.tsx
  apps/condo/domains/analytics/components/charts/payment/dataMappers.ts
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.js
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.test.js
  apps/condo/domains/analytics/utils/services/dataLoaders/payment.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3690 hotfix(condo): allow Windows users to upload archives
  apps/condo/domains/miniapp/constants.js
  apps/condo/domains/miniapp/schema/B2CAppBuild.js
  apps/condo/domains/miniapp/schema/B2CAppBuild.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3672 Feat/condo/doma 6556/call discover service consumers mutation from hooks
  apps/condo/domains/acquiring/utils/testSchema/index.js
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/BillingAccount.js
  apps/condo/domains/billing/schema/BillingAccount.test.js
  apps/condo/domains/billing/schema/BillingReceipt.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
  apps/condo/domains/billing/utils/testSchema/index.js
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/property/schema/Property.js
  apps/condo/domains/resident/access/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/constants/constants.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
  apps/condo/domains/resident/schema/RegisterResidentService.js
  apps/condo/domains/resident/schema/RegisterResidentService.test.js
  apps/condo/domains/resident/schema/ServiceConsumer.js
  apps/condo/domains/resident/tasks/discoverServiceConsumers.task.js
  apps/condo/domains/resident/tasks/index.js
  apps/condo/domains/resident/utils/serverSchema/index.js
  apps/condo/domains/user/utils/serverSchema/guards.js
  apps/condo/migrations/20230804090031-0302_serviceconsumer_isdiscovered_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/featureflags/featureToggleManager.js
  packages/keystone/test.utils.js
Labels: ✋🙂 Review please, 🚨 Migrations, 🦑 API CHANGES, 😎 Cool, 🐘 BIG

#3691 fix(condo): DOMA-6823 fix layout last meter readings filter
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/meter/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3655 feat(condo): DOMA-6693 added permissions a mini apps for requests on behalf of service user
  apps/condo/domains/miniapp/access/B2BAppAccessRight.js
  apps/condo/domains/miniapp/access/B2BAppAccessRightSet.js
  apps/condo/domains/miniapp/constants.js
  apps/condo/domains/miniapp/gql.js
  apps/condo/domains/miniapp/schema/B2BAppAccessRight.js
  apps/condo/domains/miniapp/schema/B2BAppAccessRight.test.js
  apps/condo/domains/miniapp/schema/B2BAppAccessRightSet.js
  apps/condo/domains/miniapp/schema/B2BAppAccessRightSet.test.js
  apps/condo/domains/miniapp/schema/B2CAppAccessRight.js
  apps/condo/domains/miniapp/schema/B2CAppAccessRight.test.js
  apps/condo/domains/miniapp/schema/index.js
  apps/condo/domains/miniapp/schema/preprocessors/B2BAppAccess.js
  apps/condo/domains/miniapp/schema/preprocessors/B2BAppAccess.spec.js
  apps/condo/domains/miniapp/utils/clientSchema/B2BAppAccessRightSet.ts
  apps/condo/domains/miniapp/utils/clientSchema/index.ts
  apps/condo/domains/miniapp/utils/serverSchema/index.js
  apps/condo/domains/miniapp/utils/testSchema/index.js
  apps/condo/index.js
  apps/condo/jest.config.js
  apps/condo/migrations/20230804220052-0304_b2bappaccessrightset_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3680 fix(condo): DOMA-6783 added canManageMany support to ticket comments and comment files
  apps/condo/domains/ticket/access/TicketComment.js
  apps/condo/domains/ticket/access/TicketCommentFile.js
Labels: 👶 small

#3694 feat(condo): DOMA-6796 make miniapps accessible to all 🤟😎
  apps/condo/domains/miniapp/components/AppDescription/B2BAppPage.tsx
  apps/condo/domains/miniapp/components/AppDescription/PageContent.tsx
  apps/condo/domains/miniapp/components/AppDescription/TopCard.tsx
  apps/condo/domains/miniapp/components/AppIndex/B2BAppPage.tsx
  apps/condo/domains/miniapp/components/Catalog/CardGrid.tsx
  apps/condo/domains/miniapp/components/Catalog/PageContent.tsx
  apps/condo/domains/miniapp/components/ConnectedAppsWithIconsProvider.tsx
  apps/condo/domains/miniapp/constants.js
  apps/condo/domains/miniapp/gql.js
  apps/condo/domains/miniapp/schema/AllMiniAppsService.js
  apps/condo/domains/miniapp/schema/AllMiniAppsService.test.js
  apps/condo/domains/miniapp/schema/B2BAppContext.js
  apps/condo/domains/miniapp/tasks/createDefaultB2BAppRoles.js
  apps/condo/domains/miniapp/tasks/index.js
  apps/condo/domains/miniapp/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/_app.tsx
  apps/condo/pages/miniapps/[id]/about.tsx
  apps/condo/pages/miniapps/[id]/index.tsx
  apps/condo/pages/miniapps/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🦑 API CHANGES, 😎 Cool

#3703 fix(condo): DOMA-6703 added sbbol indicator in header
  apps/condo/domains/common/components/containers/BaseLayout/Header.tsx
  apps/condo/domains/common/components/containers/BaseLayout/components/TopMenuItems.tsx
  apps/condo/domains/organization/components/SBBOLIndicator.tsx
  packages/icons/src/components/LogoSBBOL.tsx
  packages/icons/src/index.ts
Labels: 👶 small, ✋🙂 Review please

#3708 fix(condo): DOMA-6844 add acquiring context to service consumer
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3698 feat(condo): DOMA-6601 changed translate to news excel
  apps/condo/domains/news/schema/NewsItemRecipientsExportTask.test.js
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3233 fix(condo): DOMA-5956 offline status change history
  apps/condo/domains/common/components/ChangeHistory/HistoricalChange.tsx
  apps/condo/domains/ticket/access/TicketMultipleUpdateService.js
  apps/condo/domains/ticket/gql.js
  apps/condo/domains/ticket/schema/Ticket.js
  apps/condo/domains/ticket/schema/TicketChange.js
  apps/condo/domains/ticket/schema/TicketChange.test.js
  apps/condo/domains/ticket/schema/TicketMultipleUpdateService.js
  apps/condo/domains/ticket/schema/TicketMultipleUpdateService.test.js
  apps/condo/domains/ticket/schema/index.js
  apps/condo/domains/ticket/utils/serverSchema/TicketChange.js
  apps/condo/domains/ticket/utils/serverSchema/index.js
  apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
  apps/condo/domains/ticket/utils/testSchema/index.js
  apps/condo/migrations/20230810123751-0305_ticketchange_actualcreationdate.js
  apps/condo/pages/ticket/[id]/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3710 feat(condo): DOMA-6848 del name from payment details
  apps/condo/domains/banking/components/BankAccountInfo.tsx
  apps/condo/domains/organization/components/Recipient/SettingsContent.tsx
Labels: 👶 small, ✋🙂 Review please

#3612 feat(condo): DOMA-6331 push notification about the need to send meter readings
  apps/condo/domains/meter/components/CreateMeterReadingsForm.tsx
  apps/condo/domains/meter/components/MeterReportingPeriodForm.tsx
  apps/condo/domains/meter/hooks/useFilters.tsx
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.spec.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotificationsTask.js
  apps/condo/domains/meter/tasks/sendVerificationDateReminder.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/METER_SUBMIT_READINGS_REMINDER_END_PERIOD/default.njk
  apps/condo/lang/en/messages/METER_SUBMIT_READINGS_REMINDER_END_PERIOD/push.njk
  apps/condo/lang/en/messages/METER_SUBMIT_READINGS_REMINDER_END_PERIOD/sms.njk
  apps/condo/lang/en/messages/METER_SUBMIT_READINGS_REMINDER_START_PERIOD/default.njk
  apps/condo/lang/en/messages/METER_SUBMIT_READINGS_REMINDER_START_PERIOD/push.njk
  apps/condo/lang/en/messages/METER_SUBMIT_READINGS_REMINDER_START_PERIOD/sms.njk
  apps/condo/lang/ru/messages/METER_SUBMIT_READINGS_REMINDER_END_PERIOD/default.njk
  apps/condo/lang/ru/messages/METER_SUBMIT_READINGS_REMINDER_END_PERIOD/push.njk
  apps/condo/lang/ru/messages/METER_SUBMIT_READINGS_REMINDER_END_PERIOD/sms.njk
  apps/condo/lang/ru/messages/METER_SUBMIT_READINGS_REMINDER_START_PERIOD/default.njk
  apps/condo/lang/ru/messages/METER_SUBMIT_READINGS_REMINDER_START_PERIOD/push.njk
  apps/condo/lang/ru/messages/METER_SUBMIT_READINGS_REMINDER_START_PERIOD/sms.njk
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230810172249-0306_alter_notificationusersetting_messagetype.js
  apps/condo/pages/meter/index.tsx
  apps/condo/pages/meter/reportingPeriod/[id]/update.tsx
  apps/condo/pages/meter/reportingPeriod/create.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3700 feat(condo): DOMA-6613 changed indents to match layouts
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/TemplatesTabs.tsx
Labels: 👶 small, ✋🙂 Review please

#3718 fix(condo): DOMA-6859 prevent service consumers duplicates
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3719 fix(condo): DOMA-6863 fix sbbol indicator icon
  apps/condo/domains/common/components/containers/BaseLayout/Header.tsx
  apps/condo/domains/common/constants/style.js
  apps/condo/domains/organization/components/OrganizationSelect.tsx
  apps/condo/domains/organization/components/SBBOLIndicator.tsx
  packages/icons/src/components/LogoSBBOL.tsx
  packages/icons/src/index.ts
Labels: 👶 small, ✋🙂 Review please

#3715 feat(condo): DOMA-6855 send organization id in push notifications in technician mobile app
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/ticket/utils/handlers.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3713 fix(condo): DOMA-6740 move attach call record button to action bar
  apps/condo/domains/ticket/components/TicketId/TicketCallRecordHistory.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/ticket/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3695 feat(condo): DOMA-6834 added ticket resident comment create notification
  apps/condo/domains/ticket/schema/TicketComment.test.js
  apps/condo/domains/ticket/tasks/sendTicketCommentNotifications.js
  apps/condo/domains/ticket/utils/handlers.js
  apps/condo/domains/ticket/utils/handlers.spec.js
Labels: ✋🙂 Review please

#3722 DOMA-6883 remove old alert component
  apps/condo/domains/common/components/Alert.tsx
  apps/condo/domains/common/utils/helpers.ts
  apps/condo/domains/organization/components/EmployeeForm/UpdateEmployeeForm.tsx
  apps/condo/domains/organization/hooks/useTableColumns.tsx
  apps/condo/domains/scope/components/FormHintAlert.tsx
Labels: 👶 small, ✋🙂 Review please

#3724 fix(condo): DOMA-6834 added organizationId to ticket comment pushes
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/ticket/tasks/sendTicketCommentNotifications.js
  apps/condo/domains/ticket/utils/handlers.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3662 feat(condo): DOMA-6736 schema MobileFeatureConfig with tests
  apps/condo/domains/common/components/PhoneInput.tsx
  apps/condo/domains/common/components/settings/MobileFeatureConfigContent.tsx
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/common/constants/settingsTabs.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.test.js
  apps/condo/domains/settings/access/MobileFeatureConfig.js
  apps/condo/domains/settings/components/ticketSubmitting/OnlyProgressionMeterReadingsForm.tsx
  apps/condo/domains/settings/components/ticketSubmitting/OnlyProgressionMeterReadingsSettingCard.tsx
  apps/condo/domains/settings/components/ticketSubmitting/TicketSubmittingSettingCard.tsx
  apps/condo/domains/settings/components/ticketSubmitting/TicketSubmittingSettingsForm.tsx
  apps/condo/domains/settings/gql.js
  apps/condo/domains/settings/schema/MobileFeatureConfig.js
  apps/condo/domains/settings/schema/MobileFeatureConfig.test.js
  apps/condo/domains/settings/schema/index.js
  apps/condo/domains/settings/utils/MobileFeatureConfigSchemaValidations.js
  apps/condo/domains/settings/utils/clientSchema/MobileFeatureConfig.ts
  apps/condo/domains/settings/utils/clientSchema/index.ts
  apps/condo/domains/settings/utils/serverSchema/index.js
  apps/condo/domains/settings/utils/testSchema/index.js
  apps/condo/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230811140557-0307_mobilefeatureconfighistoryrecord_and_more.js
  apps/condo/pages/settings/index.tsx
  apps/condo/pages/settings/mobileFeatureConfig/onlyProgressionMeterReadings/index.tsx
  apps/condo/pages/settings/mobileFeatureConfig/ticketSubmitting/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3728 feat(condo): DOMA-6899 The webhook plugin was added to contacts model
  apps/condo/domains/contact/schema/Contact.js
Labels: 👶 small, ✋🙂 Review please

#3732 feat(condo): DOMA-6834 revert 6834 task
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/ticket/schema/TicketComment.test.js
  apps/condo/domains/ticket/tasks/sendTicketCommentNotifications.js
  apps/condo/domains/ticket/utils/handlers.js
  apps/condo/domains/ticket/utils/handlers.spec.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3731 fix(condo): DOMA-6927 fixed sonarlint suggestions
  apps/address-service/domains/common/utils/parseAddressesFromString.js
  apps/condo/domains/common/components/TextHighlighter.tsx
  apps/condo/domains/common/components/containers/BaseLayout/components/TopMenuItems.tsx
  apps/condo/domains/common/components/containers/FormList.tsx
  apps/condo/domains/common/utils/excel.utils.ts
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/CreateNewsForm.tsx
  apps/condo/domains/notification/adapters/apple/AppleJSONWebToken.spec.js
  apps/condo/domains/onboarding/utils/stepUtils.ts
  apps/condo/domains/organization/components/OrganizationSelect.tsx
  apps/condo/domains/organization/utils/testSchema/Organization.js
  apps/condo/domains/property/components/panels/Builder/BuildingPanelView.tsx
  apps/condo/domains/property/components/panels/Builder/MapConstructor.spec.ts
  apps/condo/domains/ticket/components/TicketClassifierSelect.tsx
  apps/condo/domains/ticket/utils/serverSchema/exportTicketBlanksToPdf.js
  apps/condo/domains/user/components/auth/RegisterContextProvider.tsx
  apps/condo/domains/user/schema/ForgotPasswordService.test.js
  apps/condo/pages/property/[id]/report.tsx
  apps/condo/pages/reports/detail/report-by-tickets/index.tsx
  apps/condo/pages/reports/detail/report-by-tickets/pdf.tsx
  apps/condo/public/resetEmail.html
  apps/miniapp/domains/condo/utils/clientSchema/User.ts
  packages/icons/bin/import/index.ts
  packages/ui/src/stories/Alert.stories.tsx
Labels: 👶 small, ✋🙂 Review please

#3742 fix(condo): DOMA-6922 fixed properties number translates
  apps/condo/domains/news/components/RecipientCounter.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3671 feat(condo): DOMA-6784 B2BAppPermission name field added
  apps/condo/domains/miniapp/constants.js
  apps/condo/domains/miniapp/schema/B2BAppPermission.js
  apps/condo/domains/miniapp/schema/B2BAppPermission.test.js
  apps/condo/domains/miniapp/utils/testSchema/index.js
  apps/condo/migrations/20230821152126-0308_b2bapppermission_name_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#3750 DOMA-6979 add transactions not added error for import task
  apps/condo/domains/banking/constants.js
  apps/condo/domains/banking/hooks/useBankSyncTaskUIInterface.tsx
  apps/condo/domains/banking/schema/BankSyncTask.test.js
  apps/condo/domains/banking/tasks/importBankTransactionsFrom1CClientBankExchange.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3734 feat(condo): DOMA-6582 added button of meter reading creating
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/meter/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3755 DOMA-6992 update property report page after task success
  apps/condo/domains/banking/hooks/useBankSyncTaskUIInterface.tsx
  apps/condo/domains/banking/tasks/importBankTransactionsFrom1CClientBankExchange.js
Labels: 👶 small, ✋🙂 Review please

#3756 hotfix(global): add build concurrency limit
  package.json
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3760 hotfix(condo): safe data formatting
  apps/condo/domains/ticket/components/IncidentForm/BaseIncidentForm.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3767 refactor(condo): DOMA-6567 remove redundant feature flag
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/organization/hooks/useCreateOrganizationModalForm.tsx
Labels: 👶 small, ✋🙂 Review please

#3768 chore(dev-portal): DOMA-7014 documentation update
  apps/dev-portal/docs/_meta.ru.json
  apps/dev-portal/docs/bridge/methods/modals/_meta.en.json
  apps/dev-portal/docs/bridge/methods/modals/_meta.ru.json
  apps/dev-portal/docs/bridge/methods/modals/close-modal-window.en.mdx
  apps/dev-portal/docs/bridge/methods/modals/update-modal-window.en.mdx
  apps/dev-portal/docs/bridge/methods/modals/update-modal-window.ru.mdx
  apps/dev-portal/pages/docs/[...path].tsx
  packages/bridge/src/bridge.ts
  packages/ui/src/components/Typography/paragraph.tsx
  packages/ui/src/components/Typography/text.tsx
  packages/ui/src/components/Typography/title.tsx
Labels: 👶 small, ✋🙂 Review please, 📦 Packages, 📝 Docs

#3771 DOMA-6834 Return 6834 task into master
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/ticket/schema/TicketComment.test.js
  apps/condo/domains/ticket/tasks/sendTicketCommentNotifications.js
  apps/condo/domains/ticket/utils/handlers.js
  apps/condo/domains/ticket/utils/handlers.spec.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3761 Feat/condo/doma 6990/improve discovering service consumers
  apps/condo/domains/billing/schema/BillingAccount.js
  apps/condo/domains/property/schema/Property.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
  apps/condo/domains/resident/schema/RegisterResidentService.js
  apps/condo/domains/resident/tasks/discoverServiceConsumersCron.task.js
  apps/condo/domains/resident/tasks/index.js
Labels: ✋🙂 Review please

#3764 feat(condo): DOMA-6561 added oidc auth to server apollo client
  packages/apollo-server-client/index.js
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#3776 hotfix(condo): make side-nave scroll correctly by limiting menu container height
  apps/condo/domains/common/components/containers/global-styles.css
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3787 hotfix(condo): fix generatePermissionKey for B2BAppPermission tests
  apps/condo/domains/miniapp/utils/testSchema/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3788 fix(condo): DOMA-4289 fixed a property display for a foreign organization
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/property/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3780 feat(condo): DOMA-6936 added column "Is verified" for contacts import
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/public/contact-import-example-en.xlsx
  apps/condo/public/contact-import-example-ru.xlsx
Labels: 👶 small, ✋🙂 Review please

#3773 feat(condo): DOMA-6886 added meter and meterReading access rights to …
  apps/condo/domains/meter/schema/Meter.js
  apps/condo/domains/meter/schema/MeterReading.js
  apps/condo/domains/miniapp/constants.js
  apps/condo/migrations/20230827162601-0310_b2bappaccessrightset_canmanagemeterreadings_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🔬 WIP

#3791 fix(condo): DOMA-4289 fixed translates
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3800 bug with seververConsumer in output of allResidentBillingReceipts
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
  apps/condo/domains/billing/utils/testSchema/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please
