Repository open-condo-software/condo, pull requests merged in 2023-09, with the labels that each got.

#3775 feat(condo): DOMA-6522 save usedesk chat
  apps/condo/domains/common/components/UseDeskWidget.tsx
Labels: 👶 small, ✋🙂 Review please

#3806 Feat/condo/doma 7063/billing account fields
  .sonarcloud.properties
  apps/condo/domains/billing/constants/constants.js
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/BillingAccount.js
  apps/condo/domains/billing/schema/BillingAccount.test.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
  apps/condo/migrations/20230901142157-0311_billingaccount_isclosed_billingaccount_ownertype_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3810 Revert DOMA-6936
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/public/contact-import-example-en.xlsx
  apps/condo/public/contact-import-example-ru.xlsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3812 fix(condo): DOMA-7077 added await to waitFor
  apps/condo/domains/ticket/schema/TicketComment.test.js
Labels: 👶 small, ✋🙂 Review please

#3813 DOMA-7076 ignore ui-kit tabs operations at the custom one in news domain
  apps/condo/domains/news/components/TemplatesTabs.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3793 Feat/condo/doma 7026/two billing accounts no service consumer
  apps/condo/domains/billing/gql.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
  apps/condo/domains/resident/tasks/discoverServiceConsumersCron.task.js
  apps/condo/domains/ticket/schema/TicketComment.test.js
Labels: ✋🙂 Review please

#3754 Feat/condo/doma 6521/pay-by-qr-code
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
  apps/address-service/domains/common/utils/services/suggest/SuggestionKeystoneApp.js
  apps/condo/domains/acquiring/access/CreatePaymentByLinkService.js
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
  apps/condo/domains/acquiring/schema/index.js
  apps/condo/domains/acquiring/utils/serverSchema/index.js
  apps/condo/domains/acquiring/utils/testSchema/index.js
  apps/condo/domains/billing/access/ValidateQRCodeService.js
  apps/condo/domains/billing/constants.js
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.test.js
  apps/condo/domains/billing/schema/index.js
  apps/condo/domains/billing/utils/serverSchema/index.js
  apps/condo/domains/billing/utils/testSchema/index.js
  apps/condo/domains/common/utils/serverSideAddressApi.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
  apps/condo/domains/resident/schema/RegisterResidentService.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/clients/README.md
  packages/clients/address-service-client/AddressServiceClient.js
  packages/clients/address-service-client/MockedAddressServiceClient.js
  packages/clients/address-service-client/README.md
  packages/clients/address-service-client/index.js
  packages/clients/address-service-client/utils/index.js
  packages/clients/address-service-client/utils/parseAddressesFromString.js
  packages/clients/address-service-client/utils/parseAddressesFromString.spec.js
  packages/clients/package.json
  packages/keystone/plugins/addressService.js
  packages/keystone/plugins/utils/address-service-client/README.md
  packages/keystone/test.utils.js
  yarn.lock
Labels: ✋🙂 Review please

#3817 feat(condo): DOMA-6194 send userId in useDesk additional_fields data
  apps/condo/domains/common/components/UseDeskWidget.tsx
Labels: 👶 small, ✋🙂 Review please

#3807 DOMA-7041 add configurable server url for invite employee
  .env.example
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.js
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.test.js
  apps/condo/lang/en/messages/DIRTY_INVITE_NEW_EMPLOYEE_EMAIL/default.njk
  apps/condo/lang/en/messages/DIRTY_INVITE_NEW_EMPLOYEE_SMS/default.njk
  apps/condo/lang/ru/messages/DIRTY_INVITE_NEW_EMPLOYEE_EMAIL/default.njk
  apps/condo/lang/ru/messages/DIRTY_INVITE_NEW_EMPLOYEE_SMS/default.njk
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3814 feat(condo): DOMA-7047 user direct access (isSupport alternative) 😎😎😎😎
  apps/condo/domains/miniapp/access/B2BApp.js
  apps/condo/domains/miniapp/access/B2BAppAccessRight.js
  apps/condo/domains/miniapp/access/B2BAppAccessRightSet.js
  apps/condo/domains/miniapp/access/B2BAppContext.js
  apps/condo/domains/miniapp/access/B2BAppPermission.js
  apps/condo/domains/miniapp/access/B2BAppPromoBlock.js
  apps/condo/domains/miniapp/access/B2CApp.js
  apps/condo/domains/miniapp/access/B2CAppAccessRight.js
  apps/condo/domains/miniapp/access/B2CAppBuild.js
  apps/condo/domains/miniapp/access/B2CAppProperty.js
  apps/condo/domains/miniapp/schema/B2BAppAccessRight.js
  apps/condo/domains/miniapp/schema/B2BAppPermission.test.js
  apps/condo/domains/miniapp/schema/B2CAppBuild.test.js
  apps/condo/domains/miniapp/schema/B2CAppProperty.test.js
  apps/condo/domains/organization/access/Organization.js
  apps/condo/domains/user/access/RegisterNewServiceUserService.js
  apps/condo/domains/user/access/UserRightsSet.js
  apps/condo/domains/user/gql.js
  apps/condo/domains/user/schema/User.js
  apps/condo/domains/user/schema/UserRightsSet.js
  apps/condo/domains/user/schema/UserRightsSet.test.js
  apps/condo/domains/user/schema/index.js
  apps/condo/domains/user/utils/clientSchema/UserRightsSet.ts
  apps/condo/domains/user/utils/clientSchema/index.ts
  apps/condo/domains/user/utils/directAccess/common.utils.js
  apps/condo/domains/user/utils/directAccess/config.js
  apps/condo/domains/user/utils/directAccess/directAccess.spec.js
  apps/condo/domains/user/utils/directAccess/index.js
  apps/condo/domains/user/utils/directAccess/server.utils.js
  apps/condo/domains/user/utils/serverSchema/index.js
  apps/condo/domains/user/utils/testSchema/index.js
  apps/condo/migrations/20230904150122-0312_userrightssethistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/keystone/KSv5v6/v5/prepareKeystone.js
Labels: ✋🙂 Review please, 🚨 Migrations, 😎 Cool, 🐘 BIG

#3829 Feat/condo/doma 6963/discover service consumers script
  apps/condo/bin/billing/chargeRecurrentPayments.js
  apps/condo/bin/billing/createRecurrentPaymentForNewBillingReceipt.js
  apps/condo/bin/billing/createRecurrentPaymentForReadyToPayRecurrentPaymentContexts.js
  apps/condo/bin/billing/discoverServiceConsumers.js
  apps/condo/bin/billing/notifyBeforeRecurrentPaymentDate.js
  apps/condo/domains/common/utils/serverSchema/index.js
  apps/condo/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please

#3823 feat(condo): DOMA-7005 Discover service consumers: whitelist becomes …
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotificationsTask.spec.js
  apps/condo/domains/meter/tasks/sendVerificationDateReminderTask.spec.js
  apps/condo/domains/news/schema/NewsItemRecipientsExportTask.test.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
  apps/condo/domains/resident/tasks/discoverServiceConsumers.task.js
  apps/condo/domains/resident/tasks/discoverServiceConsumersCron.task.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptNotifications.spec.js
  apps/condo/domains/ticket/schema/Ticket.test.js
  packages/featureflags/featureToggleManager.js
  packages/keystone/test.utils.js
Labels: 👶 small, ✋🙂 Review please

#3770 fix(condo): DOMA-6889 fix push submit meter readings logic
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.spec.js
Labels: 👶 small, ✋🙂 Review please

#3835 fix(address-service): DOMA-7110 keep trailing space only for trailing number
  apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
Labels: 👶 small, ✋🙂 Review please

#3836 fix(condo): DOMA-7117 fix creating consumers for different categories…
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
Labels: ✋🙂 Review please

#3837 DOMA-7118 migrate ANALYTICS_V3 feature flag from organization to growthbook
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.js
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.test.js
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/organization/constants/features.js
  apps/condo/migrations/20230911173130-0313_auto_20230911_1231.js
  apps/condo/pages/reports/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#3841 DOMA-7118 pass organization context to the featureflag controller
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.js
Labels: 👶 small, ✋🙂 Review please

#3820 DOMA-7022 miniapp permissions settings table
  apps/condo/domains/common/components/Table/Index.tsx
  apps/condo/domains/common/components/containers/GlobalStyle.tsx
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/miniapp/access/B2BAppPermission.js
  apps/condo/domains/miniapp/gql.js
  apps/condo/domains/miniapp/schema/B2BAppPermission.test.js
  apps/condo/domains/organization/components/EmployeeRolesSettingsContent.tsx
  apps/condo/domains/organization/hooks/useEmployeeRolesTableColumns.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/property/[id]/report.tsx
  apps/condo/pages/settings/index.tsx
  apps/condo/pages/ticket/index.tsx
  packages/codegen/generate.hooks.ts
Labels: ✋🙂 Review please

#3846 feat(condo): DOMA-7152 added direct access to sendMessage 💌 💌
  apps/condo/domains/notification/access/SendMessageService.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/user/schema/UserRightsSet.test.js
  apps/condo/domains/user/utils/directAccess/config.js
  apps/condo/lang/en/messages/DEV_PORTAL_MESSAGE/default.njk
  apps/condo/lang/ru/messages/DEV_PORTAL_MESSAGE/default.njk
  apps/condo/migrations/20230913155017-0314_userrightsset_canexecutesendmessage_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#3811 DOMA-7068 check tag existence inside release job
  .github/workflows/deploy_production.yaml
Labels: 👶 small, ✋🙂 Review please

#3844 chore(condo): DOMA-7138 moved bigger import limit flag to growthbook
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/pages/contact/index.tsx
  apps/condo/pages/meter/index.tsx
  apps/condo/pages/ticket/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3851 DOMA-7151 added canManageB2BApps permission to settings permissions table
  apps/condo/domains/miniapp/access/B2BAppContext.js
  apps/condo/domains/miniapp/components/AppDescription/TopCard.tsx
  apps/condo/domains/miniapp/schema/AllMiniAppsService.test.js
  apps/condo/domains/miniapp/schema/B2BAppContext.js
  apps/condo/domains/miniapp/schema/B2BAppContext.test.js
  apps/condo/domains/miniapp/schema/B2BAppPermission.js
  apps/condo/domains/miniapp/schema/B2BAppRole.js
  apps/condo/domains/miniapp/schema/B2BAppRole.test.js
  apps/condo/domains/miniapp/tasks/updateB2BAppRolesPermissions.js
  apps/condo/domains/organization/components/EmployeeRolesSettingsContent.tsx
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230914112448-0315_auto_20230914_0624.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3843 Chore/condo/doma 7111/qr codes additionals
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3852 fix(condo): DOMA-7172 fixed case when processed chunk in loadListByChunks is empty
  apps/condo/domains/common/utils/serverSchema/index.js
  apps/condo/domains/news/constants/common.js
  apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.test.js
  apps/condo/domains/news/utils/serverSchema/recipientsCounterUtils.js
  apps/condo/domains/news/utils/testSchema/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3824 fix(condo): DOMA-7051 set contact phone field if user came from client card
  apps/condo/domains/contact/components/ContactsEditor/NewContactFields.tsx
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3857 chore(condo): DOMA-7154 filter out duplicates
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
Labels: ✋🙂 Review please

#3822 fix(condo): DOMA-6194 added call setAdditionalFields inside useEffect to update data
  apps/condo/domains/common/components/UseDeskWidget.tsx
Labels: 👶 small, ✋🙂 Review please

#3864 fix(condo): DOMA-6697 fix tests
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/tasks/notifyResidentsOnPayday.js
  apps/condo/domains/resident/tasks/notifyResidentsOnPayday.spec.js
  apps/condo/domains/resident/tasks/notifyResidentsOnPaydayTask.spec.js
Labels: 👶 small, ✋🙂 Review please

#3867 fix(condo): DOMA-7203 fix is empty initial not resident value check
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3869 fix(condo): DOMA-7203 added memo deps to displayEditableFieldsWithContactOptions
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3799 feat(condo): DOMA-7056 added validation for roles OrganizationEmployee schema. Added 'Ticket' for 'UserRightsSet'
  apps/condo/domains/banking/schema/BankIntegrationAccountContext.test.js
  apps/condo/domains/banking/schema/BankIntegrationOrganizationContext.test.js
  apps/condo/domains/meter/schema/Meter.test.js
  apps/condo/domains/organization/access/OrganizationEmployee.js
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.test.js
  apps/condo/domains/organization/schema/OrganizationEmployee.js
  apps/condo/domains/organization/schema/OrganizationEmployee.test.js
  apps/condo/domains/organization/schema/OrganizationEmployeeSpecialization.test.js
  apps/condo/domains/organization/schema/OrganizationLink.test.js
  apps/condo/domains/organization/utils/testSchema/index.js
  apps/condo/domains/ticket/access/Ticket.js
  apps/condo/domains/ticket/schema/TicketChange.test.js
  apps/condo/domains/user/utils/directAccess/config.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230918155550-0317_userrightsset_canmanagetickets_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3865 feat(condo): DOMA-6936 added column "Is verified" for contacts import
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/public/contact-import-example-en.xlsx
  apps/condo/public/contact-import-example-ru.xlsx
Labels: 👶 small, ✋🙂 Review please

#3834 DOMA-7004 analytics v3 charts detail view
  apps/condo/domains/analytics/components/CustomChart.ts
  apps/condo/domains/analytics/components/CustomChartView.tsx
  apps/condo/domains/analytics/components/CustomListView.tsx
  apps/condo/domains/analytics/components/Dashboard.tsx
  apps/condo/domains/analytics/components/TicketListView.tsx
  apps/condo/domains/analytics/components/charts/index.ts
  apps/condo/domains/analytics/components/charts/payment/PaymentByPropertyChart.tsx
  apps/condo/domains/analytics/components/charts/payment/PaymentChart.ts
  apps/condo/domains/analytics/components/charts/payment/PaymentReceiptChart.tsx
  apps/condo/domains/analytics/components/charts/payment/PaymentTotalChart.tsx
  apps/condo/domains/analytics/components/charts/payment/dataMappers.ts
  apps/condo/domains/analytics/components/charts/resident/ResidentByPropertyChart.tsx
  apps/condo/domains/analytics/components/charts/resident/ResidentChart.ts
  apps/condo/domains/analytics/components/charts/resident/dataMappers.ts
  apps/condo/domains/analytics/components/charts/ticket/AllTicketsChart.tsx
  apps/condo/domains/analytics/components/charts/ticket/TicketByCategoryChart.tsx
  apps/condo/domains/analytics/components/charts/ticket/TicketByExecutorChart.tsx
  apps/condo/domains/analytics/components/charts/ticket/TicketByPropertyChart.tsx
  apps/condo/domains/analytics/components/charts/ticket/TicketQualityControlChart.tsx
  apps/condo/domains/analytics/components/charts/ticket/dataMappers.ts
  apps/condo/domains/analytics/gql.js
  apps/condo/domains/analytics/hooks/useDashboardFilters.tsx
  apps/condo/domains/analytics/hooks/useDetailChartView.tsx
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.js
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.test.js
  apps/condo/domains/analytics/schema/TicketAnalyticsReportService.js
  apps/condo/domains/analytics/utils/serverSchema/analytics.helper.js
  apps/condo/domains/analytics/utils/services/AnalyticsDataProvider.js
  apps/condo/domains/analytics/utils/services/dataLoaders/incident.js
  apps/condo/domains/analytics/utils/services/dataLoaders/payment.js
  apps/condo/domains/analytics/utils/services/dataLoaders/property.js
  apps/condo/domains/analytics/utils/services/dataLoaders/receipt.js
  apps/condo/domains/analytics/utils/services/dataLoaders/resident.js
  apps/condo/domains/analytics/utils/services/dataLoaders/ticket.js
  apps/condo/domains/common/utils/serverSchema/GqlToKnexBaseAdapter.js
  apps/condo/domains/ticket/hooks/useTableColumns.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3858 DOMA-7169 Added canReadAnalitycs permission to table
  apps/condo/domains/analytics/access/GetOverviewDashboardService.js
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.test.js
  apps/condo/domains/organization/components/EmployeeRolesSettingsContent.tsx
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/hooks/useEmployeeRolesTableData.tsx
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230919121602-0318_auto_20230919_0716.js
  apps/condo/pages/settings/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3874 fix(eps): enabled payment category
  apps/condo/domains/resident/constants/constants.js
Labels: 👶 small, ✋🙂 Review please

#3873 fix(condo): DOMA-6697 use loadListByChunks to get receipts. Some test consumers have more than 100 receipts
  apps/condo/domains/resident/tasks/notifyResidentsOnPayday.js
Labels: 👶 small, ✋🙂 Review please

#3876 fix(condo): DOMA-7223 resident registration: get `rawValue`
  apps/condo/domains/property/utils/serverSchema/helpers.js
Labels: 👶 small, ✋🙂 Review please

#3880 feat(condo): DOMA-7214 added approved flag for organizations
  apps/condo/domains/organization/access/Organization.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/Organization.js
  apps/condo/domains/organization/schema/Organization.test.js
  apps/condo/domains/user/utils/directAccess/config.js
  apps/condo/migrations/20230921160354-0319_organization_isapproved_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3882 feature(condo): DOMA-7107 getBankInfo and getOrganizationInfo
  packages/clients/finance-info-client/FinanceInfoClient.js
  packages/clients/finance-info-client/README.md
  packages/clients/finance-info-client/index.js
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#3875 feat(dev-api): DOMA-7048 dev portal API introduced 🧑‍💻 🧑‍💻
  .github/workflows/apps.dev-api.test.yml
  .github/workflows/nodejs.address-service.test.yml
  .github/workflows/nodejs.condo.cypress.yml
  .github/workflows/nodejs.condo.test.yml
  .github/workflows/nodejs.lint.yml
  .github/workflows/waitForLocalhostApiReady.sh
  apps/dev-api/.env.example
  apps/dev-api/README.md
  apps/dev-api/bin/create-user.js
  apps/dev-api/bin/prepare.js
  apps/dev-api/domains/common/constants/locales.js
  apps/dev-api/domains/common/gql.js
  apps/dev-api/domains/common/utils/messages.js
  apps/dev-api/domains/common/utils/serverClients.js
  apps/dev-api/domains/common/utils/sms.js
  apps/dev-api/domains/package.json
  apps/dev-api/domains/user/access/User.js
  apps/dev-api/domains/user/constants/errors.js
  apps/dev-api/domains/user/constants/index.js
  apps/dev-api/domains/user/gql.js
  apps/dev-api/domains/user/schema/AuthenticateUserWithPhoneAndPasswordService.js
  apps/dev-api/domains/user/schema/AuthenticateUserWithPhoneAndPasswordService.test.js
  apps/dev-api/domains/user/schema/ConfirmPhoneAction.js
  apps/dev-api/domains/user/schema/ConfirmPhoneAction.test.js
  apps/dev-api/domains/user/schema/ConfirmPhoneActionService.js
  apps/dev-api/domains/user/schema/ConfirmPhoneActionService.test.js
  apps/dev-api/domains/user/schema/RegisterNewUserService.js
  apps/dev-api/domains/user/schema/RegisterNewUserService.test.js
  apps/dev-api/domains/user/schema/User.js
  apps/dev-api/domains/user/schema/User.test.js
  apps/dev-api/domains/user/schema/index.js
  apps/dev-api/domains/user/utils/guards.js
  apps/dev-api/domains/user/utils/password.js
  apps/dev-api/domains/user/utils/phone.js
  apps/dev-api/domains/user/utils/serverSchema/index.js
  apps/dev-api/domains/user/utils/testSchema/index.js
  apps/dev-api/index.js
  apps/dev-api/jest.config.js
  apps/dev-api/jest.setupSpec.js
  apps/dev-api/jest.setupTest.js
  apps/dev-api/lang/en.json
  apps/dev-api/lang/ru.json
  apps/dev-api/migrations/20230919183825-0001_initial.js
  apps/dev-api/package.json
  apps/dev-api/schema.ts
  bin/prepare.js
  package.json
  packages/apollo-server-client/index.js
  packages/cli/index.js
  packages/codegen/index.js
  packages/keystone/errors.js
  packages/keystone/test.utils.js
  yarn.lock
Labels: ✋🙂 Review please, 🚨 Migrations, infrastructure, 😎 Cool, 🐘 BIG, 📦 Packages

#3892 Fix/condo/doma 7250/fix discover service consumers
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
Labels: ✋🙂 Review please

#3890 fix(condo): DOMA-4856 fixed render of address
  apps/condo/domains/common/utils/helpers.ts
Labels: 👶 small, ✋🙂 Review please

#3891 feat(ui): DOMA-7255 added basic input
  packages/ui/package.json
  packages/ui/src/components/Input/index.ts
  packages/ui/src/components/Input/input.tsx
  packages/ui/src/components/Input/password.tsx
  packages/ui/src/components/Input/phone.tsx
  packages/ui/src/components/Input/style.less
  packages/ui/src/index.ts
  packages/ui/src/stories/Input/Input.stories.tsx
  packages/ui/src/stories/Input/Password.stories.tsx
  packages/ui/src/stories/Input/Phone.stories.tsx
  yarn.lock
Labels: ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#3889 DOMA-7244 add addressService plugin into B2CAppProperty
  apps/condo/domains/meter/schema/Meter.test.js
  apps/condo/domains/miniapp/schema/B2CAppProperty.js
  apps/condo/domains/miniapp/schema/B2CAppProperty.test.js
  apps/condo/domains/miniapp/utils/testSchema/index.js
  apps/condo/domains/user/schema/UserRightsSet.test.js
  apps/condo/migrations/20230925160512-0321_auto_20230925_1105.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3904 Fix/condo/doma-7282/do not create consumers for empty billing account
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
Labels: 🔥 HOTFIX, ✋🙂 Review please

#3903 fix(condo): DOMA-6514 fix redirect to accruals tab on applied filters
  apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx
  apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
Labels: 👶 small

#3907 DOMA-7291 use original data for pie charts
  apps/condo/domains/analytics/components/charts/payment/dataMappers.ts
  apps/condo/domains/analytics/components/charts/resident/dataMappers.ts
Labels: 👶 small, ✋🙂 Review please

#3884 fix(condo): DOMA-7243 fix calc isPayable for receipts in AllResidentBillingReceiptsService.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
Labels: 👶 small, ✋🙂 Review please

#3910 feat(condo): DOMA-7281 moved property scopes and ticket hints to control room settings
  apps/condo/domains/common/components/settings/ControlRoomSettingsContent.tsx
  apps/condo/domains/common/constants/settingsTabs.js
  apps/condo/domains/organization/components/EmployeeRolesSettingsContent.tsx
  apps/condo/domains/organization/hooks/useEmployeeRolesTableData.tsx
  apps/condo/domains/scope/components/BasePropertyScopeForm.tsx
  apps/condo/domains/scope/components/PropertyScopeSettingsContent.tsx
  apps/condo/domains/scope/utils/clientSchema/PropertyScope.ts
  apps/condo/domains/ticket/components/TicketPropertyHint/BaseTicketPropertyHintForm.tsx
  apps/condo/domains/ticket/components/TicketPropertyHint/SettingsContent.tsx
  apps/condo/domains/ticket/utils/clientSchema/TicketPropertyHint.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/settings/hint/[id]/index.tsx
  apps/condo/pages/settings/hint/index.tsx
  apps/condo/pages/settings/index.tsx
  apps/condo/pages/settings/propertyScope/[id]/index.tsx
  apps/condo/pages/settings/propertyScope/[id]/update.tsx
  apps/condo/pages/settings/propertyScope/index.tsx
Labels: ✋🙂 Review please

#3913 hotfix(condo): added chunkSize to get serviceConsumers
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3912 DOMA-7312 set date range by default to one week
  apps/condo/domains/analytics/hooks/useDashboardFilters.tsx
Labels: 👶 small, ✋🙂 Review please
