Repository open-condo-software/condo, pull requests merged in 2023-10, with the labels that each got.

#3916 Fix/condo/doma-7311/filter out service consumers duplicates
  apps/condo/bin/billing/discoverServiceConsumers.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
Labels: 🔥 HOTFIX, ✋🙂 Review please

#3919 chore(condo): DOMA-7334 replace `setXForwardedFor()` with `client.set…
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.test.js
  packages/keystone/test.utils.js
Labels: 👶 small, ✋🙂 Review please

#3922 fix(condo): DOMA-7277 fixed importer
  apps/condo/domains/common/utils/importer.ts
Labels: 👶 small, ✋🙂 Review please

#3927 feat(dev-portal): DOMA-7323 getStaticProps -> getServerSideProps 🏃
  apps/dev-portal/pages/docs/[...path].tsx
Labels: 👶 small, ✋🙂 Review please

#3924 Fix/address service/doma 7336/fix space before send address to dadata
  apps/address-service/domains/address/access/Address.js
  apps/address-service/domains/address/schema/Address.js
  apps/address-service/domains/address/schema/Address.test.js
  apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
  apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3929 fix(condo): DOMA-7341 fix cron task for discovering of service consumers
  apps/condo/domains/resident/tasks/discoverServiceConsumersCron.task.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3935 Fix/condo/doma-7355/perion does not matter for discavering of consumers
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
Labels: 🔥 HOTFIX, ✋🙂 Review please

#3930 fix(condo): DOMA-7259 fix settings table after testing
  apps/condo/domains/organization/access/OrganizationEmployeeRole.js
  apps/condo/domains/organization/components/OrganizationRequired.tsx
  apps/condo/domains/organization/components/PageAccess.tsx
  apps/condo/domains/organization/hooks/useEmployeeRolesTableData.tsx
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.test.js
  apps/condo/domains/property/components/BuildingsTable.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/employee/create.tsx
  apps/condo/pages/news/index.tsx
Labels: ✋🙂 Review please

#3942 fix(condo): DOMA-7228 made one checkbox for read billing section in permissions table
  apps/condo/domains/organization/hooks/useEmployeeRolesTableData.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3943 hotfix(condo): DOMA-7358 fixed meter import
  apps/condo/domains/common/utils/importer.ts
  apps/condo/domains/meter/hooks/useImporterFunctions.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3915 feat(condo): DOMA-7297 added ability to directly manage fields
  apps/condo/domains/miniapp/access/B2BApp.js
  apps/condo/domains/miniapp/access/B2BAppAccessRight.js
  apps/condo/domains/miniapp/access/B2BAppAccessRightSet.js
  apps/condo/domains/miniapp/access/B2BAppContext.js
  apps/condo/domains/miniapp/access/B2BAppPermission.js
  apps/condo/domains/miniapp/access/B2BAppPromoBlock.js
  apps/condo/domains/miniapp/access/B2CApp.js
  apps/condo/domains/miniapp/access/B2CAppAccessRight.js
  apps/condo/domains/miniapp/access/B2CAppBuild.js
  apps/condo/domains/miniapp/access/B2CAppProperty.js
  apps/condo/domains/organization/access/Organization.js
  apps/condo/domains/organization/schema/Organization.test.js
  apps/condo/domains/ticket/access/Ticket.js
  apps/condo/domains/user/schema/UserRightsSet.test.js
  apps/condo/domains/user/utils/directAccess/common.utils.js
  apps/condo/domains/user/utils/directAccess/config.js
  apps/condo/domains/user/utils/directAccess/directAccess.spec.js
  apps/condo/domains/user/utils/directAccess/server.utils.js
  apps/condo/migrations/20231002183808-0325_userrightsset_canmanageorganizationisapprovedfield_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3711 chore(DOMA-6850): wrong schemaDoc text
  apps/condo/domains/miniapp/schema/B2CAppAccessRight.js
Labels: 👶 small, ✋🙂 Review please

#3816 hotfix(webhooks): fix failuresCount and add more logs
  packages/webhooks/tasks/sendWebhook.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3871 Feat/address-service/doma-7060/improve address searching
  .semgrepignore
  .sonarcloud.properties
  apps/address-service/domains/common/utils/services/suggest/SuggestionKeystoneApp.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
  apps/condo/domains/billing/schema/helpers/propertyFinder.js
  apps/condo/domains/billing/schema/helpers/propertyFinder.spec.js
Labels: ✋🙂 Review please

#3951 fix(condo): DOMA-7340 fix layout of MobileFeatureConfigContent
  apps/condo/domains/common/components/settings/MobileFeatureConfigContent.tsx
Labels: 👶 small, ✋🙂 Review please

#3950 feat(dev-portal): DOMA-7279 Auth️ 👾🤖👾🤖👾
  apps/dev-api/domains/user/schema/AuthenticateUserWithPhoneAndPasswordService.js
  apps/dev-api/domains/user/schema/ConfirmPhoneActionService.js
  apps/dev-api/domains/user/schema/RegisterNewUserService.js
  apps/dev-api/domains/user/schema/User.js
  apps/dev-api/lang/en.json
  apps/dev-api/lang/ru.json
  apps/dev-api/package.json
  apps/dev-api/schema.ts
  apps/dev-portal/bin/prepare.js
  apps/dev-portal/codegen.ts
  apps/dev-portal/docs/index.en.mdx
  apps/dev-portal/docs/index.ru.mdx
  apps/dev-portal/domains/common/components/Header.module.css
  apps/dev-portal/domains/common/components/Header.tsx
  apps/dev-portal/domains/common/components/auth/AuthAction.module.css
  apps/dev-portal/domains/common/components/auth/AuthAction.tsx
  apps/dev-portal/domains/common/components/auth/AuthForm.tsx
  apps/dev-portal/domains/common/components/auth/LoginForm.module.css
  apps/dev-portal/domains/common/components/auth/LoginForm.tsx
  apps/dev-portal/domains/common/components/auth/registration/CodeInputStep.module.css
  apps/dev-portal/domains/common/components/auth/registration/CodeInputStep.tsx
  apps/dev-portal/domains/common/components/auth/registration/IdentityInputStep.module.css
  apps/dev-portal/domains/common/components/auth/registration/IdentityInputStep.tsx
  apps/dev-portal/domains/common/components/auth/registration/PhoneInputStep.module.css
  apps/dev-portal/domains/common/components/auth/registration/PhoneInputStep.tsx
  apps/dev-portal/domains/common/components/auth/registration/RegisterForm.tsx
  apps/dev-portal/domains/common/constants/antd.ts
  apps/dev-portal/domains/common/hooks/useMutationErrorHandler.ts
  apps/dev-portal/domains/common/hooks/useValidations.ts
  apps/dev-portal/domains/common/utils/userid.utils.ts
  apps/dev-portal/domains/docs/components/CardLink.module.css
  apps/dev-portal/domains/docs/components/CardLink.tsx
  apps/dev-portal/domains/docs/components/Grid.tsx
  apps/dev-portal/domains/docs/components/mdx.tsx
  apps/dev-portal/lang/en.json
  apps/dev-portal/lang/ru.json
  apps/dev-portal/lib/apollo.ts
  apps/dev-portal/lib/auth.tsx
  apps/dev-portal/lib/gql/index.ts
  apps/dev-portal/lib/gql/user.graphql
  apps/dev-portal/next.config.js
  apps/dev-portal/package.json
  apps/dev-portal/pages/_app.tsx
  apps/dev-portal/pages/docs/[...path].tsx
  apps/dev-portal/pages/docs/path.module.css
  apps/dev-portal/public/pdpc.pdf
  apps/dev-portal/public/policy.pdf
  apps/dev-portal/tsconfig.json
  bin/create-graphql-schema.js
  packages/locales/extractReqLocale.js
  packages/locales/loader.js
  packages/ui/src/components/Input/phone.tsx
  packages/ui/src/components/Input/style.less
  packages/ui/src/components/Tabs/tabs.tsx
  packages/ui/src/index.ts
  packages/ui/src/stories/Input/Phone.stories.tsx
  packages/ui/src/stories/Tabs.stories.tsx
  yarn.lock
Labels: ✋🙂 Review please, 😎 Cool, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 🐘 BIG, 📦 Packages

#3955 Chore/condo/doma-7060/improve properties searching
  apps/condo/domains/billing/schema/helpers/propertyFinder.js
  apps/condo/domains/billing/schema/helpers/propertyFinder.spec.js
Labels: ✋🙂 Review please

#3957 feat(condo): DOMA-7400 Add logs for discover service consumers mutation
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
Labels: 👶 small, ✋🙂 Review please

#3967 feat(condo): DOMA-7426 added analytic events for miniapp session tracking
  apps/condo/domains/miniapp/components/AppIndex/B2BAppPage.tsx
Labels: 👶 small, ✋🙂 Review please

#3969 fix(condo): DOMA-7435 find consumers by accountNumber instead of billing context
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.js
Labels: 👶 small, ✋🙂 Review please

#3872 DOMA-7184 made confirmPhoneActionToken required in RegisterNewUserService
  apps/condo/domains/common/schema/fields.js
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.js
  apps/condo/domains/user/constants/errors.js
  apps/condo/domains/user/schema/ConfirmPhoneAction.js
  apps/condo/domains/user/schema/RegisterNewUserService.js
  apps/condo/domains/user/schema/RegisterNewUserService.test.js
  apps/condo/domains/user/utils/serverSchema/index.js
  apps/condo/domains/user/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3979 Feat/condo/doma-7445/invoice context model
  apps/condo/domains/marketplace/access/InvoiceContext.js
  apps/condo/domains/marketplace/constants.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/InvoiceContext.js
  apps/condo/domains/marketplace/schema/InvoiceContext.test.js
  apps/condo/domains/marketplace/schema/index.js
  apps/condo/domains/marketplace/utils/clientSchema/InvoiceContext.ts
  apps/condo/domains/marketplace/utils/clientSchema/index.ts
  apps/condo/domains/marketplace/utils/serverSchema/index.js
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/index.js
  apps/condo/migrations/20231016185656-0326_invoicecontexthistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3982 hotfix(dev-portal): DOMA-7465 api proxy via API routes + httpProxy
  apps/dev-portal/lib/apollo.ts
  apps/dev-portal/middleware.ts
  apps/dev-portal/package.json
  apps/dev-portal/pages/api/graphql.ts
  yarn.lock
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3991 DOMA-7476 update policy file
  apps/condo/domains/user/components/auth/InputPhoneForm.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/public/termsofuse.pdf
Labels: 👶 small, ✋🙂 Review please

#3995 fix(resident): DOMA-7480 Discover produce too match new indexes
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3981 feat(condo): DOMA-7450 add MarketCategory entity
  apps/condo/domains/marketplace/access/MarketCategory.js
  apps/condo/domains/marketplace/constants.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/MarketCategory.js
  apps/condo/domains/marketplace/schema/MarketCategory.test.js
  apps/condo/domains/marketplace/schema/index.js
  apps/condo/domains/marketplace/utils/clientSchema/MarketCategory.ts
  apps/condo/domains/marketplace/utils/clientSchema/index.ts
  apps/condo/domains/marketplace/utils/serverSchema/index.js
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20231017174534-0327_marketcategoryhistoryrecord_marketcategory.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#3994 refactor(condo): DOMA-7480 use `data` and `result` logging keys
  apps/condo/domains/notification/adapters/hcm/messaging.js
Labels: 👶 small, ✋🙂 Review please

#3993 refactor(condo): DOMA-7480 use existing logging key `data`
  apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
Labels: 👶 small, ✋🙂 Review please

#3992 feat(condo): DOMA-7467 schema MarketItem
  apps/condo/domains/marketplace/access/MarketItem.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/MarketItem.js
  apps/condo/domains/marketplace/schema/MarketItem.test.js
  apps/condo/domains/marketplace/schema/index.js
  apps/condo/domains/marketplace/utils/clientSchema/MarketItem.ts
  apps/condo/domains/marketplace/utils/clientSchema/index.ts
  apps/condo/domains/marketplace/utils/serverSchema/index.js
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/migrations/20231018172243-0328_marketitemhistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3914 DOMA-7314 hide analytics from menu in case of no access & redirect to tickets page
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.js
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.test.js
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/pages/_app.tsx
  apps/condo/pages/index.tsx
  apps/condo/pages/reports/index.tsx
Labels: ✋🙂 Review please

#3989 fix(condo): DOMA-7477 remove fragments from graphql log records
  packages/keystone/logging/GraphQLLoggerApp.js
Labels: 👶 small, ✋🙂 Review please

#3996 Feat/condo/doma-7446/invoice model
  apps/condo/domains/common/constants/errors.js
  apps/condo/domains/common/schema/fields.js
  apps/condo/domains/marketplace/access/Invoice.js
  apps/condo/domains/marketplace/access/InvoiceContext.js
  apps/condo/domains/marketplace/constants.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/marketplace/schema/InvoiceContext.js
  apps/condo/domains/marketplace/schema/InvoiceContext.test.js
  apps/condo/domains/marketplace/schema/fields/invoiceRows.js
  apps/condo/domains/marketplace/schema/index.js
  apps/condo/domains/marketplace/utils/clientSchema/Invoice.ts
  apps/condo/domains/marketplace/utils/clientSchema/index.ts
  apps/condo/domains/marketplace/utils/serverSchema/index.js
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20231020120727-0329_invoicehistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4005 Feat/condo/doma-7447/payment model upgrade
  apps/condo/domains/acquiring/constants/errors.js
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/schema/Payment.js
  apps/condo/domains/acquiring/schema/Payment.test.js
  apps/condo/domains/acquiring/utils/testSchema/index.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
  apps/condo/migrations/20231024105409-0331_payment_frozeninvoice_payment_invoice_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4012 fix(condo): DOMA-7541 remove ticket visibility redirect restriction
  apps/condo/pages/index.tsx
Labels: 👶 small, ✋🙂 Review please

#4015 fix(condo): DOMA-7211 set canReadEmployees and canRead(Manage)Incidents to false to contractor role
  apps/condo/domains/common/components/ResidentActions/ResidentActions.tsx
  apps/condo/domains/organization/constants/common.js
  apps/condo/migrations/20231025094409-0333_auto_20231025_0444.js
  apps/condo/pages/_app.tsx
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#4002 feat(condo): DOMA-7502 schema MarketItemPrice
  apps/condo/domains/marketplace/access/MarketItemPrice.js
  apps/condo/domains/marketplace/constants.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/MarketCategory.js
  apps/condo/domains/marketplace/schema/MarketItemPrice.js
  apps/condo/domains/marketplace/schema/MarketItemPrice.test.js
  apps/condo/domains/marketplace/schema/fields/mobileSettings.js
  apps/condo/domains/marketplace/schema/fields/price.js
  apps/condo/domains/marketplace/schema/index.js
  apps/condo/domains/marketplace/utils/clientSchema/MarketItemPrice.ts
  apps/condo/domains/marketplace/utils/clientSchema/index.ts
  apps/condo/domains/marketplace/utils/serverSchema/index.js
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20231025141303-0334_marketitempricehistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4010 feat(condo): DOMA-7503 schema MarketPriceScope
  apps/condo/domains/marketplace/access/MarketPriceScope.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/MarketPriceScope.js
  apps/condo/domains/marketplace/schema/MarketPriceScope.test.js
  apps/condo/domains/marketplace/schema/index.js
  apps/condo/domains/marketplace/utils/clientSchema/MarketPriceScope.ts
  apps/condo/domains/marketplace/utils/clientSchema/index.ts
  apps/condo/domains/marketplace/utils/serverSchema/index.js
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20231025154904-0335_marketpricescopehistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🚨 Migrations

#4021 fix(condo): DOMA-7560 fix notification about meter readings and receipts
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.js
  apps/condo/domains/resident/tasks/helpers/sendResidentsNoAccountNotifications.js
Labels: 👶 small, ✋🙂 Review please

#4022 chore(condo): DOMA-7423 updated meter import example (added all values for unit type)
  apps/condo/public/meter-import-example-en.xlsx
  apps/condo/public/meter-import-example-ru.xlsx
Labels: 👶 small, ✋🙂 Review please

#4031 hotfix(locales): DOMA-7584 more complex locale extractor
  packages/locales/extractReqLocale.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4020 Feat/condo/doma-7512/create invoice by resident
  apps/condo/domains/billing/schema/ValidateQRCodeService.test.js
  apps/condo/domains/marketplace/access/Invoice.js
  apps/condo/domains/marketplace/access/RegisterInvoiceService.js
  apps/condo/domains/marketplace/constants.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/marketplace/schema/RegisterInvoiceService.js
  apps/condo/domains/marketplace/schema/RegisterInvoiceService.test.js
  apps/condo/domains/marketplace/schema/fields/invoiceRows.js
  apps/condo/domains/marketplace/schema/index.js
  apps/condo/domains/marketplace/utils/serverSchema/index.js
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20231031101233-0337_invoice_paymenttype_invoicehistoryrecord_paymenttype.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations
