Repository open-condo-software/condo, pull requests merged in 2023-04, with the labels that each got.

#3131 feat(condo): DOMA-5738 Separate page for service-provider
  apps/condo/next.config.js
  apps/condo/pages/_app.tsx
  apps/condo/pages/service-provider-profile.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3096 feat(condo): DOMA-5601 ticket/incident classifiers changing
  apps/condo/migrations/20230403114510-0246_auto_20230403_0645.js
Labels: ✋🙂 Review please, 🚨 Migrations

#3111 DOMA-4721 contact export task
  apps/condo/domains/contact/access/ContactExportTask.js
  apps/condo/domains/contact/access/ExportContactsService.js
  apps/condo/domains/contact/gql.js
  apps/condo/domains/contact/hooks/useContactExportTaskUIInterface.ts
  apps/condo/domains/contact/hooks/useContactExportToExcelTask.tsx
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/domains/contact/schema/ContactExportTask.js
  apps/condo/domains/contact/schema/ContactExportTask.test.js
  apps/condo/domains/contact/schema/ExportContactsService.js
  apps/condo/domains/contact/schema/ExportContactsService.test.js
  apps/condo/domains/contact/schema/index.js
  apps/condo/domains/contact/tasks/exportContacts.js
  apps/condo/domains/contact/tasks/index.js
  apps/condo/domains/contact/templates/ContactsExportTemplate.xlsx
  apps/condo/domains/contact/utils/clientSchema/ContactExportTask.ts
  apps/condo/domains/contact/utils/clientSchema/index.ts
  apps/condo/domains/contact/utils/serverSchema/index.js
  apps/condo/domains/contact/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230405123909-0247_contactexporttaskhistoryrecord_contactexporttask.js
  apps/condo/pages/_app.tsx
  apps/condo/pages/contact/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3129 feat(condo): DOMA-5487 The `NewsItemTemplate` model
  apps/condo/domains/news/access/NewsItemTemplate.js
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItemTemplate.js
  apps/condo/domains/news/schema/NewsItemTemplate.test.js
  apps/condo/domains/news/schema/index.js
  apps/condo/domains/news/utils/clientSchema/NewsItemTemplate.ts
  apps/condo/domains/news/utils/clientSchema/index.ts
  apps/condo/domains/news/utils/serverSchema/index.js
  apps/condo/domains/news/utils/testSchema/index.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.test.js
  apps/condo/migrations/20230403104445-0246_newsitemtemplatehistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3138 Feat/condo/doma 5651/read news by user
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/access/NewsItemScope.js
  apps/condo/domains/news/access/NewsItemUserRead.js
  apps/condo/domains/news/constants/errors.js
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/schema/NewsItemUserRead.js
  apps/condo/domains/news/schema/NewsItemUserRead.test.js
  apps/condo/domains/news/schema/index.js
  apps/condo/domains/news/utils/accessSchema/index.js
  apps/condo/domains/news/utils/clientSchema/NewsItemUserRead.ts
  apps/condo/domains/news/utils/clientSchema/index.ts
  apps/condo/domains/news/utils/serverSchema/index.js
  apps/condo/domains/news/utils/testSchema/index.js
  apps/condo/migrations/20230403104445-0246_newsitemtemplatehistoryrecord_and_more.js
  apps/condo/migrations/20230405145721-0248_newsitemtemplatehistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3146 fix(condo): DOMA-5614 fix meterReading contact connection
  apps/condo/domains/contact/schema/Contact.js
  apps/condo/domains/contact/schema/Contact.test.js
  apps/condo/domains/meter/schema/MeterReading.js
  apps/condo/domains/meter/schema/MeterReading.test.js
  apps/condo/domains/meter/utils/serverSchema/resolveHelpers.js
Labels: ✋🙂 Review please

#3145 hotfix(condo): Disable reading of some relations
  apps/condo/domains/organization/schema/Organization.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 🦑 API CHANGES

#3154 hotfix(condo): fixed migration 246 - comment about not reversible migration
  apps/condo/migrations/20230403114510-0246_auto_20230403_0645.js
Labels: 🔥 HOTFIX, 🚨 Migrations

#3157 feat(condo): DOMA-5823 add oidc implicit flow support
  apps/condo/domains/user/oidc/configuration.js
  apps/condo/domains/user/schema/_oidc.test.js
Labels: 👶 small, ✋🙂 Review please

#3160 chore(condo): DOMA-5595 split errors and request logs and improve filtration
  packages/keystone/logging/GraphQLLoggerApp.js
Labels: 👶 small, ✋🙂 Review please

#3162 fix(condo): DOMA-5838 fix isSmall variable
  packages/ui/src/components/_utils/hooks/useBreakpoints.tsx
Labels: 👶 small, ✋🙂 Review please

#3149 chore(condo): DOMA-5783 models improvements
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/access/NewsItemUserRead.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/schema/NewsItemScope.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3166 chore(address-service): DOMA-5839 some logs were added
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
  apps/address-service/domains/common/utils/services/suggest/SuggestionKeystoneApp.js
  apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
  apps/address-service/index.js
Labels: 👶 small, ✋🙂 Review please

#3167 refactor(ui): DOMA-5842 fix useBreakpoints linter warnings
  packages/ui/src/components/_utils/hooks/useBreakpoints.tsx
  packages/ui/src/components/_utils/hooks/useForceUpdate.ts
  packages/ui/src/components/_utils/responsiveObserve.ts
Labels: 👶 small, ✋🙂 Review please

#3136 feat(condo): DOMA-5747 add validation of isOutcome field in PredictTransactionClassificationService
  apps/condo/domains/banking/schema/PredictTransactionClassificationService.js
  apps/condo/domains/banking/schema/PredictTransactionClassificationService.test.js
  apps/condo/domains/banking/tasks/importBankTransactions.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3171 DOMA-5846 remove reportVisible field from BankAccount & change ui logic to the publishedAt field
  apps/condo/domains/banking/components/BankAccountReport.tsx
  apps/condo/domains/banking/components/BankAccountVisibilitySelect.tsx
  apps/condo/domains/banking/gql.js
  apps/condo/domains/banking/hooks/useCategoryModal.tsx
  apps/condo/domains/banking/schema/BankAccount.js
  apps/condo/domains/banking/schema/BankAccount.test.js
  apps/condo/migrations/20230412110320-0256_remove_bankaccount_reportvisible_and_more.js
  apps/condo/pages/property/[id]/report.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#3180 fix(condo): DOMA-5717 do not create a new BankAccountReport instance if the transaction pool has not changed. Add tests
  apps/condo/domains/banking/schema/BankAccountReportTask.test.js
  apps/condo/domains/banking/tasks/generateReports.js
  apps/condo/migrations/20230412150028-0257_auto_20230412_1000.js
Labels: 👶 small, ✋🙂 Review please

#3181 Fix/condo/doma 5570/server side api bug
  apps/address-service/domains/common/utils/services/providerDetectors.js
  apps/address-service/domains/common/utils/services/providerDetectors.spec.js
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
  apps/address-service/domains/common/utils/services/search/plugins/AbstractSearchPlugin.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchByFiasId.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchByGooglePlaceId.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchByProvider.js
  apps/address-service/domains/common/utils/services/search/providers/AbstractSearchProvider.js
  apps/address-service/domains/common/utils/services/search/providers/DadataSearchProvider.js
  apps/address-service/domains/common/utils/services/search/providers/GoogleSearchProvider.js
  apps/address-service/domains/common/utils/services/suggest/SuggestionKeystoneApp.js
  apps/address-service/domains/common/utils/services/suggest/providers/AbstractSuggestionProvider.js
  apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
  apps/address-service/domains/common/utils/services/suggest/providers/GoogleSuggestionProvider.js
  apps/address-service/index.js
Labels: 👶 small, ✋🙂 Review please

#3185 Feat/address service/doma 5782/add block type to address key
  apps/address-service/domains/common/utils/addressKeyUtils.js
  apps/address-service/domains/common/utils/addressKeyUtils.spec.js
Labels: 👶 small, ✋🙂 Review please

#3190 DOMA-5876 add encoding converter before 1cExchange file parser
  apps/condo/domains/banking/hooks/useBankTransactionsTable.tsx
  apps/condo/domains/banking/tasks/importBankTransactions.js
  apps/condo/domains/banking/utils/serverSchema/converters/convertFrom1CExchangeToSchema.js
  apps/condo/domains/banking/utils/serverSchema/converters/convertFrom1CExchangeToSchema.spec.js
  apps/condo/domains/banking/utils/serverSchema/converters/convertToUTF8.js
  apps/condo/domains/banking/utils/serverSchema/converters/convertToUTF8.spec.js
  apps/condo/package.json
  yarn.lock
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😵‍💫 dependencies

#3194 fix(condo): DOMA-5888 fix error "not iterable" in changeClientSecret
  apps/condo/domains/banking/gql.js
  apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js
Labels: 👶 small, ✋🙂 Review please

#3198 DOMA-5906 extend postmessage analytics event name validator list
  apps/condo/domains/common/components/PostMessageProvider/validators.ts
  packages/ui/src/components/Select/select.tsx
  packages/ui/src/components/_utils/analytics.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 🎨 UI-kit

#3062 feat(condo): DOMA-5855 Migrate BillingProperty to addressService
  apps/condo/domains/billing/schema/BillingProperty.js
  apps/condo/migrations/20230418113916-0259_billingproperty_addresskey_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/keystone/plugins/addressService.js
Labels: 🔬 WIP

#3123 fix(condo): DOMA-5728 fixed single mutation if iec is null
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
Labels: 👶 small, ✋🙂 Review please

#3209 fix(address-service): DOMA-5946 fix logging
  apps/address-service/domains/common/utils/services/suggest/SuggestionKeystoneApp.js
Labels: 👶 small, ✋🙂 Review please

#3210 fix(condo): DOMA-5938 fixed tickets import
  apps/condo/domains/ticket/hooks/useImporterFunctions.ts
Labels: 👶 small, ✋🙂 Review please

#3205 feat(condo): DOMA-5891 create resetOrganization service
  apps/condo/domains/organization/access/ResetOrganizationService.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/ResetOrganizationService.js
  apps/condo/domains/organization/schema/ResetOrganizationService.test.js
  apps/condo/domains/organization/schema/index.js
  apps/condo/domains/organization/utils/serverSchema/index.js
  apps/condo/domains/organization/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3193 fix(condo): DOMA-5235 added localized-dependent import templates
  apps/condo/domains/common/components/Import/Index.tsx
  apps/condo/domains/common/utils/importer.ts
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/domains/meter/hooks/useImporterFunction.ts
  apps/condo/domains/property/components/BuildingsTable.tsx
  apps/condo/domains/property/hooks/useImporterFunctions.tsx
  apps/condo/domains/ticket/hooks/useImporterFunctions.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/contact/index.tsx
  apps/condo/pages/meter/index.tsx
  apps/condo/pages/ticket/index.tsx
  apps/condo/public/buildings-import-example-en.xlsx
  apps/condo/public/buildings-import-example-ru.xlsx
  apps/condo/public/buildings-import-example.xlsx
  apps/condo/public/contact-import-example-en.xlsx
  apps/condo/public/contact-import-example-ru.xlsx
  apps/condo/public/contact-import-example.xlsx
  apps/condo/public/meter-import-example-en.xlsx
  apps/condo/public/meter-import-example-ru.xlsx
  apps/condo/public/meter-import-example.xlsx
  apps/condo/public/ticket-import-example-en.xlsx
  apps/condo/public/ticket-import-example-ru.xlsx
  apps/condo/public/ticket-import-example.xlsx
Labels: ✋🙂 Review please

#3212 feat(condo): DOMA-5941 modify BankSyncTask to use to start syncTransactionsTask
  apps/condo/domains/banking/constants.js
  apps/condo/domains/banking/gql.js
  apps/condo/domains/banking/schema/BankAccountReportTask.test.js
  apps/condo/domains/banking/schema/BankSyncTask.js
  apps/condo/domains/banking/schema/BankSyncTask.test.js
  apps/condo/domains/banking/schema/fields/BankSyncTaskOptions.js
  apps/condo/domains/banking/utils/testSchema/index.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.spec.js
  apps/condo/domains/organization/tasks/syncSbbolTransactions.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230420101206-0261_banksynctask_options_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3223 Feat/condo/doma 5503/delayed news publication
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/constants/common.js
  apps/condo/domains/news/constants/errors.js
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/utils/accessSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#3217 fix(condo): DOMA-5872 fixed ticket deadline field
  apps/condo/domains/ticket/utils/helpers.ts
Labels: 👶 small, ✋🙂 Review please

#3229 feat(condo): DOMA-5742 add emails validation
  apps/condo/domains/common/constants/regexps.js
  apps/condo/domains/common/hooks/useValidations.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3227 fix(condo): DOMA-5992 fixed minor bugs:
  apps/condo/domains/common/components/ResidentActions/ResidentActions.tsx
  apps/condo/domains/meter/hooks/useTableColumns.tsx
  apps/condo/domains/property/components/BuildingsTable.tsx
  apps/condo/domains/property/hooks/useImporterFunctions.tsx
  apps/condo/domains/property/hooks/usePropertyValidations.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/_app.tsx
Labels: 👶 small, ✋🙂 Review please

#3239 test(condo): DOMA-6002 fix random tests
  apps/condo/domains/banking/schema/BankAccountReportTask.test.js
  apps/condo/domains/banking/schema/BankSyncTask.js
  apps/condo/domains/organization/tasks/syncSbbolTransactions.js
Labels: 👶 small, ✋🙂 Review please

#3241 fix(condo): DOMA-6003 avoid duplicated calls of requestTransactions in cron tasks
  apps/condo/domains/organization/tasks/syncSbbolBankAccounts.js
  apps/condo/domains/organization/tasks/syncSbbolTransactions.js
Labels: 👶 small, ✋🙂 Review please

#3226 DOMA-5968 bank transaction upload period select
  apps/condo/domains/banking/components/BankAccountReport.tsx
  apps/condo/domains/banking/components/BankAccountVisibilitySelect.tsx
  apps/condo/domains/banking/hooks/useBankSyncTaskExternalModal.tsx
  apps/condo/domains/banking/hooks/useBankSyncTaskUIInterface.tsx
  apps/condo/domains/banking/hooks/useFileImport.tsx
  apps/condo/domains/banking/schema/fields/BankSyncTaskOptions.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/property/[id]/report.tsx
Labels: ✋🙂 Review please

#3214 feat(condo): DOMA-5955 added active state for card
  packages/ui/src/components/Card/card.tsx
  packages/ui/src/components/Card/style.less
  packages/ui/src/stories/Card.stories.tsx
  packages/ui/src/tokens/tokens.json
Labels: 👶 small, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit

#3199 feat(condo): DOMA-5400 sendResidentMessageService
  apps/address-service/domains/address/schema/AddressSource.js
  apps/condo/domains/banking/schema/CreateBankAccountRequestService.js
  apps/condo/domains/billing/access/SendNewReceiptMessagesToResidentScopesService.js
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.js
  apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.test.js
  apps/condo/domains/billing/schema/index.js
  apps/condo/domains/billing/utils/accessSchema.js
  apps/condo/domains/billing/utils/serverSchema/index.js
  apps/condo/domains/billing/utils/testSchema/index.js
  apps/condo/domains/common/constants/index.js
  apps/condo/domains/notification/adapters/firebaseAdapter.js
  apps/condo/domains/notification/adapters/firebaseAdapter.spec.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/constants/errors.js
  apps/condo/domains/notification/schema/SendMessageService.test.js
  apps/condo/domains/notification/templates.js
  apps/condo/domains/notification/templates.spec.js
  apps/condo/domains/notification/utils/serverSchema/index.js
  apps/condo/domains/resident/access/SendMessageToResidentScopesService.js
  apps/condo/domains/resident/constants/constants.js
  apps/condo/domains/resident/constants/errors.js
  apps/condo/domains/resident/constants/index.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/schema/SendMessageToResidentScopesService.js
  apps/condo/domains/resident/schema/SendMessageToResidentScopesService.test.js
  apps/condo/domains/resident/schema/index.js
  apps/condo/domains/resident/tasks/helpers/messageTools.js
  apps/condo/domains/resident/tasks/helpers/messageTools.spec.js
  apps/condo/domains/resident/tasks/helpers/sendResidentsNoAccountNotifications.js
  apps/condo/domains/resident/tasks/helpers/sendResidentsNoAccountNotifications.spec.js
  apps/condo/domains/resident/tasks/helpers/spec.helpers.js
  apps/condo/domains/resident/tasks/sendMessageToResidentScopes.task.js
  apps/condo/domains/resident/utils/serverSchema/index.js
  apps/condo/domains/resident/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/BILLING_RECEIPT_CATEGORY_AVAILABLE/default.njk
  apps/condo/lang/en/messages/BILLING_RECEIPT_CATEGORY_AVAILABLE/push.njk
  apps/condo/lang/en/messages/BILLING_RECEIPT_CATEGORY_AVAILABLE/sms.njk
  apps/condo/lang/ru/messages/BILLING_RECEIPT_CATEGORY_AVAILABLE/default.njk
  apps/condo/lang/ru/messages/BILLING_RECEIPT_CATEGORY_AVAILABLE/push.njk
  apps/condo/lang/ru/messages/BILLING_RECEIPT_CATEGORY_AVAILABLE/sms.njk
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/codegen/generate.server.utils.js
  packages/codegen/templates/service00/domains/{{domain}}/schema/{{name}}.js
  packages/keystone/errors.js
  packages/keystone/test.utils.js
Labels: ✋🙂 Review please, 🦑 API CHANGES, 😎 Cool, 🐘 BIG

#3244 fix(condo): DOMA-6024 fixed TooManyProviderTokenUpdates issue
  apps/condo/domains/notification/adapters/apple/AppleJSONWebToken.js
  apps/condo/domains/notification/adapters/apple/AppleJSONWebToken.spec.js
  apps/condo/domains/notification/adapters/apple/AppleMessaging.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😎 Cool

#3243 fix(condo): DOMA-6027 corrected required keys
  apps/condo/domains/banking/utils/serverSchema/converters/convertFrom1CExchangeToSchema.js
  apps/condo/domains/banking/utils/serverSchema/converters/convertFrom1CExchangeToSchema.spec.js
Labels: 👶 small, ✋🙂 Review please

#3234 feat/address-service/doma-5952/bulk search for billing
  apps/address-service/domains/address/schema/Address.test.js
  apps/address-service/domains/common/utils/parseAddressesFromString.js
  apps/address-service/domains/common/utils/parseAddressesFromString.spec.js
  apps/address-service/domains/common/utils/services/index.js
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
  apps/address-service/domains/common/utils/services/search/plugins/AbstractSearchPlugin.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchByAddressKey.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchByProvider.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchBySource.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchBySource.spec.js
  apps/address-service/domains/common/utils/services/search/providers/AbstractSearchProvider.js
  apps/address-service/domains/common/utils/services/search/providers/DadataSearchProvider.js
  apps/address-service/domains/common/utils/services/search/providers/GoogleSearchProvider.js
  apps/address-service/domains/common/utils/services/search/searchServiceUtils.js
  apps/address-service/domains/common/utils/services/search/searchServiceUtils.spec.js
  apps/address-service/domains/common/utils/services/suggest/providers/AbstractSuggestionProvider.js
Labels: ✋🙂 Review please

#3248 fix(condo): DOMA-6040 fix bankAccount creating in import from 1c
  apps/condo/domains/banking/schema/BankSyncTask.test.js
  apps/condo/domains/banking/tasks/importBankTransactionsFrom1CClientBankExchange.js
Labels: 👶 small, ✋🙂 Review please

#3254 fix(condo): DOMA-6050 fixed apple adapter issues & sendAppPushMessage mutation errors
  apps/condo/domains/miniapp/schema/SendAppPushMessageService.js
  apps/condo/domains/miniapp/schema/SendAppPushMessageService.test.js
  apps/condo/domains/notification/adapters/apple/AppleMessaging.js
  apps/condo/domains/notification/transports/push.js
Labels: 👶 small, ✋🙂 Review please, 😎 Cool
