Repository open-condo-software/condo, pull requests merged in 2023-05, with the labels that each got.

#3245 Feat/condo/doma 5652/send push for news items
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/constants/errors.js
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/tasks/index.js
  apps/condo/domains/news/tasks/notifyResidentsAboutDelayedNewsItems.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.helpers.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.spec.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/templates.spec.js
  apps/condo/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/NEWS_ITEM_COMMON_MESSAGE_TYPE/default.njk
  apps/condo/lang/en/messages/NEWS_ITEM_EMERGENCY_MESSAGE_TYPE/default.njk
  apps/condo/lang/ru/messages/NEWS_ITEM_COMMON_MESSAGE_TYPE/default.njk
  apps/condo/lang/ru/messages/NEWS_ITEM_EMERGENCY_MESSAGE_TYPE/default.njk
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230428111758-0265_newsitem_ispublished_newsitem_sentat_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🔬 WIP, ✋🙂 Review please, 🚨 Migrations

#3253 fix(condo): DOMA-6049 removed checking for iec when creating/updating…
  apps/condo/domains/billing/schema/BillingReceipt.js
Labels: 👶 small

#3256 fix(condo): DOMA-6052 fix import transactions from 1c
  apps/condo/domains/banking/utils/serverSchema/converters/convertFrom1CExchangeToSchema.js
  apps/condo/domains/banking/utils/serverSchema/converters/convertFrom1CExchangeToSchema.spec.js
Labels: 👶 small, ✋🙂 Review please

#3261 DOMA-5893 change bankaccount category modal behaviour to fit-content
  apps/condo/domains/banking/hooks/useCategoryModal.tsx
Labels: 👶 small, ✋🙂 Review please

#3264 fix(condo): DOMA-5400 fixed where conditions
  apps/condo/domains/billing/schema/BillingReceipt.test.js
  apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.js
  apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.test.js
  apps/condo/domains/billing/utils/validation.utils.js
  apps/condo/domains/billing/utils/validation.utils.spec.js
  apps/condo/domains/common/utils/date.js
  apps/condo/domains/resident/tasks/sendMessageToResidentScopes.task.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3267 fix(condo): DOMA-6064 fix where condition in found duplicate transaction
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
Labels: 👶 small, ✋🙂 Review please

#3270 fix(condo): DOMA-6064 fix iso codes for sbbol
  apps/condo/domains/common/constants/currencies.js
Labels: 👶 small, ✋🙂 Review please

#3272 fix(condo): DOMA-6078 fix organization constraint. Unique only where deletedAt is null
  apps/condo/domains/organization/schema/Organization.js
  apps/condo/migrations/20230503235235-0266_remove_organization_unique_organization_importid_and_importremotesystem_and_more.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#3276 hotfix(condo): HOTFIX add deletedAt in BankSyncTask validateInput
  apps/condo/domains/banking/schema/BankSyncTask.js
Labels: 👶 small, ✋🙂 Review please

#3277 hotfix(condo): HOTFIX added deletedAt filter to find employee in syncOrganization
  apps/condo/domains/organization/integrations/sbbol/sync/syncOrganization.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncOrganization.spec.js
Labels: 👶 small, ✋🙂 Review please

#3285 DOMA-6058 allow employee to update acquiring context
  apps/condo/domains/acquiring/access/AcquiringIntegrationContext.js
  apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.test.js
Labels: 👶 small, ✋🙂 Review please

#3295 hotfix(condo): DOMA-5615 patch existing migrations to save old cols
  apps/condo/migrations/20230505173500-0267_rename_appurl_acquiringintegration_setupurl_and_more.js
  apps/condo/migrations/20230510150829-0268_rename_setupurl_acquiringintegration_appurl_and_more.js
Labels: 🔥 HOTFIX, 🚨 Migrations

#3294 fix(condo): DOMA-6088 fix BankTransaction constraint. Check uniq only group ['organization', 'importRemoteSystem', 'importId']
  apps/condo/domains/banking/schema/BankSyncTask.test.js
  apps/condo/domains/banking/schema/BankTransaction.js
  apps/condo/domains/banking/schema/BankTransaction.test.js
  apps/condo/domains/banking/schema/PredictTransactionClassificationService.js
  apps/condo/domains/banking/tasks/importBankTransactionsFrom1CClientBankExchange.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
  apps/condo/migrations/20230511104849-0269_remove_banktransaction_bank_transaction_unique_number_date_organization_and_more.js
  apps/condo/migrations/20230511104910-0270_auto_20230511_0549.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🚨 Migrations

#3293 feat(condo): DOMA-4092 deleted default value "deferredUntil" for defe…
  apps/condo/domains/property/schema/Property.test.js
  apps/condo/domains/ticket/schema/Ticket.js
  apps/condo/domains/ticket/schema/Ticket.test.js
  apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
Labels: 👶 small, ✋🙂 Review please

#3260 chore(DOMA-6063): add todo for `registerResident` API
  apps/condo/domains/resident/schema/RegisterResidentService.js
Labels: 👶 small

#3301 fix(condo): DOMA-6117 fix ticket comments scroll
  apps/condo/domains/common/components/Comments/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3298 fix(condo): DOMA-6116 catch features response parsing error
  packages/featureflags/featureToggleManager.js
Labels: 👶 small, ✋🙂 Review please

#3249 Feat/condo/doma 5708/profanity control
  apps/condo/domains/news/constants/errors.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/package.json
  yarn.lock
Labels: ✋🙂 Review please, 😎 Cool

#3266 feat(condo): DOMA-5724 News items sending delay
  .github/workflows/nodejs.condo.test.yml
  apps/condo/domains/news/README.md
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/constants/common.js
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/schema/NewsItemScope.js
  apps/condo/domains/news/schema/NewsItemScope.test.js
  apps/condo/domains/news/schema/NewsItemUserRead.test.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
  apps/condo/domains/news/utils/testSchema/index.js
Labels: ✋🙂 Review please

#3297 Feat/condo/doma 6041/notifications user settings
  apps/condo/domains/notification/access/NotificationUserSetting.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/constants/errors.js
  apps/condo/domains/notification/gql.js
  apps/condo/domains/notification/helpers/index.js
  apps/condo/domains/notification/schema/NotificationUserSetting.js
  apps/condo/domains/notification/schema/NotificationUserSetting.test.js
  apps/condo/domains/notification/schema/index.js
  apps/condo/domains/notification/tasks/deliverMessage.js
  apps/condo/domains/notification/utils/clientSchema/NotificationUserSetting.ts
  apps/condo/domains/notification/utils/clientSchema/index.ts
  apps/condo/domains/notification/utils/serverSchema/helpers.js
  apps/condo/domains/notification/utils/serverSchema/helpers.spec.js
  apps/condo/domains/notification/utils/serverSchema/index.js
  apps/condo/domains/notification/utils/testSchema/index.js
  apps/condo/migrations/20230512125356-0271_notificationusersettinghistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3311 Add hostname to metrics.js
  packages/keystone/metrics.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, infrastructure, 😎 Cool

#3315 fix(condo): DOMA-6135 fixed incident close without "workFinish"
  apps/condo/domains/ticket/hooks/useIncidentUpdateStatusModal.tsx
  apps/condo/domains/ticket/schema/Incident.js
  apps/condo/domains/ticket/schema/Incident.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3324 feat(condo): DOMA-6148 sbbol use v2 version of resource account statement
  apps/condo/domains/organization/integrations/sbbol/SbbolFintechApi.js
Labels: 👶 small

#3321 fix(condo): DOMA-5914 fixed multiple filter modal footer
  apps/condo/domains/common/components/DeleteButtonWithConfirmModal.tsx
  apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/ticket/index.tsx
  packages/ui/src/components/Button/style.less
Labels: 👶 small, ✋🙂 Review please, 📦 Packages

#3325 fix(address-service): DOMA-6154 search source case-insensitive, error…
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchBySource.js
Labels: 👶 small, ✋🙂 Review please

#3327 fix(condo): DOMA-5588 fixed validation for meter number in useUpdateMeterModal
  apps/condo/domains/meter/hooks/useUpdateMeterModal.tsx
Labels: 👶 small, ✋🙂 Review please

#3332 Feature/condo/doma 6140/allow employee to add billing recipients
  apps/condo/domains/billing/access/BillingRecipient.js
  apps/condo/domains/billing/schema/BillingRecipient.js
  apps/condo/domains/billing/schema/BillingRecipient.test.js
  apps/condo/domains/billing/utils/testSchema/index.js
Labels: 👶 small, ✋🙂 Review please

#3328 fix(condo): DOMA-5830 added "isVerified" column for exporting contacts
  apps/condo/domains/common/utils/exportToExcel.js
  apps/condo/domains/contact/schema/ContactExportTask.test.js
  apps/condo/domains/contact/tasks/exportContacts.js
  apps/condo/domains/contact/templates/ContactsExportTemplate.xlsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3341 HOTFIX update featureflag context with organizationId globally
  apps/condo/domains/ticket/contexts/AutoRefetchTicketsContext.tsx
  packages/featureflags/FeatureFlagsContext.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3342 hotfix(condo): HOTFIX use featureFlag context in sbbol syncTask
  apps/condo/domains/organization/integrations/sbbol/sync/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3319 Feat/condo/doma 5488/news push messages throttling
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
  apps/condo/domains/notification/access/NotificationUserSetting.js
  apps/condo/domains/notification/schema/NotificationUserSetting.js
  apps/condo/domains/notification/schema/NotificationUserSetting.test.js
  apps/condo/domains/notification/schema/SendMessageService.js
  packages/keystone/schema.js
Labels: ✋🙂 Review please

#3312 fix(condo): DOMA-6083 added fields, fixed/refactored/added tests
  apps/condo/domains/miniapp/access/SendB2CAppPushMessageService.js
  apps/condo/domains/miniapp/constants.js
  apps/condo/domains/miniapp/gql.js
  apps/condo/domains/miniapp/schema/MessageAppBlackList.test.js
  apps/condo/domains/miniapp/schema/SendAppPushMessageService.test.js
  apps/condo/domains/miniapp/schema/SendB2CAppPushMessageService.js
  apps/condo/domains/miniapp/schema/SendB2CAppPushMessageService.test.js
  apps/condo/domains/miniapp/schema/index.js
  apps/condo/domains/miniapp/utils/serverSchema/index.js
  apps/condo/domains/miniapp/utils/testSchema/index.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/codegen/generate.test.utils.js
Labels: ✋🙂 Review please, 🦑 API CHANGES

#3345 refactor(condo): DOMA-5862 introducing mono-pub 🎉
  .github/workflows/packages.release.yml
  bin/publish-packages.js
  package.json
  release.config.js
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#3351 fix(condo): DOMA-6163 fixed translations
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3336 fix(condo): DOMA-5494 fixed meter table rendering
  apps/condo/domains/common/components/Table/Renders.tsx
Labels: 👶 small, ✋🙂 Review please

#3339 fix(condo): DOMA-5245 fixed validator on employee creating and updating pages
  apps/condo/domains/organization/components/EmployeeForm/CreateEmployeeForm.tsx
  apps/condo/domains/organization/components/EmployeeForm/UpdateEmployeeForm.tsx
  apps/condo/domains/organization/hooks/useEmployeeValidations.ts
Labels: ✋🙂 Review please

#3330 refactor(condo): DOMA-6150 refactor auth layouts
  apps/condo/domains/common/components/Poster.tsx
  apps/condo/domains/user/components/auth/RegisterForm.tsx
  apps/condo/domains/user/components/auth/ValidatePhoneForm.tsx
  apps/condo/domains/user/components/containers/AuthHeader.tsx
  apps/condo/domains/user/components/containers/AuthLayout.tsx
  apps/condo/domains/user/components/containers/PosterLayout.tsx
  apps/condo/domains/user/components/containers/styles.tsx
  apps/condo/pages/404.tsx
  apps/condo/pages/500.tsx
  apps/condo/pages/_error.tsx
Labels: ✋🙂 Review please

#3289 feat(condo): DOMA-6054 add BillingReceiptFile model
  apps/condo/domains/billing/access/BillingReceiptFile.js
  apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
  apps/condo/domains/billing/components/ServicesModal.tsx
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/hooks/useReceiptTableColumns.ts
  apps/condo/domains/billing/schema/BillingReceiptFile.js
  apps/condo/domains/billing/schema/BillingReceiptFile.test.js
  apps/condo/domains/billing/schema/index.js
  apps/condo/domains/billing/utils/clientSchema/BillingReceiptFile.ts
  apps/condo/domains/billing/utils/clientSchema/index.ts
  apps/condo/domains/billing/utils/serverSchema/index.js
  apps/condo/domains/billing/utils/testSchema/index.js
  apps/condo/domains/common/components/Table/Renders.tsx
  apps/condo/domains/common/components/containers/GlobalStyle.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230519181459-0274_billingreceiptfilehistoryrecord_billingreceiptfile.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🔬 WIP, 🚨 Migrations

#3350 fix(condo): DOMA-5669 added number validation for contact form
  apps/condo/domains/common/hooks/useValidations.ts
  apps/condo/domains/contact/components/ContactsEditor/NewContactFields.tsx
  apps/condo/domains/contact/components/ContactsEditor/NotResidentFields.tsx
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
  apps/condo/domains/organization/hooks/useEmployeeValidations.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#3358 fix(condo): DOMA-6171 fixed display of time in history of changes on …
  apps/condo/domains/ticket/hooks/useIncidentChangedFieldMessagesOf.tsx
Labels: 👶 small, ✋🙂 Review please

#3356 feat(condo): DOMA-6170 New fields for push messages
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
Labels: 👶 small, ✋🙂 Review please

#3359 fix(condo): DOMA-6177 fixed export contacts
  apps/condo/domains/contact/utils/serverSchema/index.js
Labels: 👶 small, ✋🙂 Review please

#3360 fix(condo): DOMA-6166 fixed loading in organization select
  apps/condo/domains/organization/components/OrganizationSelect.tsx
Labels: 👶 small, ✋🙂 Review please

#3367 fix(condo): DOMA-6054 add disabled state to pdf button
  apps/condo/domains/billing/components/ServicesModal.tsx
Labels: 👶 small

#3366 fix(condo): DOMA-6196 fixed display of organizations on user page
  apps/condo/domains/user/components/UserOrganizationsList.tsx
Labels: 👶 small, ✋🙂 Review please

#3372 fix(condo): DOMA-4512 fixed contact role form validation
  apps/condo/domains/contact/components/contactRoles/BaseContactRoleForm.tsx
  apps/condo/domains/contact/components/contactRoles/useExistingContactRoles.tsx
Labels: 👶 small, ✋🙂 Review please

#3378 fix(condo): DOMA-4696 added show error on change password page
  apps/condo/domains/user/components/auth/ValidatePhoneForm.tsx
  apps/condo/pages/auth/change-password.tsx
  apps/condo/pages/auth/forgot.tsx
Labels: ✋🙂 Review please

#3384 fix(condo): DOMA-5073 fixed filter and sort by role for contacts
  apps/condo/domains/contact/hooks/useTableColumns.tsx
  apps/condo/domains/contact/hooks/useTableFilters.tsx
  apps/condo/pages/contact/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3316 Feat/condo/doma 5919/news item recipients count component
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/components/RecipientCounter.tsx
  apps/condo/domains/news/components/types.ts
  apps/condo/domains/news/constants/errors.js
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/schema/NewsItemScope.js
  apps/condo/domains/news/schema/NewsItemScope.test.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
  apps/condo/domains/news/utils/accessSchema/index.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/utils/clientSchema/Resident.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/demo/index.tsx
Labels: ✋🙂 Review please

#3383 fix(condo): DOMA-5052 fixed registration error displaying
  apps/condo/domains/user/components/auth/RegisterForm.tsx
  apps/condo/domains/user/components/auth/hooks.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3393 fix(condo): DOMA-6221 fix onboarding complete modal
  apps/condo/domains/common/components/Poster.tsx
  apps/condo/domains/onboarding/hooks/useOnBoardingCompleeteModal.tsx
  apps/condo/domains/user/components/containers/PosterLayout.tsx
  apps/condo/pages/404.tsx
  apps/condo/pages/500.tsx
Labels: 👶 small, 🔥 HOTFIX

#3394 fix(condo): DOMA-6055 added meta to file for permission check
  apps/condo/domains/billing/schema/BillingReceiptFile.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3365 fix(condo): DOMA-3289 added spaces trimming for "number" and "account Number"…
  apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalAccountNumberField.tsx
  apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalDatePicker.tsx
  apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx
  apps/condo/domains/meter/constants/errors.js
  apps/condo/domains/meter/hooks/useImporterFunctions.ts
  apps/condo/domains/meter/schema/Meter.js
  apps/condo/domains/meter/schema/Meter.test.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/meter/index.tsx
Labels: ✋🙂 Review please

#3387 fix(condo): DOMA-5070 added validation meter values when meters import
  apps/condo/domains/meter/hooks/useImporterFunctions.ts
  apps/condo/domains/meter/utils/helpers.spec.ts
  apps/condo/domains/meter/utils/helpers.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#3408 feat(condo): DOMA-4452 added meter place for import
  apps/condo/domains/meter/hooks/useImporterFunctions.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/public/meter-import-example-en.xlsx
  apps/condo/public/meter-import-example-ru.xlsx
Labels: 👶 small, ✋🙂 Review please

#3405 chore(condo): DOMA-6244 allow admin&support to read scopes
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  packages/keystone/test.utils.js
Labels: 👶 small, ✋🙂 Review please

#3409 feat(condo): DOMA-6254 restrict unitName without unitType
  apps/condo/domains/news/components/RecipientCounter.tsx
  apps/condo/domains/news/constants/errors.js
  apps/condo/domains/news/schema/NewsItemScope.js
  apps/condo/domains/news/schema/NewsItemScope.test.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
  apps/condo/domains/news/utils/accessSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3410 fix(condo): DOMA-5489 fixed autocomplete onboarding step with employe…
  apps/condo/domains/onboarding/components/OnBoardingContext.tsx
Labels: 👶 small, ✋🙂 Review please

#3414 Hotfix/condo/fix sync contact mutation error
  apps/condo/domains/contact/schema/_internalSyncContactsWithResidentsForOrganizationService.js
  apps/condo/domains/contact/schema/_internalSyncContactsWithResidentsForOrganizationService.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please
