Repository open-condo-software/condo, pull requests merged in 2023-03, with the labels that each got.

#2973 fix(address-service): DOMA-5443 improve keys regeneration script
  apps/address-service/bin/regenerate-keys.js
Labels: 👶 small, ✋🙂 Review please

#2971 fix(condo): DOMA-4930 fixed search input by phone modal
  apps/condo/domains/common/hooks/useSearchByPhoneModal.tsx
Labels: 👶 small, ✋🙂 Review please

#2975 feat(condo): DOMA-5170 add Paid column to billing page
  apps/condo/domains/billing/hooks/useReceiptTableColumns.ts
  apps/condo/domains/billing/schema/fields/BillingReceipt/ToPayDetailsField.js
  apps/condo/domains/common/components/Table/Renders.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 🔬 WIP

#2981 fix(condo): DOMA-5468 Fixed collapsed icons tooltip
  apps/condo/domains/common/components/MenuItem.tsx
Labels: 👶 small, ✋🙂 Review please

#2990 fix(condo): DOMA-5474 fixed onboarding links
  apps/condo/domains/onboarding/components/OnBoardingContext.tsx
Labels: 👶 small, ✋🙂 Review please

#2991 ci(ui): DOMA-5481 Sync chromatic
  .github/workflows/packages.ui.sync-baseline.yml
Labels: 👶 small, ✋🙂 Review please, infrastructure

#2992 hotfix(condo): DOMA-5483 added additional params to redlock acquire
  packages/keystone/fields/AutoIncrementInteger/Implementation.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2998 feat(icons): DOMA-5498 added new icons
  packages/icons/src/components/Inbox.tsx
  packages/icons/src/components/Key.tsx
  packages/icons/src/components/Search.tsx
  packages/icons/src/components/Slash.tsx
  packages/icons/src/index.ts
Labels: 👶 small, ✋🙂 Review please, 📦 Packages

#3001 Remove useless bin/warm-docker-cache file
  bin/warm-docker-cache
Labels: 👶 small, ✋🙂 Review please

#2999 fix(condo): DOMA-5500 fix changedBy role field logic
  apps/condo/domains/organization/utils/testSchema/index.js
  apps/condo/domains/ticket/schema/IncidentChange.js
  apps/condo/domains/ticket/schema/TicketChange.js
  apps/condo/domains/ticket/schema/TicketChange.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#2993 fix(condo): DOMA-5480 fixed cypress tests
  apps/condo/cypress/cypress.config.ts
  apps/condo/cypress/objects/Ticket.ts
Labels: 👶 small, ✋🙂 Review please

#3009 DOMA-5521 Renamed entity BankIntegrationContext to BankIntegrationAccountContext
  apps/condo/domains/banking/access/BankIntegrationAccountContext.js
  apps/condo/domains/banking/gql.js
  apps/condo/domains/banking/schema/BankAccount.js
  apps/condo/domains/banking/schema/BankAccount.test.js
  apps/condo/domains/banking/schema/BankIntegrationAccountContext.js
  apps/condo/domains/banking/schema/BankIntegrationAccountContext.test.js
  apps/condo/domains/banking/schema/BankSyncTask.js
  apps/condo/domains/banking/schema/BankSyncTask.test.js
  apps/condo/domains/banking/schema/BankTransaction.js
  apps/condo/domains/banking/schema/BankTransaction.test.js
  apps/condo/domains/banking/schema/index.js
  apps/condo/domains/banking/tasks/importBankTransactions.js
  apps/condo/domains/banking/tasks/importBankTransactions.spec.js
  apps/condo/domains/banking/utils/clientSchema/BankIntegrationAccountContext.ts
  apps/condo/domains/banking/utils/clientSchema/BankIntegrationContext.ts
  apps/condo/domains/banking/utils/clientSchema/index.ts
  apps/condo/domains/banking/utils/serverSchema/index.js
  apps/condo/domains/banking/utils/testSchema/index.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.spec.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncBankAccounts.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.test.js
  apps/condo/domains/organization/tasks/syncSbbolTransactions.js
  apps/condo/migrations/20230309152309-0231_rename_bankintegrationcontext_bankintegrationaccountcontext_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3012 feat(ui): DOMA-5527 Added basic tabs
  packages/ui/src/components/Tabs/index.ts
  packages/ui/src/components/Tabs/style.less
  packages/ui/src/components/Tabs/tabs.tsx
  packages/ui/src/index.ts
  packages/ui/src/stories/Tabs.stories.tsx
Labels: 👶 small, ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#3015 DOMA-5534 fix GQLError in syncSbbolBankAccounts task
  apps/condo/domains/organization/tasks/syncSbbolBankAccounts.js
  apps/condo/domains/organization/tasks/syncSbbolTransactions.js
Labels: 👶 small, ✋🙂 Review please

#3020 feat(condo): DOMA-5542 Replace origins with windows
  apps/condo/domains/common/components/PostMessageProvider/Provider.tsx
  apps/condo/domains/miniapp/components/IFrame.tsx
Labels: 👶 small, ✋🙂 Review please

#3022 feat(condo): DOMA-5540 added webhooks for Ticket
  apps/condo/domains/ticket/schema/Ticket.js
Labels: 👶 small, ✋🙂 Review please

#3025 fix(condo): DOMA-5456 fixed tracking for Select with mode "tags"
  apps/condo/domains/common/components/antd/Select.tsx
Labels: 👶 small, ✋🙂 Review please

#3002 refactor(condo): DOMA-5201 added deleteName param to resetUser mutation
  apps/condo/domains/user/schema/ResetUserService.js
  apps/condo/domains/user/schema/ResetUserService.test.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3030 fix(condo): DOMA-2668 Prevent empty organization name
  apps/condo/domains/organization/hooks/useCreateOrganizationModalForm.tsx
Labels: 👶 small, ✋🙂 Review please

#3036 fix(condo): DOMA-5570 fix address service client suggestions calls
  packages/keystone/plugins/utils/address-service-client/AddressServiceClient.js
Labels: 👶 small, ✋🙂 Review please

#3038 chore(deps): DOMA-5407 updated package "phone" to v3.1.36
  apps/condo/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😵‍💫 dependencies

#3000 Use one `debug` package for all
  package.json
  yarn.lock
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😵‍💫 dependencies

#3049 feat(ui): DOMA-5530 analytics in tabs
  packages/ui/src/components/Select/select.tsx
  packages/ui/src/components/Tabs/tabs.tsx
  packages/ui/src/components/_utils/analytics.ts
Labels: 👶 small, ✋🙂 Review please, 🎨 UI-kit, 📦 Packages

#3054 Fix/condo/doma 5604/profile language control position
  apps/condo/pages/user/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3056 fix(condo): DOMA-5605 made date field not required, set it on server side
  apps/condo/domains/meter/schema/MeterReading.js
  apps/condo/domains/meter/schema/MeterReading.test.js
  apps/condo/migrations/20230321162811-0237_alter_meterreading_date.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#3047 Fix logging and improve DX
  .env.example
  apps/condo/domains/notification/utils/serverSchema/index.js
  apps/condo/domains/organization/schema/Organization.js
  apps/condo/domains/user/schema/SendMessageToSupportService.js
  apps/condo/index.js
  bin/keystone-dev.js
  packages/featureflags/README.md
  packages/featureflags/featureToggleManager.js
  packages/keystone/logging/GraphQLLoggerApp.js
  packages/keystone/logging/getKeystonePinoOptions.js
  packages/keystone/logging/getReqLoggerContext.js
  packages/keystone/logging/index.js
  packages/keystone/tasks.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3026 Add `generateServerUtils` code guard
  apps/condo/domains/billing/utils/serverSchema/index.js
  apps/condo/domains/notification/utils/serverSchema/index.js
  apps/condo/domains/property/utils/serverSchema/index.js
  packages/codegen/generate.server.utils.js
Labels: 👶 small, ✋🙂 Review please

#2943 DOMA-5403 create schema BankIntegrationAccessRight
  apps/condo/domains/banking/access/BankAccount.js
  apps/condo/domains/banking/access/BankCategory.js
  apps/condo/domains/banking/access/BankContractorAccount.js
  apps/condo/domains/banking/access/BankCostItem.js
  apps/condo/domains/banking/access/BankIntegrationAccessRight.js
  apps/condo/domains/banking/access/BankIntegrationAccountContext.js
  apps/condo/domains/banking/access/BankIntegrationOrganizationContext.js
  apps/condo/domains/banking/access/BankTransaction.js
  apps/condo/domains/banking/gql.js
  apps/condo/domains/banking/schema/BankAccount.test.js
  apps/condo/domains/banking/schema/BankContractorAccount.test.js
  apps/condo/domains/banking/schema/BankIntegration.js
  apps/condo/domains/banking/schema/BankIntegrationAccessRight.js
  apps/condo/domains/banking/schema/BankIntegrationAccessRight.test.js
  apps/condo/domains/banking/schema/BankIntegrationAccountContext.test.js
  apps/condo/domains/banking/schema/BankTransaction.test.js
  apps/condo/domains/banking/schema/index.js
  apps/condo/domains/banking/utils/accessSchema.js
  apps/condo/domains/banking/utils/clientSchema/BankIntegrationAccessRight.ts
  apps/condo/domains/banking/utils/clientSchema/index.ts
  apps/condo/domains/banking/utils/serverSchema/index.js
  apps/condo/domains/banking/utils/testSchema/index.js
  apps/condo/domains/notification/utils/clientSchema/MessageOrganizationBlackList.ts
  apps/condo/domains/organization/access/Organization.js
  apps/condo/migrations/20230322133505-0239_bankintegrationaccessrighthistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3068 fix(condo): DOMA-5619 fix case when unitName1 and unitName2 are same
  apps/condo/domains/ticket/schema/TicketChange.test.js
Labels: 👶 small, ✋🙂 Review please

#3074 DOMA-5623 add admin gql types for customAccess User field
  apps/condo/domains/user/gql.js
  apps/condo/domains/user/schema/User.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3073 fix(condo): DOMA-5513 prevent meter creation with the same unitName and different unitType
  apps/condo/domains/meter/schema/Meter.js
  apps/condo/domains/meter/schema/Meter.test.js
Labels: 👶 small, ✋🙂 Review please

#3048 feat(condo): DOMA-5578 create ExternalTokenAccessRight schema
  apps/condo/domains/organization/gql.js
  apps/condo/domains/user/access/ExternalTokenAccessRight.js
  apps/condo/domains/user/components/.gitkeep
  apps/condo/domains/user/constants.js
  apps/condo/domains/user/gql.js
  apps/condo/domains/user/schema/ExternalTokenAccessRight.js
  apps/condo/domains/user/schema/ExternalTokenAccessRight.test.js
  apps/condo/domains/user/schema/index.js
  apps/condo/domains/user/utils/clientSchema/ExternalTokenAccessRight.ts
  apps/condo/domains/user/utils/clientSchema/index.ts
  apps/condo/domains/user/utils/serverSchema/index.js
  apps/condo/domains/user/utils/testSchema/index.js
  apps/condo/migrations/20230323133850-0242_externaltokenaccessrighthistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3088 ci(condo): DOMA-5601 fixed saving cypress screenshots in case of failure
  .github/workflows/nodejs.condo.cypress.yml
Labels: 👶 small, ✋🙂 Review please

#2931 feature(condo): DOMA-5395 added upload file support
  packages/apollo-server-client/Readme.md
  packages/apollo-server-client/examples/Todo.txt
  packages/apollo-server-client/examples/ticket.js
  packages/apollo-server-client/index.js
Labels: 👶 small, ✋🙂 Review please

#3085 feat(condo): DOMA-5613 create PredictTransactionClassificationService
  apps/condo/domains/banking/access/PredictTransactionClassificationService.js
  apps/condo/domains/banking/gql.js
  apps/condo/domains/banking/schema/PredictTransactionClassificationService.js
  apps/condo/domains/banking/schema/PredictTransactionClassificationService.test.js
  apps/condo/domains/banking/schema/index.js
  apps/condo/domains/banking/utils/serverSchema/index.js
  apps/condo/domains/banking/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3091 DOMA-5670 change property select disabled expression at sbbol import
  apps/condo/domains/banking/components/SbbolImportModal.tsx
Labels: 👶 small, ✋🙂 Review please

#3089 feature(address-service): DOMA-5656 added parsing of address from string
  apps/address-service/domains/common/utils/parseAddressesFromString.js
  apps/address-service/domains/common/utils/parseAddressesFromString.spec.js
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#3057 feat(condo): DOMA-5402 create GetAccessTokenByUserIdService
  apps/condo/bin/sbbol/crypto.js
  apps/condo/domains/organization/integrations/sbbol/SbbolFintechApi.js
  apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.js
  apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.spec.js
  apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js
  apps/condo/domains/organization/integrations/sbbol/utils/getSbbolSecretStorage.js
  apps/condo/domains/user/access/GetAccessTokenByUserIdService.js
  apps/condo/domains/user/gql.js
  apps/condo/domains/user/schema/GetAccessTokenByUserIdService.js
  apps/condo/domains/user/schema/GetAccessTokenByUserIdService.test.js
  apps/condo/domains/user/schema/index.js
  apps/condo/domains/user/utils/serverSchema/index.js
  apps/condo/domains/user/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3078 fix(condo): DOMA-5635 fixed access in UserTicketCommentReadTime
  apps/condo/domains/ticket/access/UserTicketCommentReadTime.js
  apps/condo/domains/ticket/schema/UserTicketCommentReadTime.test.js
Labels: 👶 small, ✋🙂 Review please

#3092 feat(condo): DOMA-5677 use predictTransactionClassification in syncTransaction from SBBOL
  apps/condo/domains/banking/gql.js
  apps/condo/domains/banking/schema/PredictTransactionClassificationService.js
  apps/condo/domains/banking/utils/serverSchema/index.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.spec.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3102 feat(condo): DOMA-5653 updated visible ticket sources
  apps/condo/domains/ticket/constants/common.js
Labels: 👶 small, ✋🙂 Review please

#3101 feat(condo): DOMA-5021 add deeplink to account creation form
  apps/condo/domains/notification/adapters/hcm/constants.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/schema/Resident.test.js
  apps/condo/domains/resident/tasks/helpers/sendResidentsNoAccountNotifications.js
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#3112 fix(condo): DOMA-5709 hide contacts with deleted properties in client card
  apps/condo/pages/phone/[number]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3114 fix(condo): DOMA-5700 fixed search for incidents by address
  apps/condo/pages/incident/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3113 feat(condo): DOMA-5707 two new fields for newsItem
  apps/condo/domains/news/constants/errors.js
  apps/condo/domains/news/constants/newsTypes.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230330110343-0244_newsitem_sendat_newsitem_validbefore_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3121 hotfix(condo): typo at intl lang file
  apps/condo/lang/ru/ru.json
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3127 fix(condo): DOMA-5723 fix responsive filters container
  apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
  apps/condo/domains/common/components/containers/EmptyLayout/EmptyLayout.tsx
  apps/condo/pages/ticket/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3090 Remove language hardcode
  apps/condo/domains/user/schema/ConfirmPhoneActionService.js
  apps/condo/domains/user/schema/ForgotPasswordService.js
  apps/condo/domains/user/schema/RegisterNewUserService.js
Labels: 👶 small, ✋🙂 Review please
