Repository open-condo-software/condo, pull requests merged in 2023-12, with the labels that each got.

#4134 fix(condo): DOMA-7713 add email from acquiring offer
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/OfferSetup.tsx
Labels: 👶 small, ✋🙂 Review please

#4144 fix(condo): DOMA-7890 tax percent default value in `null`
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/RequisitesSetup.tsx
Labels: 👶 small, ✋🙂 Review please

#4149 feat(condo): DOMA-7827 market item card
  apps/condo/domains/common/components/ImagesUploadList.tsx
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/utils/clientSchema/Invoice.ts
  apps/condo/domains/marketplace/utils/clientSchema/MarketItem.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/marketplace/marketItem/[id]/index.tsx
Labels: ✋🙂 Review please

#4170 fix(condo): DOMA-7890 Make 'no vat' as default option
  .husky/pre-commit
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/RequisitesSetup.tsx
Labels: 👶 small, ✋🙂 Review please

#4177 fix(condo): DOMA-7971 fix toPay field update in receiptResolver
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.new.test.js
  apps/condo/domains/billing/schema/resolvers/accountResolver.js
  apps/condo/domains/billing/schema/resolvers/lib.js
  apps/condo/domains/billing/schema/resolvers/receiptResolver.js
Labels: 👶 small, ✋🙂 Review please

#4058 News sharing domain model
  apps/condo/domains/miniapp/schema/B2BAppNewsSharingConfig.js
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/access/NewsItemSharing.js
  apps/condo/domains/news/constants/newsItemSharingStatuses.js
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/schema/NewsItemSharing.js
  apps/condo/domains/news/schema/NewsItemSharing.test.js
  apps/condo/domains/news/schema/index.js
  apps/condo/domains/news/tasks/index.js
  apps/condo/domains/news/tasks/publishSharedNewsItem.js
  apps/condo/domains/news/tasks/publishSharedNewsItemsByNewsItem.js
  apps/condo/domains/news/utils/clientSchema/NewsItemSharing.ts
  apps/condo/domains/news/utils/clientSchema/index.ts
  apps/condo/domains/news/utils/serverSchema/index.js
  apps/condo/domains/news/utils/testSchema/index.js
  apps/condo/migrations/20231212174253-0351_newsitemsharinghistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/keystone/test.utils.js
Labels: 🚨 Migrations, 🐘 BIG

#4169 feat(condo): DOMA-7882 add registerServiceConsumer v2
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
  apps/condo/domains/resident/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4187 fix(condo): Do not change isApproved on existing recipients
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.new.test.js
  apps/condo/domains/billing/schema/resolvers/recipientResolver.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4041 fix(condo): DOMA-7604 fix `TicketPropertyHintProperty` duplicates
  apps/condo/domains/ticket/components/TicketPropertyHint/BaseTicketPropertyHintForm.tsx
  apps/condo/domains/ticket/components/TicketPropertyHint/SettingsContent.tsx
  apps/condo/domains/ticket/hooks/useTicketPropertyHintTableColumns.tsx
  apps/condo/domains/ticket/schema/TicketPropertyHintProperty.js
  apps/condo/domains/ticket/schema/TicketPropertyHintProperty.test.js
  apps/condo/domains/ticket/utils/clientSchema/TicketPropertyHintProperty.ts
  apps/condo/migrations/20231214092431-0352_auto_20231214_0424.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#4191 feat(condo): DOMA-7983 added userParams to YMetrika
  apps/condo/domains/common/components/containers/YandexMetrika.tsx
Labels: 👶 small, ✋🙂 Review please

#4198 fix(condo): DOMA-7994 search property by addressKey during the reside…
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/BillingReceiptFile.test.js
  apps/condo/domains/resident/schema/RegisterResidentService.js
Labels: 👶 small, ✋🙂 Review please

#4208 chore(condo): DOMA-7999 added logs when send webhooks
  packages/webhooks/tasks/sendWebhook.js
Labels: 👶 small, ✋🙂 Review please

#4213 Revert "feat(condo): DOMA-7939 yandex metrika v2 (#4164)"
  apps/condo/domains/common/components/containers/YandexMetrika.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4210 fix(condo): DOMA-8002 fixed import limit for properties (get from fea…
  apps/condo/domains/property/components/BuildingsTable.tsx
Labels: 👶 small, ✋🙂 Review please

#4211 chore(condo): DOMA-8001 fixed typing for importer tests
  apps/condo/domains/common/utils/importer.spec.ts
Labels: 👶 small, ✋🙂 Review please

#4215 fix(condo): unified mutation review fixes
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.new.test.js
  apps/condo/domains/billing/schema/resolvers/accountResolver.js
  apps/condo/domains/billing/schema/resolvers/propertyResolver.js
  apps/condo/domains/billing/schema/resolvers/receiptResolver.js
  apps/condo/domains/billing/schema/resolvers/recipientResolver.js
  apps/condo/domains/billing/schema/resolvers/resolver.js
  apps/condo/domains/billing/schema/resolvers/utils.js
  apps/condo/domains/billing/utils/testSchema/index.js
  packages/clients/finance-info-client/index.js
Labels: 👶 small, ✋🙂 Review please

#4220 fix(condo): DOMA-8022 fix delete proeprty hint property duplicates migration
  apps/condo/migrations/20231214092431-0352_auto_20231214_0424.js
Labels: 👶 small, ✋🙂 Review please

#4184 DOMA-7937 marketplace roles
  apps/condo/domains/acquiring/access/AcquiringIntegrationContext.js
  apps/condo/domains/acquiring/access/Payment.js
  apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.test.js
  apps/condo/domains/acquiring/schema/Payment.test.js
  apps/condo/domains/common/components/Prompt.tsx
  apps/condo/domains/common/utils/date.utils.ts
  apps/condo/domains/contact/components/ContactsEditor/NewContactFields.tsx
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
  apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
  apps/condo/domains/marketplace/components/Invoice/CreateInvoiceForm.tsx
  apps/condo/domains/marketplace/components/Invoice/ResidentPaymentAlert.tsx
  apps/condo/domains/marketplace/components/MarketItem/BaseMarketItemForm.tsx
  apps/condo/domains/marketplace/components/MarketplacePageContent/index.tsx
  apps/condo/domains/marketplace/components/MarketplacePaymentsContent.tsx
  apps/condo/domains/marketplace/components/PageAccess.tsx
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/hooks/useMarketplaceServicesTableColumns.tsx
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/MarketItem.js
  apps/condo/domains/marketplace/schema/MarketItem.test.js
  apps/condo/domains/marketplace/schema/RegisterInvoiceService.js
  apps/condo/domains/marketplace/schema/RegisterInvoiceService.test.js
  apps/condo/domains/marketplace/utils/clientSchema/Invoice.ts
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/hooks/useEmployeeRolesTableData.tsx
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/domains/property/components/UnitInfo.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
  apps/condo/domains/ticket/utils/clientSchema/Ticket.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20231219103119-0354_auto_20231219_0532.js
  apps/condo/pages/marketplace/index.tsx
  apps/condo/pages/marketplace/invoice/[id]/index.tsx
  apps/condo/pages/marketplace/setup.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🔬 WIP, 🚨 Migrations

#4226 refactor(condo): DOMA-7981 move category image and bgColor to invoice rows
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/GetInvoicesWithSkuInfoService.js
  apps/condo/domains/marketplace/schema/GetInvoicesWithSkuInfoService.test.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/marketplace/schema/MarketCategory.js
  apps/condo/domains/marketplace/schema/fields/invoiceRows.js
  apps/condo/domains/marketplace/schema/index.js
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4228 fix(condo): DOMA-7643 add dv and sender to updating invoice
  apps/condo/domains/acquiring/schema/Payment.js
Labels: 👶 small, ✋🙂 Review please

#4204 feat(condo): DOMA-8003 add acquiring fields to Invoice
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/BillingReceipt.js
  apps/condo/domains/billing/schema/BillingReceipt.test.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/migrations/20231220120754-0355_billingreceipthistoryrecord_acquiringhosturl_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4230 Fix/condo/doma 8032/various bugs
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/RequisitesSetup.tsx
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/fields/invoiceRows.js
Labels: 👶 small, ✋🙂 Review please

#4234 Fix/condo/doma 8032/fix marketplace setup steps
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/OfferSetupPage.tsx
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/RequisitesSetup.tsx
  apps/condo/pages/marketplace/setup.tsx
Labels: 👶 small, ✋🙂 Review please

#4231 fix(condo): DOMA-8029 added supporting of landline phone for MeterReading
  apps/condo/domains/common/schema/fields.js
  apps/condo/domains/meter/schema/MeterReading.js
  apps/condo/domains/meter/schema/MeterReading.test.js
Labels: 👶 small, ✋🙂 Review please

#4235 refactor(condo): DOMA-8041 change `marketplace.registerInvoice` to `r…
  apps/condo/domains/marketplace/access/GetInvoiceByUserService.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/marketplace/schema/index.js
  apps/condo/domains/marketplace/utils/serverSchema/index.js
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/domains/resident/access/RegisterResidentInvoiceService.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/schema/RegisterResidentInvoiceService.js
  apps/condo/domains/resident/schema/RegisterResidentInvoiceService.test.js
  apps/condo/domains/resident/schema/index.js
  apps/condo/domains/resident/utils/serverSchema/index.js
  apps/condo/domains/resident/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4232 DOMA-8034 added featureflag to marketplace & fix some bugs & fix translations
  apps/condo/domains/acquiring/routes/paymentLinkRouter.js
  apps/condo/domains/common/components/GraphQlSearchInputWithCheckAll.tsx
  apps/condo/domains/common/constants/menuCategories.js
  apps/condo/domains/marketplace/access/Invoice.js
  apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
  apps/condo/domains/marketplace/components/Invoice/ResidentPaymentAlert.tsx
  apps/condo/domains/marketplace/components/MarketItem/BaseMarketItemForm.tsx
  apps/condo/domains/marketplace/components/MarketItem/CreateMarketItemForm.tsx
  apps/condo/domains/marketplace/components/MarketItem/UpdateMarketItemForm.tsx
  apps/condo/domains/marketplace/components/MarketItemContent.tsx
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/OfferSetup.tsx
  apps/condo/domains/marketplace/components/MarketplacePaymentsContent.tsx
  apps/condo/domains/marketplace/hooks/useMarketplaceServicesTableColumns.tsx
  apps/condo/domains/marketplace/utils/clientSchema/MarketItem.ts
  apps/condo/domains/organization/hooks/useEmployeeRolesTableData.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/_app.tsx
  apps/condo/pages/marketplace/index.tsx
  apps/condo/pages/marketplace/invoice/payment/failure.tsx
  apps/condo/pages/marketplace/invoice/payment/success.tsx
  apps/condo/pages/marketplace/marketItem/[id]/index.tsx
  packages/icons/src/components/Market.tsx
  packages/icons/src/index.ts
Labels: ✋🙂 Review please

#4238 fix(condo): DOMA-8046 fix isPayable checkbox in ticket form
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4245 hotfix: truncating was removed due to deleting all payments :(
  apps/condo/migrations/20231215145832-0353_remove_invoicecontext_createdby_and_more.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 🚨 Migrations

#4246 fix(condo): DOMA-8102 set image and bgColor from parentCategory in row meta
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/organization/hooks/useEmployeeRolesTableData.tsx
Labels: 👶 small, ✋🙂 Review please
