Repository open-condo-software/condo, pull requests merged in 2023-06, with the labels that each got.

#3416 fix(condo): DOMA-6211 fixed translations
  apps/condo/domains/property/components/panels/Builder/BuildingPanelCommon.tsx
  apps/condo/domains/property/components/panels/Builder/forms/ParkingUnitForm.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3398 chore(condo): DOMA-6223 move news items messages throttling to notifi…
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/constants/errors.js
  apps/condo/domains/notification/tasks/deliverMessage.js
  apps/condo/domains/notification/utils/serverSchema/helpers.js
  apps/condo/migrations/20230531134539-0275_alter_message_status.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3418 DOMA-6268 security issue with external report organization access
  apps/condo/domains/analytics/access/GetExternalReportIframeUrlService.js
  apps/condo/domains/analytics/schema/GetExternalReportIframeUrlService.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3419 DOMA-6285 access issue with user invalid organization
  apps/condo/domains/analytics/schema/TicketReportService.test.js
  apps/condo/domains/ticket/access/TicketReportService.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3421 DOMA-6300 replace setUserProperties with identify api at amplitude provider
  apps/condo/domains/common/components/trackers/AmplitudeInstance.ts
Labels: 👶 small, ✋🙂 Review please

#3425 fix(condo): DOMA-6311 Condo WebKitView minor issues
  apps/condo/domains/common/components/PostMessageProvider/Provider.tsx
  apps/condo/domains/common/hooks/useGlobalHints.tsx
  apps/condo/domains/property/components/BasePropertyForm/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3430 hotfix(condo): HOTFIX invert transaction direction in SBBOL transaction request
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3426 fix(condo): DOMA-2740 fixed property map label
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3428 fix(condo): DOMA-6297 fixed meter validations
  apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx
  apps/condo/domains/meter/hooks/useMeterValidations.ts
Labels: 👶 small, ✋🙂 Review please

#3427 fix(condo): DOMA-5063 fixed error text when resetting password when u…
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3434 fix(condo): DOMA-6299 added auto organization reset when changing user
  apps/condo/domains/organization/components/OrganizationSelect.tsx
  apps/condo/domains/user/components/UserOrganizationsList.tsx
Labels: 👶 small, ✋🙂 Review please

#3438 fix(condo): DOMA-6345 AutoIncrementInteger field was improved
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/migrations/20230607210813-0279_newsitem_number_newsitemhistoryrecord_number.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/keystone/fields/AutoIncrementInteger/Implementation.js
  packages/keystone/schema.js
Labels: ✋🙂 Review please, 🚨 Migrations

#3442 docs(dev-portal): added basic API docs
  apps/dev-portal/docs/_meta.en.json
  apps/dev-portal/docs/_meta.ru.json
  apps/dev-portal/docs/api/_meta.en.json
  apps/dev-portal/docs/api/_meta.ru.json
  apps/dev-portal/docs/api/about.en.mdx
  apps/dev-portal/docs/api/about.ru.mdx
  apps/dev-portal/docs/api/dv.en.mdx
  apps/dev-portal/docs/api/dv.ru.mdx
  apps/dev-portal/docs/api/examples/_meta.en.json
  apps/dev-portal/docs/api/examples/_meta.ru.json
  apps/dev-portal/docs/api/examples/auth.en.mdx
  apps/dev-portal/docs/api/examples/auth.ru.mdx
  apps/dev-portal/docs/api/merge.en.mdx
  apps/dev-portal/docs/api/merge.ru.mdx
  apps/dev-portal/docs/api/playground.en.mdx
  apps/dev-portal/docs/api/playground.ru.mdx
  apps/dev-portal/docs/api/soft-delete.en.mdx
  apps/dev-portal/docs/api/soft-delete.ru.mdx
  apps/dev-portal/public/api/auth-success.png
  apps/dev-portal/public/api/auth-user-info-extended.png
  apps/dev-portal/public/api/auth-user-info.png
  apps/dev-portal/public/api/create-organization.png
  apps/dev-portal/public/api/playground-docs-extended.png
  apps/dev-portal/public/api/playground-docs.png
  apps/dev-portal/public/api/playground-method-example.png
  apps/dev-portal/public/api/register.png
Labels: 📝 Docs

#3446 hotfix(condo): HOTFIX REVERT sbbol transactions change payee to payer requisites (#3440)
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
Labels: 🔥 HOTFIX

#3450 Fix/condo/doma 6387/fix constraint
  apps/condo/domains/notification/schema/NotificationUserSetting.js
  apps/condo/domains/notification/schema/NotificationUserSetting.test.js
  apps/condo/migrations/20230614095405-0281_remove_notificationusersetting_notificationusersetting_unique_user_messagetype_messagetransport_and_.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#3417 feat(condo): DOMA-6219 The `news` menu item was added
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/CreateNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/ResendNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/UpdateNewsForm.tsx
  apps/condo/domains/news/components/NewsPreview.tsx
  apps/condo/domains/news/components/RecipientCounter.tsx
  apps/condo/domains/news/schema/ExportNewsRecipientsService.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230614104520-0282_manual_fix_news_items_permissions.js
  apps/condo/next.config.js
  apps/condo/pages/_app.tsx
  apps/condo/pages/news/[id]/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3455 feat(condo): DOMA-6403 The array with user-related residents was adde…
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
Labels: 👶 small, ✋🙂 Review please

#3457 feat(condo): DOMA-6411 Checking of `validBefore` value was fixed
  apps/condo/domains/news/schema/NewsItem.js
Labels: 👶 small, ✋🙂 Review please

#3452 feat(condo): DOMA-6329 schema meter reporting period
  apps/condo/domains/meter/access/MeterReportingPeriod.js
  apps/condo/domains/meter/gql.js
  apps/condo/domains/meter/schema/MeterReportingPeriod.js
  apps/condo/domains/meter/schema/MeterReportingPeriod.test.js
  apps/condo/domains/meter/schema/index.js
  apps/condo/domains/meter/utils/clientSchema/MeterReportingPeriod.ts
  apps/condo/domains/meter/utils/clientSchema/index.ts
  apps/condo/domains/meter/utils/serverSchema/index.js
  apps/condo/domains/meter/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230606110411-0278_auto_20230606_0604.js
  apps/condo/migrations/20230616085904-0284_meterreportingperiodhistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3460 fix(condo): DOMA-6421 added status filter to context queries
  apps/condo/domains/acquiring/components/payments/PaymentsPageContent.tsx
  apps/condo/domains/organization/components/Recipient/SettingsContent.tsx
Labels: 👶 small, ✋🙂 Review please

#3459 fix(condo): DOMA-6408 add `deletedAt` filter to queries in accesses
  apps/condo/domains/billing/access/BillingIntegrationOrganizationContext.js
  apps/condo/domains/billing/schema/BillingIntegrationOrganizationContext.test.js
  apps/condo/domains/billing/utils/testSchema/index.js
  apps/condo/domains/organization/access/OrganizationEmployeeRole.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.test.js
  apps/condo/domains/organization/utils/accessSchema.js
Labels: 👶 small, ✋🙂 Review please

#3407 feat: DOMA-6240 OIDC bridge auth
  apps/condo/domains/common/components/PostMessageProvider/Provider.tsx
  apps/condo/domains/common/components/PostMessageProvider/types.ts
  apps/condo/domains/common/components/PostMessageProvider/validators.ts
  apps/condo/domains/miniapp/components/IFrame.tsx
  apps/miniapp/domains/common/utils/oidcAuth.tsx
  apps/miniapp/index.js
  apps/miniapp/pages/index.tsx
  packages/bridge/src/bridge.ts
  packages/bridge/src/types/methods/RequestAuth.ts
  packages/bridge/src/types/methods/index.ts
Labels: 👶 small, ✋🙂 Review please

#3420 feat(condo): DOMA-5062 updated password validation
  apps/condo/domains/user/constants/common.js
  apps/condo/domains/user/constants/errors.js
  apps/condo/domains/user/schema/ForgotPasswordService.js
  apps/condo/domains/user/schema/ForgotPasswordService.test.js
  apps/condo/domains/user/schema/RegisterNewUserService.js
  apps/condo/domains/user/schema/RegisterNewUserService.test.js
  apps/condo/domains/user/schema/User.js
  apps/condo/domains/user/schema/User.test.js
  apps/condo/domains/user/utils/serverSchema/validateHelpers.js
  apps/condo/domains/user/utils/serverSchema/validateHelpers.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3465 feat(condo): DOMA-6404 scope type was added
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/access/NewsItemScope.js
  apps/condo/domains/news/constants/errors.js
  apps/condo/domains/news/constants/scopesTypes.js
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/schema/NewsItemScope.js
  apps/condo/domains/news/schema/NewsItemScope.test.js
  apps/condo/domains/news/utils/accessSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230620170831-0286_newsitemscope_type_newsitemscopehistoryrecord_type.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations, 🦑 API CHANGES

#3467 fix(condo): DOMA-6429 wider billing modal
  apps/condo/domains/billing/components/BillingPageContent/index.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3471 DOMA-6089 reset offset on tab change at bank account report page
  apps/condo/domains/banking/hooks/useBankTransactionsTable.tsx
  apps/condo/domains/banking/hooks/useTableColumns.tsx
  apps/condo/pages/property/[id]/report.tsx
Labels: 👶 small, ✋🙂 Review please

#3479 fix(condo): DOMA-6440 pass array as comma-separated string instead of…
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
Labels: 👶 small, 🔥 HOTFIX

#3472 fix(condo): DOMA-6431 fix data displaying after news item was canceled
  apps/condo/pages/news/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3473 fix(condo): DOMA-6371 hide units&section selector if 0 or 2+ properti…
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
Labels: 👶 small, ✋🙂 Review please

#3475 fix(condo): DOMA-6412 push preview was fixed
  apps/condo/domains/news/components/NewsPreview.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3468 chore(condo): DOMA-6406 The title and body were trimmed for push-mess…
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
Labels: 👶 small, ✋🙂 Review please

#3474 fix(condo): DOMA-6396 Show only one error for `validBefore` and `body`
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
Labels: 👶 small, ✋🙂 Review please

#3482 Fix/condo/doma 6443/fix notifications settings
  apps/condo/domains/notification/tasks/deliverMessage.js
  apps/condo/domains/notification/utils/serverSchema/helpers.js
Labels: 👶 small, 🔥 HOTFIX

#3480 fix(condo): DOMA-6441 fixed random tests for password validation
  apps/condo/domains/user/schema/ForgotPasswordService.test.js
  apps/condo/domains/user/schema/RegisterNewUserService.test.js
  apps/condo/domains/user/schema/User.test.js
  apps/condo/domains/user/utils/serverSchema/validateHelpers.test.js
Labels: 👶 small, ✋🙂 Review please

#3484 DOMA-6450 add analytics events to ticket comment form send & file upload
  apps/condo/domains/common/components/Comments/CommentForm.tsx
  apps/condo/domains/common/components/MultipleFileUpload.tsx
  apps/condo/domains/common/components/TrackingContext.tsx
Labels: 👶 small, ✋🙂 Review please

#3489 fix(condo): DOMA-6382 doesn't show modal if it's webview
  apps/condo/domains/common/components/Prompt.tsx
Labels: 👶 small, ✋🙂 Review please

#3488 fix(condo): DOMA-6456 removed checking for content of user name in password
  apps/condo/domains/user/constants/errors.js
  apps/condo/domains/user/schema/ForgotPasswordService.js
  apps/condo/domains/user/schema/ForgotPasswordService.test.js
  apps/condo/domains/user/schema/RegisterNewUserService.js
  apps/condo/domains/user/schema/RegisterNewUserService.test.js
  apps/condo/domains/user/schema/User.js
  apps/condo/domains/user/schema/User.test.js
  apps/condo/domains/user/utils/serverSchema/validateHelpers.js
  apps/condo/domains/user/utils/serverSchema/validateHelpers.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#3485 fix(condo): DOMA-6452 Increase success messages counter even if some …
  apps/condo/domains/notification/tasks/deliverMessage.js
Labels: 👶 small, ✋🙂 Review please

#3490 feat(global): DOMA-6455 modal close detection
  apps/condo/domains/billing/components/BillingPageContent/ContextProvider.ts
  apps/condo/domains/billing/components/BillingPageContent/index.tsx
  apps/condo/domains/common/components/PostMessageProvider/Provider.tsx
  apps/condo/domains/common/components/PostMessageProvider/globalHandlers.tsx
  apps/condo/domains/common/components/PostMessageProvider/types.ts
  apps/condo/pages/billing/index.tsx
  packages/bridge/src/types/methods/CloseModalWindow.ts
  packages/ui/src/components/Modal/useModal.tsx
Labels: 👶 small, ✋🙂 Review please

#3492 feat(condo): DOMA-6454 Users without an access token use tokens of employees of the same organization for requests to the sbbol
  apps/condo/domains/organization/integrations/sbbol/SbbolFintechApi.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.spec.js
  apps/condo/domains/organization/integrations/sbbol/utils/getAccessTokenForUser.js
Labels: ✋🙂 Review please

#3493 fix(condo): DOMA-6453 The `publishedAt` field was added
  apps/condo/domains/news/constants/errors.js
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/schema/NewsItemScope.test.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230622093945-0287_newsitem_publishedat_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3495 hotfix: migration 287
  apps/condo/migrations/20230622093945-0287_newsitem_publishedat_and_more.js
Labels: 🔥 HOTFIX, 🚨 Migrations

#3497 fix(condo): DOMA-6467 added initial page for webview
  apps/condo/pages/initial.tsx
  apps/condo/pages/meter/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3477 feat(condo): DOMA-6438 design fix and fix unitTypes selection
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/ResendNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/UpdateNewsForm.tsx
  apps/condo/domains/news/components/RecipientCounter.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/news/[id]/index.tsx
  apps/condo/pages/news/index.tsx
Labels: ✋🙂 Review please

#3451 feat: DOMA-6389 organization types added
  apps/condo/domains/banking/schema/BankAccountReportTask.test.js
  apps/condo/domains/banking/schema/BankContractorAccount.test.js
  apps/condo/domains/banking/schema/BankSyncTask.test.js
  apps/condo/domains/banking/schema/BankTransaction.test.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/constants/errors.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/Organization.js
  apps/condo/domains/organization/schema/Organization.test.js
  apps/condo/domains/organization/schema/OrganizationLink.js
  apps/condo/domains/organization/schema/OrganizationLink.test.js
  apps/condo/domains/organization/schema/RegisterNewOrganizationService.js
  apps/condo/domains/organization/schema/RegisterNewOrganizationService.test.js
  apps/condo/domains/organization/schema/ResetOrganizationService.test.js
  apps/condo/domains/organization/utils/testSchema/index.js
  apps/condo/domains/property/access/CheckPropertyWithAddressExistService.js
  apps/condo/domains/property/gql.js
  apps/condo/domains/property/schema/CheckPropertyWithAddressExistService.js
  apps/condo/domains/property/schema/CheckPropertyWithAddressExistService.test.js
  apps/condo/domains/property/schema/Property.js
  apps/condo/domains/property/schema/Property.test.js
  apps/condo/domains/property/schema/index.js
  apps/condo/domains/property/utils/serverSchema/index.js
  apps/condo/domains/property/utils/testSchema/index.js
  apps/condo/domains/resident/schema/RegisterResidentService.test.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
  apps/condo/domains/resident/tasks/residentTicket.task.js
  apps/condo/domains/ticket/schema/TicketChange.test.js
  apps/condo/domains/ticket/schema/TicketPropertyHint.test.js
  apps/condo/domains/ticket/schema/UserTicketCommentReadTime.test.js
  apps/condo/migrations/20230623142014-0288_organization_type_organizationhistoryrecord_type.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🦑 API CHANGES, 😎 Cool

#3500 hotfix(condo): reimplement OIDC existing grant search
  apps/condo/domains/user/oidc/configuration.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3458 refactor(condo): DOMA-6414 remove hard read access
  apps/condo/domains/banking/access/BankAccount.js
Labels: 👶 small, ✋🙂 Review please

#3513 fix(condo): DOMA-6446 close notification after timeout end
  apps/condo/domains/news/components/NewsForm/CreateNewsForm.tsx
Labels: 👶 small, ✋🙂 Review please

#3512 fix(condo): DOMA-6492 fix delaying of news items
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
Labels: 👶 small, ✋🙂 Review please

#3502 feat(condo): DOMA-6434 change some translations
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small

#3504 fix(condo): DOMA-6462 fix property checkbox in news form
  apps/condo/domains/common/components/GraphQlSearchInputWithCheckAll.tsx
Labels: 👶 small

#3505 fix(condo): DOMA-6457 set max dispatch time 1 year
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
Labels: 👶 small

#3506 fix(condo): DOMA-6451 fix news type translation in card
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/news/[id]/index.tsx
Labels: 👶 small

#3508 fix(condo): doma-6449 fix display sections in news card
  apps/condo/domains/news/components/RecipientCounter.tsx
  apps/condo/pages/news/[id]/index.tsx
Labels: 👶 small

#3518 fix(condo): DOMA-6510 news item id was added to the url within the pu…
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
Labels: 👶 small, ✋🙂 Review please

#3183 feat(condo): DOMA-5601 updated classifiers
  apps/condo/domains/ticket/schema/Ticket.js
  apps/condo/migrations/20230627122434-0290_auto_20230627_0724.js
Labels: 🚨 Migrations

#3491 feat(condo): DOMA-6236 added discoverServiceConsumersMutation
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/utils/serverSchema/index.js
  apps/condo/domains/resident/access/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
  apps/condo/domains/resident/schema/index.js
  apps/condo/domains/resident/utils/serverSchema/index.js
  apps/condo/domains/resident/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🔬 WIP

#3503 feat(condo): DOMA-6435 trim listing of units and sections
  apps/condo/domains/news/components/RecipientCounter.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small

#3509 feat(condo): DOMA-6442 added error display for profanity
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/constants/errors.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#3526 fix(condo): DOMA-6444 added alllowCLear to unitNames field
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
Labels: 👶 small

#3528 fix(condo): DOMA-6436 changed cursor in news question circle
  apps/condo/domains/news/components/RecipientCounter.tsx
Labels: 👶 small

#3525 fix(condo): DOMA-6437 fixed padding excel download recipient counter
  apps/condo/domains/news/components/RecipientCounter.tsx
Labels: 👶 small

#3524 fix(condo): DOMA-6413 changed alert text in news removal
  apps/condo/domains/common/components/DeleteButtonWithConfirmModal.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/news/[id]/index.tsx
Labels: 👶 small

#3523 fix(condo) DOMA-6410 fixed news type translations
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small

#3527 fix(condo): DOMA-6509 fixed news all properties selected
  apps/condo/domains/news/components/RecipientCounter.tsx
Labels: 👶 small, ✋🙂 Review please

#3532 feat(condo): DOMA-6491 expanded model field in webhookSubscription
  apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.js
Labels: 👶 small

#3538 fix(condo): DOMA-6477 Fix OnBoarding billing filters and links
  apps/condo/domains/onboarding/components/OnBoardingContext.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3539 fix(condo): DOMA-6536 fix name links on ticket page
  apps/condo/domains/ticket/components/TicketId/TicketUserInfoField.tsx
Labels: 👶 small, ✋🙂 Review please

#3543 DOMA-6519 ignore corrupted data at custom migration section
  apps/condo/migrations/20230628110200-0291_auto_20230628_0602.js
Labels: 👶 small, 🔥 HOTFIX, 🚨 Migrations

#3534 feat(condo): DOMA-6527 handle sbbol errors from transaction request and write them to BankAccount meta
  apps/condo/domains/banking/schema/BankAccountReportTask.test.js
  apps/condo/domains/banking/tasks/generateReports.js
  apps/condo/domains/banking/tasks/importBankTransactionsFrom1CClientBankExchange.js
  apps/condo/domains/organization/integrations/sbbol/constants.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.spec.js
  apps/condo/domains/property/components/PropertyReportCard.tsx
  apps/condo/pages/property/[id]/report.tsx
Labels: 👶 small, ✋🙂 Review please

#3507 refactor(condo): DOMA-6156 Recipients counter
  apps/condo/domains/common/hooks/useExportTaskUIInterface.ts
  apps/condo/domains/common/utils/serverSchema/index.js
  apps/condo/domains/news/access/GetNewsItemsRecipientsCountersService.js
  apps/condo/domains/news/access/NewsItemRecipientsExportTask.js
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/RecipientCounter.tsx
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/hooks/useNewsItemRecipientsExportTaskUIInterface.ts
  apps/condo/domains/news/hooks/useNewsItemRecipientsExportToExcelTask.tsx
  apps/condo/domains/news/schema/ExportNewsRecipientsService.js
  apps/condo/domains/news/schema/ExportNewsRecipientsService.test.js
  apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.js
  apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.test.js
  apps/condo/domains/news/schema/NewsItemRecipientsExportTask.js
  apps/condo/domains/news/schema/NewsItemRecipientsExportTask.test.js
  apps/condo/domains/news/schema/index.js
  apps/condo/domains/news/tasks/exportRecipients.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
  apps/condo/domains/news/utils/clientSchema/NewsItemRecipientsExportTask.ts
  apps/condo/domains/news/utils/clientSchema/index.ts
  apps/condo/domains/news/utils/serverSchema/index.js
  apps/condo/domains/news/utils/serverSchema/recipientsCounterUtils.js
  apps/condo/domains/news/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230630170620-0293_newsitemrecipientsexporttaskhistoryrecord_and_more.js
  apps/condo/pages/_app.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3544 DOMA-6504 add function for convert toPayDetails values to numeric
  apps/condo/migrations/20230628110200-0291_auto_20230628_0602.js
Labels: 🔥 HOTFIX, 🚨 Migrations
