Repository open-condo-software/condo, pull requests merged in 2023-07, with the labels that each got.

#3545 hotfix(global): include turbo, yarn berry and styleliont configs in open-condo
  .github/workflows/gitexporter.sh
Labels: 👶 small

#3542 feat(condo): DOMA-6516 miniapps in side menu
  .github/workflows/nodejs.condo.test.yml
  apps/condo/domains/common/components/MenuItem.tsx
  apps/condo/domains/common/constants/menuCategories.js
  apps/condo/domains/miniapp/components/AppDescription/B2BAppPage.tsx
  apps/condo/domains/miniapp/components/AppDescription/ConnectModal.tsx
  apps/condo/domains/miniapp/components/ConnectedAppsWithIconsProvider.tsx
  apps/condo/domains/miniapp/gql.js
  apps/condo/domains/miniapp/schema/B2BApp.js
  apps/condo/domains/miniapp/schema/fields/integration.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230702142131-0294_b2bapp_icon_b2bapp_menucategory_and_more.js
  apps/condo/pages/_app.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#3547 Fix/condo/doma 6554/fix recipients counter
  apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.js
  apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.test.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/utils/serverSchema/recipientsCounterUtils.js
Labels: 👶 small, ✋🙂 Review please

#3548 fix(condo): DOMA-6493 Check role permissions and show stub
  apps/condo/domains/news/hooks/useNewsItemsAccess.ts
  apps/condo/pages/news/[id]/index.tsx
  apps/condo/pages/news/[id]/resend.tsx
  apps/condo/pages/news/[id]/update.tsx
  apps/condo/pages/news/create.tsx
  apps/condo/pages/news/index.tsx
Labels: ✋🙂 Review please

#3552 fix(condo): DOMA-6533 translation fixed
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#3549 fix(condo): DOMA-6520 show sendAt as date of delayed news items
  apps/condo/pages/news/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3556 fix(condo): fix broken index page for ticket without contact
  apps/condo/domains/ticket/components/TicketId/TicketUserInfoField.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3557 fix(condo): DOMA-6511 fix showing of recipients counter on resend
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/ResendNewsForm.tsx
Labels: 👶 small, ✋🙂 Review please

#3558 fix(condo): DOMA-6532 promises awaiting is fixed
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
Labels: 👶 small, ✋🙂 Review please

#3546 Doma-6526 pdf receipt for residents
  apps/condo/domains/billing/access/BillingReceiptFile.js
  apps/condo/domains/billing/schema/BillingReceiptFile.js
  apps/condo/domains/billing/schema/BillingReceiptFile.test.js
  apps/condo/domains/billing/utils/testSchema/index.js
  apps/condo/domains/property/utils/testSchema/factories.js
  apps/condo/migrations/20230703153423-0295_rename_file_billingreceiptfile_sensitivedatafile_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#3563 fix(condo): DOMA-6528 Allow editing only delayed news items
  apps/condo/pages/news/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3562 fix(condo): DOMA-6531 allow to select sections of a parking
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/utils/serverSchema/recipientsCounterUtils.js
Labels: 👶 small, ✋🙂 Review please

#3565 fix(condo): DOMA-6530 allow to soft-delete news item scope
  apps/condo/domains/news/access/NewsItemScope.js
  apps/condo/domains/news/schema/NewsItemScope.test.js
Labels: 👶 small, ✋🙂 Review please

#3568 feat(condo): DOMA-6449 fixed display RecipientCounter for many newsIt…
  apps/condo/pages/news/[id]/index.tsx
Labels: 👶 small

#3571 feat(condo): DOMA-6564 added high priority settings toggle for android push transport
  apps/condo/domains/notification/adapters/firebaseAdapter.js
  apps/condo/domains/notification/schema/SendMessageService.test.js
Labels: 👶 small, ✋🙂 Review please

#3567 fix/condo/doma 5916/fixed news table styles
  apps/condo/domains/news/utils/clientSchema/NewsRenders.tsx
Labels: 👶 small

#3560 feat(condo): DOMA-6537 Service provider billing section
  apps/condo/domains/acquiring/access/AcquiringIntegrationContext.js
  apps/condo/domains/acquiring/constants/context.js
  apps/condo/domains/acquiring/schema/AcquiringIntegration.js
  apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.js
  apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.test.js
  apps/condo/domains/billing/components/OnBoarding/SetupAcquiring.tsx
  apps/condo/domains/billing/components/OnBoarding/Verification.tsx
  apps/condo/domains/billing/components/OnBoarding/index.tsx
  apps/condo/domains/billing/hooks/useOnboardingProgress.ts
  apps/condo/domains/common/components/containers/BaseLayout/Header.tsx
  apps/condo/domains/common/components/containers/BaseLayout/components/SideNav/DesktopSideNav.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/_app.tsx
  apps/condo/pages/billing/index.tsx
Labels: ✋🙂 Review please, 🚨 Migrations, 😎 Cool

#3578 DOMA-6576 get metadata for property report from BankAccount integration context field
  apps/condo/domains/banking/gql.js
  apps/condo/domains/property/components/PropertyReportCard.tsx
  apps/condo/pages/property/[id]/report.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3577 fix(condo): DOMA-6574 random failing tests were fixed
  apps/condo/domains/news/schema/NewsItemRecipientsExportTask.test.js
Labels: 👶 small, ✋🙂 Review please

#3582 chore(address-service): DOMA-6583 pass request id to getSearchProvider()
  apps/address-service/bin/update-address.js
Labels: 👶 small, ✋🙂 Review please

#3581 feat(ui): DOMA-6580 added radio button only with icon
  packages/ui/src/components/Radio/radio.tsx
  packages/ui/src/components/Radio/style.less
  packages/ui/src/stories/Radio/RadioGroup.stories.tsx
Labels: 👶 small, ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#3585 fix(condo): DOMA-6585 No notification with deleting button for delaye…
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/CreateNewsForm.tsx
Labels: 👶 small, ✋🙂 Review please

#3586 fix(condo): DOMA-6529 Close notification after the news item was deleted
  apps/condo/pages/news/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3587 feat(condo): DOMA-6555 added fixed debug app id support to SendB2CAppPushMessageService
  apps/condo/domains/miniapp/constants.js
  apps/condo/domains/miniapp/schema/SendB2CAppPushMessageService.js
  apps/condo/domains/miniapp/schema/SendB2CAppPushMessageService.test.js
Labels: 👶 small, ✋🙂 Review please

#3588 fix(condo): DOMA-6531 Fix sections detection (+parkings)
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/RecipientCounter.tsx
  apps/condo/domains/news/components/types.ts
  apps/condo/domains/news/utils/clientSchema/NewsRenders.tsx
  apps/condo/domains/user/components/UnitNameInput.tsx
Labels: 👶 small, ✋🙂 Review please

#3589 feat(condo): DOMA-6589 disabled sending notifications of BILLING_RECEIPT_ADDED_WITH_NO_DEBT for receipts with no debt
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.js
  apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.spec.js
Labels: 👶 small, ✋🙂 Review please

#3584 feat(condo): DOMA-5825 fix billingProperty to property mapping, types updated, tests fixed
  apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.js
  apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.test.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/schema/Resident.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3598 feat(condo): DOMA-6593 added employee section for service providers
  apps/condo/pages/_app.tsx
  apps/condo/pages/index.tsx
Labels: 👶 small, ✋🙂 Review please

#3599 refactor(condo): DOMA-1513 remove redundant component
  apps/condo/domains/common/components/Highlighter.tsx
Labels: 👶 small, ✋🙂 Review please

#3600 refactor(condo): DOMA-6594 changed minified icon size
  apps/condo/domains/common/components/ResidentActions/ResidentActions.tsx
Labels: 👶 small, ✋🙂 Review please

#3592 feat(condo): DOMA-6267 open the `news` menu item
  apps/condo/pages/_app.tsx
Labels: 👶 small, ✋🙂 Review please

#3609 fix(condo): DOMA-6564 fix audio playing on change speed
  apps/condo/domains/common/components/AudioPlayer.tsx
Labels: 👶 small, ✋🙂 Review please

#3611 hotfix(condo): HOTFIX fix sbbol on dev with fake data
  apps/condo/domains/organization/integrations/sbbol/sync/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3606 feat(condo): DOMA-6599 added type to news templates
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/CreateNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/ResendNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/UpdateNewsForm.tsx
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItemTemplate.js
  apps/condo/domains/news/schema/NewsItemTemplate.test.js
  apps/condo/domains/news/utils/testSchema/index.js
  apps/condo/migrations/20230711141219-0300_newsitemtemplate_type_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#3618 fix(condo): DOMA-6645 del ability to resize title body textareas
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
Labels: 👶 small

#3628 feat(condo): DOMA-6669 organization select minor improvements
  apps/condo/domains/common/components/containers/global-styles.css
  apps/condo/domains/property/components/PropertyReportCard.tsx
  packages/ui/src/components/Modal/style.less
Labels: 👶 small, ✋🙂 Review please

#3627 fix/eps/DOMA-5825 fixed empty scopes issue on missing property matches to billingProperties
  apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.js
  apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.test.js
  apps/condo/domains/common/constants/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#3629 DOMA-6672 mobile layouts for bank account report page
  apps/condo/domains/banking/components/BankAccountReport.tsx
  apps/condo/pages/property/[id]/report.tsx
Labels: 👶 small, ✋🙂 Review please

#3633 fix(condo): DOMA-6607 add arrow for templates switch
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/TemplatesTabs.tsx
Labels: ✋🙂 Review please

#3619 DOMA-6234 team principal analytics
  apps/condo/domains/acquiring/utils/testSchema/index.js
  apps/condo/domains/analytics/access/GetOverviewDashboardService.js
  apps/condo/domains/analytics/components/CustomChart.ts
  apps/condo/domains/analytics/components/CustomChartView.tsx
  apps/condo/domains/analytics/components/Dashboard.tsx
  apps/condo/domains/analytics/components/TicketChart.ts
  apps/condo/domains/analytics/components/TicketChartView.tsx
  apps/condo/domains/analytics/components/charts/index.ts
  apps/condo/domains/analytics/components/charts/payment/PaymentByPropertyChart.tsx
  apps/condo/domains/analytics/components/charts/payment/PaymentChart.ts
  apps/condo/domains/analytics/components/charts/payment/PaymentReceiptChart.tsx
  apps/condo/domains/analytics/components/charts/payment/PaymentTotalChart.tsx
  apps/condo/domains/analytics/components/charts/payment/dataMappers.ts
  apps/condo/domains/analytics/components/charts/resident/ResidentByPropertyChart.tsx
  apps/condo/domains/analytics/components/charts/resident/ResidentChart.ts
  apps/condo/domains/analytics/components/charts/resident/dataMappers.ts
  apps/condo/domains/analytics/components/charts/ticket/AllTicketsChart.tsx
  apps/condo/domains/analytics/components/charts/ticket/TicketByCategoryChart.tsx
  apps/condo/domains/analytics/components/charts/ticket/TicketByExecutorChart.tsx
  apps/condo/domains/analytics/components/charts/ticket/TicketByPropertyChart.tsx
  apps/condo/domains/analytics/components/charts/ticket/dataMappers.ts
  apps/condo/domains/analytics/gql.js
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.js
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.test.js
  apps/condo/domains/analytics/schema/TicketAnalyticsReportService.js
  apps/condo/domains/analytics/schema/index.js
  apps/condo/domains/analytics/utils/helpers.ts
  apps/condo/domains/analytics/utils/serverSchema/analytics.helper.js
  apps/condo/domains/analytics/utils/serverSchema/index.js
  apps/condo/domains/analytics/utils/services/AnalyticsDataProvider.js
  apps/condo/domains/analytics/utils/services/dataLoaders/AbstractDataLoader.js
  apps/condo/domains/analytics/utils/services/dataLoaders/payment.js
  apps/condo/domains/analytics/utils/services/dataLoaders/receipt.js
  apps/condo/domains/analytics/utils/services/dataLoaders/resident.js
  apps/condo/domains/analytics/utils/services/dataLoaders/ticket.js
  apps/condo/domains/analytics/utils/testSchema/index.js
  apps/condo/domains/common/components/BaseChart.ts
  apps/condo/domains/common/components/StatsCard.tsx
  apps/condo/domains/common/components/StatsContainer.tsx
  apps/condo/domains/common/utils/serverSchema/GqlToKnexBaseAdapter.js
  apps/condo/domains/organization/constants/features.js
  apps/condo/domains/resident/utils/clientSchema/Resident.ts
  apps/condo/domains/ticket/hooks/useTableColumns.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/reports/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, ☠ Dead / 🐞 Debug, 😎 Cool, 🐘 BIG

#3630 feat(ui): DOMA-6671 added icon for "Tag" component
  packages/ui/src/components/Tag/style.less
  packages/ui/src/components/Tag/tag.tsx
  packages/ui/src/stories/Tag.stories.tsx
Labels: 👶 small, ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 📦 Packages

#3639 fix(condo): DOMA-6694 fix audio file request
  apps/condo/domains/common/components/AudioPlayer.tsx
Labels: 👶 small, ✋🙂 Review please

#3640 DOMA-6701 analytics payments period filter
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.js
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.test.js
  apps/condo/domains/analytics/utils/services/dataLoaders/payment.js
  apps/condo/domains/analytics/utils/services/dataLoaders/receipt.js
Labels: 👶 small, ✋🙂 Review please

#3650 DOMA-6722 allow upload component to fit parent width
  apps/condo/domains/banking/components/FileImportButton.tsx
  apps/condo/domains/common/components/containers/GlobalStyle.tsx
Labels: 👶 small, ✋🙂 Review please

#3661 fix(condo): DOMA-6754 fixed header alignment
  apps/condo/domains/common/components/containers/global-styles.css
Labels: 👶 small, ✋🙂 Review please

#3664 feat(condo): DOMA-6752 changed secondary button bg
  packages/ui/src/components/Button/style.less
Labels: 👶 small, ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#3665 feat(condo): DOMA-6765 added column with resident comment in ticket export
  apps/condo/domains/ticket/templates/TicketsExportTemplate.xlsx
Labels: 👶 small, ✋🙂 Review please

#3666 DOMA-6733 one file in many call records
  apps/condo/domains/common/utils/fileAdapter.js
  apps/condo/domains/common/utils/sberCloudFileAdapter.js
  apps/condo/domains/ticket/schema/CallRecord.js
Labels: ✋🙂 Review please
