Repository open-condo-software/condo, pull requests merged in 2023-11, with the labels that each got.

#4040 fix(condo): DOMA-7608 fixed regexp to check if after keyword is a space/dot/coma
  packages/clients/address-service-client/utils/parseAddressesFromString.js
  packages/clients/address-service-client/utils/parseAddressesFromString.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4039 fix(condo): DOMA-7607 disable fields in manage meter modal if no canManageMeters permission
  apps/condo/domains/common/components/DeleteButtonWithConfirmModal.tsx
  apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx
  apps/condo/domains/meter/components/CreateMeterReadingsActionBar.tsx
  apps/condo/domains/meter/components/PageAccess.tsx
  apps/condo/domains/meter/hooks/useUpdateMeterModal.tsx
  apps/condo/domains/organization/hooks/useEmployeeRolesTableData.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4037 feat(condo): DOMA-7578 added exclusions for bad words filter
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/utils/serverSchema/badWords.js
  apps/condo/domains/news/utils/serverSchema/badWords.spec.js
Labels: 👶 small, ✋🙂 Review please

#4042 refactor(condo): DOMA-7410 increased the delay between insert requests when importing files to 1000 ms
  apps/condo/domains/common/hooks/useImporter.ts
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/domains/meter/hooks/useImporterFunctions.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#4062 fix(condo): DOMA-5889 show property not found error at report page
  apps/condo/pages/property/[id]/report.tsx
Labels: 👶 small, ✋🙂 Review please

#4061 fix(condo): DOMA-7657 remove deprecated fields in access check
  apps/condo/domains/billing/access/BillingReceipt.js
  apps/condo/domains/billing/schema/BillingReceipt.test.js
  apps/condo/domains/billing/schema/BillingReceiptFile.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4068 feature(condo): DOMA-7658 added resolver for receipt in hook to work …
  apps/condo/domains/billing/schema/BillingReceiptFile.js
  apps/condo/domains/billing/schema/BillingReceiptFile.test.js
  apps/condo/domains/billing/utils/testSchema/index.js
Labels: 👶 small, ✋🙂 Review please

#4054 Feat/condo/doma-7494/multipayment for invoice
  apps/condo/domains/acquiring/constants/errors.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
  apps/condo/domains/acquiring/schema/MultiPayment.js
  apps/condo/domains/acquiring/schema/MultiPayment.test.js
  apps/condo/domains/acquiring/schema/Payment.js
  apps/condo/domains/acquiring/schema/Payment.test.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForOneReceiptService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
  apps/condo/domains/acquiring/utils/billingFridge.js
  apps/condo/domains/acquiring/utils/billingFridge.spec.js
  apps/condo/domains/acquiring/utils/freezeBillingReceipt.spec.js
  apps/condo/domains/marketplace/constants.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/marketplace/schema/InvoiceContext.js
  apps/condo/domains/marketplace/schema/InvoiceContext.test.js
  apps/condo/domains/marketplace/schema/RegisterInvoiceService.js
  apps/condo/domains/marketplace/schema/RegisterInvoiceService.test.js
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20231110091359-0340_invoicecontext_integration_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4070 Chore/condo/doma-7664/address service exception and logs
  packages/keystone/plugins/addressService.js
Labels: 👶 small, ✋🙂 Review please

#4076 feature(condo): DOMA-7682 extend register billing receipt input type
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#4077 hotfix(global): cypress EOF
  .env.example
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4085 fix(condo): DOMA-7443 fix search filter for MarketCategory in admin panel
  apps/condo/domains/marketplace/schema/MarketCategory.js
Labels: 👶 small, ✋🙂 Review please

#4084 fix(condo): DOMA-7693 fixed redirect to onboarding page after auth by sbbol/sberId/appleId
  apps/condo/domains/organization/integrations/sbbol/routes.js
  apps/condo/domains/organization/integrations/sbbol/sync/getOnBoadringStatus.js
  apps/condo/domains/user/integration/appleid/utils/helper.js
  apps/condo/domains/user/integration/sberid/routes.js
  apps/condo/pages/onboarding.tsx
Labels: 👶 small, ✋🙂 Review please

#4082 feat(condo): DOMA-7577 invoice form
  apps/condo/domains/acquiring/access/RegisterMultiPaymentService.js
  apps/condo/domains/acquiring/constants/errors.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
  apps/condo/domains/common/components/containers/GlobalStyle.tsx
  apps/condo/domains/contact/components/ContactsEditor/ContactOption.tsx
  apps/condo/domains/contact/components/ContactsEditor/NewContactFields.tsx
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
  apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
  apps/condo/domains/marketplace/components/Invoice/CreateInvoiceForm.tsx
  apps/condo/domains/marketplace/components/Invoice/InvoiceForm.tsx
  apps/condo/domains/marketplace/components/Invoice/PaymentLinkNotification.tsx
  apps/condo/domains/marketplace/components/Invoice/UpdateInvoiceForm.tsx
  apps/condo/domains/marketplace/components/MarketplacePageContent/index.tsx
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/marketplace/schema/RegisterInvoiceService.js
  apps/condo/domains/marketplace/schema/fields/invoiceRows.js
  apps/condo/domains/marketplace/utils/clientSchema/Invoice.ts
  apps/condo/domains/marketplace/utils/clientSchema/MarketPriceScope.ts
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/domains/organization/utils/accessSchema.js
  apps/condo/domains/property/components/PropertyAddressSearchInput.tsx
  apps/condo/domains/resident/access/GetResidentExistenceByPhoneAndAddressService.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/schema/GetResidentExistenceByPhoneAndAddressService.js
  apps/condo/domains/resident/schema/GetResidentExistenceByPhoneAndAddressService.test.js
  apps/condo/domains/resident/schema/index.js
  apps/condo/domains/resident/utils/serverSchema/index.js
  apps/condo/domains/resident/utils/testSchema/index.js
  apps/condo/domains/ticket/utils/clientSchema/search.ts
  apps/condo/domains/user/components/UnitNameInput.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20231114121958-0342_auto_20231114_0720.js
  apps/condo/pages/marketplace/invoice/[id]/update.tsx
  apps/condo/pages/marketplace/invoice/create.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🔬 WIP, ✋🙂 Review please, 🚨 Migrations, 🐘 BIG

#4091 fix(condo): DOMA-7712 Marketplace setup: Fixed error handling for req…
  apps/condo/domains/common/hooks/useMutationErrorHandler.ts
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/RequisitesSetup.tsx
  apps/condo/domains/marketplace/schema/InvoiceContext.js
  apps/condo/domains/marketplace/schema/InvoiceContext.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/package.json
  yarn.lock
Labels: ✋🙂 Review please

#4096 fix(condo): DOMA-7735, DOMA-7702, DOMA-7730, DOMA-7739, DOMA-6424: fixed meter reporting period, property meter readings and accesses for bulk operations
  apps/condo/domains/meter/access/MeterReportingPeriod.js
  apps/condo/domains/meter/components/MeterReportingPeriodForm.tsx
  apps/condo/domains/meter/schema/MeterReportingPeriod.js
  apps/condo/domains/meter/schema/MeterReportingPeriod.test.js
  apps/condo/domains/meter/schema/PropertyMeter.js
  apps/condo/domains/meter/tasks/deleteReadingsOfDeletedMeter.js
  apps/condo/domains/meter/tasks/deleteReadingsOfDeletedMeter.spec.js
  apps/condo/domains/meter/utils/clientSchema/MeterReportingPeriod.ts
  apps/condo/domains/organization/utils/accessSchema.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/meter/index.tsx
Labels: ✋🙂 Review please

#4090 Feat/condo/doma-7643/payment link for invoices
  apps/condo/domains/acquiring/access/RegisterMultiPaymentForInvoicesService.js
  apps/condo/domains/acquiring/constants/errors.js
  apps/condo/domains/acquiring/constants/links.js
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/routes/paymentLinkRouter.js
  apps/condo/domains/acquiring/schema/GeneratePaymentLinkService.js
  apps/condo/domains/acquiring/schema/GeneratePaymentLinkService.test.js
  apps/condo/domains/acquiring/schema/Payment.js
  apps/condo/domains/acquiring/schema/Payment.test.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForInvoicesService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForInvoicesService.test.js
  apps/condo/domains/acquiring/schema/index.js
  apps/condo/domains/acquiring/utils/serverSchema/index.js
  apps/condo/domains/acquiring/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/404-paymentLinkNoHandler.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4103 fix(condo): DOMA-7749 use COOKIE_SECRET as fallback of OIDC_COOKIE_KEYS
  apps/condo/domains/user/oidc/configuration.js
Labels: 👶 small, ✋🙂 Review please

#4095 feat(condo): DOMA-7709 invoice card
  apps/condo/domains/acquiring/access/RegisterMultiPaymentService.js
  apps/condo/domains/acquiring/constants/errors.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
  apps/condo/domains/common/utils/date.utils.ts
  apps/condo/domains/common/utils/helpers.ts
  apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
  apps/condo/domains/marketplace/components/Invoice/CopyButton.tsx
  apps/condo/domains/marketplace/components/Invoice/CreateInvoiceForm.tsx
  apps/condo/domains/marketplace/components/Invoice/InvoiceRowsTable.tsx
  apps/condo/domains/marketplace/components/Invoice/InvoiceStatusSelect.tsx
  apps/condo/domains/marketplace/components/Invoice/ResidentPaymentAlert.tsx
  apps/condo/domains/marketplace/components/Invoice/UpdateInvoiceForm.tsx
  apps/condo/domains/marketplace/components/PageAccess.tsx
  apps/condo/domains/marketplace/constants.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/hooks/useCancelStatusModal.tsx
  apps/condo/domains/marketplace/hooks/useInvoicePaymentLink.tsx
  apps/condo/domains/marketplace/schema/MarketItemPrice.test.js
  apps/condo/domains/marketplace/schema/fields/price.js
  apps/condo/domains/marketplace/utils/clientSchema/Invoice.ts
  apps/condo/domains/marketplace/utils/testSchema/index.js
  apps/condo/domains/ticket/components/TicketStatusSelect.tsx
  apps/condo/domains/ticket/utils/unit.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/marketplace/invoice/[id]/index.tsx
  apps/condo/pages/marketplace/invoice/[id]/update.tsx
  apps/condo/pages/marketplace/invoice/create.tsx
  apps/condo/pages/ticket/[id]/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4105 fix(condo): DOMA-7318 rid of date range filter values inconsistency
  apps/condo/domains/analytics/hooks/useDashboardFilters.tsx
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.js
Labels: 👶 small, ✋🙂 Review please

#4104 fix(condo): DOMA-7763 don't show organization create modal if active invites exists
  apps/condo/domains/organization/components/OrganizationSelect.tsx
  apps/condo/domains/organization/utils/clientSchema/OrganizationEmployee.ts
Labels: 👶 small, ✋🙂 Review please

#4108 fix(condo): DOMA-7718 fix crash after org was changed
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/OfferSetupPage.tsx
Labels: 👶 small, ✋🙂 Review please

#4107 Fix/condo/doma-7719/enter or choose bank account
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForInvoicesService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForInvoicesService.test.js
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/RequisitesSetup.tsx
Labels: 👶 small, ✋🙂 Review please

#4075 feat(global): DOMA-7674 Prepare.js integrated with turbo ⚡🚀💨🏎️
  .env.example
  .github/workflows/_nodejs.condo.core.tests.yml
  .github/workflows/apps.dev-api.test.yml
  .github/workflows/nodejs.condo.cypress.yml
  apps/dev-api/.env.example
  apps/dev-api/package.json
  bin/prepare.js
  packages/cli/index.js
  packages/cli/package.json
  turbo.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#4106 fix(condo): DOMA-7765 now TIN of organization can be changed only by admin
  apps/condo/domains/organization/access/Organization.js
  apps/condo/domains/organization/schema/Organization.js
  apps/condo/domains/organization/schema/Organization.test.js
  apps/condo/domains/organization/utils/testSchema/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4117 hotfix(condo): allow landline phones in ticket settings
  apps/condo/domains/settings/components/ticketSubmitting/TicketSubmittingSettingsForm.tsx
Labels: 🔥 HOTFIX

#4115 feat(condo): DOMA-7799 Prepare B2CApps for dev-api
  apps/condo/domains/miniapp/schema/B2CApp.js
  apps/condo/domains/miniapp/schema/B2CAppBuild.js
  apps/condo/domains/miniapp/utils/testSchema/index.js
  apps/condo/domains/user/schema/UserRightsSet.test.js
  apps/condo/migrations/20231124154841-0344_b2capp_importid_b2capp_importremotesystem_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/keystone/plugins/importable.js
  packages/keystone/plugins/index.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#4125 feat(condo): DOMA-7680 added filter by units (type + name)
  apps/condo/domains/contact/hooks/useTableFilters.tsx
  apps/condo/domains/property/utils/tables.utils.ts
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4124 fix(condo): DOMA-7762 check unit label uniqueness before map save
  apps/condo/domains/property/components/BasePropertyMapForm/index.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4119 feat(condo): DOMA-7772 added marketplace pushes
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/MARKETPLACE_INVOICE_PUBLISHED_MESSAGE/default.njk
  apps/condo/lang/en/messages/MARKETPLACE_INVOICE_WITH_TICKET_PUBLISHED_MESSAGE/default.njk
  apps/condo/lang/ru/messages/MARKETPLACE_INVOICE_PUBLISHED_MESSAGE/default.njk
  apps/condo/lang/ru/messages/MARKETPLACE_INVOICE_WITH_TICKET_PUBLISHED_MESSAGE/default.njk
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20231128121829-0345_alter_notificationusersetting_messagetype.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🚨 Migrations

#4118 feature(condo): Doma-7684 unified mutation new flow
  apps/condo/domains/billing/constants/registerBillingReceiptService.js
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/BillingAccount.js
  apps/condo/domains/billing/schema/BillingAccount.test.js
  apps/condo/domains/billing/schema/BillingProperty.js
  apps/condo/domains/billing/schema/BillingProperty.test.js
  apps/condo/domains/billing/schema/BillingReceipt.js
  apps/condo/domains/billing/schema/BillingReceipt.test.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.new.test.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
  apps/condo/domains/billing/schema/fields/common.js
  apps/condo/domains/billing/schema/resolvers/accountResolver.js
  apps/condo/domains/billing/schema/resolvers/categoryResolver.js
  apps/condo/domains/billing/schema/resolvers/categoryResolver.spec.js
  apps/condo/domains/billing/schema/resolvers/index.js
  apps/condo/domains/billing/schema/resolvers/lib.js
  apps/condo/domains/billing/schema/resolvers/periodResolver.js
  apps/condo/domains/billing/schema/resolvers/propertyResolver.js
  apps/condo/domains/billing/schema/resolvers/propertyResolver.spec.js
  apps/condo/domains/billing/schema/resolvers/receiptResolver.js
  apps/condo/domains/billing/schema/resolvers/recipientResolver.js
  apps/condo/domains/billing/schema/resolvers/resolver.js
  apps/condo/domains/billing/utils/testSchema/index.js
  apps/condo/migrations/20231129004832-0346_remove_billingaccount_billingaccount_unique_context_globalid_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/clients/address-service-client/AddressServiceClient.js
  packages/clients/address-service-client/MockedAddressServiceClient.js
  packages/clients/finance-info-client/index.js
Labels: ✋🙂 Review please, 🚨 Migrations, 🐘 BIG

#4130 fix(condo): merge 346 migrations
  apps/condo/migrations/20231129154046-0347_merge_20231129_1040.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 🚨 Migrations

#4132 fix(condo): DOMA-7715 add handler for button
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/OfferSetup.tsx
Labels: 👶 small, ✋🙂 Review please

#4131 feat(condo): DOMA-7718 fix redirects between onboarding steps
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/OfferSetupPage.tsx
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/RequisitesSetup.tsx
  apps/condo/domains/marketplace/gql.js
  apps/condo/pages/marketplace/setup.tsx
Labels: 👶 small, ✋🙂 Review please

#4129 Feat/condo/doma 7858/additions for mobile app 1
  apps/condo/domains/marketplace/constants.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/marketplace/schema/MarketItemPrice.js
  apps/condo/domains/marketplace/schema/MarketItemPrice.test.js
  apps/condo/domains/marketplace/tasks/cancelOldInvoices.js
  apps/condo/domains/marketplace/tasks/cancelOldInvoices.spec.js
  apps/condo/domains/marketplace/tasks/index.js
  apps/condo/index.js
  apps/condo/migrations/20231130114920-0348_invoice_canceledat_invoice_paidat_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4112 fix(condo): DOMA-7732 move isPayable field to BillingReceipt
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
  apps/condo/domains/billing/schema/BillingReceipt.js
  apps/condo/domains/billing/schema/BillingReceipt.test.js
  apps/condo/migrations/20231130115023-0349_billingreceipthistoryrecord_ispayable.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations
