Repository open-condo-software/condo, pull requests merged in 2023-01, with the labels that each got.

#2762 feat(icons): DOMA-5099 Added employee icon
  packages/icons/src/components/Employee.tsx
  packages/icons/src/index.ts
Labels: 👶 small, ✋🙂 Review please, 📦 Packages

#2759 fix(ui): DOMA-5085 fix checkboxes checkmark on import
  packages/ui/src/components/Checkbox/style.less
Labels: 👶 small, 🎨 UI-kit, 📦 Packages

#2767 fix(condo): DOMA-5100 fix initial section and floor update in ticket form
  apps/condo/domains/property/components/UnitInfo.tsx
Labels: 👶 small, ✋🙂 Review please

#2766 fix(condo): DOMA-5101 added showCountryPrefix prop to PhoneInput
  apps/condo/domains/common/components/PhoneInput.tsx
  apps/condo/domains/common/hooks/useSearchByPhoneModal.tsx
Labels: 👶 small, ✋🙂 Review please

#2739 fix(condo):DOMA-3405 fixed period select in billing
  apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
  apps/condo/domains/billing/hooks/usePeriodSelector.ts
Labels: 👶 small

#2735 ci(global): properly check for keystone build successful
  .github/workflows/nodejs.apps.build.yml
Labels: 👶 small, ✋🙂 Review please

#2775 DOMA-5097 remove force upload ssr props
  apps/condo/pages/property/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2736 chore(condo): DOMA-5036 added eslint rule about deprecated "jspdf"
  package.json
Labels: 👶 small, ✋🙂 Review please

#2785 fix(condo): DOMA-5077 fixed tag select filter dropdown icon
  apps/condo/domains/common/utils/filters.utils.ts
Labels: 👶 small, ✋🙂 Review please

#2789 fix(condo): DOMA-5102 select first contact only if there is no selected contact on minus click
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2788 feat(condo): DOMA-5169 added SMS_VERIFY_CODE_MESSAGE_TYPE
  apps/condo/domains/notification/constants/constants.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2784 fix(condo): DOMA-4947 fixed ticket layout
  apps/condo/domains/common/components/Comments/index.tsx
  apps/condo/pages/ticket/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2799 feat(condo): DOMA-5141 added resident access to manage ticket status
  apps/condo/domains/ticket/access/Ticket.js
  apps/condo/domains/ticket/schema/Ticket.test.js
Labels: 👶 small, ✋🙂 Review please

#2801 DOMA-5186 property detail page typo
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2797 feat(condo): DOMA-5177 fixed sms issue on employee invitation
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/schema/MessageOrganizationBlackList.test.js
  apps/condo/domains/notification/schema/MessageUserBlackList.test.js
  apps/condo/domains/notification/templates.spec.js
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.js
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/DIRTY_INVITE_NEW_EMPLOYEE_EMAIL/default.njk
  apps/condo/lang/en/messages/DIRTY_INVITE_NEW_EMPLOYEE_SMS/default.njk
  apps/condo/lang/ru/messages/DIRTY_INVITE_NEW_EMPLOYEE_EMAIL/default.njk
  apps/condo/lang/ru/messages/DIRTY_INVITE_NEW_EMPLOYEE_SMS/default.njk
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😎 Cool

#2803 feat(condo): DOMA-5180 open client card in new tab
  apps/condo/domains/contact/utils/clientCard.tsx
Labels: 👶 small, ✋🙂 Review please

#2810 fix(address-service): DOMA-5144 pass server utils to function
  apps/address-service/domains/common/utils/services/search/plugins/SearchByFiasId.js
Labels: 👶 small, ✋🙂 Review please

#2812 feat(condo): DOMA-5178 Notify global miniapp on organization change
  apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
  apps/condo/domains/miniapp/components/IFrame.tsx
Labels: 👶 small, ✋🙂 Review please

#2813 fix(address-service): DOMA-5199 add space before sending query to dadata
  apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
Labels: 👶 small, ✋🙂 Review please

#2808 fix(condo): DOMA-5181 set first contact value on minus click
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2804 feat(condo): DOMA-5187 open links in new tab in client card
  apps/condo/pages/phone/[number]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2816 fix(condo): DOMA-3364 fixed removed employee in ticket edit page
  apps/condo/domains/common/components/GraphQlSearchInput/Renders.tsx
  apps/condo/domains/ticket/components/BaseTicketForm/TicketAssignments.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2814 fix(condo): DOMA-5055 fixed unread resident comments indicator
  apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
Labels: 👶 small, ✋🙂 Review please

#2820 fix(condo): DOMA-5181 reset selected contact if resident/not resident tab changed
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2822 DOMA-5209 fix isExpired method in SbbolSecretStorage
  apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.js
  apps/condo/domains/organization/integrations/sbbol/utils/getAccessTokenForUser.js
Labels: 👶 small, ✋🙂 Review please

#2818 feat(condo): DOMA-4784 added ticket classification on backend
  apps/condo/domains/common/hooks/useSearchByPhoneModal.tsx
  apps/condo/domains/contact/utils/clientCard.tsx
  apps/condo/domains/ticket/schema/PredictTicketClassificationService.js
  apps/condo/domains/ticket/schema/Ticket.js
  apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
Labels: 👶 small, ✋🙂 Review please
