Repository open-condo-software/condo, pull requests merged in 2023-02, with the labels that each got.

#2834 fix(condo): DOMA-5218 registerResident mutation updated
  apps/condo/domains/resident/schema/RegisterResidentService.js
  packages/keystone/plugins/addressService.js
  packages/keystone/plugins/utils/address-service-client/index.js
Labels: 👶 small, ✋🙂 Review please

#2836 fix(condo): DOMA-5211 fixed TicketChange after declining an ticket by…
  apps/condo/domains/ticket/components/TicketChanges/TicketChange.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#2843 DOMA-5243 fix sbbol employee creation
  apps/condo/domains/organization/integrations/sbbol/sync/syncOrganization.spec.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncUser.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2823 feat(condo): DOMA-5131 VoIP push support, tests & script added
  apps/address-service/domains/address/schema/AddressInjection.test.js
  apps/condo/bin/notification/send-incoming-voip-call-notification.js
  apps/condo/domains/banking/schema/BankIntegration.test.js
  apps/condo/domains/common/utils/serverSchema/export.spec.js
  apps/condo/domains/notification/adapters/hcmAdapter.js
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/constants/errors.js
  apps/condo/domains/notification/gql.js
  apps/condo/domains/notification/helpers/index.js
  apps/condo/domains/notification/helpers/sendIncomingVoIPCallNotification.js
  apps/condo/domains/notification/schema/RemoteClient.js
  apps/condo/domains/notification/schema/SendMessageService.test.js
  apps/condo/domains/notification/schema/SyncRemoteClientService.js
  apps/condo/domains/notification/schema/SyncRemoteClientService.test.js
  apps/condo/domains/notification/tasks/deliverMessage.js
  apps/condo/domains/notification/transports/push.js
  apps/condo/domains/notification/transports/push.spec.js
  apps/condo/domains/notification/utils/testSchema/helpers.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/VOIP_INCOMING_CALL_MESSAGE/default.njk
  apps/condo/lang/en/messages/VOIP_INCOMING_CALL_MESSAGE/push.njk
  apps/condo/lang/ru/messages/VOIP_INCOMING_CALL_MESSAGE/default.njk
  apps/condo/lang/ru/messages/VOIP_INCOMING_CALL_MESSAGE/push.njk
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20230203103827-0216_auto_20230203_0538.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#2847 fix(condo): DOMA-5131 fix script payload
  apps/condo/bin/notification/send-incoming-voip-call-notification.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2854 DOMA-5256 added UserAdmin to server utils
  apps/condo/domains/user/gql.js
  apps/condo/domains/user/utils/serverSchema/index.js
Labels: 👶 small, ✋🙂 Review please

#2860 DOMA-5263 fixed unhandled exception in SBBOL completeAuth
  apps/condo/domains/organization/integrations/sbbol/routes.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncOrganization.spec.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js
Labels: 👶 small, ✋🙂 Review please

#2863 fix(condo): DOMA-5168 fixed incorrect datapicker on empty lastReport
  apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
Labels: 👶 small

#2865 fix(condo): DOMA-5273 hide property data if no selected address in contact card
  apps/condo/pages/phone/[number]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2867 fix(condo): DOMA-5268 register multipayment for payments with different fees
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#2873 refactor(condo): DOMA-5142 Remove legacy postMessages
  apps/condo/domains/common/utils/iframe.utils.ts
  apps/condo/domains/miniapp/components/IFrame.tsx
Labels: 👶 small, ✋🙂 Review please

#2869 fix(ui): DOMA-5278 fixed button with icon
  packages/ui/src/components/Button/style.less
  packages/ui/src/stories/Button.stories.tsx
Labels: 👶 small, ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit

#2879 fix(condo): DOMA-5107 fixed onMouseDown in case of using ReactPhoneInput in AutoComplete
  apps/condo/domains/common/components/PhoneInput.tsx
Labels: 👶 small, ✋🙂 Review please

#2880 fix(condo): DOMA-4846 added allowClear to contact phone input
  apps/condo/domains/contact/components/ContactsEditor/NewContactFields.tsx
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2884 fix(condo): DOMA-5131 added UPDATE migration to fix wrong default value for pushTypeVoIP field
  apps/condo/migrations/20230211121120-0219_manual_fix_default_value_pushTypeVoIP.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 🚨 Migrations, 😎 Cool

#2887 fix(condo): DOMA-5131 fixed migration issue
  apps/condo/migrations/20230211121120-0219_manual_fix_default_value_pushTypeVoIP.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 🚨 Migrations, 😎 Cool

#2883 fix(condo): DOMA-4870 cut address postfix if address street has 2 rows
  apps/condo/pages/phone/[number]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2895 DOMA-5323 extend analytics with organization id
  apps/condo/domains/common/components/TrackingContext.tsx
Labels: 👶 small, ✋🙂 Review please

#2891 feat(ui): DOMA-5318 added component id when sending analytics for Typ…
  packages/ui/src/components/Banner/banner.tsx
  packages/ui/src/components/Button/button.tsx
  packages/ui/src/components/Checkbox/checkbox.tsx
  packages/ui/src/components/Radio/radio.tsx
  packages/ui/src/components/Select/select.tsx
  packages/ui/src/components/Typography/link.tsx
  packages/ui/src/components/_utils/analytics.ts
Labels: 👶 small, ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#2904 fix(condo): DOMA-3720 fixed comment editing
  apps/condo/domains/common/components/Comments/CommentForm.tsx
  apps/condo/domains/common/components/Comments/index.tsx
Labels: 👶 small, ✋🙂 Review please

#2918 hotfix(icons): bump deps
  packages/icons/src/wrappers.tsx
Labels: 🔥 HOTFIX

#2908 fix(condo): DOMA-5068 increased arrow buttons miniapps carousel
  apps/condo/domains/common/components/containers/GlobalStyle.tsx
  apps/condo/domains/miniapp/components/AppDescription/TopCard.tsx
Labels: 👶 small

#2919 fix(condo): DOMA-5341 refactored useAllObjects hook
  apps/condo/domains/ticket/contexts/TicketVisibilityContext.tsx
  apps/condo/pages/ticket/[id]/index.tsx
  packages/codegen/generate.hooks.ts
Labels: 👶 small, ✋🙂 Review please

#2922 feat(ui): DOMA-5360 strict alert colors
  packages/ui/src/components/Alert/mixins.less
  packages/ui/src/components/Alert/style.less
Labels: 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#2923 ci(global): DOMA-5365 Fix npm deploy
  .github/workflows/packages.release.yml
  packages/bridge/package.json
  packages/icons/package.json
  packages/ui/package.json
Labels: 👶 small, 🔥 HOTFIX

#2924 feat(ui): DOMA-5365 Recolored Alert Titles and expanded doc
  packages/ui/README.md
Labels: 🔥 HOTFIX, 🎨 UI-kit, 📦 Packages

#2885 use debug package instead of hardcoded env checks
  packages/keystone/package.json
  packages/keystone/schema.js
  yarn.lock
Labels: 👶 small, ✋🙂 Review please

#2935 fix(webhooks): DOMA-5396 added missing dependency
  packages/webhooks/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😵‍💫 dependencies, 👨🏻‍🎨 Request UI-kit review, 📦 Packages

#2939 fix(dev-portal): DOMA-5409 fixed build-time .env location
  werf.yaml
Labels: 👶 small, 🔥 HOTFIX, infrastructure

#2940 fix(dev-portal): DOMA-5411 fixed edit route
  apps/dev-portal/pages/docs/[...path].tsx
Labels: 👶 small, 🔥 HOTFIX

#2933 refactor(keystone): remove useless console.log
  packages/keystone/test.utils.js
Labels: 👶 small, ✋🙂 Review please

#2925 fix(condo): DOMA-5362 fixed timezone for ticket print to pdf
  apps/condo/domains/ticket/utils/serverSchema/exportTicketBlanksToPdf.js
Labels: 👶 small, ✋🙂 Review please

#2946 fix(condo): DOMA-3292 services modal ux fixes
  apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
  apps/condo/domains/billing/components/ServicesModal.tsx
  apps/condo/domains/billing/hooks/useServicesTableColumns.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small

#2948 DOMA-5418 init analytics instances before first render
  apps/condo/domains/common/components/TrackingContext.tsx
Labels: 👶 small, ✋🙂 Review please

#2949 DOMA-5347 provide correct onChange type for Select component
  packages/ui/src/components/Select/select.tsx
  packages/ui/src/components/_utils/analytics.ts
Labels: 👶 small, ✋🙂 Review please, 🎨 UI-kit

#2957 DOMA-5432 return User instance instead user.id
  apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js
Labels: 👶 small, ✋🙂 Review please

#2951 fix(ui): DOMA-5408 fixed RadioGroup component
  packages/ui/src/components/Radio/radiogroup.tsx
  packages/ui/src/components/Radio/style.less
  packages/ui/src/stories/Radio/RadioGroup.stories.tsx
Labels: ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#2960 fix(condo): DOMA-5431 fixed comment datetime title
  apps/condo/domains/common/components/Comments/Comment.tsx
Labels: 👶 small, ✋🙂 Review please
