Repository open-condo-software/condo, pull requests merged in 2024-04, with the labels that each got.

#4548 fix(condo): DOMA-8650 fixed case when address was not resolved correctly
  apps/condo/domains/billing/schema/resolvers/accountResolver.js
  apps/condo/domains/billing/schema/resolvers/propertyResolver.js
  apps/condo/domains/billing/schema/resolvers/utils.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4557 fix(condo): DOMA-8748 removed global hints for non-ru locales
  apps/condo/domains/common/hooks/useGlobalHints.tsx
  apps/condo/pages/user/index.tsx
Labels: 👶 small, ✋🙂 Review please

#4562 deps(global): bump json5
  package.json
  packages/ui/package.json
  yarn.lock
Labels: 🔥 HOTFIX, ✋🙂 Review please, 😵‍💫 dependencies

#4563 fix(condo): DOMA-8760 do not reset activeStep when go to tour from complete flow modal
  apps/condo/domains/onboarding/hooks/TourContext/useCompletedTourModals.tsx
  apps/condo/pages/tour/index.tsx
Labels: 👶 small, ✋🙂 Review please

#4568 deps(global): bump webpack@5 and loader-utils@2
  package.json
  packages/icons/package.json
  packages/ui/package.json
  yarn.lock
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 😵‍💫 dependencies

#4509 try add log artefacts
  .github/workflows/_nodejs.condo.core.tests.yml
  .github/workflows/nodejs.condo.test.yml
  condo.tests.Dockerfile
  run_condo_domain_tests.sh
Labels: ✋🙂 Review please

#4556 fix(condo): DOMA-8739 updated logo snippet
  apps/condo/public/logoSnippet.png
Labels: 👶 small, ✋🙂 Review please

#4573 fix(condo): DOMA-8742 use custom fetch instead of 'node-fetch'
  apps/condo/domains/user/utils/hCaptcha.js
Labels: 👶 small, ✋🙂 Review please

#4574 fix(condo): DOMA-8781 fixed news item page in admin panel
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItem.js
Labels: 👶 small, ✋🙂 Review please

#4586 fix(condo): DOMA-8740 fix typo
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4584 fix(address-service): DOMA-8791 pass data from query to body for single search url
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
Labels: 👶 small, ✋🙂 Review please

#4581 fix(condo): Added test for unified mutation
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
Labels: 👶 small, ✋🙂 Review please

#4590 fix(condo: DOMA-8777): fixed incidents with deleted property
  apps/condo/domains/common/components/GraphQlSearchInput/Renders.tsx
  apps/condo/domains/property/utils/clientSchema/Renders.tsx
  apps/condo/domains/ticket/components/IncidentForm/BaseIncidentForm.tsx
  apps/condo/domains/ticket/components/IncidentForm/UpdateIncidentForm.tsx
  apps/condo/domains/ticket/hooks/useIncidentTableColumns.tsx
  apps/condo/domains/ticket/utils/clientSchema/IncidentRenders.tsx
  apps/condo/pages/incident/[id]/index.tsx
  apps/condo/pages/incident/index.tsx
Labels: ✋🙂 Review please

#4589 fix(ui): DOMA-8809 fix card link icons hover color
  apps/condo/domains/contact/components/ContactsEditor/index.tsx
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/NewsForm/CreateNewsForm.tsx
  apps/condo/domains/onboarding/components/TourPage/TourStepCard.tsx
  apps/condo/domains/onboarding/utils/clientSchema/constants.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/tour/guide.tsx
  apps/condo/pages/tour/index.tsx
  packages/ui/src/components/Card/_utils/index.tsx
  packages/ui/src/components/Card/style.less
Labels: 👶 small, ✋🙂 Review please

#4606 fix(condo): DOMA-8829 fix redirect on click to createPropertyMap tour step if no properties
  apps/condo/domains/onboarding/utils/clientSchema/constants.ts
Labels: 👶 small, ✋🙂 Review please

#4597 fix(condo): DOMA-8754 return unitType and unitName
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
Labels: 👶 small, ✋🙂 Review please

#4612 docs(global): fix README.md node version typo
  README.md
Labels: 👶 small, 📝 Docs

#4613 feat(condo): INFRA-303 Removed the requirement for some fields in B2BApps
  apps/condo/domains/miniapp/components/AppCard.tsx
  apps/condo/domains/miniapp/components/AppDescription/PageContent.tsx
  apps/condo/domains/miniapp/components/AppDescription/TopCard.tsx
  apps/condo/domains/miniapp/schema/AllMiniAppsService.js
  apps/condo/domains/miniapp/schema/AllMiniAppsService.test.js
  apps/condo/domains/miniapp/schema/B2BApp.js
  apps/condo/domains/miniapp/schema/B2BApp.test.js
  apps/condo/domains/miniapp/utils/testSchema/index.js
  apps/condo/migrations/20240412153420-0383_alter_b2bapp_detaileddescription_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#4603 fix(condo): DOMA-8823 use addressKey for MeterResorceOwner address cr…
  apps/condo/domains/meter/schema/Meter.js
Labels: 👶 small, ✋🙂 Review please

#4605 fix(condo): DOMA-8789 fixed news items recipients loading
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/components/RecipientCounter.tsx
  apps/condo/domains/news/constants/common.js
  apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.js
  apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.test.js
  apps/condo/domains/user/components/NotDefinedField.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/news/[id]/index.tsx
Labels: ✋🙂 Review please

#4627 feat(condo): DOMA-8846 added link to employee bot in onboarding
  apps/condo/domains/onboarding/components/TourPage/AppCards.tsx
  apps/condo/domains/onboarding/hooks/TourPage/useTourPageData.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4610 refactor(condo): DOMA-8715 remove old onboarding
  apps/condo/bin/fix-database-migration-state.js
  apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
  apps/condo/domains/common/components/icons/OnBoardingProgress.tsx
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/onboarding/access/CreateOnBoardingService.js
  apps/condo/domains/onboarding/access/OnBoarding.js
  apps/condo/domains/onboarding/access/OnBoardingStep.js
  apps/condo/domains/onboarding/components/OnBoardingContext.tsx
  apps/condo/domains/onboarding/components/OnBoardingProgressIconContainer.tsx
  apps/condo/domains/onboarding/components/OnBoardingStepItem/components.tsx
  apps/condo/domains/onboarding/components/OnBoardingStepItem/index.tsx
  apps/condo/domains/onboarding/components/WelcomePopup.tsx
  apps/condo/domains/onboarding/constants.js
  apps/condo/domains/onboarding/constants/errors.js
  apps/condo/domains/onboarding/contexts/TourContext.tsx
  apps/condo/domains/onboarding/gql.js
  apps/condo/domains/onboarding/hooks/useOnBoardingCompleeteModal.tsx
  apps/condo/domains/onboarding/schema/CreateOnBoardingService.js
  apps/condo/domains/onboarding/schema/CreateOnBoardingService.test.js
  apps/condo/domains/onboarding/schema/OnBoarding.js
  apps/condo/domains/onboarding/schema/OnBoarding.test.js
  apps/condo/domains/onboarding/schema/OnBoardingStep.js
  apps/condo/domains/onboarding/schema/OnBoardingStep.test.js
  apps/condo/domains/onboarding/schema/TourStep.test.js
  apps/condo/domains/onboarding/schema/index.js
  apps/condo/domains/onboarding/utils/clientSchema/OnBoarding.ts
  apps/condo/domains/onboarding/utils/clientSchema/OnBoardingStep.ts
  apps/condo/domains/onboarding/utils/clientSchema/TourStep.ts
  apps/condo/domains/onboarding/utils/clientSchema/index.ts
  apps/condo/domains/onboarding/utils/serverSchema/index.js
  apps/condo/domains/onboarding/utils/serverSideStepUtils.js
  apps/condo/domains/onboarding/utils/stepUtils.ts
  apps/condo/domains/onboarding/utils/testSchema/index.js
  apps/condo/domains/organization/components/OrganizationRequired.tsx
  apps/condo/domains/organization/components/OrganizationSelect.tsx
  apps/condo/domains/organization/integrations/sbbol/routes.js
  apps/condo/domains/organization/integrations/sbbol/sync/getOnBoadringStatus.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncUser.spec.js
  apps/condo/domains/user/integration/appleid/utils/helper.js
  apps/condo/domains/user/integration/sberid/routes.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240417171855-0386_auto_20240417_1218.js
  apps/condo/pages/_app.tsx
  apps/condo/pages/auth/register.tsx
  apps/condo/pages/index.tsx
  apps/condo/pages/onboarding.tsx
  apps/condo/public/onBoardingSuccess.png
  apps/condo/public/welcomePopupStep1.png
  apps/condo/public/welcomePopupStep2_1.png
  apps/condo/public/welcomePopupStep2_2.png
  apps/condo/public/welcomePopupStep3.png
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4637 hotfix: revert migration type conversion
  apps/condo/domains/notification/schema/fields/MessageType.js
  apps/condo/migrations/20240411155808-0381_alter_message_type_alter_messageappblacklist_type_and_more.js
  apps/condo/migrations/20240418134550-0387_alter_message_type_alter_messageappblacklist_type_and_more.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 🚨 Migrations

#4633 fix(condo): DOMA-8865 fixed deleted properties in reports of incidents
  apps/condo/domains/ticket/tasks/exportIncidents.js
  apps/condo/domains/ticket/utils/serverSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4640 fix(condo): DOMA-7240 was prohibited to create organizations directly
  apps/condo/domains/banking/schema/BankAccount.test.js
  apps/condo/domains/meter/schema/MeterResourceOwner.test.js
  apps/condo/domains/organization/access/Organization.js
  apps/condo/domains/organization/schema/Organization.test.js
  apps/condo/domains/user/schema/UserRightsSet.test.js
Labels: 👶 small, ✋🙂 Review please

#4636 feat(condo): DOMA-8828 property documents
  apps/condo/domains/common/components/MultipleFileUpload.tsx
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/document/access/Document.js
  apps/condo/domains/document/access/DocumentCategory.js
  apps/condo/domains/document/components/DocumentCategoryFormItem.tsx
  apps/condo/domains/document/constants.js
  apps/condo/domains/document/gql.js
  apps/condo/domains/document/hooks/useUpdateDocumentModal.tsx
  apps/condo/domains/document/hooks/useUploadDocumentsModal.tsx
  apps/condo/domains/document/schema/Document.js
  apps/condo/domains/document/schema/Document.test.js
  apps/condo/domains/document/schema/DocumentCategory.js
  apps/condo/domains/document/schema/DocumentCategory.test.js
  apps/condo/domains/document/schema/index.js
  apps/condo/domains/document/utils/clientSchema/Document.ts
  apps/condo/domains/document/utils/clientSchema/DocumentCategory.ts
  apps/condo/domains/document/utils/clientSchema/index.ts
  apps/condo/domains/document/utils/serverSchema/index.js
  apps/condo/domains/document/utils/testSchema/index.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/domains/property/components/PropertyDocuments/PropertyDocuments.tsx
  apps/condo/domains/property/components/panels/index.tsx
  apps/condo/domains/property/hooks/usePropertyDocumentsTableColumns.tsx
  apps/condo/domains/property/hooks/usePropertyDocumentsTableFilters.ts
  apps/condo/domains/property/utils/serverSchema/index.js
  apps/condo/domains/property/utils/testSchema/index.js
  apps/condo/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240419202652-0388_auto_20240419_1527.js
  apps/condo/pages/property/[id]/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4496 feat(condo): DOMA-8507 mutation for meters
  .github/workflows/_nodejs.condo.core.tests.yml
  .github/workflows/nodejs.condo.cypress.yml
  apps/address-service/domains/common/utils/services/search/strategies/AbstractBulkSearchStrategy.js
  apps/condo/bin/prepare.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
  apps/condo/domains/billing/schema/resolvers/propertyResolver.js
  apps/condo/domains/meter/access/RegisterMetersReadingsService.js
  apps/condo/domains/meter/constants/errors.js
  apps/condo/domains/meter/gql.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
  apps/condo/domains/meter/schema/index.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.js
  apps/condo/domains/meter/utils/serverSchema/index.js
  apps/condo/domains/meter/utils/testSchema/index.js
  apps/condo/domains/miniapp/gql.js
  apps/condo/domains/miniapp/schema/B2BAppAccessRightSet.test.js
  apps/condo/domains/miniapp/schema/B2CAppProperty.spec.js
  apps/condo/domains/miniapp/schema/B2CAppProperty.test.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/config.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/index.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/schema.utils.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/schema.utils.spec.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/server.utils.js
  apps/condo/domains/miniapp/utils/testSchema/index.js
  apps/condo/domains/onboarding/access/UserHelpRequest.js
  apps/condo/domains/onboarding/access/UserHelpRequestFile.js
  apps/condo/domains/onboarding/schema/UserHelpRequest.test.js
  apps/condo/domains/onboarding/schema/UserHelpRequestFile.test.js
  apps/condo/domains/organization/schema/Organization.test.js
  apps/condo/domains/organization/utils/accessSchema.js
  apps/condo/domains/property/schema/Property.test.js
  apps/condo/domains/resident/access/GetResidentExistenceByPhoneAndAddressService.js
  apps/condo/domains/resident/schema/GetResidentExistenceByPhoneAndAddressService.test.js
  apps/condo/domains/resident/schema/RegisterResidentService.test.js
  apps/condo/domains/user/schema/UserRightsSet.test.js
  apps/condo/jest.config.js
  apps/condo/jest.mocksSetup.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240420074546-0389_b2bappaccessrightset_canexecuteregistermetersreadings_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/clients/address-service-client/AddressServiceClient.js
  packages/clients/address-service-client/MockedAddressServiceClient.js
  packages/clients/address-service-client/README.md
  packages/clients/address-service-client/__mocks__/AddressServiceClient.js
  packages/clients/address-service-client/index.js
  packages/clients/finance-info-client/__mocks__/index.js
  packages/clients/finance-info-client/index.js
  packages/clients/finance-info-client/mocked.js
  packages/keystone/rateLimiting/request.utils.js
Labels: ✋🙂 Review please, 🚨 Migrations, 🐘 BIG

#4652 feat(condo): DOMA-8900 return PersAcc instead of PersonalAcc
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
Labels: 👶 small, ✋🙂 Review please

#4653 Feat/condo/doma-8901/anonymous access to validate qr code
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
  apps/condo/domains/billing/access/ValidateQRCodeService.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.test.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
Labels: 👶 small, ✋🙂 Review please

#4672 hotfix: update luxon dependency
  package.json
  yarn.lock
Labels: 😵‍💫 dependencies

#4676 fix(global): INFRA-312 update decode-uri-component dep to safest version
  package.json
  yarn.lock
Labels: 😵‍💫 dependencies

#4678 fix(condo): DOMA-8937 fix ticket import unitName trim
  apps/condo/domains/ticket/hooks/useImporterFunctions.ts
Labels: 👶 small, ✋🙂 Review please

#4679 fix(condo): DOMA-8947 do not show complete step modal on not first import
  apps/condo/domains/onboarding/contexts/TourContext.tsx
Labels: 👶 small, ✋🙂 Review please
