Repository open-condo-software/condo, pull requests merged in 2024-05, with the labels that each got.

#4675 feat(ui): DOMA-8921 updated Checkbox
  packages/ui/src/components/Checkbox/mixins.less
  packages/ui/src/components/Checkbox/style.less
  packages/ui/src/components/Typography/style.less
  packages/ui/src/components/style/mixins/transition.less
Labels: ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#4685 fix(global): INFRA-313 update node-fetch dep
  package.json
  yarn.lock
Labels: 😵‍💫 dependencies

#4667 feat(ui): DOMA-8920 added IconButton
  packages/ui/src/components/Button/icon/iconButton.tsx
  packages/ui/src/components/Button/icon/style.less
  packages/ui/src/components/Button/index.ts
  packages/ui/src/components/Button/style.less
  packages/ui/src/components/_utils/analytics.ts
  packages/ui/src/components/style/mixins/button.less
  packages/ui/src/index.ts
  packages/ui/src/stories/Button/Button.stories.tsx
  packages/ui/src/stories/Button/IconButton.stories.tsx
Labels: ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#4692 feat(condo): DOMA-8888 added urls to billing integration
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/BillingIntegration.js
  apps/condo/domains/billing/schema/BillingIntegration.test.js
  apps/condo/domains/billing/schema/BillingIntegrationOrganizationContext.test.js
  apps/condo/domains/billing/utils/testSchema/index.js
  apps/condo/domains/billing/utils/testSchema/utils.js
  apps/condo/domains/billing/utils/validation.utils.js
  apps/condo/migrations/20240503185927-0392_billingintegration_checkaccountnumberurl_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#4693 hotfix: add unique index by uniqKey and type for Message
  apps/condo/domains/notification/schema/Message.js
  apps/condo/migrations/20240504154034-0393_auto_20240504_1040.js
Labels: 🔥 HOTFIX, ✋🙂 Review please, 🚨 Migrations

#4711 fix/condo/doma-8972/fix-message-type
  apps/condo/domains/notification/schema/SendMessageService.test.js
  apps/condo/domains/notification/tasks/deliverMessage.js
Labels: 👶 small, ✋🙂 Review please

#4715 Feat/condo/doma 8971/add two dates to payment model
  apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/hooks/usePaymentsTableColumns.ts
  apps/condo/domains/acquiring/hooks/usePaymentsTableFilters.ts
  apps/condo/domains/acquiring/schema/Payment.js
  apps/condo/domains/acquiring/schema/fields/PaymentsFilter.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240508155221-0394_payment_depositeddate_payment_transferdate_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#4716 hotfix(condo): DOMA-8985 forbidden to use RegisterUserService without…
  apps/condo/domains/common/constants/regexps.js
  apps/condo/domains/common/utils/text.js
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/organization/schema/Organization.js
  apps/condo/domains/organization/schema/Organization.test.js
  apps/condo/domains/user/constants/errors.js
  apps/condo/domains/user/schema/RegisterNewUserService.js
  apps/condo/domains/user/schema/RegisterNewUserService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🔥 HOTFIX, ✋🙂 Review please

#4717 hotfix(condo): DOMA-8985 fixed a validation of organization name
  apps/condo/domains/common/constants/regexps.js
  apps/condo/domains/organization/schema/Organization.js
  apps/condo/domains/organization/schema/Organization.test.js
Labels: 🔥 HOTFIX, ✋🙂 Review please

#4725 hotfix(condo): HOTFIX fix auth with extended config in sbBOL`
  apps/condo/domains/organization/integrations/sbbol/oauth2.js
Labels: 🔥 HOTFIX

#4724 fix(condo): DOMA-9004 fix complete step modal show after first meter readings import
  apps/condo/domains/meter/components/Import/Index.tsx
  apps/condo/domains/onboarding/contexts/TourContext.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4733 hotfix(condo): HOTFIX fixed sbbol secret storage with extended config
  apps/condo/domains/organization/integrations/sbbol/utils/getSbbolSecretStorage.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4729 feat(condo): DOMA-9006 expanded B2B apps categories
  apps/condo/domains/miniapp/components/Catalog/CardGrid.tsx
  apps/condo/domains/miniapp/constants.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#4737 Fix/condo/doma-9025/zero processed incorrectly
  apps/condo/domains/meter/components/MetersDataImporter.tsx
  apps/condo/domains/meter/utils/metersImporters/DomaMetersImporter.ts
Labels: 👶 small, ✋🙂 Review please

#4738 hotfix(condo): HOTFIX fixed sbbol completeAuth with extended config
  apps/condo/domains/organization/integrations/sbbol/routes.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4739 Feat/condo/doma-9034/flat 1 in meters registry
  apps/condo/domains/billing/schema/resolvers/propertyResolver.spec.js
  packages/clients/address-service-client/utils/parseAddressesFromString.js
  packages/clients/address-service-client/utils/parseAddressesFromString.spec.js
Labels: 👶 small, ✋🙂 Review please

#4741 fix(condo): DOMA-9037 normalize row length
  apps/condo/domains/meter/components/MetersDataImporter.tsx
Labels: 👶 small, ✋🙂 Review please

#4745 Fix/condo/doma-9042/fix meter readings uploading
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/utils/metersImporters/DomaMetersImporter.spec.ts
  apps/condo/domains/meter/utils/metersImporters/DomaMetersImporter.ts
Labels: 👶 small, ✋🙂 Review please

#4746 hotfix(condo): HOTFIX fixed using of extended config for sbbol
  apps/condo/domains/organization/integrations/sbbol/routes.js
  apps/condo/domains/organization/integrations/sbbol/sync/index.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncTokens.js
  apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4753 hotfix(condo): HOTFIX fixed refresh sbbol client secret
  apps/condo/bin/sbbol/credentials.js
  apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js
  apps/condo/domains/organization/tasks/refreshSbbolClientSecret.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4759 Chore/condo/doma 9062/no check unit while importing meters
  apps/condo/domains/meter/constants/errors.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4760 fix(address-service): DOMA-9072 return address type for injections
  .github/workflows/nodejs.address-service.test.yml
  apps/address-service/domains/common/constants/common.js
  apps/address-service/domains/common/utils/services/InjectionsSeeker.js
  apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
Labels: 👶 small, ✋🙂 Review please

#4765 fix(condo): DOMA-9080 Add resource to conditions for searching of meters
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4767 fix(condo): DOMA-9079 fixed news creating
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
Labels: 👶 small, ✋🙂 Review please

#4766 fix(condo): DOMA-9093 show errors if there is an unknown resource and…
  apps/condo/domains/meter/components/MetersDataImporterTypes.ts
  apps/condo/domains/meter/hooks/useMetersImporter.ts
  apps/condo/domains/meter/utils/metersImporters/AbstractMetersImporter.ts
  apps/condo/domains/meter/utils/metersImporters/DomaMetersImporter.spec.ts
  apps/condo/domains/meter/utils/metersImporters/DomaMetersImporter.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#4768 feat(condo): DOMA-9073 add charset encoding for meters sbbol registry
  apps/condo/domains/meter/components/MetersDataImporter.tsx
Labels: 👶 small, ✋🙂 Review please

#4770 hotfix(condo): INFRA-317 added information about invitations in cache
  apps/condo/domains/organization/access/Organization.js
  apps/condo/domains/organization/schema/OrganizationEmployee.test.js
  apps/condo/domains/organization/utils/accessSchema.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4772 feat(condo): INFRA-336 add webHooked plugin to TicketComment
  apps/condo/domains/ticket/schema/TicketComment.js
Labels: 👶 small, ✋🙂 Review please

#4773 fix(condo): DOMA-9118 fixed custom roles after design-review
  apps/condo/domains/organization/components/EmployeeRoleForm/BaseEmployeeRoleForm.tsx
  apps/condo/domains/organization/components/EmployeeRolesSettingsContent.tsx
  apps/condo/domains/organization/hooks/useEmployeeRolesTableColumns.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4774 fix(condo): DOMA-9118 fixed custom roles after design-review
  apps/condo/domains/common/components/Form/FormItem.ts
  apps/condo/domains/common/components/TextArea.tsx
  apps/condo/domains/organization/components/EmployeeRoleForm/BaseEmployeeRoleForm.tsx
  apps/condo/domains/organization/components/EmployeeRoleForm/PermissionsGrid.tsx
Labels: 👶 small, ✋🙂 Review please

#4778 fix(condo): DOMA-9137 do not load all billing accounts and billing properties
  apps/condo/domains/billing/schema/resolvers/accountResolver.js
  apps/condo/domains/billing/schema/resolvers/propertyResolver.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4783 fix(condo): DOMA-9152 updated unique constraint for BankTransaction
  apps/condo/domains/banking/schema/BankTransaction.js
  apps/condo/domains/banking/schema/BankTransaction.test.js
  apps/condo/domains/banking/utils/testSchema/index.js
  apps/condo/migrations/20240530200526-0396_remove_banktransaction_bank_transaction_unique_organization_importremotesystem_importid_and_more.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations
