Repository open-condo-software/condo, pull requests merged in 2024-09, with the labels that each got.

#5164 feat(condo): DOMA-457 set default fetchPolicy for client utils
  apps/condo/pages/_app.tsx
  packages/codegen/generate.hooks.ts
Labels: 👶 small, ✋🙂 Review please

#5154 fix(condo): DOMA-9474 creating new resident, if it was deleted instead of restoring
  apps/condo/domains/resident/schema/RegisterResidentService.js
  apps/condo/domains/resident/schema/RegisterResidentService.test.js
Labels: 👶 small

#5173 fix(condo): INFRA-485 block auth for super users
  apps/condo/domains/miniapp/components/AppIndex/B2BAppPage.tsx
  apps/condo/domains/user/gql.js
  apps/condo/domains/user/oidc/adapter/OidcModelClientAdapter.js
  apps/condo/domains/user/oidc/configuration.js
  apps/condo/domains/user/schema/OidcClient.js
  apps/condo/domains/user/schema/OidcClient.test.js
  apps/condo/domains/user/schema/_oidc.test.js
  apps/condo/migrations/20240903202439-0418_oidcclient_canauthorizesuperusers_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#5171 feat(condo): DOMA-9935 add minimum amount settings to acquiring integration
  apps/condo/domains/acquiring/constants/errors.js
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/schema/AcquiringIntegration.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForInvoicesService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForInvoicesService.test.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForOneReceiptService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForOneReceiptService.test.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForVirtualReceiptService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForVirtualReceiptService.test.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240904172054-0420_acquiringintegration_minimumpaymentamount_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#5190 feat(condo): INFRA-466 improve syncTourSteps service
  apps/condo/domains/onboarding/schema/SyncTourStepsService.js
  apps/condo/k6/src/syncTourStep.test.ts
  apps/condo/k6/src/ticket.test.ts
  apps/condo/k6/src/utils.ts
  apps/condo/k6/webpack.config.js
Labels: ✋🙂 Review please

#5192 feat(condo): DOMA-9935 calculate fee for receipt
  apps/condo/domains/acquiring/access/CalculateFeeForReceiptService.js
  apps/condo/domains/acquiring/constants/constants.js
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/schema/CalculateFeeForReceiptService.js
  apps/condo/domains/acquiring/schema/CalculateFeeForReceiptService.test.js
  apps/condo/domains/acquiring/schema/index.js
  apps/condo/domains/acquiring/utils/serverSchema/index.js
  apps/condo/domains/acquiring/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#5196 feat(condo): DOMA-10067 basic unitName normalization
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
  apps/condo/domains/billing/utils/unitName.utils.js
  apps/condo/domains/billing/utils/unitName.utils.spec.js
  package.json
  yarn.lock
Labels: 😵‍💫 dependencies

#5201 refactor(condo): DOMA-10178 use sendEach() instead of deprecated sendAll() in firebaseAdapter.js
  apps/condo/domains/notification/adapters/firebaseAdapter.js
Labels: 🔥 HOTFIX

#5199 fix(condo): added clear bad symbols from requestId
  packages/keystone/KSv5v6/v5/prepareKeystone.js
  packages/keystone/KSv5v6/v5/validateHeaders.js
  packages/keystone/KSv5v6/v5/validateHeaders.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#5204 fix(condo): DOMA-10091 growthbook features keeping
  packages/featureflags/FeatureFlagsContext.tsx
  packages/featureflags/featureToggleManager.js
Labels: 👶 small, ✋🙂 Review please

#5214 fix(condo): fix marketPlace imports
  apps/condo/domains/common/hooks/useMutationErrorHandler.tsx
  apps/condo/domains/marketplace/components/MarketItemContent.tsx
  apps/condo/domains/marketplace/components/MarketplacePaymentsContent.tsx
  apps/condo/pages/meter/property/[id]/index.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#5227 hotfix(condo): temporary disable replication in CI
  bin/run_condo_domain_tests.sh
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#5218 chore(condo): moved slugify package from global package.json to condo/package.json
  apps/condo/package.json
  package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😵‍💫 dependencies

#5124 feat(condo): DOMA-9940 meter reading billing status
  apps/condo/domains/meter/constants/constants.js
  apps/condo/domains/meter/constants/errors.js
  apps/condo/domains/meter/gql.js
  apps/condo/domains/meter/schema/MeterReading.js
  apps/condo/domains/meter/schema/MeterReading.test.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
  apps/condo/domains/meter/tasks/importMeters.spec.js
  apps/condo/domains/meter/utils/taskSchema/AbstractMetersImporter.js
  apps/condo/domains/miniapp/schema/B2BAppAccessRightSet.test.js
  apps/condo/migrations/20240912111459-0422_meterreading_billingstatus_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/apollo-server-client/index.js
Labels: ✋🙂 Review please

#5226 fix(condo): INFRA-506 clear fetch's timeout
  packages/keystone/fetch.js
  packages/keystone/fetch.spec.js
Labels: 👶 small, ✋🙂 Review please

#5234 feat(ui): INFRA-509 migrate from CSF2 to CSF3. Fixed storybook
  .eslintrc.js
  packages/ui/src/components/Alert/alert.tsx
  packages/ui/src/components/Button/button.tsx
  packages/ui/src/components/Dropdown/button/index.tsx
  packages/ui/src/components/Markdown/markdown.tsx
  packages/ui/src/components/Modal/useModal.tsx
  packages/ui/src/components/Steps/step.tsx
  packages/ui/src/components/Steps/steps.tsx
  packages/ui/src/components/Typography/index.ts
  packages/ui/src/components/_utils/analytics.ts
  packages/ui/src/components/_utils/responsiveObserve.ts
  packages/ui/src/stories/ActionBar.stories.tsx
  packages/ui/src/stories/Alert.stories.tsx
  packages/ui/src/stories/Banner.stories.tsx
  packages/ui/src/stories/Button/Button.stories.tsx
  packages/ui/src/stories/Button/IconButton.stories.tsx
  packages/ui/src/stories/Card/Card.stories.tsx
  packages/ui/src/stories/Card/CardButton.stories.tsx
  packages/ui/src/stories/Card/CardCheckbox.stories.tsx
  packages/ui/src/stories/Carousel.stories.tsx
  packages/ui/src/stories/Checkbox.stories.tsx
  packages/ui/src/stories/Dropdown.stories.tsx
  packages/ui/src/stories/Input/Input.stories.tsx
  packages/ui/src/stories/Input/Password.stories.tsx
  packages/ui/src/stories/Input/Phone.stories.tsx
  packages/ui/src/stories/List.stories.tsx
  packages/ui/src/stories/Markdown.stories.tsx
  packages/ui/src/stories/Modal.stories.tsx
  packages/ui/src/stories/ProgressIndicator.stories.tsx
  packages/ui/src/stories/Radio/Radio.stories.tsx
  packages/ui/src/stories/Radio/RadioGroup.stories.tsx
  packages/ui/src/stories/Select.stories.tsx
  packages/ui/src/stories/Space.stories.tsx
  packages/ui/src/stories/Steps.stories.tsx
  packages/ui/src/stories/Tabs.stories.tsx
  packages/ui/src/stories/Tag.stories.tsx
  packages/ui/src/stories/Tooltip.stories.tsx
  packages/ui/src/stories/TourStep.stories.tsx
  packages/ui/src/stories/Typography/Link.stories.tsx
  packages/ui/src/stories/Typography/Paragraph.stories.tsx
  packages/ui/src/stories/Typography/Text.stories.tsx
  packages/ui/src/stories/Typography/Title.stories.tsx
  packages/ui/src/stories/colors.stories.tsx
  packages/ui/src/stories/icons.stories.tsx
Labels: ✋🙂 Review please, 📦 Packages

#5236 refactor(condo): INFRA-513 reduce gql fields in server side property utils
  apps/condo/domains/banking/tasks/importBankTransactionsFrom1CClientBankExchange.js
  apps/condo/domains/billing/schema/helpers/propertyFinder.js
  apps/condo/domains/contact/schema/_internalSyncContactsWithResidentsForOrganizationService.js
  apps/condo/domains/marketplace/schema/MarketPriceScope.js
  apps/condo/domains/meter/schema/Meter.js
  apps/condo/domains/meter/schema/MeterReportingPeriod.js
  apps/condo/domains/news/tasks/exportRecipients.js
  apps/condo/domains/notification/schema/_internalSendNotificationNewMobileAppVersionService.js
  apps/condo/domains/organization/schema/ResetOrganizationService.js
  apps/condo/domains/property/gql.js
  apps/condo/domains/property/utils/serverSchema/index.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
  apps/condo/domains/resident/schema/Resident.js
  apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
Labels: 👶 small, ✋🙂 Review please

#5240 fix(condo): INFRA-519 added dependency on "babel-loader" in packege.json
  apps/condo/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please

#5259 feat(global): INFRA-525 downgrade react to 16 for packages
  packages/apollo/package.json
  packages/miniapp-utils/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😵‍💫 dependencies, 📦 Packages

#5270 feat(condo): DOMA-10258 added "updatedAt" in ResidentBillingReceiptOutput
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#5257 feat(condo): DOMA-10237 added maximum payment amount in acquiring integration
  apps/condo/domains/acquiring/constants/errors.js
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/schema/AcquiringIntegration.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForInvoicesService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForInvoicesService.test.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForOneReceiptService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForOneReceiptService.test.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForVirtualReceiptService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentForVirtualReceiptService.test.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240923152333-0426_acquiringintegration_maximumpaymentamount_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/keystone/fields/SignedDecimal/Implementation.js
Labels: ✋🙂 Review please, 🚨 Migrations

#5279 refactor(condo): INFRA-496 fix importid constraint
  apps/condo/domains/billing/schema/BillingReceipt.js
  apps/condo/domains/billing/schema/BillingReceipt.test.js
  apps/condo/migrations/20240925164102-0427_billingreceipt_billingreceipt_unique_context_and_importid.js
Labels: 👶 small, 🚨 Migrations

#5292 feat(condo): INFRA-540 added webhooks on TicketCommentFile
  apps/condo/domains/ticket/schema/TicketCommentFile.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#5288 feat(condo): DOMA-10102 add column minFloor to PropertyMap in import excel file
  apps/condo/domains/property/hooks/useImporterFunctions.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/public/import/property/en/property-import-example.webp
  apps/condo/public/import/property/en/property-import-example.xlsx
  apps/condo/public/import/property/ru/property-import-example.webp
  apps/condo/public/import/property/ru/property-import-example.xlsx
Labels: 👶 small

#5265 feat(condo): DOMA-9648 add new templates in schema news item template
  apps/condo/domains/news/constants/newsCategory.js
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/schema/NewsItemTemplate.js
  apps/condo/domains/news/schema/NewsItemTemplate.test.js
  apps/condo/domains/news/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240927142333-0429_newsitemtemplate_category_newsitemtemplate_name_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🚨 Migrations
