Repository open-condo-software/condo, pull requests merged in 2024-06, with the labels that each got.

#4792 feat(ui): DOMA-9150 adaptive typography
  packages/ui/src/components/Tabs/style.less
  packages/ui/src/components/style/mixins/typography.less
Labels: 👶 small, ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit, 📦 Packages

#4779 chore(condo): DOMA-9105 QR code mutations return fields & logic
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
  apps/condo/domains/billing/constants/errors.js
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.test.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.spec.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4797 fix(condo): DOMA-9181 fix image and text of card on guide page
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/tour/guide.tsx
  apps/condo/public/onboarding/guide/aboutApp/en/communication/cardImage.webp
  apps/condo/public/onboarding/guide/aboutApp/en/extraIncome/cardImage.webp
  apps/condo/public/onboarding/guide/aboutApp/en/extraIncome/modalImage.webp
  apps/condo/public/onboarding/guide/aboutApp/ru/communication/cardImage.webp
  apps/condo/public/onboarding/guide/aboutApp/ru/extraIncome/cardImage.webp
  apps/condo/public/onboarding/guide/aboutApp/ru/extraIncome/modalImage.webp
Labels: 👶 small, ✋🙂 Review please

#4799 fix(keystone): DOMA-9143 use custom fetch for StitchSchemaMiddleware
  packages/keystone/stitchSchema.js
Labels: 👶 small, ✋🙂 Review please, 📦 Packages

#4805 chore(condo): DOMA-9194 improve meters errors
  apps/condo/domains/meter/constants/errors.js
  apps/condo/domains/meter/schema/Meter.js
  apps/condo/domains/meter/schema/Meter.test.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4804 feat(condo): DOMA-9047 add manual migration for water removal billingСategory
  apps/condo/migrations/20240605231910-0397_manual_insert_billing_category.js
Labels: 👶 small, ✋🙂 Review please

#4814 fix(condo): DOMA-9253 fix errors displaying while uploading meters
  apps/condo/domains/meter/utils/metersImporters/AbstractMetersImporter.ts
Labels: 👶 small, ✋🙂 Review please

#4816 hotfix(condo): HOTFIX fixed gql type error
  apps/condo/domains/ticket/utils/clientSchema/search.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4821 fix(dev-portal): INFRA-347 fix styling after antd upgrade
  apps/dev-portal/domains/common/components/CollapsibleMenu.module.css
  apps/dev-portal/domains/common/constants/antd.ts
  apps/dev-portal/pages/global.css
Labels: 👶 small, ✋🙂 Review please

#4829 fix(condo): DOMA-9242 fixed feature flags when loading data for the first time
  apps/condo/pages/_app.tsx
  packages/featureflags/FeatureFlagsContext.tsx
  packages/featureflags/featureToggleManager.js
  packages/featureflags/package.json
  yarn.lock
Labels: ✋🙂 Review please

#4832 fix(condo): DOMA-9242 fixed updating of feature flags
  apps/condo/pages/_app.tsx
  packages/featureflags/FeatureFlagsContext.tsx
Labels: 👶 small, ✋🙂 Review please

#4844 fix(condo): DOMA-9302 transform "000" to "0" instead of ""
  packages/clients/address-service-client/utils/parseAddressesFromString.js
  packages/clients/address-service-client/utils/parseAddressesFromString.spec.js
Labels: 👶 small, ✋🙂 Review please

#4828 feat(condo): DOMA-9260 QR-code acquiring requisites validation & using
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.test.js
Labels: ✋🙂 Review please

#4835 feat(condo): DOMA-9296 make cross-domain test utils
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptFileService.test.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
  apps/condo/domains/billing/utils/testSchema/mixins/acquiring.js
  apps/condo/domains/billing/utils/testSchema/mixins/billing.js
  apps/condo/domains/billing/utils/testSchema/mixins/contact.js
  apps/condo/domains/billing/utils/testSchema/mixins/meter.js
  apps/condo/domains/billing/utils/testSchema/mixins/organization.js
  apps/condo/domains/billing/utils/testSchema/mixins/property.js
  apps/condo/domains/billing/utils/testSchema/mixins/resident.js
  apps/condo/domains/billing/utils/testSchema/testUtils.js
  apps/condo/domains/billing/utils/testSchema/utils.js
Labels: 👶 small, ✋🙂 Review please

#4850 fix(address-service): DOMA-9322 send 404 when address not found
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
Labels: 👶 small, ✋🙂 Review please

#4840 feat(condo): DOMA-9224 added isVerified checkbox to contact import modal
  apps/condo/domains/common/components/Import/BaseImportWrapper.tsx
  apps/condo/domains/common/components/Import/Index.tsx
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/contact/index.tsx
  apps/condo/public/import/contact/en/contact-import-example.xlsx
  apps/condo/public/import/contact/ru/contact-import-example.xlsx
Labels: ✋🙂 Review please

#4845 fix(condo): DOMA-8515 new meter section design review fixes
  apps/condo/domains/common/components/StatusSelect.tsx
  apps/condo/domains/marketplace/components/Invoice/InvoiceStatusSelect.tsx
  apps/condo/domains/meter/components/Meters/MeterPageContent.tsx
  apps/condo/domains/meter/components/TabContent/MeterReading.tsx
  apps/condo/domains/meter/components/TabContent/PropertyMeterReading.tsx
  apps/condo/domains/onboarding/hooks/TourContext/useCompletedTourModals.tsx
  apps/condo/domains/ticket/components/TicketStatusSelect.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/meter/index.tsx
Labels: 👶 small, ✋🙂 Review please

#4853 feat(condo): DOMA-9014 remote billing integration calls for account number check
  apps/condo/domains/billing/constants/onlineInteraction.js
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/utils/serverSchema/checkAccountNumberWithOnlineInteractionUrl.js
  apps/condo/domains/resident/schema/RegisterResidentServiceConsumerService.test.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#4856 fix(condo): DOMA-9333 fixed sync transaction for an ordinary employee
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
Labels: 👶 small, ✋🙂 Review please

#4858 feat(resident-app): DOMA-9347 redesigned tabs to look more mobile-friendly 💅
  packages/ui/src/components/Tabs/style.less
Labels: 👶 small, ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 📦 Packages

#4859 chore(condo): DOMA-9352 skip left zero trimming
  packages/clients/address-service-client/utils/parseAddressesFromString.js
  packages/clients/address-service-client/utils/parseAddressesFromString.spec.js
Labels: 👶 small, ✋🙂 Review please

#4861 fix(condo): DOMA-9289 fix service user display in ticket changes and comments
  apps/condo/domains/common/components/Comments/Comment.tsx
  apps/condo/domains/ticket/schema/TicketChange.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4871 fix(global): INFRA-355 packages jobs cleanup 🧹♻️
  .github/workflows/arc-builds.yml
  .github/workflows/arc-condo-tests.yml
  .github/workflows/arc-test.yml
  .github/workflows/nodejs.condo.ci.yml
  .github/workflows/packages.bridge.build.yml
  .github/workflows/packages.icons.build.yml
  .github/workflows/packages.ui.build.yml
  .github/workflows/packages.webhooks.test.yaml
  packages/webhooks/constants.js
Labels: 👶 small, ✋🙂 Review please, infrastructure, 📦 Packages

#4873 chore(condo): DOMA-9395 Validation for numberOfTariffs was added
  apps/condo/domains/meter/constants/errors.js
  apps/condo/domains/meter/schema/Meter.test.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
  apps/condo/domains/meter/schema/fields/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#4881 feat(condo): DOMA-9003 prevent creation of duplicated meter readings
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
Labels: ✋🙂 Review please

#4889 fix(condo): DOMA-9421 fix error throwing and processing if some cells…
  apps/condo/domains/meter/utils/taskSchema/AbstractMetersImporter.js
  apps/condo/domains/meter/utils/taskSchema/DomaMetersImporter.js
  apps/condo/domains/meter/utils/taskSchema/MetersDataImporterTypes.js
  apps/condo/domains/meter/utils/taskSchema/SbbolMetersImporter.js
Labels: 👶 small, ✋🙂 Review please

#4879 chore(condo): DOMA-9298 update meter fields within unified mutation
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
Labels: ✋🙂 Review please

#4882 feat(condo): DOMA-9195 add the ability to select a transport for MessageBatch, specify the appropriate message type
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/notification/schema/MessageBatch.test.js
  apps/condo/domains/notification/tasks/sendMessageBatch.helpers.js
  apps/condo/domains/notification/tasks/sendMessageBatch.helpers.test.js
  apps/condo/migrations/20240627173535-0404_alter_messagebatch_messagetype.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, 🚨 Migrations

#4880 ci(condo): INFRA-356 migrate tests to Condo CI
  .github/workflows/_nodejs.condo.core.tests.yml
  .github/workflows/nodejs.condo.ci.yml
  .github/workflows/nodejs.condo.test.yml
  Dockerfile
  condo.tests.Dockerfile
  packages/keystone/databaseAdapters/__snapshots__/utils.spec.js.snap
  run_condo_domain_tests.sh
Labels: 👶 small, ✋🙂 Review please, infrastructure

#4900 ci(condo): INFRA-359 move Cypress to callable workflow 📝
  .github/workflows/_nodejs.condo.cypress.yml
  .github/workflows/nodejs.condo.ci.yml
  apps/condo/bin/generate-initial-data.js
Labels: 👶 small, ✋🙂 Review please, infrastructure
