Repository open-condo-software/condo, pull requests merged in 2024-01, with the labels that each got.

#4249 fix(condo): extended timeout for migration
  apps/condo/migrations/20231220120754-0355_billingreceipthistoryrecord_acquiringhosturl_and_more.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 🚨 Migrations

#4248 feat(condo): DOMA-8175 updated popupsmart
  apps/condo/domains/common/components/PopupSmart.tsx
  apps/condo/next.config.js
Labels: 👶 small, ✋🙂 Review please

#4251 fix(condo): marketplace migration
  apps/condo/migrations/20231215145832-0353_remove_invoicecontext_createdby_and_more.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 🚨 Migrations

#4256 fix(condo): DOMA-8186 fixed a date range for analytic reports
  apps/condo/domains/analytics/hooks/useDashboardFilters.tsx
Labels: 👶 small, ✋🙂 Review please

#4268 feature(condo): DOMA-8210 make sms code shorter
  apps/condo/lang/ru/messages/TRACK_TICKET_IN_DOMA_APP/default.njk
  apps/condo/lang/ru/messages/TRACK_TICKET_IN_DOMA_APP/sms.njk
Labels: 👶 small, ✋🙂 Review please

#4271 chore(condo): DOMA-8207 added delete meter readings by property and date script
  apps/condo/bin/delete-meter-readings-by-properties.js
  apps/condo/pages/meter/index.tsx
Labels: 👶 small, ✋🙂 Review please

#4274 fix(condo): DOMA-8051 fix marketplace payment filters
  apps/condo/domains/acquiring/utils/clientSchema/Payment.ts
  apps/condo/domains/marketplace/components/MarketItem/BaseMarketItemForm.tsx
  apps/condo/domains/marketplace/components/MarketplaceOnboarding/RequisitesSetup.tsx
  apps/condo/domains/marketplace/components/MarketplacePaymentsContent.tsx
  apps/condo/domains/marketplace/hooks/useMarketplacePaymentTableColumns.tsx
  apps/condo/domains/marketplace/hooks/useMarketplacePaymentsFilters.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/ticket/[id]/index.tsx
Labels: ✋🙂 Review please

#4276 feat(condo): DOMA-6905 added unit type when a exporting news
  apps/condo/domains/common/utils/exportToExcel.js
  apps/condo/domains/news/schema/NewsItemRecipientsExportTask.test.js
  apps/condo/domains/news/tasks/exportRecipients.js
  apps/condo/domains/news/templates/NewsRecipientsExportTemplate.xlsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4283 fix(condo): DOMA-8235 ignore marketplace payments at OverviewDashboard payments section
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.js
  apps/condo/domains/analytics/schema/GetOverviewDashboardService.test.js
  apps/condo/domains/analytics/utils/services/dataLoaders/payment.js
Labels: 👶 small, ✋🙂 Review please

#4282 fix(condo): DOMA-7166 fixed validation of name when importing contacts
  apps/condo/domains/common/utils/importer.ts
  apps/condo/domains/contact/hooks/useImporterFunctions.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4288 fix(condo): DOMA-8255 update delete meter reading script
  apps/condo/bin/delete-meter-readings-by-properties.js
Labels: 👶 small, ✋🙂 Review please

#4279 feat(condo): INFRA-248 healthcheck warnings
  apps/address-service/domains/common/utils/healthchecks.js
  apps/address-service/domains/common/utils/services/DadataHealthChecker.js
  packages/keystone/healthCheck.js
Labels: 👶 small, ✋🙂 Review please

#4293 hotfix(condo): added error handler in sendPush
  apps/condo/domains/notification/adapters/apple/AppleMessaging.js
Labels: 🔥 HOTFIX

#4289 fix(condo): DOMA-8103 fix scrolling within a receipt
  apps/condo/domains/acquiring/components/AcquiringReceipt.tsx
Labels: 👶 small, ✋🙂 Review please

#4294 fix(condo): DOMA-8103 checking for existing of receipts and invoices
  apps/condo/domains/acquiring/components/AcquiringReceipt.tsx
Labels: 👶 small, ✋🙂 Review please

#4262 feat(ui): DOMA-8189 added tip component
  packages/ui/src/components/Tour/index.ts
  packages/ui/src/components/Tour/style.less
  packages/ui/src/components/Tour/tourContext.tsx
  packages/ui/src/components/Tour/tourStep.tsx
  packages/ui/src/components/_utils/analytics.ts
  packages/ui/src/index.ts
  packages/ui/src/stories/TourStep.stories.tsx
Labels: ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit

#4297 Fix/condo/doma 7923/fix currency position within receipt
  apps/condo/domains/acquiring/components/AcquiringReceipt.tsx
Labels: 👶 small, ✋🙂 Review please

#4301 feat(condo): INFRA-257 Extend direct accesses and add import plugin to OIDC client
  apps/condo/domains/user/access/OidcClient.js
  apps/condo/domains/user/access/UserRightsSet.js
  apps/condo/domains/user/schema/OidcClient.js
  apps/condo/domains/user/schema/UserRightsSet.test.js
  apps/condo/domains/user/utils/directAccess/config.js
  apps/condo/migrations/20240119160733-0360_oidcclient_importid_oidcclient_importremotesystem_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  apps/dev-api/domains/miniapp/schema/PublishB2CAppService.js
Labels: ✋🙂 Review please, 🚨 Migrations

#4305 hotfix: currency position at the receipt
  apps/condo/domains/acquiring/components/AcquiringReceipt.tsx
Labels: 👶 small, 🔥 HOTFIX

#4302 feat(condo): DOMA-8260 forbid to create multiPayment which includes receipts and invoices
  apps/condo/domains/acquiring/constants/errors.js
  apps/condo/domains/acquiring/schema/MultiPayment.js
  apps/condo/domains/acquiring/schema/MultiPayment.test.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4298 fix(condo): DOMA-8261 added validation that TicketComment user must be equal with createdBy
  apps/condo/domains/ticket/constants/errors.js
  apps/condo/domains/ticket/schema/TicketComment.js
  apps/condo/domains/ticket/schema/TicketComment.test.js
  apps/condo/domains/ticket/schema/TicketCommentFile.test.js
  apps/condo/domains/ticket/schema/TicketCommentsTime.test.js
Labels: 👶 small, ✋🙂 Review please

#4309 feat(condo): INFRA-259 OIDC constraints changed
  apps/condo/domains/user/schema/OidcClient.js
  apps/condo/domains/user/schema/OidcClient.test.js
  apps/condo/migrations/20240122152303-0361_alter_oidcclient_clientid_alter_oidcclient_name_and_more.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#4306 fix(condo): DOMA-8031 fixed a very loooong news loading
  apps/condo/domains/news/gql.js
  apps/condo/domains/news/hooks/useTableColumns.tsx
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/utils/clientSchema/NewsRenders.tsx
  apps/condo/domains/property/utils/clientSchema/Renders.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240123150124-0362_newsitemhistoryrecord_compactscopes.js
  apps/condo/pages/news/[id]/index.tsx
  apps/condo/pages/news/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/keystone/schema.js
Labels: ✋🙂 Review please, 🚨 Migrations

#4311 fix(condo): DOMA-8275 added maxResults 1000 to keystone lists
  packages/keystone/KSv5v6/v5/registerSchema.js
Labels: 👶 small, ✋🙂 Review please

#4315 fix(condo): DOMA-8285 added placeholders and tooltip to market item form
  apps/condo/domains/marketplace/components/MarketItem/BaseMarketItemForm.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4314 fix(condo): DOMA-8284 fix categories sort order
  apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
  apps/condo/domains/marketplace/components/MarketItem/BaseMarketItemForm.tsx
  apps/condo/domains/marketplace/components/MarketItemContent.tsx
  apps/condo/domains/marketplace/gql.js
Labels: 👶 small, ✋🙂 Review please

#4317 fix(condo): DOMA-8288 fix invoices query skip condition
  apps/condo/pages/ticket/[id]/index.tsx
Labels: 👶 small, ✋🙂 Review please

#4319 fix(condo): DOMA-8284 sorted categories in alphabetical order
  apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
  apps/condo/domains/marketplace/components/MarketItem/BaseMarketItemForm.tsx
  apps/condo/domains/marketplace/components/MarketItemContent.tsx
Labels: 👶 small, ✋🙂 Review please

#4322 fix(global): INFRA-260 set max db connections to 3
  packages/keystone/setup.utils.js
Labels: 🔥 HOTFIX

#4313 fix(condo): DOMA-8271 optimizing of news creating
  apps/condo/domains/news/access/NewsItemScope.js
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/schema/NewsItemScope.test.js
  apps/condo/domains/news/utils/clientSchema/NewsItemScope.ts
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4324 Chore/condo/doma 8027/marketplace connecting for existing contexts
  apps/condo/domains/acquiring/access/AcquiringIntegrationContext.js
  apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.test.js
Labels: ✋🙂 Review please

#4310 refactor(condo): DOMA-8030 remove AssigneeScope schema
  apps/condo/bin/fix-database-migration-state.js
  apps/condo/domains/scope/access/AssigneeScope.js
  apps/condo/domains/scope/schema/AssigneeScope.js
  apps/condo/domains/scope/schema/AssigneeScope.test.js
  apps/condo/domains/scope/schema/index.js
  apps/condo/domains/scope/utils/clientSchema/AssigneeScope.ts
  apps/condo/domains/scope/utils/clientSchema/index.ts
  apps/condo/domains/scope/utils/serverSchema/index.js
  apps/condo/domains/scope/utils/testSchema/index.js
  apps/condo/domains/ticket/schema/Ticket.js
  apps/condo/migrations/20240129102851-0363_auto_20240129_0528.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4334 feat(condo): DOMA-8272 Use Promise.all for requests to dadata
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
Labels: 👶 small, ✋🙂 Review please

#4328 fix(condo): DOMA-8302 updated list of exceptions for profanity filter
  apps/condo/domains/news/utils/serverSchema/badWords.js
Labels: 👶 small, ✋🙂 Review please

#4332 feat(keystone): INFRA-261 Shorten service user sessions 👨‍⚕️
  packages/apollo-server-client/index.js
  packages/keystone/KSv5v6/v5/prepareKeystone.js
Labels: 👶 small, ✋🙂 Review please

#4335 feat(condo): DOMA-8295 mutation to delete meter readings
  apps/condo/domains/meter/access/_internalDeleteMeterReadingsService.js
  apps/condo/domains/meter/constants/constants.js
  apps/condo/domains/meter/constants/errors.js
  apps/condo/domains/meter/gql.js
  apps/condo/domains/meter/schema/_internalDeleteMeterAndMeterReadingsService.js
  apps/condo/domains/meter/schema/_internalDeleteMeterAndMeterReadingsService.test.js
  apps/condo/domains/meter/schema/_internalDeleteMeterReadingsService.js
  apps/condo/domains/meter/schema/_internalDeleteMeterReadingsService.test.js
  apps/condo/domains/meter/schema/index.js
  apps/condo/domains/meter/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4074 refactor(condo): DOMA-7654 moved server user accesses for b2b apps from plugin to schemas accesses
  apps/condo/domains/contact/access/Contact.js
  apps/condo/domains/contact/schema/Contact.js
  apps/condo/domains/meter/access/Meter.js
  apps/condo/domains/meter/access/MeterReading.js
  apps/condo/domains/meter/schema/Meter.js
  apps/condo/domains/meter/schema/MeterReading.js
  apps/condo/domains/miniapp/constants.js
  apps/condo/domains/miniapp/gql.js
  apps/condo/domains/miniapp/schema/B2BAppAccessRightSet.js
  apps/condo/domains/miniapp/schema/B2BAppAccessRightSet.test.js
  apps/condo/domains/miniapp/schema/plugins/serviceUserAccessForB2BApp.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/README.md
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/config.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/helpers.utils.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/helpers.utils.spec.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/index.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/schema.utils.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/schema.utils.spec.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/server.utils.js
  apps/condo/domains/miniapp/utils/serverSchema/generatePermissionFields.spec.js
  apps/condo/domains/organization/access/Organization.js
  apps/condo/domains/organization/schema/Organization.js
  apps/condo/domains/property/access/Property.js
  apps/condo/domains/property/schema/Property.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  packages/keystone/test.utils.js
Labels: ✋🙂 Review please
