Repository open-condo-software/condo, pull requests merged in 2024-03, with the labels that each got.

#4391 feat(condo): DOMA-8441 Reuse opened connection to send a batch of VOIP pushes & use RedisGuard to prevent opening multiple connection with APNS
  apps/condo/domains/notification/adapters/apple/AppleMessaging.js
  apps/condo/domains/notification/adapters/apple/AppleSession.js
  apps/condo/domains/user/utils/serverSchema/guards.js
Labels: ✋🙂 Review please

#4440 feature(condo): Doma-8542 register billing receipt file mutation
  apps/condo/domains/billing/access/RegisterBillingReceiptFileService.js
  apps/condo/domains/billing/constants.js
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptFileService.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptFileService.test.js
  apps/condo/domains/billing/schema/index.js
  apps/condo/domains/billing/utils/serverSchema/index.js
  apps/condo/domains/billing/utils/testSchema/index.js
  apps/condo/domains/billing/utils/testSchema/utils.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4441 fix(condo): DOMA-8542 fixed case when billingReceiptFile was soft deleted
  apps/condo/domains/billing/schema/RegisterBillingReceiptFileService.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptFileService.test.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4439 fix(condo): DOMA-8545 fix employee with same email or phone existing validation
  apps/condo/domains/organization/components/EmployeeForm/CreateEmployeeForm.tsx
  apps/condo/domains/organization/components/EmployeeForm/UpdateEmployeeForm.tsx
  apps/condo/domains/organization/constants/errors.js
  apps/condo/domains/organization/hooks/useEmployeeValidations.ts
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.js
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.test.js
  apps/condo/domains/organization/schema/OrganizationEmployee.js
  apps/condo/domains/organization/schema/OrganizationEmployee.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4443 feat(dev-portal): INFRA-263 Send password on email when registering service user
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/user/schema/RegisterNewServiceUserService.js
  apps/condo/domains/user/schema/RegisterNewServiceUserService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/SERVICE_USER_CREATED/email.njk
  apps/condo/lang/ru/messages/SERVICE_USER_CREATED/email.njk
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240304133206-0371_alter_notificationanonymoussetting_messagetype_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#4449 chore(deps): DOMA-6771 bump rc-picker from 2.6.10 to 4.2.0
  apps/condo/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😵‍💫 dependencies

#4444 feat(address-service): DOMA-8491 lowercase AddressSource.source
  apps/address-service/domains/address/schema/Address.test.js
  apps/address-service/domains/address/schema/AddressSource.js
  apps/address-service/domains/address/schema/AddressSource.test.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchBySource.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchBySource.spec.js
  apps/address-service/migrations/20230216132102-0004_manual_lowercase_address_source.js
Labels: 👶 small, ✋🙂 Review please

#4448 fix(condo): DOMA-7177 fixed settings of ticket visibility
  apps/condo/domains/common/components/GraphQlSearchInput/GraphQlSearchInput.tsx
  apps/condo/domains/common/components/GraphQlSearchInputWithCheckAll.tsx
Labels: 👶 small, ✋🙂 Review please

#4447 feat(condo): DOMA-8417 updated notifications to telegram
  apps/condo/domains/notification/constants/constants.js
  apps/condo/domains/ticket/tasks/sendTicketCommentCreatedNotifications.js
  apps/condo/domains/ticket/tasks/sendTicketCommentCreatedNotifications.spec.js
  apps/condo/domains/ticket/tasks/sendTicketCreatedNotifications.js
  apps/condo/domains/ticket/tasks/sendTicketCreatedNotifications.spec.js
  apps/condo/domains/ticket/utils/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/en/messages/TICKET_COMMENT_CREATED/telegram.html.njk
  apps/condo/lang/en/messages/TICKET_CREATED/telegram.html.njk
  apps/condo/lang/ru/messages/TICKET_COMMENT_CREATED/telegram.html.njk
  apps/condo/lang/ru/messages/TICKET_CREATED/telegram.html.njk
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4454 hotfix(condo): HOTFIX fixed throw chaptcha error if disabled feature flag
  apps/condo/domains/user/utils/googleRecaptcha3.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4453 feat(condo): DOMA-7635 updated bad words exclusions
  apps/condo/domains/news/constants/badWordsExclusions.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/utils/serverSchema/badWords.js
  apps/condo/domains/news/utils/serverSchema/badWords.spec.js
Labels: 👶 small, ✋🙂 Review please

#4456 chore(condo): DOMA-8229 added try/catch for "notifyResidentsAboutNewsItem" task
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
  apps/condo/domains/resident/tasks/discoverServiceConsumers.task.js
Labels: 👶 small, ✋🙂 Review please

#4457 fix(condo): DOMA-8607 show ticket create button on empty ticket view
  apps/condo/domains/common/components/EmptyListContent.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4469 hotfix(condo): DOMA-8484 updated captcha error message for users
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4470 fix(condo): added support for null offsetting account
  apps/condo/domains/billing/access/BillingRecipient.js
  apps/condo/domains/billing/schema/resolvers/propertyResolver.js
  apps/condo/domains/billing/schema/resolvers/recipientResolver.js
  packages/clients/address-service-client/utils/parseAddressesFromString.js
  packages/clients/address-service-client/utils/parseAddressesFromString.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4461 feat(address-service): DOMA-8493 Search strategies were added
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
  apps/address-service/domains/common/utils/services/search/strategies/AbstractBulkSearchStrategy.js
  apps/address-service/domains/common/utils/services/search/strategies/StrategyAllItemsToEachPlugin.js
  apps/address-service/domains/common/utils/services/search/strategies/StrategyEachItemToPlugins.js
  apps/address-service/domains/common/utils/services/search/strategies/constants.js
  apps/address-service/domains/common/utils/services/search/strategies/index.js
  apps/address-service/domains/common/utils/services/search/strategies/strategies.spec.js
Labels: ✋🙂 Review please

#4460 fix(condo): DOMA-6732 fixed default values for unitType and sectionType
  apps/condo/domains/common/schema/fields.js
  apps/condo/domains/common/utils/serverSchema/resolveHelpers.js
  apps/condo/domains/contact/schema/Contact.js
  apps/condo/domains/contact/schema/Contact.test.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
  apps/condo/domains/meter/schema/Meter.js
  apps/condo/domains/meter/schema/Meter.test.js
  apps/condo/domains/news/schema/NewsItemScope.js
  apps/condo/domains/news/schema/NewsItemScope.test.js
  apps/condo/domains/resident/schema/Resident.js
  apps/condo/domains/resident/schema/Resident.test.js
  apps/condo/domains/ticket/schema/Ticket.js
  apps/condo/domains/ticket/schema/Ticket.test.js
  apps/condo/migrations/20240307165344-0372_auto_20240307_1153.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4473 fix(condo): DOMA-8643 add org type filter to resident property
  apps/condo/domains/resident/schema/RegisterResidentService.js
  condo.tests.Dockerfile
Labels: 👶 small, ✋🙂 Review please

#4472 feat(condo): INFRA-284 Service user direct read email access
  apps/condo/domains/user/access/User.js
  apps/condo/domains/user/schema/User.test.js
  apps/condo/domains/user/schema/UserRightsSet.test.js
  apps/condo/domains/user/utils/directAccess/common.utils.js
  apps/condo/domains/user/utils/directAccess/config.js
  apps/condo/domains/user/utils/directAccess/directAccess.spec.js
  apps/condo/domains/user/utils/directAccess/index.js
  apps/condo/domains/user/utils/directAccess/server.utils.js
  apps/condo/migrations/20240315111040-0374_userrightsset_canreaduseremailfield_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  apps/dev-api/bin/prepare.js
Labels: 👶 small, ✋🙂 Review please

#4482 feat(condo): DOMA-8639 was passed some cookies (locale) in stitchSchema
  apps/condo/lang/en/en.json
  packages/keystone/package.json
  packages/keystone/stitchSchema.js
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 📦 Packages

#4480 feat(condo): INFRA-287 add importable plugin to B2CAppAccessRight
  apps/condo/domains/miniapp/schema/B2CAppAccessRight.js
  apps/condo/migrations/20240318020135-0375_b2cappaccessright_importid_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#4485 hotfix(condo): add logging response for request transactions from sbbol
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4493 fix(condo): DOMA-8660 fixed news loading
  apps/condo/pages/news/index.tsx
Labels: 👶 small, ✋🙂 Review please

#4497 fix(address-service): DOMA-8640 change plugins order
  apps/address-service/bin/update-address.js
  apps/address-service/domains/common/utils/services/search/searchServiceUtils.js
  apps/address-service/index.js
Labels: 👶 small, ✋🙂 Review please

#4491 feat(condo): DOMA-8651 moved sending ticket notifications from schema hooks to a task
  apps/condo/domains/ticket/schema/Ticket.js
  apps/condo/domains/ticket/schema/Ticket.test.js
  apps/condo/domains/ticket/tasks/index.js
  apps/condo/domains/ticket/tasks/sendTicketChangedNotifications.js
  apps/condo/domains/ticket/utils/handlers.js
Labels: ✋🙂 Review please

#4507 fix(condo): DOMA-8646 try to fix random failing of the test
  apps/condo/domains/news/schema/NewsItem.test.js
Labels: 👶 small, ✋🙂 Review please

#4508 hotfix(condo): DOMA-8651 fixed imports
  apps/condo/domains/ticket/tasks/index.js
  apps/condo/domains/ticket/tasks/sendTicketChangedNotifications.js
  apps/condo/domains/ticket/tasks/sendTicketCreatedNotifications.js
  apps/condo/domains/ticket/tasks/sendTicketCreatedNotifications.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4511 feature(condo): Doma-8682 create last report in unified mutation
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
  apps/condo/domains/billing/schema/resolvers/utils.js
  packages/clients/finance-info-client/index.js
Labels: 👶 small, ✋🙂 Review please

#4522 feat(dev-portal): INFRA-288 Service user section 👤
  apps/dev-portal/domains/common/components/Spin.module.css
  apps/dev-portal/domains/common/components/Spin.tsx
  apps/dev-portal/domains/common/components/auth/registration/CodeInputStep.tsx
  apps/dev-portal/domains/common/hooks/useMutationErrorHandler.ts
  apps/dev-portal/domains/common/hooks/useValidations.ts
  apps/dev-portal/domains/miniapp/components/B2CApp/edit/publishing/RequestStatusInfo.module.css
  apps/dev-portal/domains/miniapp/components/B2CApp/edit/publishing/RequestStatusInfo.tsx
  apps/dev-portal/domains/miniapp/components/B2CApp/edit/service-user/ServiceUserSection.tsx
  apps/dev-portal/domains/miniapp/components/OIDC/edit/ClientSettingsSubsection.module.css
  apps/dev-portal/domains/miniapp/components/OIDC/edit/ClientSettingsSubsection.tsx
  apps/dev-portal/domains/miniapp/components/User/edit/EditUserForm.tsx
  apps/dev-portal/domains/miniapp/components/User/edit/RegisterUserForm.tsx
  apps/dev-portal/domains/miniapp/components/User/edit/RegisterUserModal/CodeInputStep.module.css
  apps/dev-portal/domains/miniapp/components/User/edit/RegisterUserModal/CodeInputStep.tsx
  apps/dev-portal/domains/miniapp/components/User/edit/RegisterUserModal/EmailInputStep.tsx
  apps/dev-portal/domains/miniapp/components/User/edit/RegisterUserModal/index.tsx
  apps/dev-portal/domains/miniapp/hooks/useB2CMenuItems.tsx
  apps/dev-portal/lang/en.json
  apps/dev-portal/lang/ru.json
  apps/dev-portal/lib/gql/index.ts
  apps/dev-portal/lib/gql/miniapp/b2c.graphql
  apps/dev-portal/lib/gql/miniapp/serviceUser.graphql
  apps/dev-portal/pages/apps/b2c/[id].tsx
Labels: ✋🙂 Review please, 😎 Cool

#4527 fix(condo): DOMA-8705 added orgId to marketplace payments filter
  apps/condo/domains/marketplace/components/MarketplacePaymentsContent.tsx
Labels: 👶 small, ✋🙂 Review please

#4533 feat(dev-portal): INFRA-243 stricter icon requirements
  apps/dev-portal/domains/miniapp/components/B2CApp/edit/info/B2CAppCard.module.css
  apps/dev-portal/domains/miniapp/components/B2CApp/edit/info/B2CAppCard.tsx
  apps/dev-portal/domains/miniapp/components/B2CApp/edit/info/IconsSubsection.module.css
  apps/dev-portal/domains/miniapp/components/B2CApp/edit/info/IconsSubsection.tsx
  apps/dev-portal/domains/miniapp/components/InlineAppCard.module.css
  apps/dev-portal/domains/miniapp/components/InlineAppCard.tsx
  apps/dev-portal/domains/miniapp/components/RecentAppsPopover.module.css
  apps/dev-portal/domains/miniapp/components/RecentAppsPopover.tsx
  apps/dev-portal/domains/miniapp/constants/common.ts
  apps/dev-portal/domains/miniapp/hooks/useFileValidator.ts
  apps/dev-portal/lang/en.json
  apps/dev-portal/lang/ru.json
  apps/dev-portal/public/icons/b2c.png
Labels: 👶 small, ✋🙂 Review please

#4539 fix(condo): DOMA-8653 fixed table filters
  apps/condo/domains/common/components/Table/Index.tsx
Labels: 👶 small, ✋🙂 Review please

#4541 fix(condo): DOMA-8641 fixed deleting of assignee
  apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
  apps/condo/domains/ticket/utils/clientSchema/Ticket.ts
Labels: 👶 small, ✋🙂 Review please

#4542 fix(condo): DOMA-8710 added placeholder for organization select
  apps/condo/domains/organization/components/OrganizationSelect.tsx
Labels: 👶 small, ✋🙂 Review please

#4543 fix(condo): DOMA-8680 fixed saving of hints
  apps/condo/domains/ticket/components/TicketPropertyHint/UpdateTicketPropertyHintForm.tsx
Labels: 👶 small, ✋🙂 Review please

#4545 fix(condo): DOMA-8713 fixed author in comment component if user is deleted
  apps/condo/domains/common/components/Comments/Comment.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4546 fix(condo): DOMA-8737 fix complete step modal after news create
  apps/condo/domains/onboarding/hooks/TourContext/useCompletedTourModals.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4501 refactor(condo): DOMA-6931 refactored news sending
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.js
  apps/condo/domains/news/schema/NewsItem.test.js
  apps/condo/domains/news/schema/NewsItemScope.test.js
  apps/condo/domains/news/tasks/index.js
  apps/condo/domains/news/tasks/notifyResidentsAboutDelayedNewsItems.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.helpers.spec.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.spec.js
  apps/condo/domains/news/utils/clientSchema/NewsRenders.tsx
  apps/condo/domains/news/utils/index.js
  apps/condo/domains/ticket/tasks/sendTicketCreatedNotifications.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240327215510-0377_auto_20240327_1655.js
  apps/condo/pages/news/[id]/index.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations
