Repository open-condo-software/condo, pull requests merged in 2024-07, with the labels that each got.

#4901 hotfix(condo): DOMA-9348 fixed run of task
  apps/condo/domains/common/components/tasks/TaskLauncher.ts
  apps/condo/domains/ticket/hooks/useTicketDocumentGenerationTask.tsx
Labels: 👶 small, ✋🙂 Review please

#4898 fix(condo): DOMA-9362 fixed currency code for ruble in sbbol integration
  apps/condo/domains/common/constants/currencies.js
  apps/condo/domains/organization/integrations/sbbol/constants.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncBankAccounts.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncBankAccounts.spec.js
  apps/condo/migrations/20240629210933-0406_auto_20240629_1609.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#4903 fix(condo): DOMA-9471 fixed sending time of daily statistics email
  apps/condo/domains/analytics/tasks/sendDailyStatistics.js
Labels: 👶 small, ✋🙂 Review please

#4909 fix(condo): DOMA-9515 fixed send daily statistics task launch
  apps/condo/domains/analytics/tasks/helpers/sendDailyStatistics.js
  apps/condo/domains/analytics/tasks/sendDailyStatistics.js
Labels: 👶 small, ✋🙂 Review please

#4908 hotfix: bump trim package version to the latest safe version
  package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😵‍💫 dependencies

#4890 feat(condo): Doma-9045 find organizations for address
  apps/condo/domains/billing/constants/constants.js
  apps/condo/domains/billing/utils/serverSchema/checkAccountNumberWithOnlineInteractionUrl.js
  apps/condo/domains/billing/utils/testSchema/mixins/property.js
  apps/condo/domains/resident/access/FindOrganizationsForAddressService.js
  apps/condo/domains/resident/constants/constants.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/schema/FindOrganizationsForAddressService.js
  apps/condo/domains/resident/schema/FindOrganizationsForAddressService.test.js
  apps/condo/domains/resident/schema/index.js
  apps/condo/domains/resident/utils/serverSchema/findOrganizationsForAddress.js
  apps/condo/domains/resident/utils/serverSchema/index.js
  apps/condo/domains/resident/utils/testSchema/index.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#4883 fix(global): INFRA-348 run test dbs as docker compose services
  .github/workflows/_nodejs.condo.core.tests.yml
  docker-compose.yml
  werf.yaml
Labels: 👶 small, ✋🙂 Review please, infrastructure

#4921 fix(condo): DOMA-9558 fixed timezone for telegram notifications
  apps/condo/domains/ticket/tasks/sendTicketCommentCreatedNotifications.js
  apps/condo/domains/ticket/tasks/sendTicketCommentCreatedNotifications.spec.js
  apps/condo/domains/ticket/tasks/sendTicketCreatedNotifications.js
  apps/condo/domains/ticket/tasks/sendTicketCreatedNotifications.spec.js
Labels: 👶 small, ✋🙂 Review please

#4927 feat(condo): DOMA-9539 add new meter resource and translations
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240704212810-0407_manual_insert_meter_resource.js
Labels: 👶 small, 🚨 Migrations

#4917 feat(condo): DOMA-9367 added ServiceProblemsAlert component
  apps/condo/domains/common/components/LayoutContext.tsx
  apps/condo/domains/common/components/ServiceProblemsAlert.tsx
  apps/condo/domains/common/components/TopNotifications.tsx
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/pages/_app.tsx
  packages/ui/src/components/Alert/alert.tsx
  packages/ui/src/components/Alert/style.less
Labels: ✋🙂 Review please

#4934 feat(condo): DOMA-9591 migrate from AddressMeta in RegisterResident
  apps/condo/domains/resident/constants/errors.js
  apps/condo/domains/resident/schema/RegisterResidentService.js
  apps/condo/domains/resident/schema/RegisterResidentService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please

#4953 hotfix(condo): DOMA-9645 fixed sending of news items
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4952 fix(condo): DOMA-9293 allow to create map with same unitName and different unitType
  apps/condo/domains/property/components/BasePropertyMapForm/index.tsx
  apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
  apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
  apps/condo/domains/property/components/panels/Builder/forms/UnitForm.tsx
  apps/condo/domains/property/utils/helpers.ts
Labels: 👶 small, ✋🙂 Review please

#4951 fix(condo): DOMA-9620 meter section bug fixes
  apps/condo/domains/meter/components/CreateMeterReadingsForm.tsx
  apps/condo/domains/meter/components/Meters/ActionBarForSingleMeter.tsx
  apps/condo/domains/meter/components/Meters/BaseMetersFormFields.tsx
  apps/condo/domains/meter/components/Meters/CreateMeterForm.tsx
  apps/condo/domains/meter/components/TabContent/Meter.tsx
  apps/condo/domains/meter/components/TabContent/MeterReading.tsx
  apps/condo/domains/meter/components/TabContent/PropertyMeterReading.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4956 fix(condo): DOMA-9619 fixed generation of bank account reports
  apps/condo/domains/banking/schema/BankAccountReportTask.test.js
  apps/condo/domains/banking/tasks/generateReports.js
  apps/condo/domains/banking/utils/testSchema/bankAccount.js
  apps/condo/domains/banking/utils/testSchema/index.js
Labels: ✋🙂 Review please

#4967 feat(condo): DOMA-9697 Meter reports periods support Service Providers ⏲️📟
  apps/condo/domains/meter/access/MeterReportingPeriod.js
  apps/condo/domains/meter/schema/MeterReportingPeriod.test.js
  apps/condo/domains/meter/utils/serverSchema/index.js
  apps/condo/domains/resident/gql.js
Labels: 👶 small, ✋🙂 Review please

#4961 hotfix: update knex dependency to resolve security warning
  package.json
  yarn.lock
Labels: 😵‍💫 dependencies

#4972 chore(condo): DOMA-9658 allow import the resource named "cold air"
  apps/condo/domains/meter/constants/constants.js
  apps/condo/domains/meter/utils/taskSchema/importerResolver.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#4973 chore(condo): DOMA-8628 drainage - the new resource type
  apps/condo/domains/meter/constants/constants.js
  apps/condo/domains/meter/utils/taskSchema/importerResolver.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240718061300-0409_manual_insert_meter_resource.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#4975 fix(condo): DOMA-9622 print localized errors to the result file after meters import finished
  apps/condo/domains/meter/utils/taskSchema/AbstractMetersImporter.js
Labels: 👶 small, ✋🙂 Review please

#4974 chore(condo): DOMA-9706 restrict to create meter reading with date fr…
  apps/condo/domains/meter/constants/errors.js
  apps/condo/domains/meter/schema/MeterReading.js
  apps/condo/domains/meter/schema/MeterReading.test.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#4978 fix(condo): DOMA-9717 prohibit direct password update by user
  apps/condo/domains/user/access/User.js
  apps/condo/domains/user/schema/User.test.js
Labels: 👶 small, ✋🙂 Review please

#4981 fix(condo): DOMA-9732 add single error processing for meters importer
  apps/condo/domains/meter/utils/taskSchema/AbstractMetersImporter.js
Labels: 👶 small, ✋🙂 Review please

#4984 fix(condo): DOMA-9737 fixed context for getting of feature flag in task of close completed tickets
  apps/condo/domains/ticket/tasks/closeCompletedTickets.js
Labels: 👶 small, ✋🙂 Review please

#5001 fix(condo): Added missing csv-parse package
  apps/condo/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 📦 Packages

#4987 feat(condo): DOMA-9739 disabling notifications for specific appIds
  apps/condo/domains/notification/adapters/appleAdapter.js
  apps/condo/domains/notification/adapters/appleAdapter.spec.js
  apps/condo/domains/notification/adapters/firebaseAdapter.js
  apps/condo/domains/notification/adapters/firebaseAdapter.spec.js
  apps/condo/domains/notification/adapters/hcmAdapter.js
  apps/condo/domains/notification/constants/constants.js
Labels: 🔥 HOTFIX

#4982 feat(condo): DOMA-8525 allow to restrict send meter readings
  apps/condo/domains/meter/constants/errors.js
  apps/condo/domains/meter/schema/Meter.js
  apps/condo/domains/meter/schema/Meter.test.js
  apps/condo/domains/meter/schema/PropertyMeter.js
  apps/condo/domains/meter/schema/PropertyMeter.test.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
  apps/condo/domains/meter/tasks/importMeters.spec.js
  apps/condo/domains/meter/utils/taskSchema/DomaMetersImporter.js
  apps/condo/domains/meter/utils/taskSchema/DomaMetersImporter.spec.js
  apps/condo/domains/meter/utils/taskSchema/importerResolver.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/public/import/meter/en/meter-import-example.xlsx
  apps/condo/public/import/meter/ru/meter-import-example.xlsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#5017 fix(condo): DOMA-9780 fix translations so that mob app could take translations directly from the entity
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please

#5013 hotfix: fix holdings invite tests
  apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.test.js
  bin/prepare.js
  packages/cli/index.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#5020 feat(condo): INFRA-401 extend UserRightsSet to support MessageBatch 📩
  apps/condo/domains/notification/access/MessageBatch.js
  apps/condo/domains/notification/schema/MessageBatch.test.js
  apps/condo/domains/user/utils/directAccess/config.js
  apps/condo/migrations/20240726151836-0411_userrightsset_canmanagemessagebatches_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#5022 fix(condo): DOMA-9806 fixed generate reports of property. And fixed task launcher
  apps/condo/domains/banking/tasks/generateReports.js
  apps/condo/domains/common/components/tasks/TaskProgress.tsx
Labels: 👶 small, ✋🙂 Review please

#5023 fix(condo): DOMA-9806 fixed importing of transactions
  apps/condo/domains/organization/integrations/sbbol/sync/MockSbbolResponses.js
  apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
Labels: 👶 small, ✋🙂 Review please

#5004 feat(condo): DOMA-9715 added checkUserExistence query
  apps/condo/domains/common/constants/errors.js
  apps/condo/domains/user/access/CheckUserExistenceService.js
  apps/condo/domains/user/constants/common.js
  apps/condo/domains/user/constants/errors.js
  apps/condo/domains/user/gql.js
  apps/condo/domains/user/schema/AuthenticateUserWithPhoneAndPasswordService.test.js
  apps/condo/domains/user/schema/CheckUserExistenceService.js
  apps/condo/domains/user/schema/CheckUserExistenceService.test.js
  apps/condo/domains/user/schema/RegisterNewServiceUserService.test.js
  apps/condo/domains/user/schema/RegisterNewUserService.test.js
  apps/condo/domains/user/schema/index.js
  apps/condo/domains/user/utils/serverSchema/index.js
  apps/condo/domains/user/utils/serverSchema/requestLimitHelpers.js
  apps/condo/domains/user/utils/testSchema/index.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please

#5031 refactor(condo): DOMA-9823 expand resident property access
  apps/condo/domains/property/access/Property.js
  apps/condo/domains/property/schema/Property.test.js
Labels: 👶 small, ✋🙂 Review please

#5039 feat(condo): DOMA-9800 create B2CAppMessageSetting to manage B2CApp notification throttling and blocking
  apps/condo/domains/miniapp/access/B2CAppMessageSetting.js
  apps/condo/domains/miniapp/gql.js
  apps/condo/domains/miniapp/schema/B2CAppMessageSetting.js
  apps/condo/domains/miniapp/schema/B2CAppMessageSetting.test.js
  apps/condo/domains/miniapp/schema/MessageAppBlackList.js
  apps/condo/domains/miniapp/schema/SendB2CAppPushMessageService.js
  apps/condo/domains/miniapp/schema/SendB2CAppPushMessageService.test.js
  apps/condo/domains/miniapp/schema/index.js
  apps/condo/domains/miniapp/utils/clientSchema/B2CAppMessageSetting.ts
  apps/condo/domains/miniapp/utils/clientSchema/index.ts
  apps/condo/domains/miniapp/utils/serverSchema/index.js
  apps/condo/domains/miniapp/utils/testSchema/index.js
  apps/condo/migrations/20240731050100-0414_b2cappmessagesettinghistoryrecord_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🚨 Migrations
