Repository open-condo-software/condo, pull requests merged in 2024-08, with the labels that each got.

#5038 refactor(condo): DOMA-8306 refactored mutation "getNewsItemsRecipientsCounters"
  apps/condo/domains/news/constants/common.js
  apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.js
  apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.test.js
  apps/condo/domains/news/utils/serverSchema/recipientsCounterUtils.js
Labels: ✋🙂 Review please

#5054 feat(condo): DOMA-9868 temporary ability to create heap snapshots
  packages/keystone/KSv5v6/v5/prepareKeystone.js
Labels: 👶 small, ✋🙂 Review please

#5056 fix(condo): DOMA-9870 fix scopes shape before pass to queryFindReside…
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#5058 chore(resident-app): INFRA-414 pre-main warmup 👹
  .github/workflows/deploy_development.yaml
  .github/workflows/nodejs.condo.ci.yml
  .github/workflows/nodejs.condo.k6.yml
  .github/workflows/packages.release.yml
  .github/workflows/packages.ui.sync-baseline.yml
Labels: 👶 small, ✋🙂 Review please

#5029 fix(condo): DOMA-9763 fixed billing files load
  apps/condo/domains/billing/components/BillingPageContent/ServicesModal.tsx
  apps/condo/domains/billing/gql.js
Labels: 👶 small, ✋🙂 Review please

#5066 fix(condo): DOMA-9895 fix config for service user
  apps/condo/domains/miniapp/schema/B2BAppAccessRightSet.test.js
  apps/condo/domains/miniapp/utils/b2bAppServiceUserAccess/config.js
Labels: ✋🙂 Review please

#5041 feat (condo): DOMA-7247 DOMA-9811 DOMA-9824 qr-codes improvements
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.test.js
  apps/condo/domains/billing/utils/countrySpecificQRCodeParsers/index.js
  apps/condo/domains/billing/utils/countrySpecificQRCodeParsers/ru.qrCodeParser.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.spec.js
Labels: ✋🙂 Review please

#5069 chore: INFRA-414 update doc links
  apps/dev-portal/.env.example
  apps/dev-portal/docs/api/playground.en.mdx
  apps/dev-portal/docs/api/playground.ru.mdx
  apps/dev-portal/domains/common/constants/buildVars.ts
Labels: 👶 small, ✋🙂 Review please

#5071 fix(condo): DOMA-9902 fix canSumPayments access for directAccess
  apps/condo/domains/acquiring/access/SumPaymentsService.js
  apps/condo/domains/acquiring/schema/SumPaymentsService.test.js
  apps/condo/domains/billing/schema/SumBillingReceiptsService.test.js
Labels: 👶 small, ✋🙂 Review please

#5076 fix(condo): DOMA-9287 use math ceil instead math floor for unitsOnFloor
  apps/condo/domains/property/hooks/useImporterFunctions.tsx
Labels: 👶 small, ✋🙂 Review please

#5079 refactor(condo): DOMA-9907 allow residents to read mobile configs via consumers 🔎
  apps/condo/domains/settings/access/MobileFeatureConfig.js
  apps/condo/domains/settings/schema/MobileFeatureConfig.test.js
Labels: 👶 small, ✋🙂 Review please

#5080 feat(condo): DOMA-9839 update qr for technic app
  apps/condo/public/onboarding/technic-app-card/qr-technic-app/AppStore.svg
Labels: 👶 small, ✋🙂 Review please

#5081 chore(condo): DOMA-9803 try to monitor memory usage during lifetime
  apps/condo/index.js
  packages/keystone/KSv5v6/v5/prepareKeystone.js
  packages/keystone/memMon/plugin.js
  packages/keystone/memMon/utils.js
Labels: ✋🙂 Review please

#5085 chore(condo): DOMA-9803 improve memory monitoring
  apps/condo/index.js
  packages/keystone/memMon/plugin.js
Labels: 👶 small, ✋🙂 Review please

#5067 fix(condo): DOMA-9881 test to prevent notifications with three dots
  apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.spec.js
Labels: 👶 small, ✋🙂 Review please

#5018 feat(keystone): DOMA-9790 added extended auth strategy for a specific condo apps logic
  apps/condo/domains/user/gql.js
  apps/condo/domains/user/schema/ChangePhoneNumberResidentUserService.test.js
  apps/condo/domains/user/schema/User.test.js
  packages/keystone/KSv5v6/v5/prepareKeystone.js
  packages/keystone/authStrategy/passwordAuth.js
  packages/keystone/test.utils.js
Labels: ✋🙂 Review please, 📦 Packages

#5104 refactor(address-service): DOMA-9952 move to prepareKeystone
  apps/address-service/babel.config.js
  apps/address-service/domains/common/utils/services/search/strategies/strategies.spec.js
  apps/address-service/index.js
Labels: ✋🙂 Review please

#5074 fix(condo): DOMA-9899 keep deeplink when changing sign in to register
  apps/condo/domains/common/components/HeaderActions.tsx
  apps/condo/domains/user/components/auth/InputPhoneForm.tsx
  apps/condo/domains/user/components/auth/SignInForm.tsx
  apps/condo/pages/auth/signin.tsx
Labels: ✋🙂 Review please

#4966 feat(condo): INFRA-379 add cache for access of the resident and service consumer
  apps/condo/domains/banking/access/BankAccount.js
  apps/condo/domains/banking/access/BankAccountReport.js
  apps/condo/domains/billing/access/BillingReceipt.js
  apps/condo/domains/marketplace/access/MarketItem.js
  apps/condo/domains/marketplace/access/MarketItemFile.js
  apps/condo/domains/marketplace/access/MarketItemPrice.js
  apps/condo/domains/marketplace/access/MarketPriceScope.js
  apps/condo/domains/news/access/NewsItem.js
  apps/condo/domains/news/access/NewsItemUserRead.js
  apps/condo/domains/organization/access/Organization.js
  apps/condo/domains/property/access/Property.js
  apps/condo/domains/resident/schema/RegisterResidentService.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
  apps/condo/domains/resident/schema/Resident.js
  apps/condo/domains/resident/schema/ServiceConsumer.js
  apps/condo/domains/resident/utils/accessSchema.js
  apps/condo/domains/resident/utils/serverSchema/index.js
  apps/condo/domains/settings/access/MobileFeatureConfig.js
  apps/condo/domains/ticket/access/Ticket.js
  apps/condo/domains/ticket/access/TicketComment.js
Labels: 👶 small, ✋🙂 Review please

#5145 feat(condo): DOMA-10055 added timeouts to batch functions
  apps/condo/domains/common/utils/serverSchema/index.js
  packages/keystone/schema.js
Labels: 👶 small, ✋🙂 Review please

#5150 feat(keystone): DOMA-10066 set startReqId to tracing span if it exists in execution context
  packages/keystone/tracing.js
Labels: 👶 small, ✋🙂 Review please

#5121 fix(address-service): DOMA-10002 fix logging and provider name for go…
  apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
  apps/address-service/domains/common/utils/services/search/plugins/SearchByProvider.js
  apps/address-service/domains/common/utils/services/search/providers/GoogleSearchProvider.js
  apps/address-service/domains/common/utils/services/search/strategies/AbstractBulkSearchStrategy.js
Labels: 👶 small, ✋🙂 Review please
