Repository open-condo-software/condo, pull requests merged in 2024-10, with the labels that each got.

#5308 hotfix(codegen): hotfix useAllObjects
  packages/codegen/generate.hooks.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#5284 feat(condo): INFRA-524 optimise register meters
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
  apps/condo/k6/src/registerMetersReadings.test.ts
  apps/condo/k6/webpack.config.js
Labels: ✋🙂 Review please

#5338 hotfix(condo): fix e2e tests
  .github/workflows/_nodejs.condo.cypress.yml
Labels: 👶 small, ✋🙂 Review please

#5345 refactor(codegen): INFRA-583 updated server utils in templates of schema and apps
  packages/codegen/templates/app00/domains/user/utils/serverSchema/createOrUpdateUser.js
  packages/codegen/templates/app00/domains/user/utils/serverSchema/index.js
  packages/codegen/templates/app01/domains/user/utils/serverSchema/createOrUpdateUser.js
  packages/codegen/templates/app01/domains/user/utils/serverSchema/index.js
  packages/codegen/templates/schema00/domains/{{domain}}/utils/serverSchema/index.js.patch
Labels: 👶 small, ✋🙂 Review please

#5356 fix(condo): DOMA-5381 fixed layout rendering
  apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#5361 hotfix(miniapp): fix miniapp app error
  .gitignore
  apps/miniapp/condoSchema.graphql
  apps/miniapp/condoSchema.ts
  apps/miniapp/schema.graphql
Labels: 🔥 HOTFIX, ✋🙂 Review please

#5368 feat(condo): DOMA-10496 fill raw address in payment
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/schema/Payment.js
  apps/condo/domains/acquiring/schema/Payment.test.js
Labels: 👶 small, ✋🙂 Review please

#5374 refactor(condo): INFRA-576 update condo domains server utils
  apps/condo/bin/delete-contacts-by-organization-id.js
  apps/condo/bin/delete-meter-readings-by-properties.js
  apps/condo/bin/delete-meters-by-property-ids.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
  apps/condo/domains/billing/tasks/sendNewBillingReceiptFilesNotifications.js
  apps/condo/domains/common/utils/serverSchema/export.js
  apps/condo/domains/contact/schema/_internalSyncContactsWithResidentsForOrganizationService.js
  apps/condo/domains/contact/tasks/exportContacts.js
  apps/condo/domains/contact/utils/serverSchema/index.js
  apps/condo/domains/document/utils/serverSchema/index.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/MarketItem.js
  apps/condo/domains/marketplace/schema/MarketItemPrice.js
  apps/condo/domains/marketplace/schema/MarketPriceScope.js
  apps/condo/domains/marketplace/utils/serverSchema/index.js
  apps/condo/domains/meter/schema/ExportPropertyMeterReadingsService.js
  apps/condo/domains/meter/schema/Meter.js
  apps/condo/domains/meter/schema/MeterReading.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/schema/_internalDeleteMeterAndMeterReadingsService.js
  apps/condo/domains/meter/schema/_internalDeleteMeterReadingsService.js
  apps/condo/domains/meter/tasks/exportMeterReadings.js
  apps/condo/domains/meter/tasks/importMeters.js
  apps/condo/domains/meter/tasks/importMeters.spec.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.js
  apps/condo/domains/meter/tasks/sendVerificationDateReminder.js
  apps/condo/domains/meter/utils/serverSchema/index.js
  apps/condo/domains/meter/utils/taskSchema/importerResolver.js
  apps/condo/domains/resident/schema/RegisterResidentInvoiceService.js
  apps/condo/domains/ticket/schema/Ticket.js
  apps/condo/domains/ticket/tasks/exportIncidents.js
  apps/condo/domains/ticket/tasks/exportTickets.js
  apps/condo/domains/ticket/utils/serverSchema/TicketDocumentGeneration/completionWorks.js
  apps/condo/domains/ticket/utils/serverSchema/index.js
  apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
Labels: ✋🙂 Review please

#5357 fix(condo): INFRA-613 migrate to new k6 browser API
  .github/workflows/nodejs.condo.k6.yml
  apps/condo/k6/src/news.test.ts
  apps/condo/k6/src/registerBillingReceipt.test.ts
  apps/condo/k6/src/registerBillingReceiptFile.test.ts
  apps/condo/k6/src/ticket.test.ts
  apps/condo/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 😵‍💫 dependencies

#5379 hotfix: fix exportMeterReadings
  apps/condo/domains/meter/tasks/exportMeterReadings.js
Labels: 👶 small, 🔥 HOTFIX

#5241 feat(condo): DOMA-10204 builder for lastReport in billing context
  apps/condo/domains/billing/constants/constants.js
  apps/condo/domains/billing/gql.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
  apps/condo/domains/billing/schema/resolvers/utils.js
Labels: ✋🙂 Review please

#5380 chore (condo): DOMA-10452 improve error messages for meters
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/tasks/importMeters.spec.js
  apps/condo/domains/meter/utils/taskSchema/AbstractMetersImporter.js
  apps/condo/domains/meter/utils/taskSchema/importerResolver.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please

#5404 feat(condo): INFRA-635 run condo CI with async replication ⏳🐌
  docker-compose-postgresql-init-replication.sql
  docker-compose.yml
Labels: 👶 small, ✋🙂 Review please
