Repository open-condo-software/condo, pull requests merged in 2024-12, with the labels that each got.

#5558 fix(condo): DOMA-10614 do not send meter readings in mutation if date validation failed
  apps/condo/domains/meter/tasks/importMeters.spec.js
  apps/condo/domains/meter/utils/taskSchema/AbstractMetersImporter.js
  apps/condo/domains/meter/utils/taskSchema/AbstractMetersImporter.spec.js
  apps/condo/domains/meter/utils/taskSchema/importerResolver.js
Labels: ✋🙂 Review please

#5128 fix(condo): DOMA-8764 allow notify period end be smaller than start
  apps/condo/domains/meter/components/MeterReportingPeriodForm.tsx
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.js
  apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.spec.js
Labels: 👶 small

#5572 fix(condo): DOMA-10792 fix getPollTicketComments query
  apps/condo/domains/ticket/hooks/usePollTicketComments.tsx
  apps/condo/domains/ticket/queries/TicketComment.graphql
Labels: 👶 small, ✋🙂 Review please

#5577 deps(global): bump rollup to latest in packages ⏏️🆙
  packages/apollo/package.json
  packages/bridge/package.json
  packages/bridge/rollup.config.mjs
  packages/miniapp-utils/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 📦 Packages

#5581 fix(condo): INFRA-468 roll back skip pdf receipt update
  apps/condo/domains/billing/schema/BillingReceiptFile.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptFileService.js
  apps/condo/domains/billing/schema/RegisterBillingReceiptFileService.test.js
Labels: 👶 small, ✋🙂 Review please, 🐞 BUG

#5584 fix(condo): DOMA-9623 not set controlReadingsDate to current date
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
  apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
Labels: 👶 small, ✋🙂 Review please

#5593 fix(condo): DOMA-10792 fix ticket comments polling
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/ticket/hooks/usePollTicketComments.tsx
  apps/condo/domains/ticket/queries/TicketComment.graphql
  apps/condo/domains/ticket/queries/TicketCommentFile.graphql
  apps/condo/gql/index.ts
  apps/condo/gql/operation.types.ts
Labels: 👶 small, ✋🙂 Review please

#5596 ci(global): fix building order during release
  bin/publish-packages.js
  package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, infrastructure, 😎 Cool

#5640 refactor(global): INFRA-762 refactor log format in rate-limiting
  packages/keystone/rateLimiting/plugin.js
Labels: 👶 small, ✋🙂 Review please

#5642 refactor(global): INFRA-762 support batched request in rate-limit
  packages/keystone/rateLimiting/plugin.js
  packages/keystone/rateLimiting/request.utils.js
Labels: 👶 small, ✋🙂 Review please

#5647 feat(global): INFRA-763 add rate limiting headers 🛂
  packages/keystone/rateLimiting/plugin.js
  packages/keystone/rateLimiting/request.utils.js
Labels: 👶 small, ✋🙂 Review please, infrastructure

#5639 test(condo): test billing receipt b2b rights
  apps/condo/domains/miniapp/schema/B2BAppAccessRightSet.test.js
Labels: 👶 small, ✋🙂 Review please

#5663 feat(global): INFRA-776 add ability to increase quotas per IP / user in rate-limit
  packages/keystone/rateLimiting/config.utils.js
  packages/keystone/rateLimiting/config.utils.spec.js
  packages/keystone/rateLimiting/constants.js
  packages/keystone/rateLimiting/plugin.js
  packages/keystone/rateLimiting/request.utils.js
Labels: 👶 small, ✋🙂 Review please

#5653 fix(condo): DOMA-10909 add rate limit for AuthenticateUserWithPhoneAn…
  apps/condo/domains/user/constants/errors.js
  apps/condo/domains/user/schema/AuthenticateUserWithPhoneAndPasswordService.js
  apps/condo/domains/user/schema/AuthenticateUserWithPhoneAndPasswordService.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/es/es.json
  apps/condo/lang/ru/ru.json
Labels: ✋🙂 Review please
