Repository open-condo-software/condo, pull requests merged in 2024-02, with the labels that each got.

#4333 fix(dev-portal): INFRA-262 fix wrong pagination on build page
  apps/dev-portal/lib/gql/index.ts
  apps/dev-portal/lib/gql/miniapp.graphql
Labels: 👶 small, ✋🙂 Review please

#4346 fix(condo): DOMA-8284 fix sort options by order field
  apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
Labels: 👶 small, ✋🙂 Review please

#4345 hotfix(condo): DOMA-8350 fixed export of property meter readings
  apps/condo/domains/meter/schema/ExportPropertyMeterReadingsService.js
Labels: 👶 small, ✋🙂 Review please

#4264 feat(condo): INFRA-158 init k6 basic ticket test
  .github/workflows/arc-builds.yml
  .github/workflows/arc-condo-tests.yml
  .github/workflows/nodejs.condo.cypress.yml
  .github/workflows/nodejs.condo.k6.yml
  .gitignore
  apps/condo/domains/common/components/ChangeHistory/index.tsx
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/k6/README.md
  apps/condo/k6/src/news.test.ts
  apps/condo/k6/src/payment.test.ts
  apps/condo/k6/src/ticket.test.ts
  apps/condo/k6/src/utils.ts
  apps/condo/k6/webpack.config.js
  apps/condo/package.json
  packages/clients/finance-info-client/index.js
  run_condo_domain_tests.sh
  werf.yaml
  yarn.lock
Labels: ✋🙂 Review please, infrastructure

#4352 fix(condo): DOMA-8309 added line breaks in news item preview
  apps/condo/domains/news/components/NewsPreview.tsx
Labels: 👶 small, ✋🙂 Review please

#4348 fix(condo): DOMA-8339 fixed ticket deadline
  apps/condo/domains/ticket/utils/helpers.ts
Labels: 👶 small, ✋🙂 Review please

#3945 feat(kmigrator): DOMA-7367 add multiple knex adapters support
  bin/kmigrator.py
  packages/keystone/databaseAdapters/FakeDatabaseAdapter.js
  packages/keystone/databaseAdapters/ScalableDatabaseAdapter.js
  packages/keystone/databaseAdapters/__snapshots__/utils.spec.js.snap
  packages/keystone/databaseAdapters/index.js
  packages/keystone/databaseAdapters/utils.js
  packages/keystone/databaseAdapters/utils.spec.js
  packages/keystone/databaseAdapters/wrapToCheckOnlyPublicApi.js
  packages/keystone/setup.utils.js
Labels: 👶 small, ✋🙂 Review please

#4360 Fix/condo/infra 164/add response time to gql result log
  packages/keystone/logging/GraphQLLoggerApp.js
Labels: 👶 small, ✋🙂 Review please

#4361 fix(condo): DOMA-8383 Show "no vat"
  apps/condo/domains/acquiring/components/AcquiringReceipt.tsx
Labels: 👶 small, ✋🙂 Review please

#4347 feat(condo): DOMA-7262 skip discovering if user has 7+ residents in property
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.test.js
Labels: ✋🙂 Review please

#4356 feat(condo): DOMA-8359 add field `type` to `MarketPriceScope` model
  apps/condo/domains/marketplace/constants.js
  apps/condo/domains/marketplace/gql.js
  apps/condo/domains/marketplace/schema/MarketPriceScope.js
  apps/condo/domains/marketplace/schema/MarketPriceScope.test.js
  apps/condo/migrations/20240205113249-0364_marketpricescope_type_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4321 DOMA-8292 Remove serviceConsumer.billingAccount
  apps/condo/bin/fix-database-migration-state.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
  apps/condo/domains/acquiring/utils/testSchema/index.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
  apps/condo/domains/billing/schema/BillingReceiptFile.test.js
  apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.test.js
  apps/condo/domains/resident/gql.js
  apps/condo/domains/resident/schema/DiscoverServiceConsumersService.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
  apps/condo/domains/resident/schema/ServiceConsumer.js
  apps/condo/domains/resident/schema/ServiceConsumer.test.js
  apps/condo/domains/resident/tasks/notifyResidentsOnPayday.js
  apps/condo/domains/resident/tasks/notifyResidentsOnPayday.spec.js
  apps/condo/migrations/20240213205709-0366_remove_serviceconsumer_billingaccount_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4388 chore(address-service): DOMA-8447 remove regexp while searching addre…
  apps/address-service/domains/address/schema/AddressSource.js
  apps/condo/domains/marketplace/schema/Invoice.js
  packages/keystone/KSv5v6/v5/registerSchema.js
  packages/keystone/KSv5v6/v5/registerSchema.spec.js
  packages/keystone/fields/Text/index.js
  packages/keystone/fields/index.js
  packages/keystone/schema.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4392 hotfix(featureflags): HOTFIX added "fetch" import
  packages/featureflags/featureToggleManager.js
  packages/featureflags/package.json
  yarn.lock
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4396 hotfix(condo): fixed IncidentHints
  apps/condo/domains/ticket/components/IncidentHints.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#4359 feat(condo): DOMA-8365 changed card styles, added checkbox card
  packages/ui/src/components/Card/_utils/constants.ts
  packages/ui/src/components/Card/_utils/index.tsx
  packages/ui/src/components/Card/body/cardBody.less
  packages/ui/src/components/Card/body/cardBody.tsx
  packages/ui/src/components/Card/button/cardButton.tsx
  packages/ui/src/components/Card/card.tsx
  packages/ui/src/components/Card/checkbox/cardCheckbox.less
  packages/ui/src/components/Card/checkbox/cardCheckbox.tsx
  packages/ui/src/components/Card/header/cardHeader.less
  packages/ui/src/components/Card/header/cardHeader.tsx
  packages/ui/src/components/Card/index.ts
  packages/ui/src/components/Card/style.less
  packages/ui/src/components/Checkbox/checkbox.tsx
  packages/ui/src/components/Emoji/Emoji.tsx
  packages/ui/src/components/Emoji/index.ts
  packages/ui/src/components/ProgressIndicator/index.ts
  packages/ui/src/components/ProgressIndicator/progressIndicator.tsx
  packages/ui/src/components/ProgressIndicator/steps.tsx
  packages/ui/src/index.ts
  packages/ui/src/stories/Card/Card.stories.tsx
  packages/ui/src/stories/Card/CardButton.stories.tsx
  packages/ui/src/stories/Card/CardCheckbox.stories.tsx
  packages/ui/src/stories/ProgressIndicator.stories.tsx
Labels: ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit

#4405 fix(condo): DOMA-8434 fixed label of ticket deadline
  apps/condo/domains/ticket/utils/helpers.ts
Labels: 👶 small, ✋🙂 Review please

#4372 feat(condo): INFRA-210 enable query batching with BatchHttpLink option
  apps/condo/cypress/e2e/pages/ticket.cy.js
  apps/condo/cypress/objects/Property.ts
  apps/condo/cypress/objects/Ticket.ts
  apps/condo/cypress/support/e2e.js
  apps/condo/k6/src/ticket.test.ts
  packages/codegen/generate.hooks.ts
  packages/next/apollo.jsx
Labels: 👶 small, ✋🙂 Review please, 😎 Cool

#4344 feat(condo): INFRA-264 OIDC Enabled field and deletedAt fix
  apps/condo/bin/create-oidc-client.js
  apps/condo/domains/user/oidc/adapter/OidcModelClientAdapter.js
  apps/condo/domains/user/schema/OidcClient.js
  apps/condo/domains/user/schema/_oidc.test.js
  apps/condo/domains/user/utils/testSchema/index.js
  apps/condo/migrations/20240221230519-0368_oidcclient_isenabled_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please, 🚨 Migrations

#4398 feat(keystone): INFRA-265 rate limit observer proof of work
  packages/keystone/KSv5v6/v5/prepareKeystone.js
  packages/keystone/logging/GraphQLLoggerApp.js
  packages/keystone/logging/getReqLoggerContext.js
  packages/keystone/package.json
  packages/keystone/rateLimiting/README.md
  packages/keystone/rateLimiting/constants.js
  packages/keystone/rateLimiting/index.js
  packages/keystone/rateLimiting/plugin.js
  packages/keystone/rateLimiting/query.utils.js
  packages/keystone/rateLimiting/request.utils.js
  packages/keystone/rateLimiting/schema.utils.js
  yarn.lock
Labels: ✋🙂 Review please, 😎 Cool

#4389 feat(condo): DOMA-8376 tour step schema
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/onboarding/access/TourStep.js
  apps/condo/domains/onboarding/constants/errors.js
  apps/condo/domains/onboarding/constants/steps.js
  apps/condo/domains/onboarding/gql.js
  apps/condo/domains/onboarding/schema/TourStep.js
  apps/condo/domains/onboarding/schema/TourStep.test.js
  apps/condo/domains/onboarding/schema/index.js
  apps/condo/domains/onboarding/utils/clientSchema/TourStep.ts
  apps/condo/domains/onboarding/utils/clientSchema/index.ts
  apps/condo/domains/onboarding/utils/serverSchema/index.js
  apps/condo/domains/onboarding/utils/testSchema/index.js
  apps/condo/domains/organization/constants/common.js
  apps/condo/domains/organization/gql.js
  apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js
  apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
  apps/condo/domains/organization/schema/RegisterNewOrganizationService.js
  apps/condo/lang/en/en.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20240222102124-0369_auto_20240222_0521.js
  apps/condo/pages/auth/register.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: ✋🙂 Review please, 🚨 Migrations

#4416 hotfix(condo): fix tag in services cards
  packages/ui/src/components/Card/header/cardHeader.less
  packages/ui/src/components/Card/header/cardHeader.tsx
  packages/ui/src/components/Tag/tag.tsx
Labels: 👶 small, ✋🙂 Review please

#4411 fix(condo): DOMA-8473 fixed unitsCount and uninhabitedUnitsCount when updating property
  apps/condo/domains/property/schema/Property.js
  apps/condo/domains/property/schema/Property.test.js
Labels: 👶 small, ✋🙂 Review please

#4404 Feat/condo/doma 8437/change billing setup flow
  apps/condo/domains/acquiring/schema/fields/Recipient.js
  apps/condo/domains/billing/components/OnBoarding/BillingDescriptionModalContent.tsx
  apps/condo/domains/billing/components/OnBoarding/SetupAcquiring.tsx
  apps/condo/domains/billing/components/OnBoarding/SetupBilling.tsx
  apps/condo/schema.graphql
  apps/condo/schema.ts
Labels: 🔬 WIP

#4429 feat(condo): INFRA-266 prevent user searching
  .yarn/patches/@keystonejs-access-control-npm-7.1.2-bec144d41a.patch
  .yarn/patches/@keystonejs-keystone-npm-19.3.4-2a53e53061.patch
  .yarn/patches/@keystonejs-patches.md
  apps/condo/domains/user/access/User.js
  apps/condo/domains/user/schema/User.test.js
  apps/condo/domains/user/schema/UserRightsSet.test.js
  apps/condo/domains/user/utils/directAccess/config.js
  apps/condo/migrations/20240228171603-0370_userrightsset_canreadusers_and_more.js
  apps/condo/schema.graphql
  apps/condo/schema.ts
  apps/dev-api/bin/prepare.js
  package.json
  packages/keystone/access.js
  packages/keystone/access.spec.js
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 🦑 API CHANGES

#4434 fix(condo): DOMA-8541 register billing receipts mutation fixes
  apps/condo/domains/billing/schema/RegisterBillingReceiptsService.new.test.js
  apps/condo/domains/billing/schema/resolvers/propertyResolver.spec.js
  apps/condo/domains/billing/schema/resolvers/receiptResolver.js
  apps/condo/domains/billing/schema/resolvers/recipientResolver.js
  packages/clients/address-service-client/utils/parseAddressesFromString.js
  packages/clients/address-service-client/utils/parseAddressesFromString.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please
