Repository open-condo-software/condo, pull requests merged in 2024-11, with the labels that each got.

#5424 fix(condo): DOMA-10557 fix iteration over chunk uploading result
  apps/condo/domains/meter/tasks/importMeters.js
  apps/condo/domains/meter/utils/taskSchema/AbstractMetersImporter.js
Labels: 👶 small, ✋🙂 Review please

#5459 chore(condo): use Object.freeze on DEFAULT_ANDROID_PAYLOAD
  apps/condo/domains/notification/adapters/hcm/messaging.js
Labels: 👶 small

#5476 fix(kmigrator): DOMA-10652 no more redundant migrations for select changes
  apps/condo/migrations/20241112145945-0438_auto_20241112_1159.js
  bin/kmigrator.py
Labels: 👶 small, 🔥 HOTFIX, 🚨 Migrations, 😎 Cool

#5486 fix(condo): DOMA-10682 do not render global apps when no organization selected
  apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
Labels: 👶 small, ✋🙂 Review please

#5495 fix(condo): DOMA-9700 fix CallRecord fileMetaAfterChange
  apps/condo/domains/ticket/schema/CallRecord.js
Labels: 🔥 HOTFIX

#5490 fix(condo): DOMA-10686 fix export drops
  apps/condo/domains/common/utils/testSchema/file.js
  apps/condo/domains/contact/templates/ContactsExportTemplate.xlsx
  apps/condo/domains/news/templates/NewsRecipientsExportTemplate.xlsx
  apps/condo/domains/scope/templates/PropertyScopesExportTemplate.xlsx
  apps/condo/domains/ticket/templates/IncidentsExportTemplate.xlsx
  apps/condo/domains/ticket/templates/TicketsExportTemplate.xlsx
Labels: 👶 small, ✋🙂 Review please

#5506 fix(condo): DOMA-10475 removed double page wrappers
  apps/condo/pages/service-provider-profile.tsx
Labels: 👶 small, ✋🙂 Review please

#5507 feat(global): INFRA-650 restrict public access to User.name
  apps/condo/domains/user/access/User.js
  apps/condo/domains/user/schema/User.js
  apps/condo/domains/user/schema/User.test.js
  packages/keystone/KSv5v6/utils/graphqlCtx.js
  packages/keystone/KSv5v6/utils/resolvers.js
  packages/keystone/access.js
  packages/keystone/databaseAdapters/BalancingReplicaKnexAdapter/adapter.js
  packages/keystone/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please

#5513 feat(clients): DOMA-10717 use open-condo fetch in addressServiceClient
  packages/clients/address-service-client/AddressServiceClient.js
  packages/clients/package.json
  yarn.lock
Labels: 👶 small, ✋🙂 Review please, 📦 Packages

#5462 chore(ui): fix ActionBar `jumping` when scrolling
  packages/ui/src/components/ActionBar/actionBar.tsx
  packages/ui/src/components/ActionBar/style.less
Labels: 👶 small, ✋🙂 Review please

#5519 chore(ui): fix chromatic builds
  .github/workflows/packages.ui.review.yml
  .github/workflows/packages.ui.sync-baseline.yml
  packages/ui/package.json
Labels: 👶 small, ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review

#5516 feat(keystone): DOMA-10613 normal excel date format parsing
  apps/condo/domains/meter/utils/taskSchema/DomaMetersImporter.js
  apps/condo/domains/meter/utils/taskSchema/DomaMetersImporter.spec.js
  packages/keystone/file/file-types/excel.js
Labels: ✋🙂 Review please, 📦 Packages

#5521 fix(condo): Doma-10475 spp banners fix
  apps/condo/domains/miniapp/components/AppIndex/BillingAppPage.tsx
  apps/condo/pages/service-provider-profile.tsx
Labels: 👶 small, ✋🙂 Review please, 🐞 BUG

#5523 fix(condo): Duplicated payments temporary fix
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
  apps/condo/domains/billing/utils/serverSchema/index.js
  apps/condo/domains/billing/utils/testSchema/mixins/acquiring.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#5543 fix(condo): DOMA-10752 fix assignee select search
  apps/condo/domains/organization/utils/clientSchema/search.tsx
  apps/condo/pages/_app.tsx
Labels: 👶 small, ✋🙂 Review please

#5547 fix(condo): DOMA-10760 fix ticket invoices update
  apps/condo/domains/marketplace/components/Invoice/InvoiceRowsTable.tsx
  apps/condo/domains/marketplace/components/Invoice/UpdateInvoiceForm.tsx
  apps/condo/domains/marketplace/queries/Invoice.graphql
  apps/condo/domains/ticket/components/TicketForm/UpdateTicketForm.tsx
  apps/condo/gql/index.ts
  apps/condo/gql/operation.types.ts
Labels: 👶 small, ✋🙂 Review please

#5555 chore(keystone): DOMA-10642 remove console log 🤡
  packages/keystone/crypto/keyDerivers/pbkdf2.js
Labels: 👶 small
