Repository open-condo-software/condo, pull requests merged in 2025-03, with the labels that each got.

#5892 feat(condo): INFRA-916 migrate basic events to new analytics
  apps/condo/domains/common/components/CondoAppEventsHandler.tsx
  apps/condo/domains/common/components/TrackingContext.tsx
  apps/condo/domains/common/utils/analytics.ts
  apps/condo/domains/user/queries/User.graphql
  apps/condo/gql/index.ts
  apps/condo/gql/operation.types.ts
  apps/condo/next.config.js
  apps/condo/package.json
  apps/condo/pages/_app.tsx
Labels: 👶 small, ✋🙂 Review please

#5906 feat(condo): DOMA-11185 notifications sound switch
  apps/condo/domains/common/components/containers/BaseLayout/Header.tsx
  apps/condo/domains/common/components/containers/BaseLayout/components/TopMenuItems.tsx
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/notification/components/UserMessagesList/UserMessagesList.css
  apps/condo/domains/notification/components/UserMessagesList/UserMessagesSettingsModal.tsx
  apps/condo/domains/notification/contexts/UserMessagesListContext.tsx
  apps/condo/domains/notification/hooks/useNewMessageTitleNotification.ts
  apps/condo/domains/notification/hooks/useUserMessagesListSettingsStorage.ts
  apps/condo/domains/notification/schema/Message.js
  apps/condo/domains/notification/schema/Message.test.js
  apps/condo/lang/en/en.json
  apps/condo/lang/es/es.json
  apps/condo/lang/ru/ru.json
  apps/condo/pages/ticket/index.tsx
  packages/ui/src/components/Tooltip/tooltip.tsx
Labels: ✋🙂 Review please

#5912 fix(condo): DOMA-11185 remove ovveride tooltip max width
  apps/condo/domains/notification/components/UserMessagesList/UserMessagesList.css
  apps/condo/domains/notification/components/UserMessagesList/UserMessagesSettingsModal.tsx
  packages/ui/src/components/Tooltip/tooltip.tsx
Labels: ✋🙂 Review please

#5915 fix(condo): DOMA-11246 split overcomplicated query for payments sum
  apps/condo/domains/billing/utils/serverSchema/index.js
Labels: 👶 small, ✋🙂 Review please

#5931 feat/address-service/doma-11130/ability to update address
  apps/address-service/admin-ui/index.js
  apps/address-service/bin/prepare.js
  apps/address-service/domains/address/access/ActualizeAddressesService.js
  apps/address-service/domains/address/gql.js
  apps/address-service/domains/address/schema/ActualizeAddressesService.js
  apps/address-service/domains/address/schema/ActualizeAddressesService.spec.js
  apps/address-service/domains/address/schema/Address.js
  apps/address-service/domains/address/schema/AddressSource.js
  apps/address-service/domains/address/schema/index.js
  apps/address-service/domains/address/utils/serverSchema/index.js
  apps/address-service/domains/address/utils/testSchema/dadataUtils.js
  apps/address-service/domains/address/utils/testSchema/index.js
  apps/address-service/domains/common/utils/services/search/searchServiceUtils.js
  apps/address-service/jest.config.js
  apps/address-service/migrations/20250319094733-0006_alter_address_key_alter_addresssource_source_and_more.js
  apps/address-service/schema.ts
  apps/condo/domains/banking/schema/BankSyncTask.test.js
  packages/cli/index.js
Labels: ✋🙂 Review please, 🚨 Migrations

#5943 feat(dev-portal-web): DOMA-11304 Russian docs for working with invoices
  apps/dev-portal-web/docs/api/_meta.ru.json
  apps/dev-portal-web/docs/api/cases/_meta.ru.json
  apps/dev-portal-web/docs/api/cases/invoices/_meta.ru.json
  apps/dev-portal-web/docs/api/cases/invoices/amount-distribution.ru.mdx
  apps/dev-portal-web/docs/api/cases/invoices/prepare.ru.mdx
  apps/dev-portal-web/docs/api/cases/invoices/work-with-invoices.ru.mdx
  apps/dev-portal-web/docs/api/examples/auth.en.mdx
  apps/dev-portal-web/docs/api/examples/auth.ru.mdx
Labels: ✋🙂 Review please

#5955 fix(condo): DOMA-11336 parse common MMYYYY periods in qr code and potential YYYYMM
  apps/condo/domains/billing/schema/ValidateQRCodeService.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.spec.js
Labels: ✋🙂 Review please

#5957 fix(condo): DOMA-11337 preformat all possible casings from qr code field to one format
  apps/condo/domains/billing/schema/ValidateQRCodeService.test.js
  apps/condo/domains/billing/utils/countrySpecificQRCodeParsers/ru.qrCodeParser.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.spec.js
Labels: 👶 small, ✋🙂 Review please
