Repository open-condo-software/condo, pull requests merged in 2025-05, with the labels that each got.

#6164 fix(condo): fix random meter reading test
  apps/condo/domains/meter/schema/MeterReading.test.js
Labels: 👶 small, ✋🙂 Review please

#6159 fix (condo): DOMA-11564 add compare with B2BAppNewsSharingConfig
  apps/condo/domains/miniapp/queries/B2BApp.graphql
  apps/condo/domains/news/components/NewsForm/SelectSharingAppControl.tsx
  apps/condo/gql/index.ts
  apps/condo/gql/operation.types.ts
Labels: 👶 small, ✋🙂 Review please

#6167 chore(condo): DOMA-11590 added featureflag for skip search organizations by tin
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/organization/components/CreateOrganizationForm.tsx
Labels: 👶 small, ✋🙂 Review please

#6172 feat(condo): DOMA-11517 added loading state to create organization button
  apps/condo/domains/organization/components/CreateOrganizationForm.tsx
Labels: 👶 small, ✋🙂 Review please

#6185 chore(condo): DOMA-11618 decrease the limit used to create CSV instea…
  apps/condo/domains/ticket/tasks/exportTickets.js
Labels: 👶 small, ✋🙂 Review please

#6197 fix(condo): DOMA-11616 fixed registerServiceConsumer
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
  apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
Labels: 👶 small, ✋🙂 Review please, 🐞 BUG

#6219 feat(condo): DOMA-11572 allow to find service providers without property, if tin and account number present.
  apps/condo/domains/resident/schema/FindOrganizationsByAddressService.js
  apps/condo/domains/resident/schema/FindOrganizationsByAddressService.test.js
  apps/condo/domains/resident/utils/serverSchema/findOrganizationsByAddress.js
Labels: ✋🙂 Review please

#6248 fix(condo): DOMA-11744 fix time zone label
  apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
  apps/condo/lang/en/en.json
  apps/condo/lang/es/es.json
  apps/condo/lang/ru/ru.json
Labels: 👶 small, ✋🙂 Review please
