Repository open-condo-software/condo, pull requests merged in 2025-04, with the labels that each got.

#5981 test(condo): fix random test and remove non-english comment
  apps/condo/domains/billing/utils/receiptQRCodeUtils.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.spec.js
Labels: 👶 small

#5993 feat(condo): DOMA-11395 delete checking for uniq by ajv
  apps/condo/domains/billing/schema/fields/AmountDistribution.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
Labels: 👶 small, ✋🙂 Review please

#5908 feat(condo): DOMA-10586 added PaymentsFile model and table in UI
  apps/condo/domains/acquiring/access/AcquiringIntegrationContext.js
  apps/condo/domains/acquiring/access/MultiPayment.js
  apps/condo/domains/acquiring/access/Payment.js
  apps/condo/domains/acquiring/access/PaymentsFile.js
  apps/condo/domains/acquiring/access/SumPaymentsService.js
  apps/condo/domains/acquiring/components/payments/PaymentFilesTable.tsx
  apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx
  apps/condo/domains/acquiring/constants/constants.js
  apps/condo/domains/acquiring/gql.js
  apps/condo/domains/acquiring/hooks/useDownloadPaymentsFiles.ts
  apps/condo/domains/acquiring/hooks/usePaymentsFilesTableColumns.ts
  apps/condo/domains/acquiring/hooks/usePaymentsFilesTableFilters.ts
  apps/condo/domains/acquiring/hooks/usePaymentsSum.ts
  apps/condo/domains/acquiring/hooks/usePaymentsTableColumns.ts
  apps/condo/domains/acquiring/queries/PaymentsFile.graphql
  apps/condo/domains/acquiring/schema/PaymentsFile.js
  apps/condo/domains/acquiring/schema/PaymentsFile.test.js
  apps/condo/domains/acquiring/schema/SumPaymentsService.js
  apps/condo/domains/acquiring/schema/SumPaymentsService.test.js
  apps/condo/domains/acquiring/schema/index.js
  apps/condo/domains/acquiring/utils/accessSchema.js
  apps/condo/domains/acquiring/utils/clientSchema/Renders.tsx
  apps/condo/domains/acquiring/utils/clientSchema/index.ts
  apps/condo/domains/acquiring/utils/helpers.ts
  apps/condo/domains/acquiring/utils/serverSchema/index.js
  apps/condo/domains/acquiring/utils/testSchema/index.js
  apps/condo/domains/billing/components/BillingPageContent/MainContent.tsx
  apps/condo/domains/billing/components/BillingPageContent/PaymentsTab.tsx
  apps/condo/domains/billing/components/BillingPageContent/PaymentsTab/Payments.tsx
  apps/condo/domains/billing/components/BillingPageContent/PaymentsTab/PaymentsFiles.tsx
  apps/condo/domains/billing/components/BillingPageContent/PaymentsTab/index.tsx
  apps/condo/domains/billing/components/BillingPageContent/index.tsx
  apps/condo/domains/billing/constants/constants.js
  apps/condo/domains/billing/hooks/useQueryParams.ts
  apps/condo/domains/billing/hooks/useQueryTab.ts
  apps/condo/domains/common/components/Table/Renders.tsx
  apps/condo/domains/common/constants/featureflags.js
  apps/condo/domains/common/utils/next/apollo.ts
  apps/condo/domains/common/utils/tables.utils.ts
  apps/condo/domains/meter/components/TabContent/MeterReading.tsx
  apps/condo/domains/meter/components/TabContent/PropertyMeterReading.tsx
  apps/condo/gql/index.ts
  apps/condo/gql/operation.types.ts
  apps/condo/lang/en/en.json
  apps/condo/lang/es/es.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20250402125946-0463_paymentsfilehistoryrecord_paymentsfile_and_more.js
  apps/condo/package.json
  apps/condo/schema.graphql
  packages/ui/src/components/Tabs/tabs.tsx
  yarn.lock
Labels: ✋🙂 Review please, 🚨 Migrations

#6007 fix(condo): DOMA-9686 wrap link in tag in invite email template
  apps/condo/lang/en/messages/DIRTY_INVITE_NEW_EMPLOYEE_EMAIL/email.html.njk
  apps/condo/lang/es/messages/DIRTY_INVITE_NEW_EMPLOYEE_EMAIL/email.html.njk
  apps/condo/lang/ru/messages/DIRTY_INVITE_NEW_EMPLOYEE_EMAIL/email.html.njk
Labels: 👶 small, ✋🙂 Review please

#5991 feat(condo): DOMA-11332 added support for several billing contexts for one organization
  apps/condo/domains/acquiring/components/payments/PaymentFilesTable.tsx
  apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx
  apps/condo/domains/acquiring/hooks/usePaymentsTableColumns.ts
  apps/condo/domains/acquiring/hooks/usePaymentsTableFilters.ts
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
  apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
  apps/condo/domains/billing/components/BillingPageContent/AccrualsTab.tsx
  apps/condo/domains/billing/components/BillingPageContent/ContextProvider.ts
  apps/condo/domains/billing/components/BillingPageContent/EmptyContent.tsx
  apps/condo/domains/billing/components/BillingPageContent/MainContent.tsx
  apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
  apps/condo/domains/billing/components/BillingPageContent/ReportMessage.tsx
  apps/condo/domains/billing/components/BillingPageContent/index.tsx
  apps/condo/domains/billing/constants/constants.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
  apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
  apps/condo/pages/billing/index.tsx
Labels: 👶 small, ✋🙂 Review please

#6031 feat(condo): DOMA-11422 added hot water billing category
  apps/condo/lang/en/en.json
  apps/condo/lang/es/es.json
  apps/condo/lang/ru/ru.json
  apps/condo/migrations/20250408190624-0465_auto_20250408_1606.js
Labels: 👶 small, ✋🙂 Review please, 🚨 Migrations

#6045 chore(dev-portal-web): DOMA-11450 small improvements for distribution playground
  apps/dev-portal-web/domains/docs/components/widgets/AmountDistributionCalculator/DistributionItemCard.tsx
  apps/dev-portal-web/domains/docs/components/widgets/AmountDistributionCalculator/distributionItemCard.module.css
  apps/dev-portal-web/domains/docs/components/widgets/AmountDistributionCalculator/index.module.css
  apps/dev-portal-web/domains/docs/components/widgets/AmountDistributionCalculator/index.tsx
Labels: 👶 small, ✋🙂 Review please

#6058 fix(condo): DOMA-11469 trim tin value in resolveInput
  apps/condo/domains/organization/schema/Organization.js
  apps/condo/domains/organization/schema/Organization.test.js
Labels: 👶 small, ✋🙂 Review please

#6063 fix(condo): DOMA-11469 trim tin value in findOrganizationsByTin
  apps/condo/domains/organization/components/CreateOrganizationForm.tsx
  apps/condo/domains/organization/schema/FindOrganizationsByTinService.js
  apps/condo/domains/organization/schema/FindOrganizationsByTinService.test.js
Labels: 👶 small, ✋🙂 Review please

#6054 fix(DOMA-11255): fixed ownerType detection and removed warehouse category from category resolver
  apps/condo/domains/billing/schema/resolvers/accountResolver.spec.js
  apps/condo/domains/billing/schema/resolvers/categoryResolver.js
  apps/condo/domains/billing/schema/resolvers/utils.js
Labels: 👶 small, ✋🙂 Review please, 🐞 BUG

#6089 feat(condo): DOMA-11480 replace staff access for payments to cached version
  apps/condo/domains/acquiring/access/Payment.js
Labels: 👶 small, ✋🙂 Review please

#6030 feat(ui): DOMA-11427 added adaptive layout for tabs with extra content
  apps/condo/domains/billing/components/BillingPageContent/index.tsx
  packages/ui/src/components/Tabs/style.less
  packages/ui/src/components/Tabs/tabs.tsx
  packages/ui/src/stories/Tabs.stories.tsx
Labels: 👨🏻‍🎨 Request UI-kit review

#6019 fix(condo): DOMA-11377 fixed after design-review. fixed bugs
  apps/condo/domains/common/components/containers/LayoutWithPoster/styles.css
  apps/condo/domains/user/components/CookieAgreement.tsx
  apps/condo/domains/user/components/CookieAgreement/index.tsx
  apps/condo/domains/user/components/CookieAgreement/styles.css
  apps/condo/domains/user/components/UserProfileForm.tsx
  apps/condo/domains/user/components/UserWelcomeTitle.tsx
  apps/condo/domains/user/components/auth/InputPhoneForm.tsx
  apps/condo/domains/user/components/auth/SignInForm.tsx
  apps/condo/pages/_app.tsx
  apps/condo/pages/auth/index.tsx
  apps/condo/pages/auth/signin.tsx
Labels: 👶 small, ✋🙂 Review please

#6108 fix(condo): DOMA-11509 check deletedAt for ticket statuses
  apps/condo/domains/ticket/tasks/exportTickets.js
Labels: 👶 small, ✋🙂 Review please, 🐞 BUG

#6093 fix(condo): DOMA-9912 fix deadline filter for tickets
  apps/condo/domains/ticket/utils/tables.utils.ts
Labels: 👶 small, ✋🙂 Review please

#6106 fix(condo): DOMA-11499 added case insensitive check for user verification
  apps/condo/domains/billing/schema/BillingReceiptFile.js
  apps/condo/domains/billing/schema/BillingReceiptFile.test.js
Labels: 👶 small, ✋🙂 Review please, 🐞 BUG

#6133 fix(condo): DOMA-11546 disable webvisor
  apps/condo/domains/common/components/containers/YandexMetrika.tsx
Labels: 👶 small, ✋🙂 Review please

#6128 fix(condo): DOMA-11454 fix indicent properties initial value
  apps/condo/domains/ticket/components/IncidentForm/BaseIncidentForm.tsx
Labels: 👶 small, ✋🙂 Review please

#6156 chore(condo): DOMA-11571 Exclude insurance category from recurrent payments
  apps/condo/domains/acquiring/constants/recurrentPayment.js
  apps/condo/domains/acquiring/tasks/createRecurrentPaymentForNewBillingReceipt.spec.js
  apps/condo/domains/acquiring/tasks/createRecurrentPaymentForReadyToPayRecurrentPaymentContexts.spec.js
  apps/condo/domains/acquiring/utils/taskSchema/index.js
Labels: ✋🙂 Review please
