Repository open-condo-software/condo, pull requests merged in 2025-09, with the labels that each got.

#6611 fix(condo): updated nmp package sha.js
  yarn.lock
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#6618 fix(condo): DOMA-12177 fix classifier options render
  apps/condo/domains/ticket/components/TicketClassifierSelect.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#6652 fix(condo): DOMA-12227 fixed layout for mobile view in ssr
  apps/condo/domains/common/components/LayoutContext.tsx
  apps/condo/domains/common/components/containers/BaseLayout/Header.tsx
  apps/condo/domains/common/components/containers/BaseLayout/components/SideNav/index.tsx
  apps/condo/domains/common/utils/next/ssr.ts
  apps/condo/pages/_app.tsx
Labels: 👶 small, ✋🙂 Review please

#6664 feat(condo): add interactive app preparation script with CLI prompts …
  bin/prepare-interactive.js
  knip.js
  package.json
  yarn.lock
Labels: ✋🙂 Review please, 😎 Cool
