Repository open-condo-software/condo, pull requests merged in 2025-01, with the labels that each got.

#5677 hotfix: fix null values in price measures
  apps/condo/domains/marketplace/components/MarketItem/UpdateMarketItemForm.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#5678 hotfix: fix invoice filtering
  apps/condo/domains/marketplace/components/Invoice/MarketplaceInvoicesContent.tsx
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#5682 fix(condo): DOMA-10863 use organization's tin to boost searching by address from QR
  apps/condo/domains/billing/schema/ValidateQRCodeService.spec.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.js
Labels: ✋🙂 Review please

#5694 fix(condo): INFRA-787 add organization meta to client side queries
  .sonarcloud.properties
  apps/condo/domains/organization/queries/OrganizationEmployee.graphql
  apps/condo/gql/index.ts
  apps/condo/gql/operation.types.ts
Labels: 👶 small, ✋🙂 Review please

#5693 fix(condo): DOMA-10960 show notification for errors with type equals TOO_MANY_REQUESTS
  apps/condo/domains/common/utils/mutations.utils.ts
Labels: 👶 small, ✋🙂 Review please

#5692 test(packages): fix some random tests
  packages/keystone/crypto/EncryptionManager.spec.js
  packages/keystone/session.spec.js
Labels: 👶 small, ✋🙂 Review please, 📦 Packages

#5717 feat(condo): DOMA-11006 Process QR code by TIN+Account number instead…
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
  apps/condo/domains/billing/constants/constants.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.spec.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.test.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.spec.js
  apps/condo/domains/user/schema/OidcClient.test.js
  apps/condo/domains/user/schema/_oidc.test.js
  apps/condo/domains/user/utils/testSchema/index.js
  packages/clients/address-service-client/FakeAddressServiceClient.js
Labels: ✋🙂 Review please

#5732 fix(condo): DOMA-10907 search receipts with desc sorting by period
  apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.js
  apps/condo/domains/billing/schema/ValidateQRCodeService.test.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.js
  apps/condo/domains/billing/utils/receiptQRCodeUtils.spec.js
  apps/condo/domains/user/schema/RegisterNewUserService.js
Labels: ✋🙂 Review please

#5734 fix(condo): INFRA-837 hide link from resident ticket[id] page if there is no resident
  apps/condo/domains/ticket/components/TicketId/TicketUserInfoField.tsx
Labels: 👶 small, ✋🙂 Review please
