Repository open-condo-software/condo, pull requests merged in 2025-02, with the labels that each got.

#5778 feat(condo): DOMA-11023 add changed fields to error object
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
Labels: 👶 small, ✋🙂 Review please

#5779 fix(condo): DOMA-11023 prevent update the `client` field if no reside…
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
Labels: ✋🙂 Review please

#5801 fix(spp): sbbol api now do not return userGuid
  apps/condo/domains/organization/integrations/sbbol/constants.js
  apps/condo/domains/organization/integrations/sbbol/sync/index.js
  apps/condo/domains/organization/integrations/sbbol/utils/getSbbolUserInfoErrors.spec.js
Labels: 👶 small, 🔥 HOTFIX, ✋🙂 Review please

#5809 hotfix(condo): fixed phone normalization
  apps/condo/domains/common/utils/phone.js
  apps/condo/domains/common/utils/phone.spec.js
Labels: 👶 small, ✋🙂 Review please

#5799 feat(migrator): introduce @open-condo/migrator for backward incompatible changes 🏃🏻‍♂️🦖
  .github/workflows/nodejs.condo.ci.yml
  package.json
  packages/migrator/README.md
  packages/migrator/jest.config.js
  packages/migrator/jest.setupSpec.ts
  packages/migrator/package.json
  packages/migrator/src/cli.spec.ts
  packages/migrator/src/cli.ts
  packages/migrator/src/commands/addAppsKVPrefixes.ts
  packages/migrator/src/commands/index.ts
  packages/migrator/src/utils/envs.spec.ts
  packages/migrator/src/utils/envs.ts
  packages/migrator/src/utils/kvdb/addAppPrefix.spec.ts
  packages/migrator/src/utils/kvdb/addAppPrefix.ts
  packages/migrator/src/utils/kvdb/dataVersion.spec.ts
  packages/migrator/src/utils/kvdb/dataVersion.ts
  packages/migrator/src/utils/kvdb/filtering.spec.ts
  packages/migrator/src/utils/kvdb/filtering.ts
  packages/migrator/src/utils/kvdb/keyPrefix.spec.ts
  packages/migrator/src/utils/kvdb/keyPrefix.ts
  packages/migrator/src/utils/logging.ts
  packages/migrator/src/utils/options.ts
  packages/migrator/src/utils/packages.spec.ts
  packages/migrator/src/utils/packages.ts
  packages/migrator/src/utils/tests/kvdb.ts
  packages/migrator/src/utils/tests/repo.ts
  packages/migrator/tsconfig.json
  packages/migrator/tsup.config.mjs
  packages/ui/package.json
  yarn.lock
Labels: ✋🙂 Review please, 😎 Cool, 🐘 BIG, 📦 Packages

#5817 feat(condo): DOMA-11113 allow to change invoice status in the case wh…
  apps/condo/domains/banking/schema/BankSyncTask.test.js
  apps/condo/domains/marketplace/schema/Invoice.js
  apps/condo/domains/marketplace/schema/Invoice.test.js
Labels: 👶 small, ✋🙂 Review please

#5815 fix(condo): DOMA-11131 return source column to meter readings table
  apps/condo/domains/meter/hooks/useTableColumns.tsx
Labels: 👶 small, ✋🙂 Review please

#5789 feat(ui): DOMA-11097 added switch component
  packages/ui/src/components/Switch/index.ts
  packages/ui/src/components/Switch/style.less
  packages/ui/src/components/Switch/switch.tsx
  packages/ui/src/components/_utils/analytics.ts
  packages/ui/src/index.ts
  packages/ui/src/stories/Switch.stories.tsx
Labels: ✋🙂 Review please, 👨🏻‍🎨 Request UI-kit review, 🎨 UI-kit

#5857 fix(condo): DOMA-10800 fix resident to property connections when there are more than 100 residents at the address
  apps/condo/domains/resident/schema/RegisterResidentService.test.js
  apps/condo/domains/resident/tasks/residentTicket.task.js
  apps/condo/domains/resident/utils/helpers.js
Labels: 👶 small, ✋🙂 Review please
